### ISSUE TITLE
Build docker images error

### ISSUE THREAD

**Issue by linmengnan** [opencv/cvat#1023]
Hello,
The command 'docker-compose build' gives the following error:

Step 1/56 : FROM ubuntu:16.04
ERROR: Service 'cvat' failed to build: The command '/bin/sh -c python3 -m pip install --no-cache-dir -r /tmp/requirements/${DJANGO_CONFIGURATION}.txt' returned a non-zero code: 2
How can I resolve this?   thank you

**Comment by PavneshYadav123** [comment]
run follwing command and agian build docker-compose 
docker system prune
docker stop $(docker ps -a -q)
docker rm $(docker ps -a -q)

**Comment by LiSa20120** [comment]
@PavneshYadav123 This doesn't solve the issue for me.

**Comment by LiSa20120** [comment]
@PavneshYadav123 This doesn't solve the issue.

**Comment by nmanovic** [comment]
@linmengnan , please provide the full command which you used to build CVAT. Also need full logs. Which git branch did you use (develop or master)?

**Comment by linmengnan** [comment]
develop is used

cvat admin$ docker-compose build
........
Downloading https://files.pythonhosted.org/packages/d3/d0/ef75c788627f4218a8d08dccdf4ebc91f5b83c48d09ec8f2a3db9610014b/Django-2.2.8-py3-none-any.whl (7.5MB)
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/urllib3/response.py", line 425, in _error_catcher
    yield
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/urllib3/response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/usr/lib/python3.5/http/client.py", line 458, in read
    n = self.readinto(b)
  File "/usr/lib/python3.5/http/client.py", line 498, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/commands/install.py", line 382, in run
    resolver.resolve(requirement_set)
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/legacy_resolve.py", line 201, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/legacy_resolve.py", line 313, in _get_abstract_dist_for
    req, self.session, self.finder, self.require_hashes
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/operations/prepare.py", line 194, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/download.py", line 465, in unpack_url
    progress_bar=progress_bar
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/download.py", line 316, in unpack_http_url
    progress_bar)
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/download.py", line 551, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/download.py", line 253, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/utils/hashes.py", line 80, in check_against_chunks
    for chunk in chunks:
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/download.py", line 223, in written_chunks
    for chunk in chunks:
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/utils/ui.py", line 160, in iter
    for x in it:
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/download.py", line 212, in resp_read
    decode_content=False):
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/urllib3/response.py", line 564, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/urllib3/response.py", line 529, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/urllib3/response.py", line 430, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
ERROR: Service 'cvat' failed to build: The command '/bin/sh -c python3 -m pip 
@nmanovic  thank you!

**Comment by nmanovic** [comment]
@linmengnan , do you have a proxy? Logs clear says that data cannot be fetched from files.pythonhosted.org. Usually it means that you have some problems with your network.

**Comment by nmanovic** [comment]
@linmengnan , I will close the issue. Please don't hesitate to re-open it if you have more information for us to investigate the issue.
