### ISSUE TITLE
CVAT not responding due to django errors

### ISSUE THREAD

**Issue by aquac** [opencv/cvat#1055]
The CVAT web interface on port 8080 is dead after I restarted the container.
There a couple of errors which I don't know how to handle:

```
cvat_052          | System check identified some issues:
cvat_052          |
cvat_052          | WARNINGS:
cvat_052          | ?: (2_0.W001) Your URL pattern 'api/swagger.<slug:format>$' [name='schema-json'] has a route that contains '(?P<', begins with a '^', or ends with a '$'. This was likely an oversight when migrating to django.urls.path().
cvat_052          |
cvat_052          | 2020-01-15 09:39:33,452 INFO success: runserver entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
cvat_052          | 2020-01-15 09:39:33,452 DEBG 'runserver' stdout output:
cvat_052          | SSH keys were not found
cvat_052          | Copying them from keys volume
cvat_052          | Operations to perform:
cvat_052          |   Apply all migrations: account, admin, annotation, auth, authtoken, contenttypes, engine, git, sessions, sites, socialaccount
cvat_052          | Running migrations:
cvat_052          |   No migrations to apply.
cvat_052          |
cvat_052          | 2020-01-15 09:39:33,455 DEBG 'runserver' stderr output:
cvat_052          | Traceback (most recent call last):
cvat_052          |   File "/home/django/manage.py", line 21, in <module>
cvat_052          |     execute_from_command_line(sys.argv)
cvat_052          |   File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
cvat_052          |     utility.execute()
cvat_052          |   File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 375, in execute
cvat_052          |     self.fetch_command(subcommand).run_from_argv(self.argv)
cvat_052          |   File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 323, in run_from_argv
cvat_052          |     self.execute(*args, **cmd_options)
cvat_052          |   File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 364, in execute
cvat_052          |     output = self.handle(*args, **options)
cvat_052          |   File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 83, in wrapped
cvat_052          |     res = handle_func(*args, **kwargs)
cvat_052          |   File "/usr/local/lib/python3.5/dist-packages/django/core/management/commands/migrate.py", line 257, in handle
cvat_052          |     self.verbosity, self.interactive, connection.alias, apps=post_migrate_apps, plan=plan,
cvat_052          |   File "/usr/local/lib/python3.5/dist-packages/django/core/management/sql.py", line 51, in emit_post_migrate_signal
cvat_052          |     **kwargs
cvat_052          |   File "/usr/local/lib/python3.5/dist-packages/django/dispatch/dispatcher.py", line 175, in send
cvat_052          |     for receiver in self._live_receivers(sender)
cvat_052          |   File "/usr/local/lib/python3.5/dist-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
cvat_052          |     for receiver in self._live_receivers(sender)
cvat_052          |   File "/home/django/cvat/apps/authentication/auth.py", line 21, in create_groups
cvat_052          |     db_group, _ = Group.objects.get_or_create(name=role)
cvat_052          |   File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py", line 82, in manager_method
cvat_052          |     return getattr(self.get_queryset(), name)(*args, **kwargs)
cvat_052          |   File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 538, in get_or_create
cvat_052          |     return self.get(**kwargs), False
cvat_052          |   File "/usr/local/lib/python3.5/dist-packages/cacheops/query.py", line 354, in get
cvat_052          |     return qs._no_monkey.get(qs, *args, **kwargs)
cvat_052          |   File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 412, in get
cvat_052          |     (self.model._meta.object_name, num)
cvat_052          | django.contrib.auth.models.MultipleObjectsReturned: get() returned more than one Group -- it returned 2!
cvat_052          |
cvat_052          | 2020-01-15 09:39:33,693 DEBG fd 21 closed, stopped monitoring <POutputDispatcher at 139680959827624 for <Subprocess at 139680960012944 with name runserver in state RUNNING> (stdout)>
cvat_052          | 2020-01-15 09:39:33,694 DEBG fd 27 closed, stopped monitoring <POutputDispatcher at 139680959776600 for <Subprocess at 139680960012944 with name runserver in state RUNNING> (stderr)>
cvat_052          | 2020-01-15 09:39:33,694 INFO exited: runserver (exit status 1; not expected)
cvat_052          | 2020-01-15 09:39:33,694 DEBG received SIGCLD indicating a child quit
cvat_052          | 2020-01-15 09:39:34,703 INFO spawned: 'runserver' with pid 4291
cvat_052          | 2020-01-15 09:39:34,721 DEBG 'runserver' stderr output:
cvat_052          | wait-for-it.sh: waiting for db:5432 without a timeout
cvat_052          |
cvat_052          | 2020-01-15 09:39:34,726 DEBG 'runserver' stderr output:
cvat_052          | wait-for-it.sh: db:5432 is available after 0 seconds

```

**Comment by azhavoro** [comment]
Hi @aquac, thanks for the report.
Couple of questions:
What version of CVAT are you using (git hash would be nice)?
Could you please provide steps how to you got this CVAT behaviour?
Did you modify any source code files?
Also could you please attach output of the following command:
```sh
docker exec -it cvat_db bash
psql cvat
SELECT * FROM auth_group;
```

**Comment by IbrahimShamma99** [comment]
Try pip3 install -r cvat/requirements/all.txt 
to install all dependencies

**Comment by azhavoro** [comment]
No response from @aquac. I will close the issue for now. You can reopen it if the issue still exists.
