### ISSUE TITLE
Error when dumping annotations Error: Request failed with status code 500. "TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'\n".

### ISSUE THREAD

**Issue by Diaislam** [opencv/cvat#1175]
for the first time i meet this error when i tied to dump annotations 

Error: Request failed with status code 500. "TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'\n".

logs  : 

2020-02-21 11:37:18,791 DEBG 'rqworker_default_0' stderr output:
11:37:18 TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rq/worker.py", line 812, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 588, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 594, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/django/cvat/apps/engine/annotation.py", line 133, in dump_task_data
    annotation.init_from_db()
  File "/home/django/cvat/apps/engine/annotation.py", line 720, in init_from_db
    self._merge_data(annotation.ir_data, start_frame, overlap)
  File "/home/django/cvat/apps/engine/annotation.py", line 691, in _merge_data
    data_manager.merge(data, start_frame, overlap)
  File "/home/django/cvat/apps/engine/data_manager.py", line 19, in merge
    shapes.merge(data.shapes, start_frame, overlap)
  File "/home/django/cvat/apps/engine/data_manager.py", line 71, in merge
    new_objects = [obj for obj in objects
  File "/home/django/cvat/apps/engine/data_manager.py", line 72, in <listcomp>
    if obj["frame"] >= start_frame + overlap]
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rq/worker.py", line 812, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 588, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 594, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/django/cvat/apps/engine/annotation.py", line 133, in dump_task_data
    annotation.init_from_db()
  File "/home/django/cvat/apps/engine/annotation.py", line 720, in init_from_db
    self._merge_data(annotation.ir_data, start_frame, overlap)
  File "/home/django/cvat/apps/engine/annotation.py", line 691, in _merge_data
    data_manager.merge(data, start_frame, overlap)
  File "/home/django/cvat/apps/engine/data_manager.py", line 19, in merge
    shapes.merge(data.shapes, start_frame, overlap)
  File "/home/django/cvat/apps/engine/data_manager.py", line 71, in merge
    new_objects = [obj for obj in objects
  File "/home/django/cvat/apps/engine/data_manager.py", line 72, in <listcomp>
    if obj["frame"] >= start_frame + overlap]
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

 <AnnotationDumper: AnnotationDumper object (CVAT XML 1.1 for images)>, 'http', 'localhost:8080') (user@/api/v1/tasks/102/annotations/CVAT XML 1.1 for images/task)

**Comment by Diaislam** [comment]
when i go to the task link : localhost:8080/api/v1/tasks/102/annotations
its showing Server Error (500)

This error happens only with this task

**Comment by azhavoro** [comment]
@Diaislam Hi, thanks for the report. 
Could you please open admin panel http://localhost:8080/admin/engine/task/102/change/ and attach screenshot of this page?

**Comment by Diaislam** [comment]
![image](https://user-images.githubusercontent.com/33395350/75044831-8f224d80-54c2-11ea-99a8-cd25b8e47c34.png)

@azhavoro

**Comment by Diaislam** [comment]
@azhavoro 
![image](https://user-images.githubusercontent.com/33395350/75044981-cbee4480-54c2-11ea-9947-e0abcba64cd7.png)

**Comment by azhavoro** [comment]
@Diaislam what is value of `overlap` field?

**Comment by Diaislam** [comment]
@azhavoro 
its emtpy value = "-"

**Comment by azhavoro** [comment]
You try to dump annotation for task that is not properly created, it has no data(size == 0, start_frame==0, stop_frame==0 and overlap field is NULL in the database). How do you create this task? I mean web interface or via CLI util?

**Comment by Diaislam** [comment]
@azhavoro

**Comment by Diaislam** [comment]
@azhavoro 
i have created this task using CLI util
i have created more than 1000 tasks using util and all of them are working except for this one
the problem is that i annotated it all and it contains 4200 objects

**Comment by azhavoro** [comment]
@Diaislam can you open the task page http://localhost:8080/tasks/102 ?

**Comment by Diaislam** [comment]
![image](https://user-images.githubusercontent.com/33395350/75049041-cd6f3b00-54c9-11ea-861b-91ee6303b50a.png)

**Comment by Diaislam** [comment]
![image](https://user-images.githubusercontent.com/33395350/75049202-18894e00-54ca-11ea-861c-156762e23647.png)

**Comment by azhavoro** [comment]
@Diaislam it's very strange....
Let's try to set overlap value manually:
```
docker exec -it cvat bash
python3 manage.py shell
>>> from cvat.apps.engine.models import Task
>>> db_task = Task.objects.get(pk=102)
>>> db_task.overlap = 0
>>> db_task.save()
>>> exit()
```
and try to dump it again

**Comment by Diaislam** [comment]
This worked Thank you very much for your help
