### ISSUE TITLE
can not annotation

### ISSUE THREAD

**Issue by 1329844541** [opencv/cvat#140]
Traceback (most recent call last):
  File "/home/mou/cvat/cvat/apps/engine/views.py", line 126, in get_frame
    return sendfile(request, path)
  File "/usr/local/lib/python3.5/dist-packages/sendfile/__init__.py", line 59, in sendfile
    raise Http404('"%s" does not exist' % filename)
django.http.response.Http404: "/home/mou/cvat/data/4/data/0/0/0.jpg" does not exist
[2018-10-18 11:34:46,318] WARNING django.server: "GET /get/task/4/frame/0 HTTP/1.1" 400 53
[2018-10-18 11:38:22,278] INFO django.server: "GET /dashboard/ HTTP/1.1" 200 12615
[2018-10-18 11:38:22,356] ERROR cvat.server.task_4: cannot get frame #0
Traceback (most recent call last):
  File "/home/mou/cvat/cvat/apps/engine/views.py", line 126, in get_frame
    return sendfile(request, path)
  File "/usr/local/lib/python3.5/dist-packages/sendfile/__init__.py", line 59, in sendfile
    raise Http404('"%s" does not exist' % filename)
djangohhttp.response.Http404: "/home/mou/cvat/data/4/data/0/0/0.jpg" does not exist
[2018-10-18 11:38:22,357] WARNING django.server: "GET /get/task/4/frame/0 HTTP/1.1" 400 53
How to start a vedio annotation?There is my Error when I Creat New Task.I do not know how to deal with it? 
Please help me.I would be very thankful.

**Comment by bsekachev** [comment]
@1329844541 
Are you sure, task was created successful? 
Please provide next files from docker container:
- /home/django/logs/*.log
- /home/django/data/4/*.log

**Comment by nmanovic** [comment]
@1329844541 ,

One more question. Do you run the tool locally without docker (/home/mou isn't typical path)?

**Comment by 1329844541** [comment]
> @1329844541
> Are you sure, task was created successful?
> Please provide next files from docker container:
> 
>     * /home/django/logs/*.log
> 
>     * /home/django/data/4/*.log

https://blog.csdn.net/qq_26572229/article/details/83150120
There can not past picture,so the link is the question's description.
I am a green hand.I am so happy you answer my issue.Thank you again

**Comment by 1329844541** [comment]
I was just do like this 

>  https://blog.csdn.net/minstyrain/article/details/82454991#commentBox

 And I am a rookie,do not know how to  run the tool locally without docker .Thank you for you answer.May be I should annotation by MATLAB may easy for me?

**Comment by 1329844541** [comment]
> @1329844541
> You can build tool without docker as showed [here](https://github.com/opencv/cvat/blob/develop/CONTRIBUTING.md#development-environment). But such approach is recommended for development only. It works slower than build with docker. Besides, with docker you wouldn't meet that problem, I suppose.
> If you want use development build, I think you need change mode in visual studio code from "CVAT Server" to "CVAT Debugging". "CVAT Debugging" also starts some RQ queues which are responsible for creating a task.

Thank you.You are very nice,I haven't met a person in git who reply question in real earnest.I will try it.Thanks again.

**Comment by bsekachev** [comment]
@1329844541 
Thanks a lot, 
Let me know if you will have any issues.
