### ISSUE TITLE
Unable to upload video with uneven size

### ISSUE THREAD

**Issue by zhiltsov-max** [opencv/cvat#1411]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

Task is created.

### Current Behaviour

Task creation fails.

### Possible Solution

MPEG4 requires even frame size. For compressed images there is padding applied, so no issue there. However, for source video there is no. May be, we can just use the original one, or add padding, or use another format.

### Steps to Reproduce (for bugs)

1. Get a random video with uneven frame size (I just used a screen record of size 1600x839)
1. Try to create a task from this video

### Your Environment

- Git hash commit (`git log -1`): cf511ae7cd2d319429445ac4a63cb32c35ea3bec
- Docker version `docker version` (e.g. Docker 17.0.05): -
- Are you using Docker Swarm or Kubernetes? -
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 18.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
   <details>
   <summary>Logs from `cvat` container</summary>
   
  INFO:cvat.server:create task #10
  ERROR:libav.libx264:height not divisible by 2 (1600x839)
  ERROR:rq.worker:av.AVError: [Errno 542398533] Generic error in an external library (16: libx264)
  Traceback (most recent call last):
    File "/home/max/cvat/.env/lib/python3.6/site-packages/rq/worker.py", line 812, in perform_job
      rv = job.perform()
    File "/home/max/cvat/.env/lib/python3.6/site-packages/rq/job.py", line 588, in perform
      self._result = self._execute()
    File "/home/max/cvat/.env/lib/python3.6/site-packages/rq/job.py", line 594, in _execute
      return self.func(*self.args, **self.kwargs)
    File "/usr/lib/python3.6/contextlib.py", line 52, in inner
      return func(*args, **kwds)
    File "/home/max/cvat/cvat/apps/engine/task.py", line 284, in _create_thread
      original_chunk_writer.save_as_chunk(chunk_data, original_chunk_path)
    File "/home/max/cvat/cvat/apps/engine/media_extractors.py", line 333, in save_as_chunk
      self._encode_images(images, output_container, output_v_stream)
    File "/home/max/cvat/cvat/apps/engine/media_extractors.py", line 344, in _encode_images
      for packet in stream.encode(frame):
    File "av/stream.pyx", line 130, in av.stream.Stream.encode
    File "av/codec/context.pyx", line 309, in av.codec.context.CodecContext.encode
    File "av/codec/context.pyx", line 138, in av.codec.context.CodecContext.open
    File "av/utils.pyx", line 109, in av.utils.err_check
   av.AVError: [Errno 542398533] Generic error in an external library (16: libx264)
   
   </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@azhavoro , I think it is a critical issue for the release.
