### ISSUE TITLE
ZeroDivisionError when attempting to download annotations

### ISSUE THREAD

**Issue by akarimbux** [opencv/cvat#1437]
### My actions before raising this issue
I searched both existing issues and gitter for this error and couldn't find a reference

### Current Behaviour
XML that causes this issue attached.

I am running into an issue with the TASK endpoint where annotations that have loaded successfully raise an error when I attempt to download them. The created task has a segment size of 1500 frames and 5 frames of overlap. This generates 2 jobs against which the attached annotation xml file is loaded. 

Without making any changes to the annotations, attempting to download them, throws the following error:

`
2020-04-20 17:56:51,915 DEBG 'rqworker_default_1' stderr output:
17:56:51 cvat.apps.engine.utils.InterpreterError: AssertionError
Traceback (most recent call last):
  File "/home/django/cvat/apps/engine/utils.py", line 45, in execute_python_code
    exec(source_code, global_vars, local_vars)
  File "<string>", line 1, in <module>
  File "<string>", line 393, in dump_as_cvat_interpolation
  File "/home/django/cvat/apps/annotation/annotation.py", line 341, in tracks
    tracked_shapes = TrackManager.get_interpolated_shapes(track, 0, self._db_task.size)
  File "/home/django/cvat/apps/engine/data_manager.py", line 360, in get_interpolated_shapes
    assert shape["frame"] > curr_frame
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rq/worker.py", line 812, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 588, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 594, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/django/cvat/apps/engine/annotation.py", line 135, in dump_task_data
    annotation.dump(filename, dumper, scheme, host)
  File "/home/django/cvat/apps/engine/annotation.py", line 740, in dump
    execute_python_code("{}(file_object, annotations)".format(dumper.handler), global_vars)
  File "/home/django/cvat/apps/engine/utils.py", line 54, in execute_python_code
    raise InterpreterError("{}".format(error_class))
cvat.apps.engine.utils.InterpreterError: AssertionError
Traceback (most recent call last):
  File "/home/django/cvat/apps/engine/utils.py", line 45, in execute_python_code
    exec(source_code, global_vars, local_vars)
  File "<string>", line 1, in <module>
  File "<string>", line 393, in dump_as_cvat_interpolation
  File "/home/django/cvat/apps/annotation/annotation.py", line 341, in tracks
    tracked_shapes = TrackManager.get_interpolated_shapes(track, 0, self._db_task.size)
  File "/home/django/cvat/apps/engine/data_manager.py", line 360, in get_interpolated_shapes
    assert shape["frame"] > curr_frame
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rq/worker.py", line 812, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 588, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 594, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/django/cvat/apps/engine/annotation.py", line 135, in dump_task_data
    annotation.dump(filename, dumper, scheme, host)
  File "/home/django/cvat/apps/engine/annotation.py", line 740, in dump
    execute_python_code("{}(file_object, annotations)".format(dumper.handler), global_vars)
  File "/home/django/cvat/apps/engine/utils.py", line 54, in execute_python_code
    raise InterpreterError("{}".format(error_class))
cvat.apps.engine.utils.InterpreterError: AssertionError
`

Sometimes a different error is thrown using the same set of actions above:
`
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rq/worker.py", line 812, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 588, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 594, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/django/cvat/apps/engine/annotation.py", line 112, in load_task_data
    annotation.upload(filename, loader)
  File "/home/django/cvat/apps/engine/annotation.py", line 761, in upload
    self.create(annotation_importer.data.serialize())
  File "/home/django/cvat/apps/engine/annotation.py", line 697, in create
    self._patch_data(data, PatchAction.CREATE)
  File "/home/django/cvat/apps/engine/annotation.py", line 687, in _patch_data
    self._merge_data(_data, jobs[jid]["start"], self.db_task.overlap)
  File "/home/django/cvat/apps/engine/annotation.py", line 691, in _merge_data
    data_manager.merge(data, start_frame, overlap)
  File "/home/django/cvat/apps/engine/data_manager.py", line 22, in merge
    tracks.merge(data.tracks, start_frame, overlap)
  File "/home/django/cvat/apps/engine/data_manager.py", line 107, in merge
    int_obj, old_obj, start_frame, overlap)
  File "/home/django/cvat/apps/engine/data_manager.py", line 278, in _calc_objects_similarity
    return 1 - error / count
ZeroDivisionError: division by zero
`

### Your Environment

- Git hash commit (`git log -1`): feebec2670186f8f56f4314cb45d596d5dc13e8a
- Docker version `docker version` (e.g. Docker 17.0.05): 19.03.8
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

[bad.xml.txt](https://github.com/opencv/cvat/files/4505548/bad.xml.txt)

**Comment by nmanovic** [comment]
@azhavoro , please verify that we already have a fix for the issue. Otherwise please assign a correct milestone target.

**Comment by azhavoro** [comment]
should be fixed by https://github.com/opencv/cvat/pull/1396, but need to re-upload annotation.

**Comment by joon612** [comment]
It seems reproduced in current version. (commit id: 2b221d26fd65cd4f7c81d19247459f3f2416ed73).
We have 1 task including 11 jobs. After annotation, we cannot dump annotations by 'cvat for videos 1.1'.
![image](https://user-images.githubusercontent.com/34393671/119450030-f8e47380-bd65-11eb-92a5-f6aa32be7f82.png)

![image](https://user-images.githubusercontent.com/34393671/119449979-e5d1a380-bd65-11eb-8af2-7c677297b868.png)

**Comment by azhavoro** [comment]
@joon612 Please provide steps to reproduce this issue

**Comment by joon612** [comment]
@azhavoro 
We create a cvat task by cli, including 11 jobs, "segment_size": 4500.
After that we do annotation jobs, labeling manually.
After annotation job, we save operations and return to task page.
We use 'Actions -> Dump annotations -> CVAT for video 1.1' to dump annotation file.
Finally we got this error in the upper right corner of the screen.
![image](https://user-images.githubusercontent.com/34393671/119456730-8d060900-bd6d-11eb-9806-046b7d1eb793.png)

Thanks.
