### ISSUE TITLE
Feature: custom label colors

### ISSUE THREAD

**Issue by M-Younus** [opencv/cvat#1480]
Is this possible?
Like red for person,blue for car,so whenever I annotate a car it should've blue color and whenever I annotate person it should've red color.

**Comment by zhiltsov-max** [comment]
Currently, there is no way to do this in UI. However, it is possible in [Datumaro](https://github.com/opencv/cvat/tree/master/datumaro), where you can provide a custom colormap for export in `voc_segmentation` format.

**Comment by nmanovic** [comment]
@M-Younus , please don't ignore our issue template. You can choose a color in UI for a label (temporary). I will close the issue. Don't hesitate to re-open if you can share more information how you want it should be implemented.

**Comment by zhiltsov-max** [comment]
@bsekachev, as we already have a temporary color selector for labels in UI
![image](https://user-images.githubusercontent.com/13832349/81679721-1ac0d000-945b-11ea-878c-1a9cc530b59b.png)
can we extend this to be persistent and provide same selector at the task page?
Here: 
![image](https://user-images.githubusercontent.com/13832349/81678237-219b1300-945a-11ea-868a-8286acfe4b7a.png)
As tasks can have more than N labels, I think it would be nice to provide just a typical color selector like we can see in most of image editors - with exact numbers and a palette.

<details>

Example (PDN):
![image](https://user-images.githubusercontent.com/13832349/81679558-fa911100-945a-11ea-894b-1e03fac2401f.png)

</details>

**Comment by bsekachev** [comment]
@zhiltsov-max 

We can, but:
1) First need implement the feature on the server (storing color in the database)
2) I suppose predefined colors not enough in general case. We need something [more advanced](https://casesandberg.github.io/react-color/). But on the first iteration we might support only predefined colors.

**Comment by creativesiva** [comment]
> Currently, there is no way to do this in UI. However, it is possible in [Datumaro](https://github.com/opencv/cvat/tree/master/datumaro), where you can provide a custom colormap for export in `voc_segmentation` format.

Hi Could you please let suggest how to setup custom colors for segmentation using Datumaro
Thanks

**Comment by zhiltsov-max** [comment]
Please check the last example [here](https://github.com/opencv/cvat/tree/develop/datumaro#examples).

**Comment by creativesiva** [comment]
Could you pls help me to fix below issue, I am running this command "datum project import --format voc --input-path /home/aipl/segmentation/images/siva"

(myannotation) siva@siva-dl:~$ datum project import --format voc --input-path /home/aipl/segmentation/images/siva
2020-08-03 18:25:13,355 WARNING: Failed to import module 'openvino_launcher.py': libpython3.7m.so.1.0: cannot open shared object file: No such file or directory
2020-08-03 18:25:15,691 INFO: Importing project from '/home/aipl/segmentation/images/siva'
2020-08-03 18:25:15,691 INFO: Importing project as 'voc'
2020-08-03 18:25:15,691 INFO: Checking the dataset...
2020-08-03 18:25:15,696 ERROR: Train
Traceback (most recent call last):
  File "/home/aipl/anaconda3/envs/myannotation/bin/datum", line 8, in <module>
    sys.exit(main())
  File "/home/aipl/anaconda3/envs/myannotation/lib/python3.8/site-packages/datumaro/cli/__main__.py", line 114, in main
    return args.command(args)
  File "/home/aipl/anaconda3/envs/myannotation/lib/python3.8/site-packages/datumaro/cli/contexts/project/__init__.py", line 222, in import_command
    dataset = project.make_dataset()
  File "/home/aipl/anaconda3/envs/myannotation/lib/python3.8/site-packages/datumaro/components/project.py", line 815, in make_dataset
    return ProjectDataset(self)
  File "/home/aipl/anaconda3/envs/myannotation/lib/python3.8/site-packages/datumaro/components/project.py", line 554, in __init__
    for item in source:
  File "/home/aipl/anaconda3/envs/myannotation/lib/python3.8/site-packages/datumaro/plugins/voc_format/extractor.py", line 127, in __iter__
    anns = self._parse_annotations(root_elem)
  File "/home/aipl/anaconda3/envs/myannotation/lib/python3.8/site-packages/datumaro/plugins/voc_format/extractor.py", line 147, in _parse_annotations
    obj_label_id = self._get_label_id(label_elem.text)
  File "/home/aipl/anaconda3/envs/myannotation/lib/python3.8/site-packages/datumaro/plugins/voc_format/extractor.py", line 54, in _get_label_id
    assert label_id is not None, label
AssertionError: Train

**Comment by zhiltsov-max** [comment]
Apparently, the dataset has a `Train` class, which is not listed in the `labelmap.txt`, make sure all the classes are listed in this file. Names are case sensitive. More information on the file usage [here](https://github.com/opencv/cvat/tree/develop/cvat/apps/dataset_manager/formats#segmentation-mask-import).

**Comment by creativesiva** [comment]
It worked now. Thanks a lot.

**Comment by creativesiva** [comment]
Looks like there is limitation in the #colors, I am trying to add 70 classes (labelmap.txt), But when i download the project after segmentation using UI, the labelmap color codes are changing.
