### ISSUE TITLE
Potential Datumaro Bug  ( And Solution )

### ISSUE THREAD

**Issue by ID56** [opencv/cvat#1494]
Hello. I opened a prior issue here for getting annotations of unannotated images: #1350 . The solution was very precise and simple, but there seemed to be a problem. I could export the project in other formats but not cvat, which kept throwing an error. Here's the trace:

> (restenv) mashrur@dealer-hp:~/This_PC/Work/datumaro-sandbox/test_project_0$ datum project export -f cvat
2020-05-06 00:31:42,240 ERROR: __init__() missing 1 required positional argument: 'self'
Traceback (most recent call last):
  File "/home/mashrur/anaconda3/envs/restenv/bin/datum", line 8, in <module>
    sys.exit(main())
  File "/home/mashrur/anaconda3/envs/restenv/lib/python3.6/site-packages/datumaro/cli/__main__.py", line 156, in main
    return args.command(args)
  File "/home/mashrur/anaconda3/envs/restenv/lib/python3.6/site-packages/datumaro/cli/contexts/project/__init__.py", line 310, in export_command
    extra_args = converter.from_cmdline(args.extra_args)
  File "/home/mashrur/anaconda3/envs/restenv/lib/python3.6/site-packages/datumaro/components/cli_plugin.py", line 36, in from_cmdline
    parser = cls.build_cmdline_parser()
  File "/home/mashrur/anaconda3/envs/restenv/lib/python3.6/site-packages/datumaro/plugins/cvat_format/converter.py", line 373, in build_cmdline_parser
    parser = super().__init__(**kwargs)
TypeError: __init__() missing 1 required positional argument: 'self'

It works fine for exporting in other formats like voc, coco or datumaro. Since I had a manual workaround, I didn't spend much time on reviewing this, but sometime back I returned to this problem to see if I could figure out what's wrong. build_cmdline_parser isn't taking self and thus calling super().\_\_init()\_\_ in it is a bit strange. After checking out the superclasses of the CvatConverter I figured out a fix:

This is from datumaro>plugins>cvat_format>converter.py:

    class CvatConverter(Converter, CliPlugin):
        @classmethod
        def build_cmdline_parser(cls, **kwargs):
            parser = super().__init__(**kwargs)
            parser.add_argument('--save-images', action='store_true',
                help="Save images (default: %(default)s)")
            return parser
If we change the above to:

    class CvatConverter(Converter, CliPlugin):
        @classmethod
        def build_cmdline_parser(cls, **kwargs):
            parser = super().build_cmdline_parser(**kwargs) #super().__init__(**kwargs)
            parser.add_argument('--save-images', action='store_true',
                help="Save images (default: %(default)s)")
            return parser

Now it works fine and exports in cvat format as I wanted. 

> (restenv) mashrur@dealer-hp:~/This_PC/Work/datumaro-sandbox/test_project_0$ datum project export -f cvat
2020-05-06 00:47:06,574 INFO: Loading the project...
2020-05-06 00:47:06,575 INFO: Exporting the project...
2020-05-06 00:47:06,579 INFO: Project exported to '/home/mashrur/This_PC/Work/datumaro-sandbox/test_project_0/test_project_0-cvat' as 'cvat'

I'm not sure if this is a bug (it could be some problem with my installation/environment?), so I'm again opening an issue to get your opinion on this. If this is indeed a bug, then should I open a pull request?

**Comment by ID56** [comment]
Also referencing #1488 here as this solves that too.

**Comment by zhiltsov-max** [comment]
Hi, thanks for the report. This problem is already going to be fixed with #1352.

**Comment by ID56** [comment]
Alright then, I'll close the issue. Thanks!
