### ISSUE TITLE
Error after removing a tag

### ISSUE THREAD

**Issue by mkostiv** [opencv/cvat#1540]
Steps to reproduce:
1. Add a tag to an image
2. Try to remove tag -> Crash
3. Reload the page, select the frame with a tag you previously tried to remove
4. Hover the mouse over the tag -> Crash

TypeError
Cannot read property 'removeClass' of undefined

TypeError: Cannot read property 'removeClass' of undefined
    at Mu.deactivateShape (http://34.91.5.56:8080/cvat-ui.min.js:72:1383456)
    at Mu.deactivate (http://34.91.5.56:8080/cvat-ui.min.js:72:1383969)
    at Mu.activate (http://34.91.5.56:8080/cvat-ui.min.js:72:1386548)
    at Mu.notify (http://34.91.5.56:8080/cvat-ui.min.js:72:1376400)
    at Cc.notify (http://34.91.5.56:8080/cvat-ui.min.js:72:1293622)
    at Cc.activate (http://34.91.5.56:8080/cvat-ui.min.js:72:1296706)
    at Lu.activate (http://34.91.5.56:8080/cvat-ui.min.js:72:1391016)
    at od.componentDidUpdate (http://34.91.5.56:8080/cvat-ui.min.js:72:1424991)
    at yl (http://34.91.5.56:8080/cvat-ui.min.js:43:100837)
    at t.unstable_runWithPriority (http://34.91.5.56:8080/cvat-ui.min.js:51:3465)
<img width="1675" alt="Screen Shot 2020-05-14 at 9 45 30 PM" src="https://user-images.githubusercontent.com/45266535/81973070-4646e480-962c-11ea-9a8b-5564d1d6bdda.png">

**Comment by mkostiv** [comment]
`git describe` 0.2.0-706-g6566e4a

**Comment by bsekachev** [comment]
Also found the issue. It is enough just to deactivate a tag. 

@ActiveChooN could you please look into this?

**Comment by ActiveChooN** [comment]
@bsekachev, maybe it's good idea to add activated shape id checking in cvat-canvas in activation method, is it?
