### ISSUE TITLE
CVAT new UI: Error when switching to another frame immediately after opening the job

### ISSUE THREAD

**Issue by TOsmanov** [opencv/cvat#1611]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

N/A
### Current Behaviour

An error occurs if you switch to a large number of frames ahead (by clicking on the slider), approximately 5 seconds after the task is opened.

### Possible Solution

N/A
### Steps to Reproduce (for bugs)

1. Open job
1. Wait ~5 seconds
1. Switch to a another frame (by clicking on the player slider)

### Context

CVAT version
Server: 1.0rc0
Core: 2.0.1
Canvas: 1.1.1
UI: 1.2.0

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS): Windows 10 and Chrome Version 83.0.4103.61 (Official Build) (64-bit)
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Error message
TypeError
Cannot read property 'objectType' of undefined

TypeError: Cannot read property 'objectType' of undefined
    at ld.activateOnCanvas (.../cvat-ui.min.js:72:1424130)
    at ld.componentDidUpdate (.../cvat-ui.min.js:72:1422014)
    at yl (.../cvat-ui.min.js:43:100837)
    at t.unstable_runWithPriority (.../cvat-ui.min.js:51:3465)
    at Br (.../cvat-ui.min.js:43:45441)
    at gl (.../cvat-ui.min.js:43:97113)
    at ol (.../cvat-ui.min.js:43:87489)
    at .../cvat-ui.min.js:43:45732
    at t.unstable_runWithPriority (.../cvat-ui.min.js:51:3465)
    at Br (.../cvat-ui.min.js:43:45441)</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by fBacak97** [comment]
We are also experiencing the same issue and it happens way often than just at the first 5 seconds. Any progress on a fix?

**Comment by Sentient07** [comment]
Hi,

I've just faced this issue. My CVAT is at `7679434bc200385d5ceb7544ac2f094403756587` and docker logs : 

```
2020-08-01 22:57:03,115 DEBG 'runserver' stderr output:
[Sat Aug 01 22:57:03.115762 2020] [wsgi:error] [pid 172:tid 140089708197632] [remote 172.19.0.6:40698] ERROR:cvat.client.task_1:{"client":"chrome","job_id":1,"message":"Cannot read property 'objectType' of undefined","name":"Send exception","client_id":518608,"column":1424130,"stack":"TypeError: Cannot read property 'objectType' of undefined\\n    at ld.activateOnCanvas (http://pneuma.irisa.fr:8080/cvat-ui.min.js:72:1424130)\\n    at ld.componentDidUpdate (http://pneuma.irisa.fr:8080/cvat-ui.min.js:72:1422014)\\n    at yl (http://pneuma.irisa.fr:8080/cvat-ui.min.js:43:100837)\\n    at t.unstable_runWithPriority (http://pneuma.irisa.fr:8080/cvat-ui.min.js:51:3465)\\n    at Br (http://pneuma.irisa.fr:8080/cvat-ui.min.js:43:45441)\\n    at gl (http://pneuma.irisa.fr:8080/cvat-ui.min.js:43:97113)\\n    at ol (http://pneuma.irisa.fr:8080/cvat-ui.min.js:43:87489)\\n    at http://pneuma.irisa.fr:8080/cvat-ui.min.js:43:45732\\n    at t.unstable_runWithPriority (http://pneuma.irisa.fr:8080/cvat-ui.min.js:51:3465)\\n    at Br (http://pneuma.irisa.fr:8080/cvat-ui.min.js:43:45441)","task_id":1,"time":"2020-08-01T22:57:02.340000Z","username":"abc123","filename":"http://pneuma.irisa.fr:8080/cvat-ui.min.js","line":72,"system":"Windows 10"}
```

**Comment by Sentient07** [comment]
@azhavoro I am not sure whether I have the correct rights to reopen this issue. Could you please do it? Furthermore, my client faces this issue quiet often. They were able to reproduce, but however, that screenshot and the above-mentioned logs are the only thing we could see. Could you please advise what to do?

**Comment by azhavoro** [comment]
@Sentient07 Thanks for the report, it would be nice if you provided steps to reproduce this issue.

**Comment by vskubriev** [comment]
Hello everyone. We a faced same issue on `d0b9481`. CVAT deployed at commit `d0b9481` approximately before release `v1.0.0`.

We are working on the annotation for about 6 months (the CVAT instance is the same, ~ 60 tasks and ~ 1150 jobs, each job contains 100 images). We come across this issue when:
a) Our data scientist tries to jump from the first image in the job to, for example, 80 ones or 90 ones by entering this number in the appropriate field.
b) Our data scientist jums over images within a job very quickly by clicking next all the time.

This issue happens NOT every time when above-stated occurs.

We will appreciate if anybody can help us to find out what's happened on client browsers.

This error haunts us since instance setuped (about a year ago). And applies to almost every data scientist, whos using this instance. About a thousand such errors occurred in a year.

From server point of view that look like follows:

```
{"time":"2021-02-17T21:14:14.973000Z","username":"someuser","name":"Fit image","is_active":true,"client_id":682228,"task_id":254,"payload":{},"job_id":2426}
{"time":"2021-02-17T21:14:15.483000Z","username":"someuser","name":"Change frame","is_active":true,"client_id":682228,"task_id":254,"payload":{"from":1071,"to":1070},"job_id":2426}
{"time":"2021-02-17T21:14:15.510000Z","username":"someuser","name":"Fit image","is_active":true,"client_id":682228,"task_id":254,"payload":{},"job_id":2426}
{"time":"2021-02-17T21:14:19.402000Z","username":"someuser","name":"Change frame","is_active":true,"client_id":682228,"task_id":254,"payload":{"from":1070,"to":1071},"job_id":2426}
{"time":"2021-02-17T21:14:19.421000Z","username":"someuser","name":"Fit image","is_active":true,"client_id":682228,"task_id":254,"payload":{},"job_id":2426}
{"time":"2021-02-17T21:14:19.969000Z","username":"someuser","name":"Change frame","is_active":true,"client_id":682228,"task_id":254,"payload":{"from":1071,"to":1072},"job_id":2426}
{"time":"2021-02-17T21:14:19.989000Z","username":"someuser","name":"Fit image","is_active":true,"client_id":682228,"task_id":254,"payload":{},"job_id":2426}
{"time":"2021-02-17T21:14:21.021000Z","username":"someuser","name":"Save job","is_active":true,"client_id":682228,"task_id":254,"payload":{"duration":2379},"job_id":2426}
{"time":"2021-02-17T21:14:23.401000Z","username":"someuser","name":"Send task info","is_active":true,"client_id":682228,"task_id":254,"payload":{"track count":241,"tag count":0,"polyline count":0,"polygon count":241,"frame count":100,"object count":241,"points count":0,"cuboids count":0,"box count":0},"job_id":2426}
{"time":"2021-02-17T21:14:23.409000Z","username":"someuser","name":"Send user activity","is_active":true,"client_id":682228,"task_id":254,"payload":{"working_time":220786},"job_id":2426}
{"time":"2021-02-17T21:14:28.053000Z","username":"someuser","name":"Change frame","is_active":true,"client_id":682228,"task_id":254,"payload":{"from":1072,"to":1073},"job_id":2426}
{"time":"2021-02-17T21:14:28.085000Z","username":"someuser","name":"Fit image","is_active":true,"client_id":682228,"task_id":254,"payload":{},"job_id":2426}
{"time":"2021-02-17T21:14:30.011000Z","username":"someuser","name":"Change frame","is_active":true,"client_id":682228,"task_id":254,"payload":{"from":1073,"to":1074},"job_id":2426}
{"time":"2021-02-17T21:14:30.030000Z","username":"someuser","name":"Fit image","is_active":true,"client_id":682228,"task_id":254,"payload":{},"job_id":2426}
{"time":"2021-02-17T21:14:30.542000Z","username":"someuser","name":"Change frame","is_active":true,"client_id":682228,"task_id":254,"payload":{"from":1074,"to":1075},"job_id":2426}
{"time":"2021-02-17T21:14:30.576000Z","username":"someuser","name":"Fit image","is_active":true,"client_id":682228,"task_id":254,"payload":{},"job_id":2426}
{"time":"2021-02-17T21:14:31.174000Z","username":"someuser","name":"Change frame","is_active":true,"client_id":682228,"task_id":254,"payload":{"from":1075,"to":1076},"job_id":2426}
{"time":"2021-02-17T21:14:31.196000Z","username":"someuser","name":"Fit image","is_active":true,"client_id":682228,"task_id":254,"payload":{},"job_id":2426}
{"time":"2021-02-17T21:14:31.750000Z","username":"someuser","name":"Change frame","is_active":true,"client_id":682228,"task_id":254,"payload":{"from":1076,"to":1077},"job_id":2426}
{"time":"2021-02-17T21:14:31.775000Z","username":"someuser","name":"Fit image","is_active":true,"client_id":682228,"task_id":254,"payload":{},"job_id":2426}
{"time":"2021-02-17T21:14:33.215000Z","username":"someuser","name":"Change frame","is_active":true,"client_id":682228,"task_id":254,"payload":{"from":1077,"to":1078},"job_id":2426}
{"time":"2021-02-17T21:14:33.242000Z","username":"someuser","name":"Fit image","is_active":true,"client_id":682228,"task_id":254,"payload":{},"job_id":2426}
{"time":"2021-02-17T21:14:34.680000Z","username":"someuser","name":"Change frame","is_active":true,"client_id":682228,"task_id":254,"payload":{"from":1078,"to":1079},"job_id":2426}
{"time":"2021-02-17T21:14:34.707000Z","username":"someuser","name":"Fit image","is_active":true,"client_id":682228,"task_id":254,"payload":{},"job_id":2426}
{"time":"2021-02-17T21:14:35.744000Z","username":"someuser","name":"Change frame","is_active":true,"client_id":682228,"task_id":254,"payload":{"from":1079,"to":1080},"job_id":2426}
{"column":1423832,"username":"someuser","task_id":254,"filename":"https://cvat-traffic.example.com/cvat-ui.min.js","client_id":682228,"line":72,"client":"chrome","time":"2021-02-17T21:14:36.512000Z","system":"Windows 10","name":"Send exception","stack":"TypeError: Cannot read property 'objectType' of undefined\n    at ld.activateOnCanvas (https://cvat-traffic.example.com/cvat-ui.min.js:72:1423832)\n    at ld.componentDidUpdate (https://cvat-traffic.example.com/cvat-ui.min.js:72:1421716)\n    at yl (https://cvat-traffic.example.com/cvat-ui.min.js:43:100837)\n    at t.unstable_runWithPriority (https://cvat-traffic.example.com/cvat-ui.min.js:51:3465)\n    at Br (https://cvat-traffic.example.com/cvat-ui.min.js:43:45441)\n    at gl (https://cvat-traffic.example.com/cvat-ui.min.js:43:97113)\n    at ol (https://cvat-traffic.example.com/cvat-ui.min.js:43:87489)\n    at https://cvat-traffic.example.com/cvat-ui.min.js:43:45732\n    at t.unstable_runWithPriority (https://cvat-traffic.example.com/cvat-ui.min.js:51:3465)\n    at Br (https://cvat-traffic.example.com/cvat-ui.min.js:43:45441)","job_id":2426,"message":"Cannot read property 'objectType' of undefined"}
{"time":"2021-02-17T21:15:23.885000Z","username":"someuser","name":"Load job","is_active":true,"client_id":521794,"task_id":254,"payload":{"duration":4187,"track count":241,"tag count":0,"polyline count":0,"object count":241,"frame count":100,"polygon count":241,"points count":0,"cuboids count":0,"box count":0},"job_id":2426}
{"time":"2021-02-17T21:15:28.081000Z","username":"someuser","name":"Fit image","is_active":true,"client_id":521794,"task_id":254,"payload":{},"job_id":2426}
{"time":"2021-02-17T21:15:55.709000Z","username":"someuser","name":"Change frame","is_active":true,"client_id":521794,"task_id":254,"payload":{"from":1000,"to":1050},"job_id":2426}
{"time":"2021-02-17T21:15:56.353000Z","username":"someuser","name":"Fit image","is_active":true,"client_id":521794,"task_id":254,"payload":{},"job_id":2426}
{"time":"2021-02-17T21:15:59.561000Z","username":"someuser","name":"Change frame","is_active":true,"client_id":521794,"task_id":254,"payload":{"from":1050,"to":1051},"job_id":2426}
{"time":"2021-02-17T21:15:59.596000Z","username":"someuser","name":"Fit image","is_active":true,"client_id":521794,"task_id":254,"payload":{},"job_id":2426}
{"time":"2021-02-17T21:16:01.736000Z","username":"someuser","name":"Change frame","is_active":true,"client_id":521794,"task_id":254,"payload":{"from":1051,"to":1052},"job_id":2426}
{"time":"2021-02-17T21:16:01.793000Z","username":"someuser","name":"Fit image","is_active":true,"client_id":521794,"task_id":254,"payload":{},"job_id":2426}
{"time":"2021-02-17T21:16:02.271000Z","username":"someuser","name":"Change frame","is_active":true,"client_id":521794,"task_id":254,"payload":{"from":1052,"to":1053},"job_id":2426}
{"time":"2021-02-17T21:16:02.325000Z","username":"someuser","name":"Fit image","is_active":true,"client_id":521794,"task_id":254,"payload":{},"job_id":2426}
{"time":"2021-02-17T21:16:03.171000Z","username":"someuser","name":"Change frame","is_active":true,"client_id":521794,"task_id":254,"payload":{"from":1053,"to":1054},"job_id":2426}
{"time":"2021-02-17T21:16:03.204000Z","username":"someuser","name":"Fit image","is_active":true,"client_id":521794,"task_id":254,"payload":{},"job_id":2426}
{"time":"2021-02-17T21:16:04.002000Z","username":"someuser","name":"Change frame","is_active":true,"client_id":521794,"task_id":254,"payload":{"from":1054,"to":1055},"job_id":2426}
{"time":"2021-02-17T21:16:04.032000Z","username":"someuser","name":"Fit image","is_active":true,"client_id":521794,"task_id":254,"payload":{},"job_id":2426}
{"time":"2021-02-17T21:16:04.439000Z","username":"someuser","name":"Change frame","is_active":true,"client_id":521794,"task_id":254,"payload":{"from":1055,"to":1056},"job_id":2426}
{"time":"2021-02-17T21:16:04.461000Z","username":"someuser","name":"Fit image","is_active":true,"client_id":521794,"task_id":254,"payload":{},"job_id":2426}
{"time":"2021-02-17T21:16:04.875000Z","username":"someuser","name":"Change frame","is_active":true,"client_id":521794,"task_id":254,"payload":{"from":1056,"to":1057},"job_id":2426}
{"time":"2021-02-17T21:16:04.905000Z","username":"someuser","name":"Fit image","is_active":true,"client_id":521794,"task_id":254,"payload":{},"job_id":2426}
{"time":"2021-02-17T21:16:05.665000Z","username":"someuser","name":"Change frame","is_active":true,"client_id":521794,"task_id":254,"payload":{"from":1057,"to":1058},"job_id":2426}
```
