### ISSUE TITLE
Dump annotations with frame step: Key error

### ISSUE THREAD

**Issue by mkostiv** [opencv/cvat#1613]
**Steps to reproduce:**
1. Create a task with frame step (5 in my case)
2. Annotate a few images
3. Dump annotations

`git describe 0.2.0-750-g3f46258`

![image](https://user-images.githubusercontent.com/45266535/83173301-7eb4eb00-a121-11ea-8f06-0457062e01a4.png)

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rq/worker.py", line 812, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 588, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 594, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/django/cvat/apps/dataset_manager/views.py", line 87, in export_task_annotations
    return export_task(task_id, dst_format, server_url=server_url, save_images=False)
  File "/home/django/cvat/apps/dataset_manager/views.py", line 62, in export_task
    server_url=server_url, save_images=save_images)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 723, in export_task
    save_images=save_images)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 619, in export
    exporter(dst_file, task_data, **options)
  File "/home/django/cvat/apps/dataset_manager/formats/registry.py", line 35, in __call__
    f_or_cls(*args, **kwargs)
  File "/home/django/cvat/apps/dataset_manager/formats/cvat.py", line 545, in _export_images
    anno_callback=dump_as_cvat_annotation, save_images=save_images)
  File "/home/django/cvat/apps/dataset_manager/formats/cvat.py", line 517, in _export
    anno_callback(f, task_data)
  File "/home/django/cvat/apps/dataset_manager/formats/cvat.py", line 178, in dump_as_cvat_annotation
    for frame_annotation in annotations.group_by_frame(include_empty=True):
  File "/home/django/cvat/apps/dataset_manager/bindings.py", line 259, in group_by_frame
    get_frame(shape['frame']).labeled_shapes.append(
  File "/home/django/cvat/apps/dataset_manager/bindings.py", line 234, in get_frame
    frame_info = self._frame_info[idx]
KeyError: 1

**Comment by nmanovic** [comment]
@zhiltsov-max , do you think you can look at the issue tomorrow?
