### ISSUE TITLE
Attributes Annotation Broken

### ISSUE THREAD

**Issue by michaelmruta** [opencv/cvat#1614]
To reproduce issue,
- Open a job
- Switch view from 'Standard' to 'Attributes Annotation'
- Switch Frame w/ 'Go Next' or 'Go Back' twice

```
TypeError: Cannot read property 'removeClass' of undefined
    at Mu.deactivateShape (http://localhost:8080/cvat-ui.min.js:72:1377820)
    at Mu.deactivate (http://localhost:8080/cvat-ui.min.js:72:1378333)
    at Mu.activate (http://localhost:8080/cvat-ui.min.js:72:1380912)
    at Mu.notify (http://localhost:8080/cvat-ui.min.js:72:1370764)
    at Cc.notify (http://localhost:8080/cvat-ui.min.js:72:1287600)
    at Cc.activate (http://localhost:8080/cvat-ui.min.js:72:1290684)
    at Lu.activate (http://localhost:8080/cvat-ui.min.js:72:1385380)
    at od.componentDidUpdate (http://localhost:8080/cvat-ui.min.js:72:1419343)
    at yl (http://localhost:8080/cvat-ui.min.js:43:100837)
    at t.unstable_runWithPriority (http://localhost:8080/cvat-ui.min.js:51:3465)
```

or Switch Frame then pressing [Tab]

```
TypeError: Cannot read property 'pinned' of undefined
    at Mu.deactivateShape (http://localhost:8080/cvat-ui.min.js:72:1377910)
    at Mu.deactivate (http://localhost:8080/cvat-ui.min.js:72:1378333)
    at Mu.activate (http://localhost:8080/cvat-ui.min.js:72:1380912)
    at Mu.notify (http://localhost:8080/cvat-ui.min.js:72:1370764)
    at Cc.notify (http://localhost:8080/cvat-ui.min.js:72:1287600)
    at Cc.activate (http://localhost:8080/cvat-ui.min.js:72:1290684)
    at Lu.activate (http://localhost:8080/cvat-ui.min.js:72:1385380)
    at od.componentDidUpdate (http://localhost:8080/cvat-ui.min.js:72:1419343)
    at yl (http://localhost:8080/cvat-ui.min.js:43:100837)
    at t.unstable_runWithPriority (http://localhost:8080/cvat-ui.min.js:51:3465)
```
CVAT version
Server: 1.0rc0
Core: 2.0.0
Canvas: 1.0.0
UI: 1.1.2
Chrome: Version 83.0.4103.61 (Official Build) (64-bit)

**Comment by bsekachev** [comment]
@michaelmruta 

Hi, the issue might be related with #1541
Could you please update CVAT (by the way we have released the new version) and check if fix works for you?

**Comment by a-andre** [comment]
Using 972e2f2ab40dd51badfaea499ec771a360722555, I can reproduce the first problem ('removeClass' of undefined). A user also reported the second problem, but couldn't say how reproduce it.
