### ISSUE TITLE
Dump Annotation Error: ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()\n

### ISSUE THREAD

**Issue by miso-ramen** [opencv/cvat#1869]
Tried to dump annotations from a task with polygons and rectangles. I received the following error:

Could not dump annotations for the task 2
Error: Request failed with status code 500. "ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()\n".

I don't understand where I would use a.any() or a.all()?

### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

I expected annotations to be successfully dumped. 

### Current Behaviour

I set up a different task (very few frames) with simple labels (both rectangles and polygons including overlaps) and the dump was successful. I'm wondering if it's unhappy with the size of the task (over 15,500 frames), or if my labeler did something weird in hiding/overlapping labels/shapes? I tried docker-compose down and docker-compose up -d and the error is always the same for this particular task.

### Your Environment
Docker version 19.03.12
OS: Ubuntu 18.04 LTS

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by zhiltsov-max** [comment]
Hi, could you provide `docker logs cvat` output?

**Comment by miso-ramen** [comment]
2020-07-09 09:10:15,805 DEBG 'rqworker_default_1' stderr output:
INFO:rq.worker:default: Job OK (65cdab24-20b4-404f-923c-d00fcefed425)

2020-07-09 09:10:15,806 DEBG 'rqworker_default_1' stderr output:
INFO:rq.worker:Result is kept for 500 seconds

2020-07-09 09:10:15,815 DEBG 'rqworker_default_1' stderr output:
INFO:rq.worker:Cleaning registries for queue: default

2020-07-09 12:00:18,851 DEBG 'runserver' stderr output:
[Thu Jul 09 12:00:18.850947 2020] [wsgi:error] [pid 266:tid 140033706432256] [remote 172.18.0.6:39570] INFO:cvat.client:{"client_id":702842,"name":"Send user activity","username":"mike","is_active":true,"payload":{"working_time":14019},"time":"2020-07-09T12:00:18.834000Z"}

2020-07-09 12:00:30,704 DEBG 'rqworker_default_0' stderr output:
INFO:rq.worker:default: cvat.apps.dataset_manager.views.export_task_annotations(2, 'CVAT for video 1.1', 'http://localhost:8080') (/api/v1/tasks/2/annotations/CVAT for video 1.1)

2020-07-09 12:00:31,505 DEBG 'rqworker_default_0' stderr output:
[2020-07-09 12:00:31,503] ERROR cvat.server.task_2: [cvat.apps.dataset_manager.views @ export_task]: exception occurred
Traceback (most recent call last):
  File "/home/django/cvat/apps/dataset_manager/views.py", line 62, in export_task
    server_url=server_url, save_images=save_images)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 723, in export_task
    save_images=save_images)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 619, in export
    exporter(dst_file, task_data, **options)
  File "/home/django/cvat/apps/dataset_manager/formats/registry.py", line 36, in __call__
    f_or_cls(*args, **kwargs)
  File "/home/django/cvat/apps/dataset_manager/formats/cvat.py", line 539, in _export_video
    anno_callback=dump_as_cvat_interpolation, save_images=save_images)
  File "/home/django/cvat/apps/dataset_manager/formats/cvat.py", line 517, in _export
    anno_callback(f, task_data)
  File "/home/django/cvat/apps/dataset_manager/formats/cvat.py", line 378, in dump_as_cvat_interpolation
    for track in annotations.tracks:
  File "/home/django/cvat/apps/dataset_manager/bindings.py", line 288, in tracks
    track, 0, self._db_task.data.size)
  File "/home/django/cvat/apps/dataset_manager/annotation.py", line 739, in get_interpolated_shapes
    shapes.extend(interpolate(prev_shape, shape))
  File "/home/django/cvat/apps/dataset_manager/annotation.py", line 719, in interpolate
    shapes = polyshape_interpolation(shape0, shape1)
  File "/home/django/cvat/apps/dataset_manager/annotation.py", line 692, in polyshape_interpolation
    shapes.append(copy_shape(shape0, frame, points))
  File "/home/django/cvat/apps/dataset_manager/annotation.py", line 449, in copy_shape
    if points:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

2020-07-09 12:00:31,505 DEBG 'rqworker_default_0' stderr output:
ERROR:cvat.server.task_2:[cvat.apps.dataset_manager.views @ export_task]: exception occurred
Traceback (most recent call last):
  File "/home/django/cvat/apps/dataset_manager/views.py", line 62, in export_task
    server_url=server_url, save_images=save_images)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 723, in export_task
    save_images=save_images)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 619, in export
    exporter(dst_file, task_data, **options)
  File "/home/django/cvat/apps/dataset_manager/formats/registry.py", line 36, in __call__
    f_or_cls(*args, **kwargs)
  File "/home/django/cvat/apps/dataset_manager/formats/cvat.py", line 539, in _export_video
    anno_callback=dump_as_cvat_interpolation, save_images=save_images)
  File "/home/django/cvat/apps/dataset_manager/formats/cvat.py", line 517, in _export
    anno_callback(f, task_data)
  File "/home/django/cvat/apps/dataset_manager/formats/cvat.py", line 378, in dump_as_cvat_interpolation
    for track in annotations.tracks:
  File "/home/django/cvat/apps/dataset_manager/bindings.py", line 288, in tracks
    track, 0, self._db_task.data.size)
  File "/home/django/cvat/apps/dataset_manager/annotation.py", line 739, in get_interpolated_shapes
    shapes.extend(interpolate(prev_shape, shape))
  File "/home/django/cvat/apps/dataset_manager/annotation.py", line 719, in interpolate
    shapes = polyshape_interpolation(shape0, shape1)
  File "/home/django/cvat/apps/dataset_manager/annotation.py", line 692, in polyshape_interpolation
    shapes.append(copy_shape(shape0, frame, points))
  File "/home/django/cvat/apps/dataset_manager/annotation.py", line 449, in copy_shape
    if points:
**ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()**

2020-07-09 12:00:31,507 DEBG 'rqworker_default_0' stderr output:
ERROR:rq.worker:ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rq/worker.py", line 812, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 588, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 594, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/django/cvat/apps/dataset_manager/views.py", line 87, in export_task_annotations
    return export_task(task_id, dst_format, server_url=server_url, save_images=False)
  File "/home/django/cvat/apps/dataset_manager/views.py", line 62, in export_task
    server_url=server_url, save_images=save_images)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 723, in export_task
    save_images=save_images)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 619, in export
    exporter(dst_file, task_data, **options)
  File "/home/django/cvat/apps/dataset_manager/formats/registry.py", line 36, in __call__
    f_or_cls(*args, **kwargs)
  File "/home/django/cvat/apps/dataset_manager/formats/cvat.py", line 539, in _export_video
    anno_callback=dump_as_cvat_interpolation, save_images=save_images)
  File "/home/django/cvat/apps/dataset_manager/formats/cvat.py", line 517, in _export
    anno_callback(f, task_data)
  File "/home/django/cvat/apps/dataset_manager/formats/cvat.py", line 378, in dump_as_cvat_interpolation
    for track in annotations.tracks:
  File "/home/django/cvat/apps/dataset_manager/bindings.py", line 288, in tracks
    track, 0, self._db_task.data.size)
  File "/home/django/cvat/apps/dataset_manager/annotation.py", line 739, in get_interpolated_shapes
    shapes.extend(interpolate(prev_shape, shape))
  File "/home/django/cvat/apps/dataset_manager/annotation.py", line 719, in interpolate
    shapes = polyshape_interpolation(shape0, shape1)
  File "/home/django/cvat/apps/dataset_manager/annotation.py", line 692, in polyshape_interpolation
    shapes.append(copy_shape(shape0, frame, points))
  File "/home/django/cvat/apps/dataset_manager/annotation.py", line 449, in copy_shape
    if points:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rq/worker.py", line 812, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 588, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 594, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/django/cvat/apps/dataset_manager/views.py", line 87, in export_task_annotations
    return export_task(task_id, dst_format, server_url=server_url, save_images=False)
  File "/home/django/cvat/apps/dataset_manager/views.py", line 62, in export_task
    server_url=server_url, save_images=save_images)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 723, in export_task
    save_images=save_images)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 619, in export
    exporter(dst_file, task_data, **options)
  File "/home/django/cvat/apps/dataset_manager/formats/registry.py", line 36, in __call__
    f_or_cls(*args, **kwargs)
  File "/home/django/cvat/apps/dataset_manager/formats/cvat.py", line 539, in _export_video
    anno_callback=dump_as_cvat_interpolation, save_images=save_images)
  File "/home/django/cvat/apps/dataset_manager/formats/cvat.py", line 517, in _export
    anno_callback(f, task_data)
  File "/home/django/cvat/apps/dataset_manager/formats/cvat.py", line 378, in dump_as_cvat_interpolation
    for track in annotations.tracks:
  File "/home/django/cvat/apps/dataset_manager/bindings.py", line 288, in tracks
    track, 0, self._db_task.data.size)
  File "/home/django/cvat/apps/dataset_manager/annotation.py", line 739, in get_interpolated_shapes
    shapes.extend(interpolate(prev_shape, shape))
  File "/home/django/cvat/apps/dataset_manager/annotation.py", line 719, in interpolate
    shapes = polyshape_interpolation(shape0, shape1)
  File "/home/django/cvat/apps/dataset_manager/annotation.py", line 692, in polyshape_interpolation
    shapes.append(copy_shape(shape0, frame, points))
  File "/home/django/cvat/apps/dataset_manager/annotation.py", line 449, in copy_shape
    if points:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

2020-07-09 12:00:31,525 DEBG 'rqworker_default_0' stderr output:
INFO:rq.worker:Cleaning registries for queue: default

2020-07-09 12:00:33,747 DEBG 'runserver' stderr output:
[Thu Jul 09 12:00:33.747057 2020] [wsgi:error] [pid 266:tid 140033698039552] [remote 172.18.0.6:39604] [2020-07-09 12:00:33,746] ERROR django.request: Internal Server Error: /api/v1/tasks/2/annotations

2020-07-09 12:00:33,747 DEBG 'runserver' stderr output:
[Thu Jul 09 12:00:33.747201 2020] [wsgi:error] [pid 266:tid 140033698039552] [remote 172.18.0.6:39604] ERROR:django.request:Internal Server Error: /api/v1/tasks/2/annotations
