### ISSUE TITLE
Could not dump annotations for the task 1 | COCO 1.0 

### ISSUE THREAD

**Issue by RotemEmergi** [opencv/cvat#1918]
Hi !

I am getting this error when I am trying to dump annotations with COCO 1.0 :
Error: Request failed with status code 500. "ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()\n".

My branch is release-1.1.0 .

Error from docker logs :

```
2020-07-20 16:34:06,445 DEBG 'rqworker_default_1' stderr output:
[2020-07-20 16:34:06,443] ERROR cvat.server.task_1: [cvat.apps.dataset_manager.views @ export_task]: exception occurred
Traceback (most recent call last):
  File "/home/django/cvat/apps/dataset_manager/views.py", line 62, in export_task
    server_url=server_url, save_images=save_images)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 723, in export_task
    save_images=save_images)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 619, in export
    exporter(dst_file, task_data, **options)
  File "/home/django/cvat/apps/dataset_manager/formats/registry.py", line 36, in __call__
    f_or_cls(*args, **kwargs)
  File "/home/django/cvat/apps/dataset_manager/formats/coco.py", line 23, in _export
    converter(extractor, save_dir=temp_dir)
  File "/home/django/datumaro/datumaro/plugins/coco_format/converter.py", line 609, in __call__
    converter.convert()
  File "/home/django/datumaro/datumaro/plugins/coco_format/converter.py", line 552, in convert
    task_conv.save_annotations(item)
  File "/home/django/datumaro/datumaro/plugins/coco_format/converter.py", line 265, in save_annotations
    instances = [self.find_instance_parts(i, w, h) for i in instances]
  File "/home/django/datumaro/datumaro/plugins/coco_format/converter.py", line 265, in <listcomp>
    instances = [self.find_instance_parts(i, w, h) for i in instances]
  File "/home/django/datumaro/datumaro/plugins/coco_format/converter.py", line 208, in find_instance_parts
    leader = anno_tools.find_group_leader(anns)
  File "/home/django/datumaro/datumaro/util/annotation_tools.py", line 23, in find_group_leader
    return max(group, key=lambda x: x.get_area())
  File "/home/django/datumaro/datumaro/util/annotation_tools.py", line 23, in <lambda>
    return max(group, key=lambda x: x.get_area())
  File "/home/django/datumaro/datumaro/components/extractor.py", line 434, in get_area
    _, _, w, h = self.get_bbox()
  File "/home/django/datumaro/datumaro/components/extractor.py", line 384, in get_bbox
    if not points:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

2020-07-20 16:34:06,445 DEBG 'rqworker_default_1' stderr output:
ERROR:cvat.server.task_1:[cvat.apps.dataset_manager.views @ export_task]: exception occurred
Traceback (most recent call last):
  File "/home/django/cvat/apps/dataset_manager/views.py", line 62, in export_task
    server_url=server_url, save_images=save_images)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 723, in export_task
    save_images=save_images)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 619, in export
    exporter(dst_file, task_data, **options)
  File "/home/django/cvat/apps/dataset_manager/formats/registry.py", line 36, in __call__
    f_or_cls(*args, **kwargs)
  File "/home/django/cvat/apps/dataset_manager/formats/coco.py", line 23, in _export
    converter(extractor, save_dir=temp_dir)
  File "/home/django/datumaro/datumaro/plugins/coco_format/converter.py", line 609, in __call__
    converter.convert()
  File "/home/django/datumaro/datumaro/plugins/coco_format/converter.py", line 552, in convert
    task_conv.save_annotations(item)
  File "/home/django/datumaro/datumaro/plugins/coco_format/converter.py", line 265, in save_annotations
    instances = [self.find_instance_parts(i, w, h) for i in instances]
  File "/home/django/datumaro/datumaro/plugins/coco_format/converter.py", line 265, in <listcomp>
    instances = [self.find_instance_parts(i, w, h) for i in instances]
  File "/home/django/datumaro/datumaro/plugins/coco_format/converter.py", line 208, in find_instance_parts
    leader = anno_tools.find_group_leader(anns)
  File "/home/django/datumaro/datumaro/util/annotation_tools.py", line 23, in find_group_leader
    return max(group, key=lambda x: x.get_area())
  File "/home/django/datumaro/datumaro/util/annotation_tools.py", line 23, in <lambda>
    return max(group, key=lambda x: x.get_area())
  File "/home/django/datumaro/datumaro/components/extractor.py", line 434, in get_area
    _, _, w, h = self.get_bbox()
  File "/home/django/datumaro/datumaro/components/extractor.py", line 384, in get_bbox
    if not points:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

2020-07-20 16:34:06,447 DEBG 'rqworker_default_1' stderr output:
ERROR:rq.worker:ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rq/worker.py", line 812, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 588, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 594, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/django/cvat/apps/dataset_manager/views.py", line 87, in export_task_annotations
    return export_task(task_id, dst_format, server_url=server_url, save_images=False)
  File "/home/django/cvat/apps/dataset_manager/views.py", line 62, in export_task
    server_url=server_url, save_images=save_images)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 723, in export_task
    save_images=save_images)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 619, in export
    exporter(dst_file, task_data, **options)
  File "/home/django/cvat/apps/dataset_manager/formats/registry.py", line 36, in __call__
    f_or_cls(*args, **kwargs)
  File "/home/django/cvat/apps/dataset_manager/formats/coco.py", line 23, in _export
    converter(extractor, save_dir=temp_dir)
  File "/home/django/datumaro/datumaro/plugins/coco_format/converter.py", line 609, in __call__
    converter.convert()
  File "/home/django/datumaro/datumaro/plugins/coco_format/converter.py", line 552, in convert
    task_conv.save_annotations(item)
  File "/home/django/datumaro/datumaro/plugins/coco_format/converter.py", line 265, in save_annotations
    instances = [self.find_instance_parts(i, w, h) for i in instances]
  File "/home/django/datumaro/datumaro/plugins/coco_format/converter.py", line 265, in <listcomp>
    instances = [self.find_instance_parts(i, w, h) for i in instances]
  File "/home/django/datumaro/datumaro/plugins/coco_format/converter.py", line 208, in find_instance_parts
    leader = anno_tools.find_group_leader(anns)
  File "/home/django/datumaro/datumaro/util/annotation_tools.py", line 23, in find_group_leader
    return max(group, key=lambda x: x.get_area())
  File "/home/django/datumaro/datumaro/util/annotation_tools.py", line 23, in <lambda>
    return max(group, key=lambda x: x.get_area())
  File "/home/django/datumaro/datumaro/components/extractor.py", line 434, in get_area
    _, _, w, h = self.get_bbox()
  File "/home/django/datumaro/datumaro/components/extractor.py", line 384, in get_bbox
    if not points:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rq/worker.py", line 812, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 588, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 594, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/django/cvat/apps/dataset_manager/views.py", line 87, in export_task_annotations
    return export_task(task_id, dst_format, server_url=server_url, save_images=False)
  File "/home/django/cvat/apps/dataset_manager/views.py", line 62, in export_task
    server_url=server_url, save_images=save_images)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 723, in export_task
    save_images=save_images)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 619, in export
    exporter(dst_file, task_data, **options)
  File "/home/django/cvat/apps/dataset_manager/formats/registry.py", line 36, in __call__
    f_or_cls(*args, **kwargs)
  File "/home/django/cvat/apps/dataset_manager/formats/coco.py", line 23, in _export
    converter(extractor, save_dir=temp_dir)
  File "/home/django/datumaro/datumaro/plugins/coco_format/converter.py", line 609, in __call__
    converter.convert()
  File "/home/django/datumaro/datumaro/plugins/coco_format/converter.py", line 552, in convert
    task_conv.save_annotations(item)
  File "/home/django/datumaro/datumaro/plugins/coco_format/converter.py", line 265, in save_annotations
    instances = [self.find_instance_parts(i, w, h) for i in instances]
  File "/home/django/datumaro/datumaro/plugins/coco_format/converter.py", line 265, in <listcomp>
    instances = [self.find_instance_parts(i, w, h) for i in instances]
  File "/home/django/datumaro/datumaro/plugins/coco_format/converter.py", line 208, in find_instance_parts
    leader = anno_tools.find_group_leader(anns)
  File "/home/django/datumaro/datumaro/util/annotation_tools.py", line 23, in find_group_leader
    return max(group, key=lambda x: x.get_area())
  File "/home/django/datumaro/datumaro/util/annotation_tools.py", line 23, in <lambda>
    return max(group, key=lambda x: x.get_area())
  File "/home/django/datumaro/datumaro/components/extractor.py", line 434, in get_area
    _, _, w, h = self.get_bbox()
  File "/home/django/datumaro/datumaro/components/extractor.py", line 384, in get_bbox
    if not points:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by shimen** [comment]
Together with @RotemEmergi, we found a fix:
change:  "if not points:" to "if points is None:"

def get_bbox(self):
        points = self.points
        if points is None:
            return None
