### ISSUE TITLE
FileNotFoundError and django Internal Server Error

### ISSUE THREAD

**Issue by mariusud** [opencv/cvat#1990]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Current Behaviour
The docker logs for the cvat container consistenly gives a FileNotFoundError when opening a new task   
in CVAT, the following error is printed: 
```
Could not receive repository status
Error: Request failed with status code 400. "[Errno 2] No such file or directory: '/home/django/data/tasks/45/logs/task.log'".

```
### Your Environment

OS/Arch:          linux/amd64
Docker version 19.03.12, build 48a66213fe

### Logs
```
[Wed Aug 05 12:11:27.763861 2020] [wsgi:error] [pid 263:tid 140309955544832] [remote 172.23.0.6:55136] [2020-08-05 12:11:27,763] ERROR django.request: Internal Server Error: /api/v1/tasks/34/data
[Wed Aug 05 12:11:27.763885 2020] [wsgi:error] [pid 263:tid 140309955544832] [remote 172.23.0.6:55136] Traceback (most recent call last):
[Wed Aug 05 12:11:27.763900 2020] [wsgi:error] [pid 263:tid 140309955544832] [remote 172.23.0.6:55136]   File "/home/django/cvat/apps/engine/views.py", line 440, in data
[Wed Aug 05 12:11:27.763902 2020] [wsgi:error] [pid 263:tid 140309955544832] [remote 172.23.0.6:55136]     frame_provider = FrameProvider(db_task.data)
[Wed Aug 05 12:11:27.763904 2020] [wsgi:error] [pid 263:tid 140309955544832] [remote 172.23.0.6:55136]   File "/home/django/cvat/apps/engine/frame_provider.py", line 77, in __init__
[Wed Aug 05 12:11:27.763906 2020] [wsgi:error] [pid 263:tid 140309955544832] [remote 172.23.0.6:55136]     reader_class[db_data.compressed_chunk_type],
[Wed Aug 05 12:11:27.763908 2020] [wsgi:error] [pid 263:tid 140309955544832] [remote 172.23.0.6:55136] AttributeError: 'NoneType' object has no attribute 'compressed_chunk_type'
[Wed Aug 05 12:11:27.763910 2020] [wsgi:error] [pid 263:tid 140309955544832] [remote 172.23.0.6:55136] 
[Wed Aug 05 12:11:27.763912 2020] [wsgi:error] [pid 263:tid 140309955544832] [remote 172.23.0.6:55136] During handling of the above exception, another exception occurred:
[Wed Aug 05 12:11:27.763913 2020] [wsgi:error] [pid 263:tid 140309955544832] [remote 172.23.0.6:55136] 
[Wed Aug 05 12:11:27.763915 2020] [wsgi:error] [pid 263:tid 140309955544832] [remote 172.23.0.6:55136] Traceback (most recent call last):
[Wed Aug 05 12:11:27.763917 2020] [wsgi:error] [pid 263:tid 140309955544832] [remote 172.23.0.6:55136]   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 34, in inner
[Wed Aug 05 12:11:27.763919 2020] [wsgi:error] [pid 263:tid 140309955544832] [remote 172.23.0.6:55136]     response = get_response(request)
[Wed Aug 05 12:11:27.763920 2020] [wsgi:error] [pid 263:tid 140309955544832] [remote 172.23.0.6:55136]   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 115, in _get_response
[Wed Aug 05 12:11:27.763922 2020] [wsgi:error] [pid 263:tid 140309955544832] [remote 172.23.0.6:55136]     response = self.process_exception_by_middleware(e, request)
[Wed Aug 05 12:11:27.763924 2020] [wsgi:error] [pid 263:tid 140309955544832] [remote 172.23.0.6:55136]   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 113, in _get_response
[Wed Aug 05 12:11:27.763925 2020] [wsgi:error] [pid 263:tid 140309955544832] [remote 172.23.0.6:55136]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Wed Aug 05 12:11:27.763927 2020] [wsgi:error] [pid 263:tid 140309955544832] [remote 172.23.0.6:55136]   File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
[Wed Aug 05 12:11:27.763929 2020] [wsgi:error] [pid 263:tid 140309955544832] [remote 172.23.0.6:55136]     return view_func(*args, **kwargs)
[Wed Aug 05 12:11:27.763930 2020] [wsgi:error] [pid 263:tid 140309955544832] [remote 172.23.0.6:55136]   File "/usr/local/lib/python3.5/dist-packages/rest_framework/viewsets.py", line 114, in view
[Wed Aug 05 12:11:27.763932 2020] [wsgi:error] [pid 263:tid 140309955544832] [remote 172.23.0.6:55136]     return self.dispatch(request, *args, **kwargs)
[Wed Aug 05 12:11:27.763934 2020] [wsgi:error] [pid 263:tid 140309955544832] [remote 172.23.0.6:55136]   File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 505, in dispatch
[Wed Aug 05 12:11:27.763935 2020] [wsgi:error] [pid 263:tid 140309955544832] [remote 172.23.0.6:55136]     response = self.handle_exception(exc)
[Wed Aug 05 12:11:27.763937 2020] [wsgi:error] [pid 263:tid 140309955544832] [remote 172.23.0.6:55136]   File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 465, in handle_exception
[Wed Aug 05 12:11:27.763939 2020] [wsgi:error] [pid 263:tid 140309955544832] [remote 172.23.0.6:55136]     self.raise_uncaught_exception(exc)
[Wed Aug 05 12:11:27.763943 2020] [wsgi:error] [pid 263:tid 140309955544832] [remote 172.23.0.6:55136]   File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
[Wed Aug 05 12:11:27.763944 2020] [wsgi:error] [pid 263:tid 140309955544832] [remote 172.23.0.6:55136]     raise exc
[Wed Aug 05 12:11:27.763946 2020] [wsgi:error] [pid 263:tid 140309955544832] [remote 172.23.0.6:55136]   File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 502, in dispatch
[Wed Aug 05 12:11:27.763948 2020] [wsgi:error] [pid 263:tid 140309955544832] [remote 172.23.0.6:55136]     response = handler(request, *args, **kwargs)
[Wed Aug 05 12:11:27.763949 2020] [wsgi:error] [pid 263:tid 140309955544832] [remote 172.23.0.6:55136]   File "/home/django/cvat/apps/engine/views.py", line 468, in data
[Wed Aug 05 12:11:27.763951 2020] [wsgi:error] [pid 263:tid 140309955544832] [remote 172.23.0.6:55136]     slogger.task[pk].error(msg, exc_info=True)
[Wed Aug 05 12:11:27.763952 2020] [wsgi:error] [pid 263:tid 140309955544832] [remote 172.23.0.6:55136]   File "/home/django/cvat/apps/engine/log.py", line 28, in __getitem__
[Wed Aug 05 12:11:27.763954 2020] [wsgi:error] [pid 263:tid 140309955544832] [remote 172.23.0.6:55136]     self._storage[tid] = self._create_task_logger(tid)
[Wed Aug 05 12:11:27.763956 2020] [wsgi:error] [pid 263:tid 140309955544832] [remote 172.23.0.6:55136]   File "/home/django/cvat/apps/engine/log.py", line 35, in _create_task_logger
[Wed Aug 05 12:11:27.763957 2020] [wsgi:error] [pid 263:tid 140309955544832] [remote 172.23.0.6:55136]     server_file = logging.FileHandler(filename=task.get_log_path())
[Wed Aug 05 12:11:27.763959 2020] [wsgi:error] [pid 263:tid 140309955544832] [remote 172.23.0.6:55136]   File "/usr/lib/python3.5/logging/__init__.py", line 1008, in __init__
[Wed Aug 05 12:11:27.763960 2020] [wsgi:error] [pid 263:tid 140309955544832] [remote 172.23.0.6:55136]     StreamHandler.__init__(self, self._open())
[Wed Aug 05 12:11:27.763962 2020] [wsgi:error] [pid 263:tid 140309955544832] [remote 172.23.0.6:55136]   File "/usr/lib/python3.5/logging/__init__.py", line 1037, in _open
[Wed Aug 05 12:11:27.763964 2020] [wsgi:error] [pid 263:tid 140309955544832] [remote 172.23.0.6:55136]     return open(self.baseFilename, self.mode, encoding=self.encoding)

2020-08-05 12:11:27,764 DEBG 'runserver' stderr output:
[Wed Aug 05 12:11:27.763967 2020] [wsgi:error] [pid 263:tid 140309955544832] [remote 172.23.0.6:55136] FileNotFoundError: [Errno 2] No such file or directory: '/home/django/data/tasks/34/logs/task.log'
```

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by azhavoro** [comment]
Hi, please specify cvat version and steps to reproduce your issue.

**Comment by mariusud** [comment]
> Hi, please specify cvat version and steps to reproduce your issue.

Hi,
Using latest from master (aka v1.0.0) and setup on a Azure 
It could have been because of cvat_data container being migrated to a  /mnt/ device since the error is not reproduced on newly created tasks. However, the error still runs on all older tasks

**Comment by azhavoro** [comment]
I think this could have happened if you didn't copy the volume data.

**Comment by mariusud** [comment]
In that case I'm not able to replicate it further unfortunately. However, it appears for all the roughly 20 annotations on the server.

**Comment by azhavoro** [comment]
CVAT stores images and video data inside the cvat_data docker volume, so if you want to change the volume storage location, you must move the volume data as well. CVAT cannot find data if the data has been deleted.

**Comment by mariusud** [comment]
volume data was moved aswell, but it doesn't detect a logfile for the tasks

**Comment by azhavoro** [comment]
CVAT doesn't delete any task related data (logs, chunk data, etc) until you click 'Delete' action in the UI. So, does the log file '/home/django/data/tasks/45/logs/task.log'  or `/home/django/data/tasks/45` exists inside you cvat container? You can attach to the container with `docker exec -it cvat bash` to check that.

**Comment by mariusud** [comment]
Hi, I believe it has somehow edited the filepaths for the log, for the following file exists
`/home/django/data/tasks/tasks/45/logs/task.log` exists instead of `/home/django/data/tasks/45/logs/task.log`
After i moved all the files in tasks/tasks/ to tasks/ everything worked fine.
However, there must be some bug that makes the double task folder.

**Comment by azhavoro** [comment]
How did you copy data? I think the most likely reason is data folder structure is changed during coping. Cvat doesn't contain any code that copy(or move) task data except migration but it's not your case.

**Comment by mariusud** [comment]
> How did you copy data? I think the most likely reason is data folder structure is changed during coping. Cvat doesn't contain any code that copy(or move) task data except migration but it's not your case.

I moved the cvat_data to a /mnt/ directory and cp the files but you're right that its probably just the folder structure changed so you can close this
