### ISSUE TITLE
datumaro merge error

### ISSUE THREAD

**Issue by zmfkzj** [opencv/cvat#2020]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Current Behaviour

```bash
$ datum project merge -p 1/ -o merge/2/ 2/
2020-08-12 15:42:47,926 ERROR: 'Namespace' object has no attribute 'other_project_dir'
Traceback (most recent call last):
  File "/home/tm/anaconda3/envs/datum/bin/datum", line 8, in <module>
    sys.exit(main())
  File "/home/tm/anaconda3/envs/datum/lib/python3.6/site-packages/datumaro/cli/__main__.py", line 114, in main
    return args.command(args)
  File "/home/tm/anaconda3/envs/datum/lib/python3.6/site-packages/datumaro/cli/contexts/project/__init__.py", line 482, in merge_command
    second_project = load_project(args.other_project_dir)
AttributeError: 'Namespace' object has no attribute 'other_project_dir'
```
### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by zmfkzj** [comment]
I solve it by changing [this line](https://github.com/opencv/cvat/blob/2c661020b61b6c87efe086a8de6aeeb7052aa747/datumaro/datumaro/cli/contexts/project/__init__.py#L468) 'other_object' to 'other_object_dir'.

Instead, another error occurred.
```
2020-08-12 16:05:15,162 ERROR: 'cvat_rest_api_task_images'
Traceback (most recent call last):
  File "/home/tm/anaconda3/envs/datum/bin/datum", line 8, in <module>
    sys.exit(main())
  File "/home/tm/anaconda3/envs/datum/lib/python3.6/site-packages/datumaro/cli/__main__.py", line 114, in main
    return args.command(args)
  File "/home/tm/anaconda3/envs/datum/lib/python3.6/site-packages/datumaro/cli/contexts/project/__init__.py", line 682, in info_command
    dataset = project.make_dataset()
  File "/home/tm/anaconda3/envs/datum/lib/python3.6/site-packages/datumaro/components/project.py", line 815, in make_dataset
    return ProjectDataset(self)
  File "/home/tm/anaconda3/envs/datum/lib/python3.6/site-packages/datumaro/components/project.py", line 525, in __init__
    url, **options)
  File "/home/tm/anaconda3/envs/datum/lib/python3.6/site-packages/datumaro/components/project.py", line 289, in make_extractor
    return self.extractors.get(name)(*args, **kwargs)
  File "/home/tm/anaconda3/envs/datum/lib/python3.6/site-packages/datumaro/components/project.py", line 65, in get
    return self.items[key] # returns a class / ctor
KeyError: 'cvat_rest_api_task_images'
```

**Comment by zhiltsov-max** [comment]
Hi, thanks for the report. The problem with `cvat_rest_api_task_images` is supposed to be solved by following instructions in `README.md` of the downloaded archive. Basically, add the path to the `cvat/cli` directory to `PYTHONPATH` and install `requests` python library.
