### ISSUE TITLE
Functions deployed to nuclio not available in cvat

### ISSUE THREAD

**Issue by elsucht** [opencv/cvat#2323]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

models deployed in nuclio are not available in cvat. 
Message "Could not get models from the server Error: Request failed with status code 500. "Server Error (500)." pops up in Chrome. As long as no function is deployed in nuclio project, the error does not occur.

### Context
want to auto annotate images using nuclio serverless functions.

### Your Environment
- Release 1.1.0  commit 8eb7c13619e39d9546ba3807027d30eab9c5ce2b 
- Docker version `19.03.13` 
- Windows 10
Logs:
    chrome console: http://localhost:8080/api/v1/lambda/functions 500 (Internal Server Error)
    docker logs cvat:
```
[Wed Oct 14 17:56:23.169731 2020] [wsgi:error] [pid 278:tid 139668765869824] [remote 172.28.0.11:54624] ERROR:django.request:Internal Server Error: /api/v1/lambda/functions
[Wed Oct 14 17:56:23.169739 2020] [wsgi:error] [pid 278:tid 139668765869824] [remote 172.28.0.11:54624] Traceback (most recent call last):
[Wed Oct 14 17:56:23.169742 2020] [wsgi:error] [pid 278:tid 139668765869824] [remote 172.28.0.11:54624]   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 34, in inner
[Wed Oct 14 17:56:23.169744 2020] [wsgi:error] [pid 278:tid 139668765869824] [remote 172.28.0.11:54624]     response = get_response(request)
[Wed Oct 14 17:56:23.169747 2020] [wsgi:error] [pid 278:tid 139668765869824] [remote 172.28.0.11:54624]   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 115, in _get_response
[Wed Oct 14 17:56:23.169749 2020] [wsgi:error] [pid 278:tid 139668765869824] [remote 172.28.0.11:54624]     response = self.process_exception_by_middleware(e, request)
[Wed Oct 14 17:56:23.169752 2020] [wsgi:error] [pid 278:tid 139668765869824] [remote 172.28.0.11:54624]   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 113, in _get_response
[Wed Oct 14 17:56:23.169755 2020] [wsgi:error] [pid 278:tid 139668765869824] [remote 172.28.0.11:54624]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Wed Oct 14 17:56:23.169757 2020] [wsgi:error] [pid 278:tid 139668765869824] [remote 172.28.0.11:54624]   File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
[Wed Oct 14 17:56:23.169760 2020] [wsgi:error] [pid 278:tid 139668765869824] [remote 172.28.0.11:54624]     return view_func(*args, **kwargs)
[Wed Oct 14 17:56:23.169763 2020] [wsgi:error] [pid 278:tid 139668765869824] [remote 172.28.0.11:54624]   File "/usr/local/lib/python3.5/dist-packages/rest_framework/viewsets.py", line 114, in view
[Wed Oct 14 17:56:23.169765 2020] [wsgi:error] [pid 278:tid 139668765869824] [remote 172.28.0.11:54624]     return self.dispatch(request, *args, **kwargs)
[Wed Oct 14 17:56:23.169768 2020] [wsgi:error] [pid 278:tid 139668765869824] [remote 172.28.0.11:54624]   File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 505, in dispatch
[Wed Oct 14 17:56:23.169770 2020] [wsgi:error] [pid 278:tid 139668765869824] [remote 172.28.0.11:54624]     response = self.handle_exception(exc)
[Wed Oct 14 17:56:23.169773 2020] [wsgi:error] [pid 278:tid 139668765869824] [remote 172.28.0.11:54624]   File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 465, in handle_exception
[Wed Oct 14 17:56:23.169776 2020] [wsgi:error] [pid 278:tid 139668765869824] [remote 172.28.0.11:54624]     self.raise_uncaught_exception(exc)
[Wed Oct 14 17:56:23.169778 2020] [wsgi:error] [pid 278:tid 139668765869824] [remote 172.28.0.11:54624]   File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
[Wed Oct 14 17:56:23.169781 2020] [wsgi:error] [pid 278:tid 139668765869824] [remote 172.28.0.11:54624]     raise exc
[Wed Oct 14 17:56:23.169783 2020] [wsgi:error] [pid 278:tid 139668765869824] [remote 172.28.0.11:54624]   File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 502, in dispatch
[Wed Oct 14 17:56:23.169786 2020] [wsgi:error] [pid 278:tid 139668765869824] [remote 172.28.0.11:54624]     response = handler(request, *args, **kwargs)
[Wed Oct 14 17:56:23.169788 2020] [wsgi:error] [pid 278:tid 139668765869824] [remote 172.28.0.11:54624]   File "/home/django/cvat/apps/lambda_manager/views.py", line 485, in func_wrapper
[Wed Oct 14 17:56:23.169791 2020] [wsgi:error] [pid 278:tid 139668765869824] [remote 172.28.0.11:54624]     data = func(*args, **kwargs)
[Wed Oct 14 17:56:23.169796 2020] [wsgi:error] [pid 278:tid 139668765869824] [remote 172.28.0.11:54624]   File "/home/django/cvat/apps/lambda_manager/views.py", line 523, in list
[Wed Oct 14 17:56:23.169799 2020] [wsgi:error] [pid 278:tid 139668765869824] [remote 172.28.0.11:54624]     return [f.to_dict() for f in gateway.list()]
[Wed Oct 14 17:56:23.169801 2020] [wsgi:error] [pid 278:tid 139668765869824] [remote 172.28.0.11:54624]   File "/home/django/cvat/apps/lambda_manager/views.py", line 63, in list
[Wed Oct 14 17:56:23.169804 2020] [wsgi:error] [pid 278:tid 139668765869824] [remote 172.28.0.11:54624]     response = [LambdaFunction(self, item) for item in data.values()]
[Wed Oct 14 17:56:23.169806 2020] [wsgi:error] [pid 278:tid 139668765869824] [remote 172.28.0.11:54624]   File "/home/django/cvat/apps/lambda_manager/views.py", line 63, in <listcomp>
[Wed Oct 14 17:56:23.169809 2020] [wsgi:error] [pid 278:tid 139668765869824] [remote 172.28.0.11:54624]     response = [LambdaFunction(self, item) for item in data.values()]
[Wed Oct 14 17:56:23.169812 2020] [wsgi:error] [pid 278:tid 139668765869824] [remote 172.28.0.11:54624]   File "/home/django/cvat/apps/lambda_manager/views.py", line 89, in __init__
[Wed Oct 14 17:56:23.169814 2020] [wsgi:error] [pid 278:tid 139668765869824] [remote 172.28.0.11:54624]     kind = data['metadata']['annotations'].get('type')
[Wed Oct 14 17:56:23.169819 2020] [wsgi:error] [pid 278:tid 139668765869824] [remote 172.28.0.11:54624] KeyError: 'annotations'
[Wed Oct 14 17:56:23.169826 2020] [wsgi:error] [pid 278:tid 139668765869824] [remote 172.28.0.11:54624]
```

**Comment by VinceJnz** [comment]
I seem to be have the same problem.
Is there any update on this or is there a workaround?

**Comment by yasakova-anastasia** [comment]
I wasn't able to reproduce the issue.
