### ISSUE TITLE
TypeError: Cannot read property 'close' of null

### ISSUE THREAD

**Issue by azhavoro** [opencv/cvat#269]
Error: Uncaught TypeError: Cannot read property 'close' of null Source file: https://cvat-icv.inn.intel.com/static/CACHE/js/99c118d9b707.js
Line: 4713
Error count: 1
Stack:

TypeError: Cannot read property 'close' of null
    at initializer._uis.shape.selectize.resize.on.on.on (https://cvat-icv.inn.intel.com/static/CACHE/js/99c118d9b707.js:4713:35)
    at initializer.fire (https://cvat-icv.inn.intel.com/static/CACHE/js/e21661c7e642.js:15108:19)
    at ResizeHandler.done (https://cvat-icv.inn.intel.com/static/CACHE/js/e21661c7e642.js:18002:17)
    at https://cvat-icv.inn.intel.com/static/CACHE/js/e21661c7e642.js:17962:19

P.S. I can't reproduce this issue.

**Comment by bsekachev** [comment]
I think we have fixed it.
