### ISSUE TITLE
Could not open a connection to your authentication agent.

### ISSUE THREAD

**Issue by Lazy12316** [opencv/cvat#277]
Hi, 

I get the error **Could not open a connection to your authentication agent.**
 when i am trying to build the cvat docker image.  

I tried to remove the unsuccessful build image and rebuild, but i am getting the same error at step40/42.

Took a look at docker file and found command **RUN python3 manage.py collectstatic** throws the error. 

Could you help me in troublshooting this error.

I am attaching the Screen shot of the error. 

![error](https://user-images.githubusercontent.com/29017758/51110198-c2090500-181d-11e9-9569-bea2487c0748.png)

**Comment by nmanovic** [comment]
@Lazy12316 , could you please send us logs for full build (attach a txt file with the output)? Errors in the output are very strange.

**Comment by Lazy12316** [comment]
@nmanovic , Here is the log file(txt format).  
[cvat_build.txt](https://github.com/opencv/cvat/files/2758585/cvat_build.txt)

**Comment by nmanovic** [comment]
Hi @Lazy12316 ,

Thanks for your report. The real problem is below.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/apps/config.py", line 118, in create
    cls = getattr(mod, cls_name)
AttributeError: module 'cvat.apps' has no attribute 'engine'
```

Could you please help us to investigate it and do more checks on your side?
- Remove your CVAT code and clone it again. It looks like your clone version isn't complete.
- After that run `git status` and post output here if you still have problems
- Build and run the container one more time. Please post your build and run commands here as well with outputs.

I hope together we will understand the problem and fix.

**Comment by Lazy12316** [comment]
@nmanovic , as per your suggestions, I again did clone cvat. Here is the output of `git status` .
[cvat-cloning-git-status.txt](https://github.com/opencv/cvat/files/2758660/cvat-cloning-git-status.txt)

I am unable to build the image as it throws the error 

```
Step 40/42 : RUN python3 manage.py collectstatic
 ---> Running in 551467168c1f
Could not open a connection to your authentication agent.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/apps/config.py", line 118, in create
    cls = getattr(mod, cls_name)
AttributeError: module 'cvat.apps' has no attribute 'engine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/usr/local/lib/python3.5/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.5/dist-packages/django/apps/registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.5/dist-packages/django/apps/config.py", line 123, in create
    import_module(entry)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'cvat.apps.engine'
ERROR: Service 'cvat' failed to build: The command '/bin/sh -c python3 manage.py collectstatic' returned a non-zero code: 1
```
I am trying to build the cvat application again and let you know the output as soon as possible.

Thanks :+1:

**Comment by nmanovic** [comment]
@Lazy12316 , cool! Don't hesitate to contact us if you have other problems. I will close the issue.
