### ISSUE TITLE
How to select files

### ISSUE THREAD

**Issue by kkew3** [opencv/cvat#280]
Hi. I'm having difficulty uploading images at task creation window. I tried uploading `avi` files but failed. Later I found in [this thread](https://github.com/opencv/cvat/issues/131) that I should convert the video to frames first. However, uploading `png` files failed for the same complaint. The complaint appears as a long document of red HTML at the bottom of the task creation window. Thank for any suggestion of fixing this issue.

I'm running on `macOS Majove 10.14.1`. I'm using Docker CE desktop app.

**Comment by nmanovic** [comment]
Hi @kkew3 , could you please send us logs (`docker logs cvat` output) and screenshots which describe the issue? You don't need to convert videos to frames in general case. CVAT will do it for you.

**Comment by JetteKA** [comment]
Hi, I am having the same problem of being unable to upload files. I receive the following message: 
![screenshot from 2019-01-18 10-52-34](https://user-images.githubusercontent.com/36188697/51397554-77360880-1b0f-11e9-829a-6502a3b90441.png)

docker logs cvat gives me:
![screenshot from 2019-01-18 11-01-34](https://user-images.githubusercontent.com/36188697/51398056-96816580-1b10-11e9-8ce9-876c9c0d6f04.png)

**Comment by kkew3** [comment]
Yeah, exactly the same issue. See the log below the screenshot. Thanks

<img width="270" alt="out" src="https://user-images.githubusercontent.com/13264071/51416088-e40bcb80-1b2c-11e9-8173-8620e4a85aa5.png">

```
2019-01-18 22:19:00,364 INFO RPC interface 'supervisor' initialized
2019-01-18 22:19:00,367 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2019-01-18 22:19:00,367 INFO supervisord started with pid 1
2019-01-18 22:19:01,372 INFO spawned: 'ssh-agent' with pid 11
2019-01-18 22:19:01,377 INFO spawned: 'git_status_updater' with pid 12
2019-01-18 22:19:01,380 INFO spawned: 'rqworker_low' with pid 13
2019-01-18 22:19:01,385 INFO spawned: 'runserver' with pid 14
2019-01-18 22:19:01,390 INFO spawned: 'rqworker_default_0' with pid 15
2019-01-18 22:19:01,392 INFO spawned: 'rqworker_default_1' with pid 16
2019-01-18 22:19:01,406 DEBG 'rqworker_low' stderr output:
wait-for-it.sh: waiting for redis:6379 without a timeout

2019-01-18 22:19:01,406 DEBG 'runserver' stderr output:
wait-for-it.sh: waiting for db:5432 without a timeout

2019-01-18 22:19:01,407 DEBG 'rqworker_default_0' stderr output:
wait-for-it.sh: waiting for cvat_redis:6379 without a timeout

2019-01-18 22:19:01,407 DEBG 'ssh-agent' stdout output:
SSH_AUTH_SOCK=/tmp/ssh-agent.sock; export SSH_AUTH_SOCK;
echo Agent pid 22;

2019-01-18 22:19:01,407 DEBG 'ssh-agent' stderr output:
debug2: fd 3 setting O_NONBLOCK

2019-01-18 22:19:01,407 DEBG 'rqworker_default_1' stderr output:
wait-for-it.sh: waiting for cvat_redis:6379 without a timeout

2019-01-18 22:19:01,408 DEBG 'git_status_updater' stderr output:
wait-for-it.sh: waiting for redis:6379 without a timeout

2019-01-18 22:19:01,418 DEBG 'runserver' stderr output:
wait-for-it.sh: db:5432 is available after 0 seconds

2019-01-18 22:19:01,418 DEBG 'rqworker_default_0' stderr output:
wait-for-it.sh: cvat_redis:6379 is available after 0 seconds

2019-01-18 22:19:01,418 DEBG 'rqworker_default_1' stderr output:
wait-for-it.sh: cvat_redis:6379 is available after 0 seconds

2019-01-18 22:19:01,418 DEBG 'git_status_updater' stderr output:
wait-for-it.sh: redis:6379 is available after 0 seconds

2019-01-18 22:19:01,418 DEBG 'rqworker_low' stderr output:
wait-for-it.sh: redis:6379 is available after 0 seconds

2019-01-18 22:19:01,420 DEBG 'rqworker_low' stderr output:
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell

2019-01-18 22:19:01,420 DEBG 'runserver' stderr output:
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell

2019-01-18 22:19:01,421 DEBG 'rqworker_default_1' stderr output:
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell

2019-01-18 22:19:01,421 DEBG 'git_status_updater' stderr output:
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell

2019-01-18 22:19:01,422 DEBG 'rqworker_default_0' stderr output:
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell

2019-01-18 22:19:01,721 DEBG 'ssh-agent' stderr output:
debug2: fd 4 setting O_NONBLOCK

2019-01-18 22:19:01,722 DEBG 'ssh-agent' stderr output:
debug1: XXX shrink: 3 < 4

2019-01-18 22:19:01,725 DEBG 'ssh-agent' stderr output:
debug2: fd 4 setting O_NONBLOCK
debug1: type 11

2019-01-18 22:19:01,726 DEBG 'ssh-agent' stderr output:
debug1: XXX shrink: 3 < 4

2019-01-18 22:19:01,730 DEBG 'ssh-agent' stderr output:
debug2: fd 4 setting O_NONBLOCK

2019-01-18 22:19:01,732 DEBG 'ssh-agent' stderr output:
debug1: type 17

2019-01-18 22:19:01,734 DEBG 'git_status_updater' stderr output:
Identity added: /home/django/.ssh/id_rsa (/home/django/.ssh/id_rsa)

2019-01-18 22:19:01,734 DEBG 'ssh-agent' stderr output:
debug1: XXX shrink: 3 < 4

2019-01-18 22:19:01,737 DEBG 'ssh-agent' stderr output:
debug2: fd 4 setting O_NONBLOCK

2019-01-18 22:19:01,739 DEBG 'ssh-agent' stderr output:
debug1: type 17

2019-01-18 22:19:01,741 DEBG 'ssh-agent' stderr output:
debug1: XXX shrink: 3 < 4

2019-01-18 22:19:01,745 DEBG 'ssh-agent' stderr output:
debug2: fd 4 setting O_NONBLOCK
debug1: type 11

2019-01-18 22:19:01,746 DEBG 'ssh-agent' stderr output:
debug1: XXX shrink: 3 < 4

2019-01-18 22:19:01,750 DEBG 'ssh-agent' stderr output:
debug2: fd 4 setting O_NONBLOCK

2019-01-18 22:19:01,753 DEBG 'ssh-agent' stderr output:
debug1: type 17

2019-01-18 22:19:01,755 DEBG 'ssh-agent' stderr output:
debug1: XXX shrink: 3 < 4

2019-01-18 22:19:01,760 DEBG 'ssh-agent' stderr output:
debug2: fd 4 setting O_NONBLOCK
debug1: type 11

2019-01-18 22:19:01,760 DEBG 'ssh-agent' stderr output:
debug1: XXX shrink: 3 < 4

2019-01-18 22:19:01,766 DEBG 'ssh-agent' stderr output:
debug2: fd 4 setting O_NONBLOCK

2019-01-18 22:19:01,777 DEBG 'ssh-agent' stderr output:
debug1: type 17

2019-01-18 22:19:01,779 DEBG 'ssh-agent' stderr output:
debug1: XXX shrink: 3 < 4

2019-01-18 22:19:01,784 DEBG 'ssh-agent' stderr output:
debug2: fd 4 setting O_NONBLOCK
debug1: type 11

2019-01-18 22:19:01,785 DEBG 'ssh-agent' stderr output:
debug1: XXX shrink: 3 < 4

2019-01-18 22:19:01,790 DEBG 'ssh-agent' stderr output:
debug2: fd 4 setting O_NONBLOCK

2019-01-18 22:19:01,793 DEBG 'ssh-agent' stderr output:
debug1: type 17

2019-01-18 22:19:01,795 DEBG 'ssh-agent' stderr output:
debug1: XXX shrink: 3 < 4

2019-01-18 22:19:01,800 DEBG 'ssh-agent' stderr output:
debug2: fd 4 setting O_NONBLOCK
debug1: type 11

2019-01-18 22:19:01,801 DEBG 'ssh-agent' stderr output:
debug1: XXX shrink: 3 < 4

2019-01-18 22:19:02,802 INFO success: ssh-agent entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-01-18 22:19:02,802 INFO success: git_status_updater entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-01-18 22:19:02,802 INFO success: rqworker_low entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-01-18 22:19:02,803 INFO success: runserver entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-01-18 22:19:02,803 INFO success: rqworker_default_0 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-01-18 22:19:02,803 INFO success: rqworker_default_1 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-01-18 22:19:03,323 DEBG 'rqworker_default_1' stderr output:
22:19:03 Registering birth of worker a9d3d40a3f16.16

2019-01-18 22:19:03,326 DEBG 'rqworker_default_1' stderr output:
22:19:03 RQ worker 'rq:worker:a9d3d40a3f16.16' started, version 0.10.0

2019-01-18 22:19:03,326 DEBG 'rqworker_default_1' stderr output:
22:19:03 *** Listening on default...

2019-01-18 22:19:03,328 DEBG 'rqworker_default_1' stderr output:
22:19:03 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.

2019-01-18 22:19:03,329 DEBG 'rqworker_default_1' stderr output:
22:19:03 Cleaning registries for queue: default

2019-01-18 22:19:03,330 DEBG 'rqworker_default_1' stderr output:
22:19:03 *** Listening on default...

2019-01-18 22:19:03,331 DEBG 'rqworker_default_1' stderr output:
22:19:03 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.

2019-01-18 22:19:03,336 DEBG 'rqworker_low' stderr output:
22:19:03 Registering birth of worker a9d3d40a3f16.13

2019-01-18 22:19:03,337 DEBG 'rqworker_default_0' stderr output:
22:19:03 Registering birth of worker a9d3d40a3f16.15

2019-01-18 22:19:03,339 DEBG 'rqworker_low' stderr output:
22:19:03 RQ worker 'rq:worker:a9d3d40a3f16.13' started, version 0.10.0

2019-01-18 22:19:03,340 DEBG 'rqworker_low' stderr output:
22:19:03 *** Listening on low...

2019-01-18 22:19:03,340 DEBG 'rqworker_default_0' stderr output:
22:19:03 RQ worker 'rq:worker:a9d3d40a3f16.15' started, version 0.10.0

2019-01-18 22:19:03,341 DEBG 'rqworker_low' stderr output:
22:19:03 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
22:19:03 Cleaning registries for queue: low

2019-01-18 22:19:03,342 DEBG 'rqworker_default_0' stderr output:
22:19:03 *** Listening on default...
22:19:03 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.

2019-01-18 22:19:03,343 DEBG 'rqworker_low' stderr output:
22:19:03 *** Listening on low...

2019-01-18 22:19:03,343 DEBG 'rqworker_default_0' stderr output:
22:19:03 Cleaning registries for queue: default

2019-01-18 22:19:03,344 DEBG 'rqworker_low' stderr output:
22:19:03 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.

2019-01-18 22:19:03,344 DEBG 'rqworker_default_0' stderr output:
22:19:03 *** Listening on default...

2019-01-18 22:19:03,345 DEBG 'rqworker_default_0' stderr output:
22:19:03 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.

2019-01-18 22:19:03,706 DEBG 'runserver' stdout output:
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, engine, git, sessions
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.

2019-01-18 22:19:03,929 DEBG 'ssh-agent' stderr output:
debug2: fd 4 setting O_NONBLOCK

2019-01-18 22:19:03,930 DEBG 'ssh-agent' stderr output:
debug1: type 17

2019-01-18 22:19:03,932 DEBG 'ssh-agent' stderr output:
debug1: XXX shrink: 3 < 4

2019-01-18 22:19:03,935 DEBG 'ssh-agent' stderr output:
debug2: fd 4 setting O_NONBLOCK
debug1: type 11

2019-01-18 22:19:03,935 DEBG 'ssh-agent' stderr output:
debug1: XXX shrink: 3 < 4

2019-01-18 22:19:04,241 DEBG 'runserver' stdout output:

0 static files copied to '/home/django/static', 301 unmodified.

2019-01-18 22:19:04,364 DEBG 'ssh-agent' stderr output:
debug2: fd 4 setting O_NONBLOCK

2019-01-18 22:19:04,366 DEBG 'ssh-agent' stderr output:
debug1: type 17

2019-01-18 22:19:04,367 DEBG 'ssh-agent' stderr output:
debug1: XXX shrink: 3 < 4

2019-01-18 22:19:04,370 DEBG 'ssh-agent' stderr output:
debug2: fd 4 setting O_NONBLOCK
debug1: type 11

2019-01-18 22:19:04,370 DEBG 'ssh-agent' stderr output:
debug1: XXX shrink: 3 < 4

2019-01-18 22:19:04,835 DEBG 'runserver' stdout output:
Successfully ran command.
Server URL         : http://localhost:8080/
Server Root        : /tmp/mod_wsgi-localhost:8080:1000
Server Conf        : /tmp/mod_wsgi-localhost:8080:1000/httpd.conf
Error Log File     : /dev/stderr (INFO)
Request Capacity   : 5 (1 process * 5 threads)
Request Timeout    : 60 (seconds)
Startup Timeout    : 15 (seconds)
Queue Backlog      : 100 (connections)
Queue Timeout      : 45 (seconds)
Server Capacity    : 20 (event/worker), 20 (prefork)
Server Backlog     : 500 (connections)
Locale Setting     : C.UTF-8

2019-01-18 22:19:04,894 DEBG 'runserver' stderr output:
[Fri Jan 18 22:19:04.893938 2019] [wsgi:info] [pid 146:tid 140681297155968] mod_wsgi (pid=146): Starting process 'localhost:8080' with threads=5.
[Fri Jan 18 22:19:04.894006 2019] [mpm_event:notice] [pid 14:tid 140681297155968] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.6.2 Python/3.5 configured -- resuming normal operations
[Fri Jan 18 22:19:04.894060 2019] [mpm_event:info] [pid 14:tid 140681297155968] AH00490: Server built: 2018-06-07T19:43:03
[Fri Jan 18 22:19:04.894085 2019] [core:notice] [pid 14:tid 140681297155968] AH00094: Command line: 'apache2 (mod_wsgi-express) -f /tmp/mod_wsgi-localhost:8080:1000/httpd.conf -D MOD_WSGI_MPM_ENABLE_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_WORKER_MODULE -D MOD_WSGI_MPM_EXISTS_PREFORK_MODULE -D FOREGROUND'

2019-01-18 22:19:04,895 DEBG 'runserver' stderr output:
[Fri Jan 18 22:19:04.894976 2019] [wsgi:info] [pid 146:tid 140681297155968] mod_wsgi (pid=146): Python home /usr.
[Fri Jan 18 22:19:04.895034 2019] [wsgi:info] [pid 146:tid 140681297155968] mod_wsgi (pid=146): Initializing Python.

2019-01-18 22:19:04,919 DEBG 'runserver' stderr output:
[Fri Jan 18 22:19:04.919105 2019] [wsgi:info] [pid 146:tid 140681297155968] mod_wsgi (pid=146): Attach interpreter ''.

2019-01-18 22:19:04,930 DEBG 'runserver' stderr output:
[Fri Jan 18 22:19:04.929809 2019] [wsgi:info] [pid 146:tid 140681297155968] mod_wsgi (pid=146): Imported 'mod_wsgi'.
[Fri Jan 18 22:19:04.929884 2019] [wsgi:info] [pid 146:tid 140681297155968] mod_wsgi (pid=146, process='localhost:8080', application=''): Loading Python script file '/tmp/mod_wsgi-localhost:8080:1000/handler.wsgi'.

2019-01-18 22:19:05,078 DEBG 'ssh-agent' stderr output:
debug2: fd 4 setting O_NONBLOCK

2019-01-18 22:19:05,079 DEBG 'ssh-agent' stderr output:
debug1: type 17

2019-01-18 22:19:05,080 DEBG 'ssh-agent' stderr output:
debug1: XXX shrink: 3 < 4

2019-01-18 22:19:05,083 DEBG 'ssh-agent' stderr output:
debug2: fd 4 setting O_NONBLOCK
debug1: type 11

2019-01-18 22:19:05,083 DEBG 'ssh-agent' stderr output:
debug1: XXX shrink: 3 < 4

2019-01-18 22:19:40,506 DEBG 'runserver' stderr output:
[Fri Jan 18 22:19:40.506074 2019] [wsgi:error] [pid 146:tid 140681079125760] [remote 172.18.0.1:41260] [2019-01-18 22:19:40,503] WARNING django.request: Forbidden (Permission denied): /create/task
[Fri Jan 18 22:19:40.506113 2019] [wsgi:error] [pid 146:tid 140681079125760] [remote 172.18.0.1:41260] Traceback (most recent call last):
[Fri Jan 18 22:19:40.506117 2019] [wsgi:error] [pid 146:tid 140681079125760] [remote 172.18.0.1:41260]   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 34, in inner
[Fri Jan 18 22:19:40.506119 2019] [wsgi:error] [pid 146:tid 140681079125760] [remote 172.18.0.1:41260]     response = get_response(request)
[Fri Jan 18 22:19:40.506120 2019] [wsgi:error] [pid 146:tid 140681079125760] [remote 172.18.0.1:41260]   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 126, in _get_response
[Fri Jan 18 22:19:40.506122 2019] [wsgi:error] [pid 146:tid 140681079125760] [remote 172.18.0.1:41260]     response = self.process_exception_by_middleware(e, request)
[Fri Jan 18 22:19:40.506123 2019] [wsgi:error] [pid 146:tid 140681079125760] [remote 172.18.0.1:41260]   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 124, in _get_response
[Fri Jan 18 22:19:40.506125 2019] [wsgi:error] [pid 146:tid 140681079125760] [remote 172.18.0.1:41260]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jan 18 22:19:40.506126 2019] [wsgi:error] [pid 146:tid 140681079125760] [remote 172.18.0.1:41260]   File "/home/django/cvat/apps/authentication/decorators.py", line 20, in _wrapped_view
[Fri Jan 18 22:19:40.506128 2019] [wsgi:error] [pid 146:tid 140681079125760] [remote 172.18.0.1:41260]     return view_func(request, *args, **kwargs)
[Fri Jan 18 22:19:40.506129 2019] [wsgi:error] [pid 146:tid 140681079125760] [remote 172.18.0.1:41260]   File "/usr/local/lib/python3.5/dist-packages/rules/contrib/views.py", line 132, in _wrapped_view
[Fri Jan 18 22:19:40.506130 2019] [wsgi:error] [pid 146:tid 140681079125760] [remote 172.18.0.1:41260]     raise PermissionDenied()
[Fri Jan 18 22:19:40.506133 2019] [wsgi:error] [pid 146:tid 140681079125760] [remote 172.18.0.1:41260] django.core.exceptions.PermissionDenied
[Fri Jan 18 22:19:40.506138 2019] [wsgi:error] [pid 146:tid 140681079125760] [remote 172.18.0.1:41260] 

2019-01-18 22:25:03,361 DEBG 'rqworker_low' stderr output:
22:25:03 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.

2019-01-18 22:25:03,361 DEBG 'rqworker_default_1' stderr output:
22:25:03 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.

2019-01-18 22:25:03,362 DEBG 'rqworker_default_0' stderr output:
22:25:03 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
```

**Comment by nmanovic** [comment]
> 2019-01-18 22:19:40,506 DEBG 'runserver' stderr output:
[Fri Jan 18 22:19:40.506074 2019] [wsgi:error] [pid 146:tid 140681079125760] [remote 172.18.0.1:41260] [2019-01-18 22:19:40,503] WARNING django.request: Forbidden (Permission denied): /create/task
[Fri Jan 18 22:19:40.506113 2019] [wsgi:error] [pid 146:tid 140681079125760] [remote 172.18.0.1:41260] Traceback (most recent call last):
[Fri Jan 18 22:19:40.506117 2019] [wsgi:error] [pid 146:tid 140681079125760] [remote 172.18.0.1:41260]   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 34, in inner
[Fri Jan 18 22:19:40.506119 2019] [wsgi:error] [pid 146:tid 140681079125760] [remote 172.18.0.1:41260]     response = get_response(request)
[Fri Jan 18 22:19:40.506120 2019] [wsgi:error] [pid 146:tid 140681079125760] [remote 172.18.0.1:41260]   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 126, in _get_response
[Fri Jan 18 22:19:40.506122 2019] [wsgi:error] [pid 146:tid 140681079125760] [remote 172.18.0.1:41260]     response = self.process_exception_by_middleware(e, request)
[Fri Jan 18 22:19:40.506123 2019] [wsgi:error] [pid 146:tid 140681079125760] [remote 172.18.0.1:41260]   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 124, in _get_response
[Fri Jan 18 22:19:40.506125 2019] [wsgi:error] [pid 146:tid 140681079125760] [remote 172.18.0.1:41260]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jan 18 22:19:40.506126 2019] [wsgi:error] [pid 146:tid 140681079125760] [remote 172.18.0.1:41260]   File "/home/django/cvat/apps/authentication/decorators.py", line 20, in _wrapped_view
[Fri Jan 18 22:19:40.506128 2019] [wsgi:error] [pid 146:tid 140681079125760] [remote 172.18.0.1:41260]     return view_func(request, *args, **kwargs)
[Fri Jan 18 22:19:40.506129 2019] [wsgi:error] [pid 146:tid 140681079125760] [remote 172.18.0.1:41260]   File "/usr/local/lib/python3.5/dist-packages/rules/contrib/views.py", line 132, in _wrapped_view
[Fri Jan 18 22:19:40.506130 2019] [wsgi:error] [pid 146:tid 140681079125760] [remote 172.18.0.1:41260]     raise PermissionDenied()
[Fri Jan 18 22:19:40.506133 2019] [wsgi:error] [pid 146:tid 140681079125760] [remote 172.18.0.1:41260] django.core.exceptions.PermissionDenied
[Fri Jan 18 22:19:40.506138 2019] [wsgi:error] [pid 146:tid 140681079125760] [remote 172.18.0.1:41260] 


It is a problem with permissions. Probably you try to use a user account which doesn't have permissions to create tasks. There are two solutions:
- Create annotation tasks as admin
- Add permissions to your user to create tasks. For that you need to go to `/admin` panel, find your specific user, add `user` group for the user, and save changes.

![image](https://user-images.githubusercontent.com/40690625/51457663-40583080-1d63-11e9-9190-7498c484755d.png)

**Comment by nmanovic** [comment]
hi @kkew3 ,

I will close the issue. Don't hesitate to ask additional question here: gitter.im/opencv-cvat
