### ISSUE TITLE
Cannot read property 'color' of undefined

### ISSUE THREAD

**Issue by bsekachev** [opencv/cvat#3461]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

```
Source file: https://cvat.org/cvat-ui.b40eb572e7cfa9120412.min.js
Line: 414
Error count: 40
Stack:

TypeError: Cannot read property 'color' of undefined
    at Function.mapToProps (https://cvat.org/cvat-ui.b40eb572e7cfa9120412.min.js:414:1046760)
    at r (https://cvat.org/cvat-ui.b40eb572e7cfa9120412.min.js:6:8176)
    at h (https://cvat.org/cvat-ui.b40eb572e7cfa9120412.min.js:6:9570)
    at https://cvat.org/cvat-ui.b40eb572e7cfa9120412.min.js:6:9642
    at e.f (https://cvat.org/cvat-ui.b40eb572e7cfa9120412.min.js:6:4909)
    at e.t.handleChangeWrapper (https://cvat.org/cvat-ui.b40eb572e7cfa9120412.min.js:6:3216)
    at https://cvat.org/cvat-ui.b40eb572e7cfa9120412.min.js:6:2543
    at el (https://cvat.org/cvat-ui.b40eb572e7cfa9120412.min.js:352:93938)
    at Object.notify (https://cvat.org/cvat-ui.b40eb572e7cfa9120412.min.js:6:2512)
    at e.t.notifyNestedSubs (https://cvat.org/cvat-ui.b40eb572e7cfa9120412.min.js:6:3148)

```

### Expected Behaviour
Error does not occur

### Current Behaviour
Error occurs on cvat.org

### Possible Solution
Fix the bug

### Steps to Reproduce (for bugs)

1. Need to investigate, email notification with exception
2. 

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
The issue is quite old and maybe outdated. 
Since it does not have a way to reproduce I will close the issue now and maybe will investigate it in the future if it appears again.
