### ISSUE TITLE
Cannot read property 'loaders' of null

### ISSUE THREAD

**Issue by bsekachev** [opencv/cvat#3462]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

```
Error: Cannot read property 'loaders' of null Source file: https://cvat.org/cvat-ui.b40eb572e7cfa9120412.min.js
Line: 414
Error count: 1
Stack:

TypeError: Cannot read property 'loaders' of null
    at https://cvat.org/cvat-ui.b40eb572e7cfa9120412.min.js:414:917507
    at Ko (https://cvat.org/cvat-ui.b40eb572e7cfa9120412.min.js:352:57930)
    at gs (https://cvat.org/cvat-ui.b40eb572e7cfa9120412.min.js:352:104169)
    at cl (https://cvat.org/cvat-ui.b40eb572e7cfa9120412.min.js:352:96717)
    at sl (https://cvat.org/cvat-ui.b40eb572e7cfa9120412.min.js:352:96642)
    at Qs (https://cvat.org/cvat-ui.b40eb572e7cfa9120412.min.js:352:93672)
    at https://cvat.org/cvat-ui.b40eb572e7cfa9120412.min.js:352:45314
    at t.unstable_runWithPriority (https://cvat.org/cvat-ui.b40eb572e7cfa9120412.min.js:360:3844)
    at Ba (https://cvat.org/cvat-ui.b40eb572e7cfa9120412.min.js:352:45023)
    at Ga (https://cvat.org/cvat-ui.b40eb572e7cfa9120412.min.js:352:45259)

```

### Expected Behaviour
Error does not occur

### Current Behaviour
Error occurs on cvat.org

### Steps to Reproduce (for bugs)

1. Need to investigate, email notification

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
The issue is quite old and maybe outdated. 
Since it does not have a way to reproduce I will close the issue now and maybe will investigate it in the future if it appears again.
