### ISSUE TITLE
Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

### ISSUE THREAD

**Issue by bsekachev** [opencv/cvat#3463]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

```
Source file: https://cvat.org/cvat-ui.b40eb572e7cfa9120412.min.js
Line: 352
Error count: 6
Stack:

Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at e (https://cvat.org/cvat-ui.b40eb572e7cfa9120412.min.js:352:85984)
    at e (https://cvat.org/cvat-ui.b40eb572e7cfa9120412.min.js:352:86057)
    at e (https://cvat.org/cvat-ui.b40eb572e7cfa9120412.min.js:352:86057)
    at cs (https://cvat.org/cvat-ui.b40eb572e7cfa9120412.min.js:352:86109)
    at pl (https://cvat.org/cvat-ui.b40eb572e7cfa9120412.min.js:352:99638)
    at t.unstable_runWithPriority (https://cvat.org/cvat-ui.b40eb572e7cfa9120412.min.js:360:3844)
    at Ba (https://cvat.org/cvat-ui.b40eb572e7cfa9120412.min.js:352:45023)
    at fl (https://cvat.org/cvat-ui.b40eb572e7cfa9120412.min.js:352:97717)
    at Qs (https://cvat.org/cvat-ui.b40eb572e7cfa9120412.min.js:352:93871)
    at https://cvat.org/cvat-ui.b40eb572e7cfa9120412.min.js:352:45314

```

### Expected Behaviour
Error does not occur

### Current Behaviour
Error occurs on cvat.org

### Steps to Reproduce (for bugs)

1. Need to investigate, email notification

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
Not sure it is still relevant. Let's close for now.
