### ISSUE TITLE
Import Task failed: 'UnboundLocalError: local variable 'source' referenced before assignment'

### ISSUE THREAD

**Issue by timiil** [opencv/cvat#3637]
hi,  i am trying to import a task with a zip file, which have the files : annotations.json, task.json, data\*.png, manifest.jsonl ;

but i hit this error: 
```
Error: Request failed with status code 500. "UnboundLocalError: local variable 'source' referenced before assignment\n".
```

check the detail docker logs :

```
2021-09-03 08:00:01,197 DEBG 'rqworker_default_0' stderr output:
[2021-09-03 08:00:01,196] INFO cvat.server: create task #19

2021-09-03 08:00:01,197 DEBG 'rqworker_default_0' stderr output:
INFO - 2021-09-03 08:00:01,196 - task - create task #19

2021-09-03 08:00:01,243 DEBG 'rqworker_default_0' stderr output:
[2021-09-03 08:00:01,242] INFO cvat.server: Found frames 111 for Data #19

2021-09-03 08:00:01,243 DEBG 'rqworker_default_0' stderr output:
INFO - 2021-09-03 08:00:01,242 - task - Found frames 111 for Data #19

2021-09-03 08:00:01,243 DEBG 'rqworker_default_0' stderr output:
[2021-09-03 08:00:01,243] INFO cvat.server: New segment for task #19: start_frame = 0,             stop_frame = 30

2021-09-03 08:00:01,243 DEBG 'rqworker_default_0' stderr output:
INFO - 2021-09-03 08:00:01,243 - task - New segment for task #19: start_frame = 0,             stop_frame = 30

2021-09-03 08:00:01,247 DEBG 'rqworker_default_0' stderr output:
[2021-09-03 08:00:01,247] INFO cvat.server: New segment for task #19: start_frame = 31,             stop_frame = 61

2021-09-03 08:00:01,247 DEBG 'rqworker_default_0' stderr output:
INFO - 2021-09-03 08:00:01,247 - task - New segment for task #19: start_frame = 31,             stop_frame = 61

2021-09-03 08:00:01,249 DEBG 'rqworker_default_0' stderr output:
[2021-09-03 08:00:01,248] INFO cvat.server: New segment for task #19: start_frame = 62,             stop_frame = 92

2021-09-03 08:00:01,249 DEBG 'rqworker_default_0' stderr output:
INFO - 2021-09-03 08:00:01,248 - task - New segment for task #19: start_frame = 62,             stop_frame = 92

2021-09-03 08:00:01,250 DEBG 'rqworker_default_0' stderr output:
[2021-09-03 08:00:01,250] INFO cvat.server: New segment for task #19: start_frame = 93,             stop_frame = 110

2021-09-03 08:00:01,251 DEBG 'rqworker_default_0' stderr output:
INFO - 2021-09-03 08:00:01,250 - task - New segment for task #19: start_frame = 93,             stop_frame = 110

2021-09-03 08:00:01,279 DEBG 'rqworker_default_0' stderr output:
DEBUG - 2021-09-03 08:00:01,279 - worker - Handling failed execution of job admin@/api/v1/tasks/063fbeb2-2cef-4eef-a5ab-5c1c2d37c742/import

2021-09-03 08:00:01,280 DEBG 'rqworker_default_0' stderr output:
ERROR - 2021-09-03 08:00:01,280 - worker - Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/rq/worker.py", line 936, in perform_job
    rv = job.perform()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 684, in perform
    self._result = self._execute()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 690, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/django/cvat/apps/engine/backup.py", line 549, in import_task
    db_task = task_importer.import_task()
  File "/home/django/cvat/apps/engine/backup.py", line 542, in import_task
    self._import_annotations()
  File "/home/django/cvat/apps/engine/backup.py", line 538, in _import_annotations
    self._create_annotations(db_job, annotations)
  File "/home/django/cvat/apps/engine/backup.py", line 428, in _create_annotations
    self._prepare_annotations(annotations, self._labels_mapping)
  File "/home/django/cvat/apps/engine/backup.py", line 133, in _prepare_annotations
    label = _update_label(tag)
  File "/home/django/cvat/apps/engine/backup.py", line 128, in _update_label
    shape[dest] = label_mapping[source]['value']
UnboundLocalError: local variable 'source' referenced before assignment
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/rq/worker.py", line 936, in perform_job
    rv = job.perform()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 684, in perform
    self._result = self._execute()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 690, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/django/cvat/apps/engine/backup.py", line 549, in import_task
    db_task = task_importer.import_task()
  File "/home/django/cvat/apps/engine/backup.py", line 542, in import_task
    self._import_annotations()
  File "/home/django/cvat/apps/engine/backup.py", line 538, in _import_annotations
    self._create_annotations(db_job, annotations)
  File "/home/django/cvat/apps/engine/backup.py", line 428, in _create_annotations
    self._prepare_annotations(annotations, self._labels_mapping)
  File "/home/django/cvat/apps/engine/backup.py", line 133, in _prepare_annotations
    label = _update_label(tag)
  File "/home/django/cvat/apps/engine/backup.py", line 128, in _update_label
    shape[dest] = label_mapping[source]['value']
UnboundLocalError: local variable 'source' referenced before assignment

```

could someone give me some tips that more more detail information ?

**Comment by bsekachev** [comment]
Not sure it is still relevant. Let's close it for now. If somebody can reproduce it in newest version, please, reopen
