### ISSUE TITLE
Cannot run the sample code

### ISSUE THREAD

**Issue by lamsongianm** [opencv/cvat#4597]
python classification_sample_async.py -m /home/ron/PycharmProjects/behavior_detection/ir/googlenet-v1.xml -i ~/Downloads/car.jpg -d MYRIAD
[ INFO ] Creating OpenVINO Runtime Core
[ INFO ] Reading the model: /home/ron/PycharmProjects/behavior_detection/ir/googlenet-v1.xml
[ INFO ] Loading the model to the plugin
Traceback (most recent call last):
  File "/opt/intel/openvino_2022.1.0.643/samples/python/classification_sample_async/classification_sample_async.py", line 131, in <module>
    sys.exit(main())
  File "/opt/intel/openvino_2022.1.0.643/samples/python/classification_sample_async/classification_sample_async.py", line 113, in main
    compiled_model = core.compile_model(model, args.device)
  File "/home/ron/anaconda3/lib/python3.9/site-packages/openvino/runtime/ie_api.py", line 266, in compile_model
    super().compile_model(model, device_name, {} if config is None else config)
RuntimeError: Cannot load library 'libopenvino_intel_myriad_plugin.so: libopenvino_intel_myriad_plugin.so: cannot open shared object file: No such file or directory

**Comment by lamsongianm** [comment]
fixed it

**Comment by nmanovic** [comment]
@lamsongianm , I'm not sure it is the right repository for the issue.

**Comment by lamsongianm** [comment]
@nmanovic  Hi, I reinstall the runtime and development tools, the system shows the different message as below: 

[ INFO ] Loading the model to the plugin
E: [ncAPI] [    705965] [python] ncDeviceOpen:1013	Failed to find booted device after boot
Traceback (most recent call last):
  File "/opt/intel/openvino_2022.1.0.643/samples/python/classification_sample_async/classification_sample_async.py", line 131, in <module>
    sys.exit(main())
  File "/opt/intel/openvino_2022.1.0.643/samples/python/classification_sample_async/classification_sample_async.py", line 113, in main
    compiled_model = core.compile_model(model, args.device)
  File "/opt/intel/openvino_2022.1.0.643/python/python3.9/openvino/runtime/ie_api.py", line 266, in compile_model
    super().compile_model(model, device_name, {} if config is None else config)
RuntimeError: Failed to allocate graph: MYRIAD device is not opened.

Please help to fix it, thanks a lot.
