### ISSUE TITLE
The Build failed with following error-The command '/bin/sh -c python3 manage.py collectstatic' returned a non-zero code: 1

### ISSUE THREAD

**Issue by msaqib17** [opencv/cvat#4640]
**The build is failing for CVAT.**
**sudo docker-compose -f docker-compose.yml -f docker-compose.dev.yml build**

### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

Step 52/54 : RUN python3 manage.py collectstatic
 ---> Running in 74c710c4f8f3
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/config.py", line 388, in resolve
    found = getattr(found, frag)
AttributeError: module 'logstash_async' has no attribute 'handler'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/config.py", line 390, in resolve
    self.importer(used)
  File "/opt/venv/lib/python3.8/site-packages/logstash_async/handler.py", line 11, in <module>
    from logstash_async.worker import LogProcessingWorker
  File "/opt/venv/lib/python3.8/site-packages/logstash_async/worker.py", line 12, in <module>
    from limits import parse as parse_rate_limit
  File "/opt/venv/lib/python3.8/site-packages/limits/__init__.py", line 5, in <module>
    from . import _version, aio, storage, strategies
  File "/opt/venv/lib/python3.8/site-packages/limits/aio/__init__.py", line 1, in <module>
    from . import storage, strategies
  File "/opt/venv/lib/python3.8/site-packages/limits/aio/storage/__init__.py", line 6, in <module>
    from .base import MovingWindowSupport, Storage
  File "/opt/venv/lib/python3.8/site-packages/limits/aio/storage/base.py", line 5, in <module>
    from limits.storage.registry import StorageRegistry
  File "/opt/venv/lib/python3.8/site-packages/limits/storage/__init__.py", line 12, in <module>
    from .base import MovingWindowSupport, Storage
  File "/opt/venv/lib/python3.8/site-packages/limits/storage/base.py", line 4, in <module>
    from limits.storage.registry import StorageRegistry
  File "/opt/venv/lib/python3.8/site-packages/limits/storage/registry.py", line 5, in <module>
    from limits.typing import Dict, List, Tuple, Union
  File "/opt/venv/lib/python3.8/site-packages/limits/typing.py", line 13, in <module>
    from typing_extensions import ClassVar, Counter, ParamSpec, Protocol
ImportError: cannot import name 'ParamSpec' from 'typing_extensions' (/opt/venv/lib/python3.8/site-packages/typing_extensions.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/config.py", line 563, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/lib/python3.8/logging/config.py", line 721, in configure_handler
    klass = self.resolve(cname)
  File "/usr/lib/python3.8/logging/config.py", line 397, in resolve
    raise v
  File "/usr/lib/python3.8/logging/config.py", line 390, in resolve
    self.importer(used)
  File "/opt/venv/lib/python3.8/site-packages/logstash_async/handler.py", line 11, in <module>
    from logstash_async.worker import LogProcessingWorker
  File "/opt/venv/lib/python3.8/site-packages/logstash_async/worker.py", line 12, in <module>
    from limits import parse as parse_rate_limit
  File "/opt/venv/lib/python3.8/site-packages/limits/__init__.py", line 5, in <module>
    from . import _version, aio, storage, strategies
  File "/opt/venv/lib/python3.8/site-packages/limits/aio/__init__.py", line 1, in <module>
    from . import storage, strategies
  File "/opt/venv/lib/python3.8/site-packages/limits/aio/storage/__init__.py", line 6, in <module>
    from .base import MovingWindowSupport, Storage
  File "/opt/venv/lib/python3.8/site-packages/limits/aio/storage/base.py", line 5, in <module>
    from limits.storage.registry import StorageRegistry
  File "/opt/venv/lib/python3.8/site-packages/limits/storage/__init__.py", line 12, in <module>
    from .base import MovingWindowSupport, Storage
  File "/opt/venv/lib/python3.8/site-packages/limits/storage/base.py", line 4, in <module>
    from limits.storage.registry import StorageRegistry
  File "/opt/venv/lib/python3.8/site-packages/limits/storage/registry.py", line 5, in <module>
    from limits.typing import Dict, List, Tuple, Union
  File "/opt/venv/lib/python3.8/site-packages/limits/typing.py", line 13, in <module>
    from typing_extensions import ClassVar, Counter, ParamSpec, Protocol
ValueError: Cannot resolve 'logstash_async.handler.AsynchronousLogstashHandler': cannot import name 'ParamSpec' from 'typing_extensions' (/opt/venv/lib/python3.8/site-packages/typing_extensions.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/opt/venv/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/opt/venv/lib/python3.8/site-packages/django/utils/log.py", line 75, in configure_logging
    logging_config_func(logging_settings)
  File "/usr/lib/python3.8/logging/config.py", line 808, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python3.8/logging/config.py", line 570, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'logstash'
The command '/bin/sh -c python3 manage.py collectstatic' returned a non-zero code: 1
ERROR: Service 'cvat' failed to build : Build failed

### Your Environment

- Git hash commit (`git log -1`): 2bb8643c1aba53b9ee4fd836b0955340f61d80ed
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.16
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 20.04.4 LTS
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
Hi, I didn't meet such the issue. Did you do any changes in dependencies?
Try to use pre-built CVAT: ``docker-compose -f docker-compose.yml -f up -d --build``

**Comment by bsekachev** [comment]
Also, please, try this patch #4574

**Comment by PMazarovich** [comment]
Got the same stuff.
I added these:
--use-deprecated=legacy-resolver in Dockerfile:49
and 
typing-extensions==3.10.0.2 to base.txt (requirements)

**Comment by kirill-sizov** [comment]
Hi, @msaqib17, is this issue still relevant for you?

**Comment by msaqib17** [comment]
> Hi, @msaqib17, is this issue still relevant for you?

Hi @kirill-sizov  the issue was resolved. You can close the issue. Thanks for the support.
