### ISSUE TITLE
Management group was deleted incorrectly

### ISSUE THREAD

**Issue by Sunny-Day200** [opencv/cvat#4788]
Operation error delete management group, unable to log in to admin。
How should I add it again。
-----------------------------------------------------------------------------
docker exec -it cvat bash -ic 'python3 ~/manage.py createsuperuser'
Traceback (most recent call last):
  File "/home/django/manage.py", line 21, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/venv/lib/python3.8/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 79, in execute
    return super().execute(*args, **options)
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/venv/lib/python3.8/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 189, in handle
    self.UserModel._default_manager.db_manager(database).create_superuser(**user_data)
  File "/opt/venv/lib/python3.8/site-packages/django/contrib/auth/models.py", line 163, in create_superuser
    return self._create_user(username, email, password, **extra_fields)
  File "/opt/venv/lib/python3.8/site-packages/django/contrib/auth/models.py", line 146, in _create_user
    user.save(using=self._db)
  File "/opt/venv/lib/python3.8/site-packages/django/contrib/auth/base_user.py", line 67, in save
    super().save(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/opt/venv/lib/python3.8/site-packages/django/db/models/base.py", line 787, in save_base
    post_save.send(
  File "/opt/venv/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 180, in send
    return [
  File "/opt/venv/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/home/django/cvat/apps/iam/signals.py", line 21, in create_user
    db_group = Group.objects.get(name=settings.IAM_ADMIN_ROLE)
  File "/opt/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.DoesNotExist: Group matching query does not exist.

**Comment by Sunny-Day200** [comment]
I should delete [user， business， admin]

How to solve this embarrassing problem

**Comment by nmanovic** [comment]
@Sunny-Day200 , could you please provide steps how to reproduce the issue?

**Comment by Sunny-Day200** [comment]
> @Sunny-Day200 , could you please provide steps how to reproduce the issue?
I deleted these groups
![image](https://user-images.githubusercontent.com/53826251/182518395-31d165c1-faa2-4fd9-b56a-a66cddd21c78.png)


But after I restart docker, this problem has been fixed   "automatically create delete group"

**Comment by kirill-sizov** [comment]
Hi, @Sunny-Day200, Is this issue still relevant for you?

If it is, then could you please provide more information about your problem:

1. Which version of CVAT do you use?
2. Which actions lead to error?

**Comment by kirill-sizov** [comment]
@Sunny-Day200 I`ll close this issue, but if you still have any related problems or questions, then feel free to re-open it.
