### ISSUE TITLE
video upload timeout

### ISSUE THREAD

**Issue by guozj583** [opencv/cvat#482]
hey,friend:
     When I used cvat to upload video, I encountered the following problems:
```
cvat          | 2019-05-16 16:45:22,358 DEBG 'runserver' stderr output:
cvat          | [Thu May 16 16:45:22.358390 2019] [reqtimeout:info] [pid 119:tid 140380869302016] [client 172.16.117.183:3838] AH01382: Request body read timeout
cvat          | [Thu May 16 16:45:22.358425 2019] [wsgi:error] [pid 119:tid 140380869302016] [client 172.16.117.183:3838] mod_wsgi (pid=119): Request data read error when proxying data to daemon process: The timeout specified has expired., referer: http://isg-anno-02.bj.intel.com:8080/dashboard/
cvat          |
cvat          | 2019-05-16 16:45:22,380 DEBG 'runserver' stderr output:
cvat          | [Thu May 16 16:45:22.380399 2019] [wsgi:error] [pid 118:tid 140380660668160] [remote 172.16.117.183:3838] [2019-05-16 16:45:22,380] INFO cvat.server: create task with params = {'owner': <SimpleLazyObject: <User: shuozh2x>>}
cvat          |
cvat          | 2019-05-16 16:45:22,382 DEBG 'runserver' stderr output:
cvat          | [Thu May 16 16:45:22.382272 2019] [wsgi:error] [pid 118:tid 140380660668160] [remote 172.16.117.183:3838] [2019-05-16 16:45:22,381] ERROR django.request: Internal Server Error: /create/task
cvat          | [Thu May 16 16:45:22.382297 2019] [wsgi:error] [pid 118:tid 140380660668160] [remote 172.16.117.183:3838] Traceback (most recent call last):
cvat          | [Thu May 16 16:45:22.382304 2019] [wsgi:error] [pid 118:tid 140380660668160] [remote 172.16.117.183:3838]   File "/home/django/cvat/apps/engine/views.py", line 57, in create_task
cvat          | [Thu May 16 16:45:22.382310 2019] [wsgi:error] [pid 118:tid 140380660668160] [remote 172.16.117.183:3838]     db_task = task.create_empty(params)
cvat          | [Thu May 16 16:45:22.382316 2019] [wsgi:error] [pid 118:tid 140380660668160] [remote 172.16.117.183:3838]   File "/usr/lib/python3.5/contextlib.py", line 30, in inner
cvat          | [Thu May 16 16:45:22.382321 2019] [wsgi:error] [pid 118:tid 140380660668160] [remote 172.16.117.183:3838]     return func(*args, **kwds)
cvat          | [Thu May 16 16:45:22.382326 2019] [wsgi:error] [pid 118:tid 140380660668160] [remote 172.16.117.183:3838]   File "/home/django/cvat/apps/engine/task.py", line 42, in create_empty
cvat          | [Thu May 16 16:45:22.382332 2019] [wsgi:error] [pid 118:tid 140380660668160] [remote 172.16.117.183:3838]     db_task.name = params['task_name']
cvat          | [Thu May 16 16:45:22.382338 2019] [wsgi:error] [pid 118:tid 140380660668160] [remote 172.16.117.183:3838] KeyError: 'task_name'
cvat          | [Thu May 16 16:45:22.382342 2019] [wsgi:error] [pid 118:tid 140380660668160] [remote 172.16.117.183:3838]
cvat          | [Thu May 16 16:45:22.382347 2019] [wsgi:error] [pid 118:tid 140380660668160] [remote 172.16.117.183:3838] During handling of the above exception, another exception occurred:
cvat          | [Thu May 16 16:45:22.382352 2019] [wsgi:error] [pid 118:tid 140380660668160] [remote 172.16.117.183:3838]
cvat          | [Thu May 16 16:45:22.382357 2019] [wsgi:error] [pid 118:tid 140380660668160] [remote 172.16.117.183:3838] Traceback (most recent call last):
cvat          | [Thu May 16 16:45:22.382363 2019] [wsgi:error] [pid 118:tid 140380660668160] [remote 172.16.117.183:3838]   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 34, in inner
cvat          | [Thu May 16 16:45:22.382371 2019] [wsgi:error] [pid 118:tid 140380660668160] [remote 172.16.117.183:3838]     response = get_response(request)
cvat          |
cvat          | 2019-05-16 16:45:22,383 DEBG 'runserver' stderr output:
cvat          | [Thu May 16 16:45:22.382378 2019] [wsgi:error] [pid 118:tid 140380660668160] [remote 172.16.117.183:3838]   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 126, in _get_response
cvat          | [Thu May 16 16:45:22.382386 2019] [wsgi:error] [pid 118:tid 140380660668160] [remote 172.16.117.183:3838]     response = self.process_exception_by_middleware(e, request)
cvat          | [Thu May 16 16:45:22.382393 2019] [wsgi:error] [pid 118:tid 140380660668160] [remote 172.16.117.183:3838]   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 124, in _get_response
cvat          | [Thu May 16 16:45:22.382401 2019] [wsgi:error] [pid 118:tid 140380660668160] [remote 172.16.117.183:3838]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
cvat          | [Thu May 16 16:45:22.382409 2019] [wsgi:error] [pid 118:tid 140380660668160] [remote 172.16.117.183:3838]   File "/home/django/cvat/apps/authentication/decorators.py", line 20, in _wrapped_view
cvat          | [Thu May 16 16:45:22.382417 2019] [wsgi:error] [pid 118:tid 140380660668160] [remote 172.16.117.183:3838]     return view_func(request, *args, **kwargs)
cvat          | [Thu May 16 16:45:22.382424 2019] [wsgi:error] [pid 118:tid 140380660668160] [remote 172.16.117.183:3838]   File "/usr/local/lib/python3.5/dist-packages/rules/contrib/views.py", line 138, in _wrapped_view
cvat          | [Thu May 16 16:45:22.382433 2019] [wsgi:error] [pid 118:tid 140380660668160] [remote 172.16.117.183:3838]     return view_func(request, *args, **kwargs)
cvat          | [Thu May 16 16:45:22.382440 2019] [wsgi:error] [pid 118:tid 140380660668160] [remote 172.16.117.183:3838]   File "/home/django/cvat/apps/engine/views.py", line 100, in create_task
cvat          | [Thu May 16 16:45:22.382448 2019] [wsgi:error] [pid 118:tid 140380660668160] [remote 172.16.117.183:3838]     slogger.glob.error("cannot create task {}".format(params['task_name']), exc_info=True)
cvat          | [Thu May 16 16:45:22.382460 2019] [wsgi:error] [pid 118:tid 140380660668160] [remote 172.16.117.183:3838] KeyError: 'task_name'
cvat          | [Thu May 16 16:45:22.382478 2019] [wsgi:error] [pid 118:tid 140380660668160] [remote 172.16.117.183:3838]
```
  but, some video is ok ,I don't know why? please help me have a look,thank you !

**Comment by nmanovic** [comment]
@guozj583 ,

Which version of CVAT are you using? Could you please try the latest version?

**Comment by guozj583** [comment]
Hey,friend:
    First of all, thank you for your quick reply. 
    I am using version 0.3.0. Then do I need to update to version 0.4.1?
thanks.

**Comment by nmanovic** [comment]
@guozj583 , please try the latest version and if the problem still exists create a bug request. I will close the issue for now.
