### ISSUE TITLE
Maximum call stack size exceeded when creating a task from cloud storage with 400K images manifest

### ISSUE THREAD

**Issue by helloWorldHitech** [opencv/cvat#4822]
see recording
https://watch.screencastify.com/v/tJECMClF8dH4NbTtw9EZ

### Expected Behaviour
User is able to create a task with a big manifest file

### Current Behaviour
when creating a task using cloud storage (s3) and manifest.jsonl with 400K files I'm not seeing any notification on screen but see 
Maximum call stack size exceeded in console log. 

### Steps to Reproduce (for bugs)

1.Click on tasks
2. create new task
3. give a name and a project
4. select cloud storage with a big manifest file
5. wait for files list to load and select all files
6. submit

Environment
Chrome:
Version 104.0.5112.102 (Official Build) (64-bit)
Cvat
Server version: 1.7
Core version: 3.16.1
Canvas version: 2.8.0
UI version: 1.24.0

**Comment by bsekachev** [comment]
Hi, @helloWorldHitech 

Could you please provide us a screenshot with this error?

**Comment by bsekachev** [comment]
Thank you, @helloWorldHitech 

Just interested if you can share a manifest file with us, without data themselves.

**Comment by helloWorldHitech** [comment]
sent a google drive link with the jsonl to your gmail @bsekachev

**Comment by bsekachev** [comment]
@helloWorldHitech 

Thank you, I will try to investigate it ASAP.

**Comment by bsekachev** [comment]
@helloWorldHitech 

Can you try the linked PR? I currently do not have enough powerful HW to proceed with your data, but the task creation request was sent to the server.

**Comment by helloWorldHitech** [comment]
Checking, thank you for the quick fix

**Comment by bsekachev** [comment]
@helloWorldHitech 

Thank you, let us know the results

**Comment by moshehooriec** [comment]
Hi, 
I tested the PR, It did solve the "Maximum callstack exceeded" issue, 
but after a few minutes I got another error:
on the browser console I got:
```
xhr.js:220          POST http://0.0.0.0:8080/api/tasks/2/data?org= 500 (Internal Server Error)
```
and in CVAT logs, igot:
```
cvat_server            | [Thu Sep 01 07:10:39.306560 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812] [2022-09-01 07:10:39,282] ERROR django.request: Internal Server Error: /api/tasks/1
cvat_server            | 
cvat_server            | 2022-09-01 07:10:39,306 DEBG 'runserver' stderr output:
cvat_server            | [Thu Sep 01 07:10:39.306724 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812] Traceback (most recent call last):
cvat_server            | [Thu Sep 01 07:10:39.306726 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]   File "/opt/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 242, in _commit
cvat_server            | [Thu Sep 01 07:10:39.306727 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]     return self.connection.commit()
cvat_server            | [Thu Sep 01 07:10:39.306729 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812] psycopg2.errors.ForeignKeyViolation: update or delete on table "engine_data" violates foreign key constraint "engine_serverfile_data_id_2364110a_fk_engine_data_id" on table "engine_serverfile"
cvat_server            | [Thu Sep 01 07:10:39.306730 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812] DETAIL:  Key (id)=(1) is still referenced from table "engine_serverfile".
cvat_server            | [Thu Sep 01 07:10:39.306731 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812] 
cvat_server            | [Thu Sep 01 07:10:39.306732 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812] 
cvat_server            | [Thu Sep 01 07:10:39.306733 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812] The above exception was the direct cause of the following exception:
cvat_server            | [Thu Sep 01 07:10:39.306734 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812] 
cvat_server            | [Thu Sep 01 07:10:39.306734 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812] Traceback (most recent call last):
cvat_server            | [Thu Sep 01 07:10:39.306735 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
cvat_server            | [Thu Sep 01 07:10:39.306736 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]     response = get_response(request)
cvat_server            | [Thu Sep 01 07:10:39.306737 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
cvat_server            | [Thu Sep 01 07:10:39.306739 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
cvat_server            | [Thu Sep 01 07:10:39.306740 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]   File "/opt/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
cvat_server            | [Thu Sep 01 07:10:39.306742 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]     return view_func(*args, **kwargs)
cvat_server            | [Thu Sep 01 07:10:39.306743 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
cvat_server            | [Thu Sep 01 07:10:39.306744 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]     return self.dispatch(request, *args, **kwargs)
cvat_server            | [Thu Sep 01 07:10:39.306746 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
cvat_server            | [Thu Sep 01 07:10:39.306747 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]     response = self.handle_exception(exc)
cvat_server            | [Thu Sep 01 07:10:39.306748 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
cvat_server            | [Thu Sep 01 07:10:39.306750 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]     self.raise_uncaught_exception(exc)
cvat_server            | [Thu Sep 01 07:10:39.306751 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
cvat_server            | [Thu Sep 01 07:10:39.306752 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]     raise exc
cvat_server            | [Thu Sep 01 07:10:39.306754 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
cvat_server            | [Thu Sep 01 07:10:39.306756 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]     response = handler(request, *args, **kwargs)
cvat_server            | [Thu Sep 01 07:10:39.306758 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]   File "/opt/venv/lib/python3.8/site-packages/drf_spectacular/drainage.py", line 156, in wrapped_method
cvat_server            | [Thu Sep 01 07:10:39.306759 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]     return method(self, request, *args, **kwargs)
cvat_server            | [Thu Sep 01 07:10:39.306761 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/mixins.py", line 91, in destroy
cvat_server            | [Thu Sep 01 07:10:39.306762 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]     self.perform_destroy(instance)
cvat_server            | [Thu Sep 01 07:10:39.306763 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]   File "/home/django/cvat/apps/engine/views.py", line 808, in perform_destroy
cvat_server            | [Thu Sep 01 07:10:39.306765 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]     instance.data.delete()
cvat_server            | [Thu Sep 01 07:10:39.306766 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]   File "/opt/venv/lib/python3.8/site-packages/django/db/models/base.py", line 967, in delete
cvat_server            | [Thu Sep 01 07:10:39.306768 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]     return collector.delete()
cvat_server            | [Thu Sep 01 07:10:39.306769 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]   File "/opt/venv/lib/python3.8/site-packages/django/db/models/deletion.py", line 435, in delete
cvat_server            | [Thu Sep 01 07:10:39.306770 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]     signals.post_delete.send(
cvat_server            | [Thu Sep 01 07:10:39.306772 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]   File "/opt/venv/lib/python3.8/site-packages/django/db/transaction.py", line 246, in __exit__
cvat_server            | [Thu Sep 01 07:10:39.306773 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]     connection.commit()
cvat_server            | [Thu Sep 01 07:10:39.306775 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]   File "/opt/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
cvat_server            | [Thu Sep 01 07:10:39.306776 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]     return func(*args, **kwargs)
cvat_server            | [Thu Sep 01 07:10:39.306778 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]   File "/opt/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 266, in commit
cvat_server            | [Thu Sep 01 07:10:39.306779 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]     self._commit()
cvat_server            | 
cvat_server            | 2022-09-01 07:10:39,306 DEBG 'runserver' stderr output:
cvat_server            | [Thu Sep 01 07:10:39.306781 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]   File "/opt/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 242, in _commit
cvat_server            | [Thu Sep 01 07:10:39.306791 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]     return self.connection.commit()
cvat_server            | [Thu Sep 01 07:10:39.306792 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]   File "/opt/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
cvat_server            | [Thu Sep 01 07:10:39.306794 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]     raise dj_exc_value.with_traceback(traceback) from exc_value
cvat_server            | [Thu Sep 01 07:10:39.306795 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]   File "/opt/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 242, in _commit
cvat_server            | [Thu Sep 01 07:10:39.306797 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]     return self.connection.commit()
cvat_server            | [Thu Sep 01 07:10:39.306798 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812] django.db.utils.IntegrityError: update or delete on table "engine_data" violates foreign key constraint "engine_serverfile_data_id_2364110a_fk_engine_data_id" on table "engine_serverfile"
cvat_server            | [Thu Sep 01 07:10:39.306800 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812] DETAIL:  Key (id)=(1) is still referenced from table "engine_serverfile".
cvat_server            | [Thu Sep 01 07:10:39.306802 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812] 
cvat_server            | 
cvat_server            | 2022-09-01 07:10:39,307 DEBG 'runserver' stderr output:
cvat_server            | [Thu Sep 01 07:10:39.306971 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812] ERROR:django.request:Internal Server Error: /api/tasks/1
cvat_server            | [Thu Sep 01 07:10:39.306977 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812] Traceback (most recent call last):
cvat_server            | [Thu Sep 01 07:10:39.306978 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]   File "/opt/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 242, in _commit
cvat_server            | [Thu Sep 01 07:10:39.306979 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]     return self.connection.commit()
cvat_server            | [Thu Sep 01 07:10:39.306980 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812] psycopg2.errors.ForeignKeyViolation: update or delete on table "engine_data" violates foreign key constraint "engine_serverfile_data_id_2364110a_fk_engine_data_id" on table "engine_serverfile"
cvat_server            | [Thu Sep 01 07:10:39.306982 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812] DETAIL:  Key (id)=(1) is still referenced from table "engine_serverfile".
cvat_server            | [Thu Sep 01 07:10:39.306983 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812] 
cvat_server            | [Thu Sep 01 07:10:39.306983 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812] 
cvat_server            | [Thu Sep 01 07:10:39.306984 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812] The above exception was the direct cause of the following exception:
cvat_server            | [Thu Sep 01 07:10:39.306986 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812] 
cvat_server            | 
cvat_server            | 2022-09-01 07:10:39,307 DEBG 'runserver' stderr output:
cvat_server            | [Thu Sep 01 07:10:39.306987 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812] Traceback (most recent call last):
cvat_server            | [Thu Sep 01 07:10:39.306988 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
cvat_server            | [Thu Sep 01 07:10:39.306990 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]     response = get_response(request)
cvat_server            | [Thu Sep 01 07:10:39.306991 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
cvat_server            | [Thu Sep 01 07:10:39.306993 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
cvat_server            | [Thu Sep 01 07:10:39.306994 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]   File "/opt/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
cvat_server            | [Thu Sep 01 07:10:39.306995 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]     return view_func(*args, **kwargs)
cvat_server            | [Thu Sep 01 07:10:39.306996 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
cvat_server            | [Thu Sep 01 07:10:39.306998 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]     return self.dispatch(request, *args, **kwargs)
cvat_server            | [Thu Sep 01 07:10:39.306999 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
cvat_server            | [Thu Sep 01 07:10:39.307000 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]     response = self.handle_exception(exc)
cvat_server            | [Thu Sep 01 07:10:39.307001 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
cvat_server            | [Thu Sep 01 07:10:39.307003 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]     self.raise_uncaught_exception(exc)
cvat_server            | [Thu Sep 01 07:10:39.307004 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
cvat_server            | [Thu Sep 01 07:10:39.307005 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]     raise exc
cvat_server            | [Thu Sep 01 07:10:39.307007 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
cvat_server            | [Thu Sep 01 07:10:39.307008 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]     response = handler(request, *args, **kwargs)
cvat_server            | [Thu Sep 01 07:10:39.307009 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]   File "/opt/venv/lib/python3.8/site-packages/drf_spectacular/drainage.py", line 156, in wrapped_method
cvat_server            | [Thu Sep 01 07:10:39.307011 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]     return method(self, request, *args, **kwargs)
cvat_server            | [Thu Sep 01 07:10:39.307012 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/mixins.py", line 91, in destroy
cvat_server            | [Thu Sep 01 07:10:39.307013 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]     self.perform_destroy(instance)
cvat_server            | [Thu Sep 01 07:10:39.307015 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]   File "/home/django/cvat/apps/engine/views.py", line 808, in perform_destroy
cvat_server            | [Thu Sep 01 07:10:39.307016 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]     instance.data.delete()
cvat_server            | [Thu Sep 01 07:10:39.307017 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]   File "/opt/venv/lib/python3.8/site-packages/django/db/models/base.py", line 967, in delete
cvat_server            | [Thu Sep 01 07:10:39.307019 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]     return collector.delete()
cvat_server            | [Thu Sep 01 07:10:39.307020 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]   File "/opt/venv/lib/python3.8/site-packages/django/db/models/deletion.py", line 435, in delete
cvat_server            | [Thu Sep 01 07:10:39.307022 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]     signals.post_delete.send(
cvat_server            | [Thu Sep 01 07:10:39.307023 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]   File "/opt/venv/lib/python3.8/site-packages/django/db/transaction.py", line 246, in __exit__
cvat_server            | [Thu Sep 01 07:10:39.307024 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]     connection.commit()
cvat_server            | [Thu Sep 01 07:10:39.307026 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]   File "/opt/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
cvat_server            | [Thu Sep 01 07:10:39.307027 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]     return func(*args, **kwargs)
cvat_server            | [Thu Sep 01 07:10:39.307028 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]   File "/opt/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 266, in commit
cvat_server            | [Thu Sep 01 07:10:39.307029 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]     self._commit()
cvat_server            | [Thu Sep 01 07:10:39.307031 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]   File "/opt/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 242, in _commit
cvat_server            | [Thu Sep 01 07:10:39.307032 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]     return self.connection.commit()
cvat_server            | [Thu Sep 01 07:10:39.307033 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]   File "/opt/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
cvat_server            | [Thu Sep 01 07:10:39.307035 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]     raise dj_exc_value.with_traceback(traceback) from exc_value
cvat_server            | [Thu Sep 01 07:10:39.307036 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]   File "/opt/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 242, in _commit
cvat_server            | [Thu Sep 01 07:10:39.307037 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812]     return self.connection.commit()
cvat_server            | [Thu Sep 01 07:10:39.307039 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812] django.db.utils.IntegrityError: update or delete on table "engine_data" violates foreign key constraint "engine_serverfile_data_id_2364110a_fk_engine_data_id" on table "engine_serverfile"
cvat_server            | [Thu Sep 01 07:10:39.307040 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812] DETAIL:  Key (id)=(1) is still referenced from table "engine_serverfile".
cvat_server            | [Thu Sep 01 07:10:39.307042 2022] [wsgi:error] [pid 104:tid 140115899574016] [remote 172.22.0.2:43812] 
cvat_server            | 
cvat_opa               | {"client_addr":"172.22.0.8:59440","level":"info","msg":"Received request.","req_id":22,"req_method":"POST","req_path":"/v1/data/tasks/allow","time":"2022-09-01T07:11:11Z"}
cvat_opa               | {"decision_id":"3525a6fa-258a-4f3e-9467-0b599129ab88","input":{"auth":{"organization":null,"user":{"id":1,"privilege":"user"}},"resource":{"assignee":{"id":null},"id":null,"organization":{"id":null},"owner":{"id":1},"project":null,"user":{"num_resources":1}},"scope":"create"},"labels":{"id":"d3518414-7cfc-462f-81ee-d7d7ff67e264","version":"0.34.2"},"level":"info","metrics":{"counter_server_query_cache_hit":1,"timer_rego_input_parse_ns":81700,"timer_rego_query_eval_ns":1191749,"timer_server_handler_ns":1313816},"msg":"Decision Log","path":"tasks/allow","requested_by":"172.22.0.8:59440","result":true,"time":"2022-09-01T07:11:11Z","timestamp":"2022-09-01T07:11:11.197838489Z","type":"openpolicyagent.org/decision_logs"}
cvat_opa               | {"client_addr":"172.22.0.8:59440","level":"info","msg":"Sent response.","req_id":22,"req_method":"POST","req_path":"/v1/data/tasks/allow","resp_bytes":68,"resp_duration":1.739067,"resp_status":200,"time":"2022-09-01T07:11:11Z"}
cvat_opa               | {"client_addr":"172.22.0.8:59442","level":"info","msg":"Received request.","req_id":23,"req_method":"POST","req_path":"/v1/data/tasks/allow","time":"2022-09-01T07:12:26Z"}
cvat_opa               | {"decision_id":"62f5955a-b71a-4315-a537-80110265d361","input":{"auth":{"organization":null,"user":{"id":1,"privilege":"user"}},"resource":{"assignee":{"id":null},"id":2,"organization":{"id":null},"owner":{"id":1},"project":null},"scope":"upload:data"},"labels":{"id":"d3518414-7cfc-462f-81ee-d7d7ff67e264","version":"0.34.2"},"level":"info","metrics":{"counter_server_query_cache_hit":1,"timer_rego_input_parse_ns":101974,"timer_rego_query_eval_ns":1302785,"timer_server_handler_ns":1463017},"msg":"Decision Log","path":"tasks/allow","requested_by":"172.22.0.8:59442","result":true,"time":"2022-09-01T07:12:26Z","timestamp":"2022-09-01T07:12:26.172415635Z","type":"openpolicyagent.org/decision_logs"}
cvat_opa               | {"client_addr":"172.22.0.8:59442","level":"info","msg":"Sent response.","req_id":23,"req_method":"POST","req_path":"/v1/data/tasks/allow","resp_bytes":68,"resp_duration":1.808602,"resp_status":200,"time":"2022-09-01T07:12:26Z"}


```

**Comment by helloWorldHitech** [comment]
thanks @moshehooriec 
@bsekachev

**Comment by bsekachev** [comment]
Okay, I will merge this one PR.
Probably this error requires further investigations.
