### ISSUE TITLE
Server error 500 occurs open invaid (account is already active, invalid token, etc.) account activation link

### ISSUE THREAD

**Issue by yasakova-anastasia** [opencv/cvat#4832]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Current Behaviour

```python
Traceback (most recent call last):
File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
  response = get_response(request)
File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
  response = response.render()
File "/opt/venv/lib/python3.8/site-packages/django/template/response.py", line 105, in render
  self.content = self.rendered_content
File "/opt/venv/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
  return template.render(context, self._request)
File "/opt/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
  return self.template.render(context)
File "/opt/venv/lib/python3.8/site-packages/django/template/base.py", line 170, in render
  return self._render(context)
File "/opt/venv/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
  return self.nodelist.render(context)
File "/opt/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
  bit = node.render_annotated(context)
File "/opt/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
  return self.render(context)
File "/opt/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
  return compiled_parent._render(context)
File "/opt/venv/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
  return self.nodelist.render(context)
File "/opt/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
  bit = node.render_annotated(context)
File "/opt/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
  return self.render(context)
File "/opt/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
  result = block.nodelist.render(context)
File "/opt/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)
File "/opt/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
  return self.render(context)
File "/opt/venv/lib/python3.8/site-packages/django/template/defaulttags.py", line 315, in render
  return nodelist.render(context)
File "/opt/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
  bit = node.render_annotated(context)
File "/opt/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
  return self.render(context)
File "/opt/venv/lib/python3.8/site-packages/django/template/defaulttags.py", line 449, in render
  url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
File "/opt/venv/lib/python3.8/site-packages/django/urls/base.py", line 86, in reverse
  return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
File "/opt/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 698, in _reverse_with_prefix
  raise NoReverseMatch(msg)

django.urls.exceptions.NoReverseMatch: Reverse for 'account_login' not found. 'account_login' is not a valid view function or pattern name.
```

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

Issue by @azhavoro

**Comment by Marishka17** [comment]
Has been fixed in #5147
