### ISSUE TITLE
Encounter HTTP ERROR 500 when upload CVAT 1.1 annotation to task in V2.1

### ISSUE THREAD

**Issue by joon612** [opencv/cvat#4833]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
Upload success

### Current Behaviour

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/34393671/186633495-72ec36aa-53fb-452f-92c4-a8dcd5587972.png)

### Possible Solution
I really have no idea.

### Steps to Reproduce (for bugs)
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/34393671/186633523-a6f74c54-cd74-4ae0-9f15-71e8edf6b0af.png)

### Context
Do you know possible reason about this?

### Your Environment

- Git hash commit (`git log -1`): Tag: 2.1.0
- Are you using Docker Swarm or Kubernetes? Kubernetes
- Operating System and version (e.g. Linux, Windows, MacOS): Linux
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/34393671/186633570-b6080bd7-5f9b-4d05-aa0f-ca6309057a16.png)

**Comment by bsekachev** [comment]
Hi,

Can you provide us ``docker logs cvat`` output?

**Comment by joon612** [comment]
```
2022-08-26 02:43:18,570 DEBG 'runserver' stderr output:
[Fri Aug 26 02:43:18.570748 2022] [wsgi:error] [pid 379:tid 139914663466752] [client 10.244.2.9:39812] Truncated or oversized response headers received from daemon process 'localhost:8080': /tmp/cvat-server/htdocs/api, referer: https://cvatprod.westus2.cloudapp.azure.com/tasks?page=1



2022-08-26 02:43:18,571 DEBG 'runserver' stderr output:
[Fri Aug 26 02:43:18.571799 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812] [2022-08-26 02:43:18,571] ERROR django.request: Internal Server Error: /api/tasks/4263/annotations
[Fri Aug 26 02:43:18.571824 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812] Traceback (most recent call last):
[Fri Aug 26 02:43:18.571828 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
[Fri Aug 26 02:43:18.571832 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]     response = get_response(request)
[Fri Aug 26 02:43:18.571836 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
[Fri Aug 26 02:43:18.571839 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Aug 26 02:43:18.571843 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]   File "/opt/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
[Fri Aug 26 02:43:18.571846 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]     return view_func(*args, **kwargs)
[Fri Aug 26 02:43:18.571849 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
[Fri Aug 26 02:43:18.571853 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]     return self.dispatch(request, *args, **kwargs)
[Fri Aug 26 02:43:18.571856 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch



2022-08-26 02:43:18,572 DEBG 'runserver' stderr output:
[Fri Aug 26 02:43:18.571859 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]     response = self.handle_exception(exc)
[Fri Aug 26 02:43:18.571862 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
[Fri Aug 26 02:43:18.571865 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]     self.raise_uncaught_exception(exc)
[Fri Aug 26 02:43:18.571869 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
[Fri Aug 26 02:43:18.571872 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]     raise exc
[Fri Aug 26 02:43:18.571875 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
[Fri Aug 26 02:43:18.571878 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]     response = handler(request, *args, **kwargs)
[Fri Aug 26 02:43:18.571881 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]   File "/home/django/cvat/apps/engine/views.py", line 842, in annotations
[Fri Aug 26 02:43:18.571884 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]     return self.upload_data(request)
[Fri Aug 26 02:43:18.571887 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]   File "/home/django/cvat/apps/engine/mixins.py", line 136, in upload_data
[Fri Aug 26 02:43:18.571890 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]     return self.upload_finished(request)
[Fri Aug 26 02:43:18.571893 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]   File "/home/django/cvat/apps/engine/views.py", line 681, in upload_finished
[Fri Aug 26 02:43:18.571897 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]     return _import_annotations(
[Fri Aug 26 02:43:18.571900 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]   File "/home/django/cvat/apps/engine/views.py", line 1713, in _import_annotations
[Fri Aug 26 02:43:18.571903 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]     os.remove(rq_job.meta['tmp_file'])
[Fri Aug 26 02:43:18.571906 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812] FileNotFoundError: [Errno 2] No such file or directory: '/tmp/cvat_4263gl_yf5sd'
[Fri Aug 26 02:43:18.572107 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812] ERROR - 2022-08-26 02:43:18,571 - log - Internal Server Error: /api/tasks/4263/annotations
[Fri Aug 26 02:43:18.572126 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812] Traceback (most recent call last):
[Fri Aug 26 02:43:18.572132 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
[Fri Aug 26 02:43:18.572137 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]     response = get_response(request)
[Fri Aug 26 02:43:18.572142 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
[Fri Aug 26 02:43:18.572148 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Aug 26 02:43:18.572152 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]   File "/opt/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
[Fri Aug 26 02:43:18.572157 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]     return view_func(*args, **kwargs)
[Fri Aug 26 02:43:18.572162 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
[Fri Aug 26 02:43:18.572174 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]     return self.dispatch(request, *args, **kwargs)
[Fri Aug 26 02:43:18.572179 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
[Fri Aug 26 02:43:18.572185 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]     response = self.handle_exception(exc)
[Fri Aug 26 02:43:18.572190 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
[Fri Aug 26 02:43:18.572194 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]     self.raise_uncaught_exception(exc)
[Fri Aug 26 02:43:18.572199 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
[Fri Aug 26 02:43:18.572204 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]     raise exc
[Fri Aug 26 02:43:18.572209 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
[Fri Aug 26 02:43:18.572214 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]     response = handler(request, *args, **kwargs)
[Fri Aug 26 02:43:18.572220 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]   File "/home/django/cvat/apps/engine/views.py", line 842, in annotations
[Fri Aug 26 02:43:18.572225 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]     return self.upload_data(request)
[Fri Aug 26 02:43:18.572230 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]   File "/home/django/cvat/apps/engine/mixins.py", line 136, in upload_data
[Fri Aug 26 02:43:18.572235 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]     return self.upload_finished(request)
[Fri Aug 26 02:43:18.572240 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]   File "/home/django/cvat/apps/engine/views.py", line 681, in upload_finished
[Fri Aug 26 02:43:18.572244 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]     return _import_annotations(
[Fri Aug 26 02:43:18.572249 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]   File "/home/django/cvat/apps/engine/views.py", line 1713, in _import_annotations
[Fri Aug 26 02:43:18.572254 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812]     os.remove(rq_job.meta['tmp_file'])
[Fri Aug 26 02:43:18.572259 2022] [wsgi:error] [pid 337:tid 139913985509120] [remote 10.244.2.9:39812] FileNotFoundError: [Errno 2] No such file or directory: '/tmp/cvat_4263gl_yf5sd'
```

**Comment by bsekachev** [comment]
@joon612 

On the first screenshot I see server request with 409 code, code you please share its details?

**Comment by joon612** [comment]
That's because a compressed package with the same name was uploaded.

**Comment by bsekachev** [comment]
@joon612 

> That's because a compressed package with the same name was uploaded. 

I am not sure I understand your idea.

**Comment by joon612** [comment]
409 is generated by a later operation, we mainly want to know the possible cause of the 500 error.
