### ISSUE TITLE
No way to create a job and attach it to a task through the API

### ISSUE THREAD

**Issue by kaninaba94** [opencv/cvat#4922]
### Update 2
I have changed the mimetype of the image in S3 to image/jpeg, and then it worked. But when I tried to reproduce this with another image and manifest, cvat is looking for the manifest file locally.
```
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/rq/worker.py", line 936, in perform_job
    rv = job.perform()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 684, in perform
    self._result = self._execute()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 690, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/django/cvat/apps/engine/task.py", line 305, in _create_thread
    manifest_file = _validate_manifest(manifest_files, manifest_root)
  File "/home/django/cvat/apps/engine/task.py", line 204, in _validate_manifest
    if is_manifest(full_manifest_path):
  File "/home/django/utils/dataset_manifest/core.py", line 724, in is_manifest
    return _is_video_manifest(full_manifest_path) or \
  File "/home/django/utils/dataset_manifest/core.py", line 729, in _is_video_manifest
    return validator.validate()
  File "/home/django/utils/dataset_manifest/core.py", line 642, in validate
    with open(self._manifest.path, 'r') as manifest:
FileNotFoundError: [Errno 2] No such file or directory: '/home/django/data/storages/7/test_manifest10.jsonl'

```

### Update 1
I went into the docker container's logs and this is the traceback:
```
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/rq/worker.py", line 936, in perform_job
    rv = job.perform()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 684, in perform
    self._result = self._execute()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 690, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/django/cvat/apps/engine/task.py", line 291, in _create_thread
    media, task_mode = _validate_data(media, manifest_files)
  File "/home/django/cvat/apps/engine/task.py", line 190, in _validate_data
    raise ValueError('No media data found')
ValueError: No media data found

```

### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I copied the POST-requests that I observed when manually creating a task in the UI (see code below). There seems to be no way to create a new job through the API. Also, no API request for job creation is observed when manually creating the task in the UI, though a job is created properly and assigned to a task.

### Expected Behaviour

A task should appear in the UI. The task should have a job attached to it.

### Current Behaviour

The task is created, but no job is attached to it, i.e. it is not visible in the UI. One exception: When a task was manually created and deleted before (i.e., a task using the same dataset and manifest), full task creation (with a job attached) through the API works. 

### Possible Solution

A. If there is a way to create a job and somehow pass it the correct task ID (the API route for getting jobs even returns an object with a field "task_id"), that could be the solution.
B. When successfully creating a task, the segments are part of the response. If there is a way to pass the segments in the request, that could be a solution.

### Steps to Reproduce (for bugs)

```
import json
import copy
import requests
from typing import List
import pandas as pd

API_BASE_PATH = 'http://my_aws_ec2:8080'


def authenticate():
    login_json = {"username": username, "password": password}
    login_resp = requests.post(f'{API_BASE_PATH}/api/auth/login', json=login_json)
    assert login_resp.status_code == 200
    return login_resp


username = 'mycvatuser'
password = 'mycvatpw'
cookies = authenticate().cookies
post_headers = headers = {
    'Content-Type': 'application/json',
    'X-CSRFToken': cookies['csrftoken'],
}


def get_cloud_storages():
    return pd.DataFrame(
        json.loads(requests.get(f'{API_BASE_PATH}/api/cloudstorages', cookies=cookies).content)['results'])


def create_task(name: str, cloud_storage_name: str, manifest_filename: str, image_UUIDs,
                description: str = '', labels: List = [], image_quality: str = '70', use_zip_chunks: str = 'true',
                use_cache: str = 'true', sorting_method: str = 'lexicographical'):
    body = {
        "description": description,
        "name": name,
        "labels": labels,
        'segment_size': 3,
        "status": "annotation",
    }
    headers = post_headers
    response = requests.post(f'{API_BASE_PATH}/api/tasks?org=', headers=headers, data=json.dumps(body),
                             cookies=cookies)
    assert response.status_code == 201
    response_content = json.loads(response.content)
    task_id = response_content['id']
    cloud_storages = get_cloud_storages()  # some self-writte function that returns a pandas DataFrame of the CVAT cloudstorage instances
    cloud_storage_id = str(cloud_storages[cloud_storages['display_name'] == cloud_storage_name]['id'].values[0])
    server_files = []
    for img in image_UUIDs:
        server_files.append({'file': f'{img}.jpg'})
    server_files.append(manifest_filename)

    body = {
        'server_files': server_files,
        'image_quality': image_quality,
        'use_zip_chunks': use_zip_chunks,
        'use_cache': use_cache,
        'sorting_method': sorting_method,
        'cloud_storage_id': cloud_storage_id,
        'storage': 'cloud_storage'
    }
    headers = copy.deepcopy(post_headers)
    headers['Upload-Start'] = 'true'
    response = requests.post(f'{API_BASE_PATH}/api/tasks/{task_id}/data?org=', data=json.dumps(body),
                             headers=headers, cookies=cookies)
    assert response.status_code == 202

    import time
    time.sleep(2)

    headers = copy.deepcopy(post_headers)
    headers['Upload-Finish'] = 'true'
    response = requests.post(f'{API_BASE_PATH}/api/tasks/{task_id}/data?org=', data=json.dumps(body),
                             headers=headers, cookies=cookies)
    assert response.status_code == 202


labels = [
    {'name': 'label_A', "attributes": []}
]

images = [
    'img1',
    'img2',
    'img3'
]

create_task(manifest_filename='my_manifest.jsonl',
            image_UUIDs=images, name='my_task',
            cloud_storage_name='cloudstorage_instance', labels=labels,
            description='test description')

```
This is my manifest file:
```
{"version": "1.1"}
{"type": "images"}
{"name": "img1","extension":".jpg","width":5328,"height": 4608,"meta":{"related_images":[]}}
{"name": "img2","extension":".jpg","width":5328,"height": 4608,"meta":{"related_images":[]}}
{"name": "img3","extension":".jpg","width":5328,"height": 4608,"meta":{"related_images":[]}}

```

### Context

I am trying to create labelling tasks for an object detection task.

### Your Environment
I am using AWS S3 cloudstorage instance for my images, and run CVAT in EC2.

**Comment by Marishka17** [comment]
Hi, @kaninaba94, I see in your logs that you are not using the latest CVAT version which fixed this problem. Could you please try the develop branch or `cvat/server:dev`?
