### ISSUE TITLE
export project ,AssertionError!

### ISSUE THREAD

**Issue by xiongda777** [opencv/cvat#4968]
### My actions before raising this issue
- [ yes] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [yes] Searched [past issues](/issues)

### Expected Behaviour

export xml file of project
### Current Behaviour

Error: Request failed with status code 500. "AssertionError\n".
### Possible Solution

dont know
### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

I get docker logs cvat as follow:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/rq/worker.py", line 936, in perform_job
    rv = job.perform()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 684, in perform
    self._result = self._execute()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 690, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/django/cvat/apps/dataset_manager/views.py", line 110, in export_project_annotations
    return export(dst_format, project_id=project_id, server_url=server_url, save_images=False)
  File "/home/django/cvat/apps/dataset_manager/views.py", line 74, in export
    export_fn(db_instance.id, temp_file, dst_format,
  File "/home/django/cvat/apps/dataset_manager/project.py", line 32, in export_project
    project.export(f, exporter, host=server_url, save_images=save_images)
  File "/home/django/cvat/apps/dataset_manager/project.py", line 130, in export
    exporter(dst_file, project_data, **options)
  File "/home/django/cvat/apps/dataset_manager/formats/registry.py", line 37, in __call__
    f_or_cls(*args, **kwargs)
  File "/home/django/cvat/apps/dataset_manager/formats/cvat.py", line 1080, in _export_images
    _export_project(dst_file, instance_data,
  File "/home/django/cvat/apps/dataset_manager/formats/cvat.py", line 1057, in _export_project
    dump_project_anno(f, project_data, anno_callback)
  File "/home/django/cvat/apps/dataset_manager/formats/cvat.py", line 1024, in dump_project_anno
    callback(dumper, project_data)
  File "/home/django/cvat/apps/dataset_manager/formats/cvat.py", line 596, in dump_as_cvat_annotation
    for frame_annotation in annotations.group_by_frame(include_empty=True):
  File "/home/django/cvat/apps/dataset_manager/bindings.py", line 839, in group_by_frame
    for shape in sorted(anno_manager.to_shapes(task.data.size),
  File "/home/django/cvat/apps/dataset_manager/annotation.py", line 162, in to_shapes
    return shapes + tracks.to_shapes(end_frame)
  File "/home/django/cvat/apps/dataset_manager/annotation.py", line 364, in to_shapes
    for shape in TrackManager.get_interpolated_shapes(track, 0, end_frame):
  File "/home/django/cvat/apps/dataset_manager/annotation.py", line 725, in get_interpolated_shapes
    assert shape["frame"] > curr_frame
AssertionError

I want to know AssertionError mean, and what is my problem?

**Comment by nmanovic** [comment]
@xiongda777 , which CVAT version are you using?

**Comment by bsekachev** [comment]
```assert shape["frame"] > curr_frame```

Old problem we meet time to time, but were not able to reproduce so far ... :(

#500 #610 #1081 #2814 #3360

**Comment by CaoHoangTung** [comment]
For me, I encountered the error after importing the annotations (MOT1.1 format) with duplicated track ids in some frames. Importing was okay for the first time, but the error occurred when I tried to export the dataset.

There seems to be no validating mechanism for duplicated track ids while importing?

**Comment by zhiltsov-max** [comment]
This problem might have been fixed in #5250

**Comment by F10JM** [comment]
I have the same issue, i can't do all the work over again while checking for duplicates, is there a way to fix it without doing it all over again??

**Comment by zhiltsov-max** [comment]
Related: https://github.com/cvat-ai/cvat/issues/6779
