### ISSUE TITLE
Can't reopen the job when project has both skeleton and box label

### ISSUE THREAD

**Issue by leonwujy** [opencv/cvat#4990]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Current Behaviour

After doing some label work, the job can't be opened from task page again. (Not always, but with high probability)
There has some ways to recover:
1. If you still has a web page open on this job, delete all skeleton labes and save the job, and the job can be opened again.
2. go to project page, delete all box labels, and the job can be opened again.

### Steps to Reproduce (for bugs)

1. create the Project and Task
![create project_part](https://user-images.githubusercontent.com/31384995/192082067-101a635b-6b31-4ea2-8ded-3e031079b461.png)
2. use automatic annotation (optional)
3. add some skeleton labels and other labels, and save the job
4. open another web page, try to open the job. Sometimes, you will get this error[Sorry, but this job was not found]. Once this error occurs, it cannot be opened no matter how many times you try.
![error](https://user-images.githubusercontent.com/31384995/192081978-459694b2-229e-4ddd-af40-0e14222c43dd.png)

### Your Environment

- Git hash commit (`git log -1`): b9abbce411d5d5538de1b9abe3d6b988a5f05805
- Docker version `docker version:  Docker 20.10.18
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS): Linux
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

Logs from `cvat_server` container:

```
2022-09-24 05:17:46,306 DEBG 'runserver' stderr output:
[Sat Sep 24 05:17:46.305948 2022] [wsgi:error] [pid 104:tid 140042918934272] [remote 172.18.0.7:39720] INFO:cvat.client:{"client_id":665336,"name":"Send user activity","time":"2022-09-24T05:17:46.270000Z","payload":{"working_time":0},"is_active":true,"username":"xxxxx"}

2022-09-24 05:17:48,357 DEBG 'runserver' stderr output:
[Sat Sep 24 05:17:48.357453 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766] [2022-09-24 05:17:48,356] ERROR django.request: Internal Server Error: /api/jobs/9/annotations
[Sat Sep 24 05:17:48.357471 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766] Traceback (most recent call last):
[Sat Sep 24 05:17:48.357475 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
[Sat Sep 24 05:17:48.357478 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]     response = get_response(request)
[Sat Sep 24 05:17:48.357481 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
[Sat Sep 24 05:17:48.357484 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Sat Sep 24 05:17:48.357486 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]   File "/opt/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
[Sat Sep 24 05:17:48.357490 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]     return view_func(*args, **kwargs)
[Sat Sep 24 05:17:48.357492 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
[Sat Sep 24 05:17:48.357496 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]     return self.dispatch(request, *args, **kwargs)
[Sat Sep 24 05:17:48.357498 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
[Sat Sep 24 05:17:48.357502 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]     response = self.handle_exception(exc)
[Sat Sep 24 05:17:48.357504 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
[Sat Sep 24 05:17:48.357507 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]     self.raise_uncaught_exception(exc)
[Sat Sep 24 05:17:48.357510 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception

2022-09-24 05:17:48,357 DEBG 'runserver' stderr output:
[Sat Sep 24 05:17:48.357513 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]     raise exc
[Sat Sep 24 05:17:48.357522 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
[Sat Sep 24 05:17:48.357525 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]     response = handler(request, *args, **kwargs)
[Sat Sep 24 05:17:48.357528 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]   File "/home/django/cvat/apps/engine/views.py", line 1416, in annotations
[Sat Sep 24 05:17:48.357531 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]     return self.export_annotations(
[Sat Sep 24 05:17:48.357534 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]   File "/home/django/cvat/apps/engine/mixins.py", line 276, in export_annotations
[Sat Sep 24 05:17:48.357537 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]     data = get_data(pk)
[Sat Sep 24 05:17:48.357540 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]   File "/home/django/cvat/apps/profiler.py", line 11, in wrapped
[Sat Sep 24 05:17:48.357543 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]     return f(*args, **kwargs)
[Sat Sep 24 05:17:48.357545 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]   File "/usr/lib/python3.8/contextlib.py", line 75, in inner
[Sat Sep 24 05:17:48.357548 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]     return func(*args, **kwds)
[Sat Sep 24 05:17:48.357551 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]   File "/home/django/cvat/apps/dataset_manager/task.py", line 659, in get_job_data
[Sat Sep 24 05:17:48.357554 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]     annotation.init_from_db()
[Sat Sep 24 05:17:48.357557 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]   File "/home/django/cvat/apps/dataset_manager/task.py", line 535, in init_from_db
[Sat Sep 24 05:17:48.357560 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]     self._init_shapes_from_db()
[Sat Sep 24 05:17:48.357563 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]   File "/home/django/cvat/apps/dataset_manager/task.py", line 437, in _init_shapes_from_db
[Sat Sep 24 05:17:48.357566 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]     shapes[db_shape.parent].elements.append(db_shape)
[Sat Sep 24 05:17:48.357569 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766] KeyError: 2529
[Sat Sep 24 05:17:48.357741 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766] ERROR:django.request:Internal Server Error: /api/jobs/9/annotations
[Sat Sep 24 05:17:48.357748 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766] Traceback (most recent call last):
[Sat Sep 24 05:17:48.357751 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
[Sat Sep 24 05:17:48.357753 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]     response = get_response(request)
[Sat Sep 24 05:17:48.357756 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
[Sat Sep 24 05:17:48.357759 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Sat Sep 24 05:17:48.357762 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]   File "/opt/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
[Sat Sep 24 05:17:48.357765 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]     return view_func(*args, **kwargs)
[Sat Sep 24 05:17:48.357769 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
[Sat Sep 24 05:17:48.357772 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]     return self.dispatch(request, *args, **kwargs)
[Sat Sep 24 05:17:48.357775 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
[Sat Sep 24 05:17:48.357779 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]     response = self.handle_exception(exc)
[Sat Sep 24 05:17:48.357782 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception

2022-09-24 05:17:48,357 DEBG 'runserver' stderr output:
[Sat Sep 24 05:17:48.357784 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]     self.raise_uncaught_exception(exc)
[Sat Sep 24 05:17:48.357789 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
[Sat Sep 24 05:17:48.357791 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]     raise exc
[Sat Sep 24 05:17:48.357794 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
[Sat Sep 24 05:17:48.357797 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]     response = handler(request, *args, **kwargs)
[Sat Sep 24 05:17:48.357800 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]   File "/home/django/cvat/apps/engine/views.py", line 1416, in annotations
[Sat Sep 24 05:17:48.357802 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]     return self.export_annotations(
[Sat Sep 24 05:17:48.357805 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]   File "/home/django/cvat/apps/engine/mixins.py", line 276, in export_annotations
[Sat Sep 24 05:17:48.357808 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]     data = get_data(pk)
[Sat Sep 24 05:17:48.357810 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]   File "/home/django/cvat/apps/profiler.py", line 11, in wrapped
[Sat Sep 24 05:17:48.357813 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]     return f(*args, **kwargs)
[Sat Sep 24 05:17:48.357815 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]   File "/usr/lib/python3.8/contextlib.py", line 75, in inner
[Sat Sep 24 05:17:48.357818 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]     return func(*args, **kwds)
[Sat Sep 24 05:17:48.357821 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]   File "/home/django/cvat/apps/dataset_manager/task.py", line 659, in get_job_data
[Sat Sep 24 05:17:48.357823 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]     annotation.init_from_db()
[Sat Sep 24 05:17:48.357826 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]   File "/home/django/cvat/apps/dataset_manager/task.py", line 535, in init_from_db
[Sat Sep 24 05:17:48.357829 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]     self._init_shapes_from_db()
[Sat Sep 24 05:17:48.357832 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]   File "/home/django/cvat/apps/dataset_manager/task.py", line 437, in _init_shapes_from_db
[Sat Sep 24 05:17:48.357834 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766]     shapes[db_shape.parent].elements.append(db_shape)
[Sat Sep 24 05:17:48.357837 2022] [wsgi:error] [pid 104:tid 140042910541568] [remote 172.18.0.7:39766] KeyError: 2529
```
Label RAW info
```
[
  {
    "name": "skeleton_A",
    "id": 52,
    "color": "#3d3df5",
    "type": "skeleton",
    "sublabels": [
      {
        "name": "1",
        "attributes": [],
        "type": "points",
        "color": "#d12345",
        "id": 53
      },
      {
        "name": "2",
        "attributes": [],
        "type": "points",
        "color": "#350dea",
        "id": 54
      },
      {
        "name": "3",
        "attributes": [],
        "type": "points",
        "color": "#479ffe",
        "id": 55
      },
      {
        "name": "4",
        "attributes": [],
        "type": "points",
        "color": "#4a649f",
        "id": 56
      },
      {
        "name": "5",
        "attributes": [],
        "type": "points",
        "color": "#478144",
        "id": 57
      }
    ],
    "svg": "<line x1=&quot;56.63188171386719&quot; y1=&quot;28.813142776489258&quot; x2=&quot;70.06201171875&quot; y2=&quot;17.37938690185547&quot; stroke=&quot;black&quot; data-type=&quot;edge&quot; data-node-from=&quot;4&quot; stroke-width=&quot;0.5&quot; data-node-to=&quot;5&quot;></line><line x1=&quot;32.13097381591797&quot; y1=&quot;37.34309005737305&quot; x2=&quot;56.63188171386719&quot; y2=&quot;28.813142776489258&quot; stroke=&quot;black&quot; data-type=&quot;edge&quot; data-node-from=&quot;3&quot; stroke-width=&quot;0.5&quot; data-node-to=&quot;4&quot;></line><line x1=&quot;23.964004516601562&quot; y1=&quot;23.36849594116211&quot; x2=&quot;32.13097381591797&quot; y2=&quot;37.34309005737305&quot; stroke=&quot;black&quot; data-type=&quot;edge&quot; data-node-from=&quot;2&quot; stroke-width=&quot;0.5&quot; data-node-to=&quot;3&quot;></line><line x1=&quot;19.245311737060547&quot; y1=&quot;10.119857788085938&quot; x2=&quot;23.964004516601562&quot; y2=&quot;23.36849594116211&quot; stroke=&quot;black&quot; data-type=&quot;edge&quot; data-node-from=&quot;1&quot; stroke-width=&quot;0.5&quot; data-node-to=&quot;2&quot;></line><circle r=&quot;1.5&quot; stroke=&quot;black&quot; fill=&quot;#b3b3b3&quot; cx=&quot;19.245311737060547&quot; cy=&quot;10.119857788085938&quot; stroke-width=&quot;0.1&quot; data-type=&quot;element node&quot; data-element-id=&quot;1&quot; data-node-id=&quot;1&quot; data-label-id=&quot;53&quot;></circle><circle r=&quot;1.5&quot; stroke=&quot;black&quot; fill=&quot;#b3b3b3&quot; cx=&quot;23.964004516601562&quot; cy=&quot;23.36849594116211&quot; stroke-width=&quot;0.1&quot; data-type=&quot;element node&quot; data-element-id=&quot;2&quot; data-node-id=&quot;2&quot; data-label-id=&quot;54&quot;></circle><circle r=&quot;1.5&quot; stroke=&quot;black&quot; fill=&quot;#b3b3b3&quot; cx=&quot;32.13097381591797&quot; cy=&quot;37.34309005737305&quot; stroke-width=&quot;0.1&quot; data-type=&quot;element node&quot; data-element-id=&quot;3&quot; data-node-id=&quot;3&quot; data-label-id=&quot;55&quot;></circle><circle r=&quot;1.5&quot; stroke=&quot;black&quot; fill=&quot;#b3b3b3&quot; cx=&quot;56.63188171386719&quot; cy=&quot;28.813142776489258&quot; stroke-width=&quot;0.1&quot; data-type=&quot;element node&quot; data-element-id=&quot;4&quot; data-node-id=&quot;4&quot; data-label-id=&quot;56&quot;></circle><circle r=&quot;1.5&quot; stroke=&quot;black&quot; fill=&quot;#b3b3b3&quot; cx=&quot;70.06201171875&quot; cy=&quot;17.37938690185547&quot; stroke-width=&quot;0.1&quot; data-type=&quot;element node&quot; data-element-id=&quot;5&quot; data-node-id=&quot;5&quot; data-label-id=&quot;57&quot;></circle>",
    "attributes": []
  },
  {
    "name": "skeleton_D",
    "id": 58,
    "color": "#ff6037",
    "type": "skeleton",
    "sublabels": [
      {
        "name": "1",
        "attributes": [],
        "type": "points",
        "color": "#d12345",
        "id": 59
      },
      {
        "name": "2",
        "attributes": [],
        "type": "points",
        "color": "#350dea",
        "id": 60
      },
      {
        "name": "3",
        "attributes": [],
        "type": "points",
        "color": "#479ffe",
        "id": 61
      }
    ],
    "svg": "<line x1=&quot;22.14912223815918&quot; y1=&quot;43.33219909667969&quot; x2=&quot;46.287052154541016&quot; y2=&quot;58.819190979003906&quot; stroke=&quot;black&quot; data-type=&quot;edge&quot; data-node-from=&quot;1&quot; stroke-width=&quot;0.5&quot; data-node-to=&quot;3&quot;></line><line x1=&quot;22.14912223815918&quot; y1=&quot;43.33219909667969&quot; x2=&quot;8.356019020080566&quot; y2=&quot;60.0896110534668&quot; stroke=&quot;black&quot; data-type=&quot;edge&quot; data-node-from=&quot;1&quot; stroke-width=&quot;0.5&quot; data-node-to=&quot;2&quot;></line><circle r=&quot;1.5&quot; stroke=&quot;black&quot; fill=&quot;#b3b3b3&quot; cx=&quot;22.14912223815918&quot; cy=&quot;43.33219909667969&quot; stroke-width=&quot;0.1&quot; data-type=&quot;element node&quot; data-element-id=&quot;1&quot; data-node-id=&quot;1&quot; data-label-id=&quot;59&quot;></circle><circle r=&quot;1.5&quot; stroke=&quot;black&quot; fill=&quot;#b3b3b3&quot; cx=&quot;8.356019020080566&quot; cy=&quot;60.0896110534668&quot; stroke-width=&quot;0.1&quot; data-type=&quot;element node&quot; data-element-id=&quot;2&quot; data-node-id=&quot;2&quot; data-label-id=&quot;60&quot;></circle><circle r=&quot;1.5&quot; stroke=&quot;black&quot; fill=&quot;#b3b3b3&quot; cx=&quot;46.287052154541016&quot; cy=&quot;58.819190979003906&quot; stroke-width=&quot;0.1&quot; data-type=&quot;element node&quot; data-element-id=&quot;3&quot; data-node-id=&quot;3&quot; data-label-id=&quot;61&quot;></circle>",
    "attributes": []
  },
  {
    "name": "skeleton_B",
    "id": 62,
    "color": "#ffcc33",
    "type": "skeleton",
    "sublabels": [
      {
        "name": "1",
        "attributes": [],
        "type": "points",
        "color": "#d12345",
        "id": 63
      },
      {
        "name": "2",
        "attributes": [],
        "type": "points",
        "color": "#350dea",
        "id": 64
      }
    ],
    "svg": "<line x1=&quot;11.44131851196289&quot; y1=&quot;40.24689865112305&quot; x2=&quot;44.472171783447266&quot; y2=&quot;41.88029479980469&quot; stroke=&quot;black&quot; data-type=&quot;edge&quot; data-node-from=&quot;1&quot; stroke-width=&quot;0.5&quot; data-node-to=&quot;2&quot;></line><circle r=&quot;1.5&quot; stroke=&quot;black&quot; fill=&quot;#b3b3b3&quot; cx=&quot;11.44131851196289&quot; cy=&quot;40.24689865112305&quot; stroke-width=&quot;0.1&quot; data-type=&quot;element node&quot; data-element-id=&quot;1&quot; data-node-id=&quot;1&quot; data-label-id=&quot;63&quot;></circle><circle r=&quot;1.5&quot; stroke=&quot;black&quot; fill=&quot;#b3b3b3&quot; cx=&quot;44.472171783447266&quot; cy=&quot;41.88029479980469&quot; stroke-width=&quot;0.1&quot; data-type=&quot;element node&quot; data-element-id=&quot;2&quot; data-node-id=&quot;2&quot; data-label-id=&quot;64&quot;></circle>",
    "attributes": []
  },
  {
    "name": "skeleton_C",
    "id": 65,
    "color": "#24b353",
    "type": "skeleton",
    "sublabels": [
      {
        "name": "1",
        "attributes": [],
        "type": "points",
        "color": "#d12345",
        "id": 66
      },
      {
        "name": "2",
        "attributes": [],
        "type": "points",
        "color": "#350dea",
        "id": 67
      }
    ],
    "svg": "<line x1=&quot;20.69721794128418&quot; y1=&quot;42.42475891113281&quot; x2=&quot;58.80973815917969&quot; y2=&quot;43.87666320800781&quot; stroke=&quot;black&quot; data-type=&quot;edge&quot; data-node-from=&quot;1&quot; stroke-width=&quot;0.5&quot; data-node-to=&quot;2&quot;></line><circle r=&quot;1.5&quot; stroke=&quot;black&quot; fill=&quot;#b3b3b3&quot; cx=&quot;20.69721794128418&quot; cy=&quot;42.42475891113281&quot; stroke-width=&quot;0.1&quot; data-type=&quot;element node&quot; data-element-id=&quot;1&quot; data-node-id=&quot;1&quot; data-label-id=&quot;66&quot;></circle><circle r=&quot;1.5&quot; stroke=&quot;black&quot; fill=&quot;#b3b3b3&quot; cx=&quot;58.80973815917969&quot; cy=&quot;43.87666320800781&quot; stroke-width=&quot;0.1&quot; data-type=&quot;element node&quot; data-element-id=&quot;2&quot; data-node-id=&quot;2&quot; data-label-id=&quot;67&quot;></circle>",
    "attributes": []
  },
  {
    "name": "A",
    "id": 68,
    "color": "#e400a8",
    "type": "any",
    "attributes": []
  },
  {
    "name": "B",
    "id": 69,
    "color": "#7ca7df",
    "type": "any",
    "attributes": []
  },
  {
    "name": "C",
    "id": 70,
    "color": "#906025",
    "type": "any",
    "attributes": []
  },
  {
    "name": "D",
    "id": 71,
    "color": "#f4baf3",
    "type": "any",
    "attributes": []
  }
]
```

**Comment by bsekachev** [comment]
Hi @leonwujy

Thank you for detailed report. 
Just give us some time to look into the issue.

**Comment by matt-d** [comment]
I believe this error is also related - it occurs when trying to export/backup a keypoint job.

`cvat_worker_default    | 2022-09-26 14:54:44,523 DEBG 'rqworker_default_0' stderr output:
cvat_worker_default    | [2022-09-26 14:54:44,522] ERROR cvat.server.task_3: [cvat.apps.dataset_manager.views @ _create_backup]: exception occurred
cvat_worker_default    | Traceback (most recent call last):
cvat_worker_default    |   File "/home/django/cvat/apps/engine/backup.py", line 710, in _create_backup
cvat_worker_default    |     exporter.export_to(temp_file)
cvat_worker_default    |   File "/home/django/cvat/apps/engine/backup.py", line 386, in export_to
cvat_worker_default    |     self._export_task(zip_obj=zf, target_dir=target_dir)
cvat_worker_default    |   File "/home/django/cvat/apps/engine/backup.py", line 377, in _export_task
cvat_worker_default    |     self._write_annotations(zip_obj, target_dir)
cvat_worker_default    |   File "/home/django/cvat/apps/engine/backup.py", line 369, in _write_annotations
cvat_worker_default    |     annotations = serialize_annotations()
cvat_worker_default    |   File "/home/django/cvat/apps/engine/backup.py", line 362, in serialize_annotations
cvat_worker_default    |     annotations = dm.task.get_job_data(db_job_id)
cvat_worker_default    |   File "/home/django/cvat/apps/profiler.py", line 11, in wrapped
cvat_worker_default    |     return f(*args, **kwargs)
cvat_worker_default    |   File "/usr/lib/python3.8/contextlib.py", line 75, in inner
cvat_worker_default    |     return func(*args, **kwds)
cvat_worker_default    |   File "/home/django/cvat/apps/dataset_manager/task.py", line 659, in get_job_data
cvat_worker_default    |     annotation.init_from_db()
cvat_worker_default    |   File "/home/django/cvat/apps/dataset_manager/task.py", line 535, in init_from_db
cvat_worker_default    |     self._init_shapes_from_db()
cvat_worker_default    |   File "/home/django/cvat/apps/dataset_manager/task.py", line 437, in _init_shapes_from_db
cvat_worker_default    |     shapes[db_shape.parent].elements.append(db_shape)
cvat_worker_default    | KeyError: 73
`
