### ISSUE TITLE
Impossible import annotations in MOT 1.1 format

### ISSUE THREAD

**Issue by Marishka17** [opencv/cvat#5099]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

It is impossible to upload annotations in MOT 1.1 format when images names contain only numbers
### Expected Behaviour

Annotations should be uploaded successfully
### Steps to Reproduce (for bugs)

1. Create a task with images whose names contain only numbers (or restore [demo_task.zip](https://github.com/opencv/cvat/files/9766315/demo_task.zip))
1. Create dummy annotations
1. Export annotations in MOT 1.1 format
1. Upload this annotations

<details><summary>Details</summary>

``` bash
Traceback (most recent call last):
  File "/home/maya/Documents/cvat_ai/cvat/.env/lib/python3.8/site-packages/rq/worker.py", line 936, in perform_job
    rv = job.perform()
  File "/home/maya/Documents/cvat_ai/cvat/.env/lib/python3.8/site-packages/rq/job.py", line 684, in perform
    self._result = self._execute()
  File "/home/maya/Documents/cvat_ai/cvat/.env/lib/python3.8/site-packages/rq/job.py", line 690, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/maya/Documents/cvat_ai/cvat/cvat/apps/dataset_manager/task.py", line 775, in import_task_annotations
    task.import_annotations(f, importer)
  File "/home/maya/Documents/cvat_ai/cvat/cvat/apps/dataset_manager/task.py", line 658, in import_annotations
    importer(src_file, task_data, **options)
  File "/home/maya/Documents/cvat_ai/cvat/cvat/apps/dataset_manager/formats/registry.py", line 37, in __call__
    f_or_cls(*args, **kwargs)
  File "/home/maya/Documents/cvat_ai/cvat/cvat/apps/dataset_manager/formats/mot.py", line 112, in _import
    _import_task(dataset, instance_data)
  File "/home/maya/Documents/cvat_ai/cvat/cvat/apps/dataset_manager/formats/mot.py", line 22, in _import_task
    frame_number = task_data.abs_frame_id(frame_number)
  File "/home/maya/Documents/cvat_ai/cvat/cvat/apps/dataset_manager/bindings.py", line 198, in abs_frame_id
    raise ValueError("Unknown internal frame id %s" % relative_id)
ValueError: Unknown internal frame id 1097793130
```

</details>

### Your Environment

- Git hash commit (`git log -1`): c3dd3499
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by johnnynunez** [comment]
why is int and not float?
