### ISSUE TITLE
Unable to attach a file to created task

### ISSUE THREAD

**Issue by j22054022** [opencv/cvat#5221]
I followed this guide (https://opencv.github.io/cvat/docs/contributing/development-environment/) to create a develop environment on Nvidia Xavier(ARMv8)

I started CVAT by doing:
    1. `python manage.py rqworker default --worker-class cvat.simpleworker.SimpleWorker &`
    2. `python manage.py rqscheduler &`
    3. `python manage.py rqworker low --worker-class cvat.simpleworker.SimpleWorker &`
    4. `python manage.py rqworker webhooks --worker-class cvat.simpleworker.SimpleWorker &`
    5. `sudo docker run -it --rm --network=host --name test_opa -v /home/aaeon/cvat/cvat/apps/iam/rules:/rules openpolicyagent/opa:0.37.0-dev-static run --server --addr :8181 --set=decision_logs.console=true /rules`
    6. `python manage.py runserver --noreload --nothreading --insecure 127.0.0.1:7000`
    7. `CVAT_UI_HOST='0.0.0.0' yarn run start:cvat-ui`

I can log in CVAT ui, create task, attach image, labeling .etc but when I want to use API to attach an image to a created task, it return an error (OSError: `data/data/2/raw/latest.jpg` file already exists or its name is too long), I already logged in and checked task 2 is created but has no data in it. 

![Task 2 has no data](https://user-images.githubusercontent.com/51041343/199471072-aa7639de-c64b-422a-a21f-66ada92dd115.PNG)

I used `python manage.py dumpdata` and found out there's a raw image stored in cvat/data but unlike task 1(which attached image by cvat-ui), there's no preview.jpeg, index.json and manifest.jsonl in task 2
![Task 2 raw image](https://user-images.githubusercontent.com/51041343/199648668-90b0f2d3-1f64-4af8-beb8-2ba908666beb.png)

Code I used for requesting (this code I'm using can be executed without any error under docker-compose env):
```
ret, frame = cv2.VideoCapture("rtsp://www.cactus.tv:1554/cam58").read()
flag, encoded = cv2.imencode('.jpg', frame)
byte_encoded = encoded.tostring()
headers = {'Authorization':f"Token c04a43afc17d96868a369b2a76e3a09fb882cb79", 'Upload-Start': 'true', 'Upload-Finish': 'true'}
body = {'image_quality': 70}
files = {'client_files[0]': ("latest.jpg", byte_encoded, "image/jpg")}
r = requests.post("http://192.168.0.121:8890/api/tasks/2/data", headers=headers, data=body, files=files)
```

Error:
```
[2022-11-02 10:17:31,489] ERROR django.request: Internal Server Error: /api/tasks/2/data
Traceback (most recent call last):
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/aaeon/cvat/cvat/apps/engine/views.py", line 968, in data
    return self.upload_data(request)
  File "/home/aaeon/cvat/cvat/apps/engine/mixins.py", line 147, in upload_data
    return self.upload_finished(request)
  File "/home/aaeon/cvat/cvat/apps/engine/views.py", line 891, in upload_finished
    db_data = serializer.save()
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/rest_framework/serializers.py", line 200, in save
    self.instance = self.update(self.instance, validated_data)
  File "/home/aaeon/cvat/cvat/apps/engine/serializers.py", line 410, in update
    self._create_files(instance, files)
  File "/home/aaeon/cvat/cvat/apps/engine/serializers.py", line 434, in _create_files
    models.ClientFile.objects.bulk_create(client_objects)
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/django/db/models/query.py", line 514, in bulk_create
    returned_columns = self._batched_insert(
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/django/db/models/query.py", line 1293, in _batched_insert
    self._insert(item, fields=fields, using=self.db, ignore_conflicts=ignore_conflicts)
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1415, in execute_sql
    for sql, params in self.as_sql():
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1358, in as_sql
    value_rows = [
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1359, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1359, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1310, in pre_save_val
    return field.pre_save(obj, add=True)
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/django/db/models/fields/files.py", line 302, in pre_save
    file.save(file.name, file.file, save=False)
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/django/db/models/fields/files.py", line 89, in save
    self.name = self.storage.save(name, content, max_length=self.field.max_length)
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/django/core/files/storage.py", line 53, in save
    name = self.get_available_name(name, max_length=max_length)
  File "/home/aaeon/cvat/cvat/apps/engine/models.py", line 396, in get_available_name
    raise IOError('`{}` file already exists or its name is too long'.format(name))
OSError: `data/data/2/raw/latest.jpg` file already exists or its name is too long
ERROR:django.request:Internal Server Error: /api/tasks/2/data
Traceback (most recent call last):
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/aaeon/cvat/cvat/apps/engine/views.py", line 968, in data
    return self.upload_data(request)
  File "/home/aaeon/cvat/cvat/apps/engine/mixins.py", line 147, in upload_data
    return self.upload_finished(request)
  File "/home/aaeon/cvat/cvat/apps/engine/views.py", line 891, in upload_finished
    db_data = serializer.save()
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/rest_framework/serializers.py", line 200, in save
    self.instance = self.update(self.instance, validated_data)
  File "/home/aaeon/cvat/cvat/apps/engine/serializers.py", line 410, in update
    self._create_files(instance, files)
  File "/home/aaeon/cvat/cvat/apps/engine/serializers.py", line 434, in _create_files
    models.ClientFile.objects.bulk_create(client_objects)
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/django/db/models/query.py", line 514, in bulk_create
    returned_columns = self._batched_insert(
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/django/db/models/query.py", line 1293, in _batched_insert
    self._insert(item, fields=fields, using=self.db, ignore_conflicts=ignore_conflicts)
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1415, in execute_sql
    for sql, params in self.as_sql():
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1358, in as_sql
    value_rows = [
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1359, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1359, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1310, in pre_save_val
    return field.pre_save(obj, add=True)
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/django/db/models/fields/files.py", line 302, in pre_save
    file.save(file.name, file.file, save=False)
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/django/db/models/fields/files.py", line 89, in save
    self.name = self.storage.save(name, content, max_length=self.field.max_length)
  File "/home/aaeon/cvat/.env/lib/python3.9/site-packages/django/core/files/storage.py", line 53, in save
    name = self.get_available_name(name, max_length=max_length)
  File "/home/aaeon/cvat/cvat/apps/engine/models.py", line 396, in get_available_name
    raise IOError('`{}` file already exists or its name is too long'.format(name))
OSError: `data/data/2/raw/latest.jpg` file already exists or its name is too long
[2022-11-02 10:17:31,494] ERROR django.server: "POST /api/tasks/2/data HTTP/1.1" 500 207196
ERROR:django.server:"POST /api/tasks/2/data HTTP/1.1" 500 207196
```

`pip list`
```
Package                  Version
------------------------ -----------
asgiref                  3.5.2
astroid                  2.11.7
attrs                    21.4.0
av                       10.0.0
azure-core               1.26.0
azure-storage-blob       12.13.0
bcrypt                   4.0.1
boto3                    1.17.61
botocore                 1.20.112
cachetools               5.2.0
certifi                  2022.9.24
cffi                     1.15.1
charset-normalizer       2.0.12
click                    7.1.2
contourpy                1.0.5
coreapi                  2.3.3
coreschema               0.0.4
cPython                  0.0.6
croniter                 1.3.7
cryptography             38.0.1
cycler                   0.11.0
datumaro                 0.3
defusedxml               0.7.1
Deprecated               1.2.13
dill                     0.3.6
diskcache                5.0.2
distro                   1.8.0
dj-pagination            2.5.0
dj-rest-auth             2.2.4
Django                   3.2.16
django-allauth           0.50.0
django-appconf           1.0.4
django-auth-ldap         2.2.0
django-compressor        2.4
django-cors-headers      3.5.0
django-extensions        3.0.8
django-filter            2.4.0
django-rq                2.3.2
django-sendfile2         0.7.0
djangorestframework      3.12.4
dnspython                2.2.0
docker                   6.0.0
docker-compose           1.29.2
dockerpty                0.4.1
docopt                   0.6.2
drf-spectacular          0.22.1
EasyProcess              0.3
entrypoint2              1.1
fonttools                4.38.0
furl                     2.1.0
gitdb                    4.0.9
GitPython                3.1.27
google-api-core          2.10.2
google-auth              2.13.0
google-cloud-core        2.3.2
google-cloud-storage     1.42.0
google-crc32c            1.5.0
google-resumable-media   2.4.0
googleapis-common-protos 1.56.4
h5py                     3.6.0
idna                     3.4
inflection               0.5.1
isodate                  0.6.1
isort                    5.10.1
itypes                   1.2.0
Jinja2                   3.1.2
jmespath                 0.10.0
jsonschema               3.2.0
kiwisolver               1.4.4
lazy-object-proxy        1.8.0
limits                   2.7.1
lxml                     4.9.1
Markdown                 3.2.2
MarkupSafe               2.1.1
matplotlib               3.6.1
mccabe                   0.7.0
mistune                  2.0.4
msrest                   0.7.1
natsort                  8.0.0
networkx                 2.8.7
nibabel                  4.0.2
numpy                    1.22.0
oauthlib                 3.2.2
opencv-python            4.6.0.66
opencv-python-headless   4.5.5.62
orderedmultidict         1.0.1
orjson                   3.8.1
packaging                21.3
pandas                   1.5.1
paramiko                 2.11.0
patool                   1.12
pdf2image                1.14.0
Pillow                   9.0.1
pip                      22.3
platformdirs             2.5.2
protobuf                 3.19.6
pyasn1                   0.4.8
pyasn1-modules           0.2.8
pycocotools              2.0.5
pycparser                2.21
Pygments                 2.7.4
PyJWT                    2.6.0
pylint                   2.14.5
pylint-django            2.5.3
pylint-plugin-utils      0.7
pylogbeat                2.0.0
pymongo                  4.3.2
PyNaCl                   1.5.0
pyparsing                3.0.9
pyrsistent               0.18.1
python-dateutil          2.8.2
python-dotenv            0.21.0
python-ldap              3.4.0
python-logstash-async    2.2.0
python3-openid           3.2.0
pytz                     2020.1
pyunpack                 0.2.1
PyYAML                   5.4.1
rcssmin                  1.0.6
redis                    3.5.3
requests                 2.26.0
requests-oauthlib        1.3.1
rjsmin                   1.1.0
rope                     0.17.0
rq                       1.5.1
rq-scheduler             0.10.0
rsa                      4.9
ruamel.yaml              0.17.21
ruamel.yaml.clib         0.2.7
rules                    2.2
s3transfer               0.4.2
scipy                    1.9.3
setuptools               65.5.0
Shapely                  1.8.5.post1
six                      1.16.0
smmap                    5.0.0
snakeviz                 2.1.0
sqlparse                 0.4.2
tensorboardX             2.5.1
texttable                1.6.4
tomli                    2.0.1
tomlkit                  0.11.6
tornado                  6.2
typing_extensions        4.4.0
uritemplate              4.1.1
urllib3                  1.26.12
websocket-client         0.59.0
Werkzeug                 1.0.1
wheel                    0.37.1
wrapt                    1.14.1
```

**Comment by bsekachev** [comment]
Hello, please consider using [SDK](https://opencv.github.io/cvat/docs/api_sdk/sdk/).

**Comment by j22054022** [comment]
found out that a part of my code are blocking django (I intentionally keeps using GET method to get new job id which causing django to response and not attaching data to a task)
