### ISSUE TITLE
AttributeError while installing CVAT

### ISSUE THREAD

**Issue by haimat** [opencv/cvat#5300]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I followed the official CVAT installation guide - first cloned the git repository, installed latest docker-compose via pip (`pip install docker-compose --upgrade`), then wanted to start via:

```bash
$ docker-compose up -d
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 5, in <module>
    from compose.cli.main import main
  File "/usr/local/lib/python3.10/dist-packages/compose/cli/main.py", line 19, in <module>
    from ..config import ConfigurationError
  File "/usr/local/lib/python3.10/dist-packages/compose/config/__init__.py", line 3, in <module>
    from .config import ConfigurationError
  File "/usr/local/lib/python3.10/dist-packages/compose/config/config.py", line 48, in <module>
    from .validation import match_named_volumes
  File "/usr/local/lib/python3.10/dist-packages/compose/config/validation.py", line 8, in <module>
    from jsonschema import Draft4Validator
  File "/usr/lib/python3/dist-packages/jsonschema/__init__.py", line 11, in <module>
    from jsonschema.exceptions import (
  File "/usr/lib/python3/dist-packages/jsonschema/exceptions.py", line 152, in <module>
    @attr.s(hash=True)
AttributeError: module 'attr' has no attribute 's'
```

Any ideas what could be the problem here?

### Your Environment

- Git hash commit (`git log -1`): commit 7706eee504e73d538dd9d7ff76e7b9ae6aaaf7cb (HEAD -> develop, origin/develop, origin/HEAD)

- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.21
- Are you using Docker Swarm or Kubernetes? no
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu Linux 22.04

**Comment by nmanovic** [comment]
@haimat , something is wrong with your environment. Please try to reinstall docker-compose. Be sure that you can run it. It is definitely not a problem with CVAT.

**Comment by haimat** [comment]
@nmanovic I am trying to install CVAT on an ARM machine.
Could that be the issue - do you support that architecture?
