### ISSUE TITLE
CVAT crashes when viewing Keypoint annotations

### ISSUE THREAD

**Issue by jitaxis** [opencv/cvat#5309]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I upload COCO keypoint annotations, and when viewed and hovered over the browser crashes.

### Expected Behaviour

To be able to view COCO keypoint annotations without it crashing.

### Current Behaviour

When on the image I can see the Keypoints. Other error boxes pop up, but only when I hover over the points that the window crash and provides an error report.

**The pop-ups show the following error:**
TypeError: Cannot read properties of null (reading 'svg')

**The crash shows the following error:**

TypeError
Cannot read properties of undefined (reading 'addClass')

TypeError: Cannot read properties of undefined (reading 'addClass')
    at yw.activateShape (http://localhost:8080/assets/cvat-ui.33dd02fc10388e3784d9.min.js:2:5618087)
    at yw.activate (http://localhost:8080/assets/cvat-ui.33dd02fc10388e3784d9.min.js:2:5621272)
    at yw.notify (http://localhost:8080/assets/cvat-ui.33dd02fc10388e3784d9.min.js:2:5605174)
    at iy.notify (http://localhost:8080/assets/cvat-ui.33dd02fc10388e3784d9.min.js:2:5458777)
    at iy.activate (http://localhost:8080/assets/cvat-ui.33dd02fc10388e3784d9.min.js:2:5462895)
    at xw.activate (http://localhost:8080/assets/cvat-ui.33dd02fc10388e3784d9.min.js:2:5636342)
    at IB.activateOnCanvas (http://localhost:8080/assets/cvat-ui.33dd02fc10388e3784d9.min.js:2:6198499)
    at IB.componentDidUpdate (http://localhost:8080/assets/cvat-ui.33dd02fc10388e3784d9.min.js:2:6196352)
    at ss (http://localhost:8080/assets/cvat-ui.33dd02fc10388e3784d9.min.js:2:4412421)
    at vl (http://localhost:8080/assets/cvat-ui.33dd02fc10388e3784d9.min.js:2:4429948)

### Steps to Reproduce (for bugs)

1. Uploaded COCO keypoint annotations
2. View annotations (Pop-up errors are shown)
3. Hover over keypoints to make the window crash.

### Context

This stops my ability to check my COCO annotations.

### Your Environment

OS:
 Linux 20.04 Ubuntu
CVAT version:
  Server: 2.3
  Core: 7.2.0
  Canvas: 2.16.1
  UI: 1.43.2
- Git hash commit (`git log -1`):
 6acab035f2ad2cb9501d814c9c5c38e49bf8e628
- Docker version:
   20.10.12

**Comment by bsekachev** [comment]
@jitaxis 

Please, provide the task specification and annotations to reproduce the issue.

**Comment by jitaxis** [comment]
[cvat_kp_error_dataset.zip](https://github.com/opencv/cvat/files/10059871/cvat_kp_error_dataset.zip)

Make sure to upload as "COCO keypoint". I'm not sure what specification you would like.

**Comment by jitaxis** [comment]
This is either fixed or I had a mistake as it is fine now.
I am on commit bc079c3129544d8dd91aae36289123958902483b on the develop branch
