### ISSUE TITLE
Import error during make migrations. 

### ISSUE THREAD

**Issue by xmac** [opencv/cvat#5322]
While setting up the cvat in my local, I found this below error while running the migration command.

Error message:

`(.env) keshav@BLTSL03245:~/new_setup/cvat$ python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    execute_from_command_line(sys.argv)
  File "/home/keshav/new_setup/cvat/.env/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/keshav/new_setup/cvat/.env/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute    
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/keshav/new_setup/cvat/.env/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv  
    self.execute(*args, **cmd_options)
  File "/home/keshav/new_setup/cvat/.env/lib/python3.8/site-packages/django/core/management/base.py", line 393, in execute
    self.check()
  File "/home/keshav/new_setup/cvat/.env/lib/python3.8/site-packages/django/core/management/base.py", line 419, in check
    all_issues = checks.run_checks(
  File "/home/keshav/new_setup/cvat/.env/lib/python3.8/site-packages/django/core/checks/registry.py", line 76, in run_checks      
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/keshav/new_setup/cvat/.env/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config    
    return check_resolver(resolver)
  File "/home/keshav/new_setup/cvat/.env/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver      
    return check_method()
  File "/home/keshav/new_setup/cvat/.env/lib/python3.8/site-packages/django/urls/resolvers.py", line 416, in check
    for pattern in self.url_patterns:
  File "/home/keshav/new_setup/cvat/.env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[[self.name](http://self.name/)] = self.func(instance)
  File "/home/keshav/new_setup/cvat/.env/lib/python3.8/site-packages/django/urls/resolvers.py", line 602, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/keshav/new_setup/cvat/.env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[[self.name](http://self.name/)] = self.func(instance)
  File "/home/keshav/new_setup/cvat/.env/lib/python3.8/site-packages/django/urls/resolvers.py", line 595, in urlconf_module       
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/keshav/new_setup/cvat/cvat/urls.py", line 27, in <module
    path('', include('cvat.apps.engine.urls')),
  File "/home/keshav/new_setup/cvat/.env/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/keshav/new_setup/cvat/cvat/apps/engine/urls.py", line 7, in <module>
    from . import views
  File "/home/keshav/new_setup/cvat/cvat/apps/engine/views.py", line 45, in <module>
    import cvat.apps.dataset_manager.views  # pylint: disable=unused-import
  File "/home/keshav/new_setup/cvat/cvat/apps/dataset_manager/views.py", line 15, in <module>
    import cvat.apps.dataset_manager.task as task
  File "/home/keshav/new_setup/cvat/cvat/apps/dataset_manager/task.py", line 18, in <module>
    from .annotation import AnnotationIR, AnnotationManager
  File "/home/keshav/new_setup/cvat/cvat/apps/dataset_manager/annotation.py", line 9, in <module>
    from scipy.optimize import linear_sum_assignment
  File "/home/keshav/new_setup/cvat/.env/lib/python3.8/site-packages/scipy/optimize/__init__.py", line 401, in <module>
    from ._minimize import *
  File "/home/keshav/new_setup/cvat/.env/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 26, in <module>
    from ._trustregion_constr import _minimize_trustregion_constr
  File "/home/keshav/new_setup/cvat/.env/lib/python3.8/site-packages/scipy/optimize/_trustregion_constr/__init__.py", line 4, in <module>
    from .minimize_trustregion_constr import _minimize_trustregion_constr
  File "/home/keshav/new_setup/cvat/.env/lib/python3.8/site-packages/scipy/optimize/_trustregion_constr/minimize_trustregion_constr.py", line 5, in <module>
    from .._constraints import (
  File "/home/keshav/new_setup/cvat/.env/lib/python3.8/site-packages/scipy/optimize/_constraints.py", line 8, in <module>
    from numpy.testing import suppress_warnings
  File "/home/keshav/new_setup/cvat/.env/lib/python3.8/site-packages/numpy/testing/__init__.py", line 12, in <module>
    from ._private import extbuild, decorators as dec
  File "/hom/keshav/new_setup/cvat/.env/lib/python3.8/site-packages/numpy/testing/_private/extbuild.py", line 11, in <module>    
    from numpy.distutils.ccompiler import new_compiler
  File "/home/keshav/new_setup/cvat/.env/lib/python3.8/site-packages/numpy/distutils/__init__.py", line 24, in <module>
    from . import ccompiler
  File "/home/keshav/new_setup/cvat/.env/lib/python3.8/site-packages/numpy/distutils/ccompiler.py", line 20, in <module>
   from numpy.distutils import log
  File "/home/keshav/new_setup/cvat/.env/lib/python3.8/site-packages/numpy/distutils/log.py", line 4, in <module>
    from distutils.log import Log as old_Log
ImportError: cannot import name 'Log' from 'distutils.log' (/home/keshav/new_setup/cvat/.env/lib/python3.8/site-packages/setuptools/_distutils/log.py)`

**Comment by nmanovic** [comment]
@xmac , You have some problems with your environment. Try to re-create the python virtual environment.

```ImportError: cannot import name 'Log' from 'distutils.log'```

We cannot help here. Most probably it is not an issue with CVAT. I will close the ticket.
