### ISSUE TITLE
Cvat.org don't work

### ISSUE THREAD

**Issue by claudio9russo7** [opencv/cvat#5374]
### My actions before raising this issue
- [ x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x ] Searched [past issues](/issues)

I was try to migrate my data but i can't access the cvat.org site

TypeError
Cannot read properties of null (reading 'dumpers')

TypeError: Cannot read properties of null (reading 'dumpers')
    at https://cvat.org/assets/cvat-ui.0fe2808fbbf18ef375cd.min.js:372:728328
    at https://cvat.org/assets/cvat-ui.0fe2808fbbf18ef375cd.min.js:372:338531
    at https://cvat.org/assets/cvat-ui.0fe2808fbbf18ef375cd.min.js:372:339065
    at Sv (https://cvat.org/assets/cvat-ui.0fe2808fbbf18ef375cd.min.js:372:728294)
    at Ko (https://cvat.org/assets/cvat-ui.0fe2808fbbf18ef375cd.min.js:346:57930)
    at Ri (https://cvat.org/assets/cvat-ui.0fe2808fbbf18ef375cd.min.js:346:66791)
    at Di (https://cvat.org/assets/cvat-ui.0fe2808fbbf18ef375cd.min.js:346:66610)
    at Ai (https://cvat.org/assets/cvat-ui.0fe2808fbbf18ef375cd.min.js:346:66293)
    at gs (https://cvat.org/assets/cvat-ui.0fe2808fbbf18ef375cd.min.js:346:107698)
    at cl (https://cvat.org/assets/cvat-ui.0fe2808fbbf18ef375cd.min.js:346:96717)

This is the type of error i get.

**Comment by claudio9russo7** [comment]
Hello, i tryed againt this mornig. Now i can connect but when i try to backup the project i get this error
<img width="405" alt="image" src="https://user-images.githubusercontent.com/99536010/204726899-d072cec4-26b3-41c0-b643-8a9916bce9ff.png">

**Comment by zhiltsov-max** [comment]
@azhavoro, could you please check?

Related #5375

**Comment by nmanovic** [comment]
@claudio9russo7 , we don't support cvat.org and it will be terminated in Feburary. I will recommend using our official server [app.cvat.ai](https://app.cvat.ai/)

**Comment by syyxtl** [comment]
> @claudio9russo7 , we don't support cvat.org and it will be terminated in Feburary. I will recommend using our official server [app.cvat.ai](https://app.cvat.ai/)

i can not visit app.cvat.ai (Oct 13, 2023). Do you know what happened?
