### ISSUE TITLE
could not create the task on server code:400

### ISSUE THREAD

**Issue by cyril10xds** [opencv/cvat#539]
Unable to create a task. 
could not create the task on server code:400
![11](https://user-images.githubusercontent.com/50192526/60504299-f6df1a80-9cde-11e9-8083-664f4a9804dd.png)

**Comment by bsekachev** [comment]
@cyril10xds 
What is an output of ```docker logs cvat```?

**Comment by cyril10xds** [comment]
STDERR:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rq/worker.py", line 812, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 588, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 594, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/django/cvat/apps/engine/task.py", line 399, in _create_thread
    _copy_video_to_task(video, db_task, db_task.get_frame_step())
  File "/home/django/cvat/apps/engine/task.py", line 193, in _copy_video_to_task
    step, db_task.start_frame, db_task.stop_frame)
  File "/home/django/cvat/apps/engine/task.py", line 79, in __init__
    ff.run()
  File "/usr/local/lib/python3.5/dist-packages/ffmpy.py", line 105, in run
    raise FFRuntimeError(self.cmd, self.process.returncode, out[0], out[1])
ffmpy.FFRuntimeError: `ffmpeg -i /home/django/data/91/.upload/Rest_FallOnFloor.mpg -start_number 0 -b:v 10000k -vsync 0 -an -y -q:v 16 /tmp/cvat-llqr88dj.data/%d.jpg` exited with status 1

STDOUT:
[cvat_log.txt](https://github.com/opencv/cvat/files/3349730/cvat_log.txt)

**Comment by bsekachev** [comment]
@cyril10xds Something wrong with your video file, ffmpeg can't convert it.

**Comment by bsekachev** [comment]
@cyril10xds 
You can try reconvert it into another format (.mp4, .avi, etc). It might help you.

**Comment by bsekachev** [comment]
We also have to improve error handling. A user need more information. Related issue: #511

**Comment by cyril10xds** [comment]
@bsekachev 
thanks for your guidance

**Comment by bsekachev** [comment]
I will close issue. Let me know if you have other questions.
