### ISSUE TITLE
Cannot upload annotations

### ISSUE THREAD

**Issue by namdvt** [opencv/cvat#5493]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I am unable to upload the coco annotations to my local sever. 

### Expected Behaviour
The annotations should be loaded successfully to my task.

### Current Behaviour
The annotations cannot be loaded.
here is the browser log
```
:8080/api/user-agreements?org=:1          Failed to load resource: the server responded with a status of 404 (Not Found)
:8080/api/lambda/requests?org=:1          Failed to load resource: the server responded with a status of 403 (Forbidden)
:8080/api/lambda/requests?org=:1          Failed to load resource: the server responded with a status of 403 (Forbidden)
:8080/api/lambda/requests?org=:1          Failed to load resource: the server responded with a status of 403 (Forbidden)
:8080/api/lambda/requests?org=:1          Failed to load resource: the server responded with a status of 403 (Forbidden)
:8080/api/jobs/3/annotations/:1          Failed to load resource: the server responded with a status of 403 (Forbidden)
cvat-app.tsx:357 Error: tus: unexpected response while creating upload, originated from request (method: POST, url: http://localhost:8080/api/jobs/3/annotations/, response code: 403, response text: {"detail":"CSRF Failed: CSRF token missing or incorrect."}, request id: n/a).
e @ cvat-app.tsx:357
:8080/api/jobs/3/annotations/:1          Failed to load resource: the server responded with a status of 403 (Forbidden)
cvat-app.tsx:357 Error: tus: unexpected response while creating upload, originated from request (method: POST, url: http://localhost:8080/api/jobs/3/annotations/, response code: 403, response text: {"detail":"CSRF Failed: CSRF token missing or incorrect."}, request id: n/a).
e @ cvat-app.tsx:357
:8080/api/jobs/3/annotations/:1          Failed to load resource: the server responded with a status of 403 (Forbidden)
cvat-app.tsx:357 Error: tus: unexpected response while creating upload, originated from request (method: POST, url: http://localhost:8080/api/jobs/3/annotations/, response code: 403, response text: {"detail":"CSRF Failed: CSRF token missing or incorrect."}, request id: n/a).
e @ cvat-app.tsx:357
translate.js:1091 Uncaught (in promise) Error: getTranslators: detection is already running
    at Zotero.Translate.Web.<anonymous> (translate.js:1091:45)
    at Zotero.Translate.Web.getTranslators (promise.js:36:17)
    at Object.init (inject.js:105:25)
    at Object.historyChanged (inject.js:705:21)
    at messageListener (messaging_inject.js:122:50)
    at messaging_inject.js:132:6
(anonymous) @ translate.js:1091
(anonymous) @ promise.js:36
init @ inject.js:105
(anonymous) @ inject.js:705
messageListener @ messaging_inject.js:122
(anonymous) @ messaging_inject.js:132
2translate.js:1091 Uncaught (in promise) Error: getTranslators: detection is already running
    at Zotero.Translate.Web.<anonymous> (translate.js:1091:45)
    at Zotero.Translate.Web.getTranslators (promise.js:36:17)
    at Object.init (inject.js:105:25)
    at Object.historyChanged (inject.js:705:21)
    at messageListener (messaging_inject.js:122:50)
    at messaging_inject.js:132:6
:8080/api/lambda/requests?org=:1          Failed to load resource: the server responded with a status of 403 (Forbidden)
:8080/api/lambda/requests?org=:1          Failed to load resource: the server responded with a status of 403 (Forbidden)
:8080/api/jobs/4/annotations/:1          Failed to load resource: the server responded with a status of 403 (Forbidden)
cvat-app.tsx:357 Error: tus: unexpected response while creating upload, originated from request (method: POST, url: http://localhost:8080/api/jobs/4/annotations/, response code: 403, response text: {"detail":"CSRF Failed: CSRF token missing or incorrect."}, request id: n/a).
e @ cvat-app.tsx:357
:8080/api/jobs/4/annotations/:1          Failed to load resource: the server responded with a status of 403 (Forbidden)
cvat-app.tsx:357 Error: tus: unexpected response while creating upload, originated from request (method: POST, url: http://localhost:8080/api/jobs/4/annotations/, response code: 403, response text: {"detail":"CSRF Failed: CSRF token missing or incorrect."}, request id: n/a).
e @ cvat-app.tsx:357
:8080/api/jobs/4/annotations/:1          Failed to load resource: the server responded with a status of 403 (Forbidden)
cvat-app.tsx:357 Error: tus: unexpected response while creating upload, originated from request (method: POST, url: http://localhost:8080/api/jobs/4/annotations/, response code: 403, response text: {"detail":"CSRF Failed: CSRF token missing or incorrect."}, request id: n/a).
e @ cvat-app.tsx:357
showErrors @ cvat-app.tsx:368
componentDidUpdate @ cvat-app.tsx:263
ss @ react-dom.production.min.js:212
vl @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Ua @ react-dom.production.min.js:122
gl @ react-dom.production.min.js:248
rl @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Ua @ react-dom.production.min.js:122
qa @ react-dom.production.min.js:123
Ga @ react-dom.production.min.js:122
al @ react-dom.production.min.js:240
notify @ Subscription.js:16
notifyNestedSubs @ Subscription.js:88
a @ Subscription.js:93
v @ redux.js:296
(anonymous) @ redux-logger.es.js:832
(anonymous) @ index.js:20
dispatch @ redux.js:691
(anonymous) @ import-actions.ts:147
:8080/api/jobs/4/annotations/:1          Failed to load resource: the server responded with a status of 403 (Forbidden)
cvat-app.tsx:357 Error: tus: unexpected response while creating upload, originated from request (method: POST, url: http://localhost:8080/api/jobs/4/annotations/, response code: 403, response text: {"detail":"CSRF Failed: CSRF token missing or incorrect."}, request id: n/a).
e @ cvat-app.tsx:357
DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
```
and the docker log
```
2022-12-20 23:25:51 cvat_opa              | {"client_addr":"172.21.0.9:37926","level":"info","msg":"Received request.","req_id":213,"req_method":"POST","req_path":"/v1/data/tasks/allow","time":"2022-12-20T10:25:51Z"}
2022-12-20 23:25:51 cvat_opa              | {"bundles":{"cvat":{}},"decision_id":"ebc718b2-8bad-47db-9a7c-165308548525","input":{"auth":{"organization":null,"user":{"id":1,"privilege":"user"}},"resource":{"assignee":{"id":null},"id":4,"organization":{"id":null},"owner":{"id":1},"project":{"assignee":{"id":null},"organization":{"id":null},"owner":{"id":1}}},"scope":"view"},"labels":{"id":"d07f0c29-1f64-4f1c-9b5a-98632a992286","version":"0.34.2"},"level":"info","metrics":{"counter_server_query_cache_hit":1,"timer_rego_input_parse_ns":333133,"timer_rego_query_eval_ns":3316490,"timer_server_handler_ns":3953712},"msg":"Decision Log","path":"tasks/allow","requested_by":"172.21.0.9:37926","result":true,"time":"2022-12-20T10:25:51Z","timestamp":"2022-12-20T10:25:51.627752346Z","type":"openpolicyagent.org/decision_logs"}
2022-12-20 23:25:51 cvat_opa              | {"client_addr":"172.21.0.9:37926","level":"info","msg":"Sent response.","req_id":213,"req_method":"POST","req_path":"/v1/data/tasks/allow","resp_bytes":68,"resp_duration":7.050942,"resp_status":200,"time":"2022-12-20T10:25:51Z"}
2022-12-20 23:26:07 cvat_opa              | {"client_addr":"172.21.0.9:37938","level":"info","msg":"Received request.","req_id":214,"req_method":"POST","req_path":"/v1/data/jobs/allow","time":"2022-12-20T10:26:07Z"}
2022-12-20 23:26:07 cvat_opa              | {"bundles":{"cvat":{}},"decision_id":"8e9649dc-4c15-4303-90b1-9011b6dd68ed","input":{"auth":{"organization":null,"user":{"id":1,"privilege":"user"}},"resource":{"assignee":{"id":null},"id":4,"organization":{"id":null},"project":{"assignee":{"id":null},"owner":{"id":1}},"task":{"assignee":{"id":null},"owner":{"id":1}}},"scope":"import:annotations"},"labels":{"id":"d07f0c29-1f64-4f1c-9b5a-98632a992286","version":"0.34.2"},"level":"info","metrics":{"counter_server_query_cache_hit":1,"timer_rego_input_parse_ns":170307,"timer_rego_query_eval_ns":1287791,"timer_server_handler_ns":1585318},"msg":"Decision Log","path":"jobs/allow","requested_by":"172.21.0.9:37938","result":true,"time":"2022-12-20T10:26:07Z","timestamp":"2022-12-20T10:26:07.758090031Z","type":"openpolicyagent.org/decision_logs"}
2022-12-20 23:26:07 cvat_opa              | {"client_addr":"172.21.0.9:37938","level":"info","msg":"Sent response.","req_id":214,"req_method":"POST","req_path":"/v1/data/jobs/allow","resp_bytes":68,"resp_duration":2.169108,"resp_status":200,"time":"2022-12-20T10:26:07Z"}
2022-12-20 23:26:07 cvat_server           | 2022-12-20 10:26:07,813 DEBG 'runserver' stderr output:
2022-12-20 23:26:07 cvat_server           | [Tue Dec 20 10:26:07.812998 2022] [wsgi:error] [pid 106:tid 140339888269056] [remote 172.21.0.5:45184] [2022-12-20 10:26:07,812] WARNING django.request: Forbidden: /api/jobs/4/annotations/
2022-12-20 23:26:07 cvat_server           | 
2022-12-20 23:26:07 cvat_server           | 2022-12-20 10:26:07,814 DEBG 'runserver' stderr output:
2022-12-20 23:26:07 cvat_server           | [Tue Dec 20 10:26:07.814040 2022] [wsgi:error] [pid 106:tid 140339888269056] [remote 172.21.0.5:45184] WARNING:django.request:Forbidden: /api/jobs/4/annotations/
2022-12-20 23:26:07 cvat_server           | 
2022-12-20 23:26:40 cvat_worker_default   | 2022-12-20 10:26:40,228 DEBG 'rqworker_default_1' stderr output:
2022-12-20 23:26:40 cvat_worker_default   | DEBUG:rq.worker:Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.
2022-12-20 23:26:40 cvat_worker_default   | 
```
### Steps to Reproduce (for bugs)
1. Load some images
1. Do the annotations
1. Save the annotations (I already tried with coco/cvat format)
1. Load the annotations (xml or zip extension)

### Your Environment
- Git hash commit (`git log -1`): 4fdac637394a03d5b
- Docker version `docker version`: Docker version 20.10.21, build baeda1f  
- Operating System and version: Windows 10
- Code example or link to GitHub repo or gist to reproduce problem:

Thank for your support.

**Comment by bsekachev** [comment]
Hello @namdvt 

Try to logout/login.

**Comment by bsekachev** [comment]
@klakhov 

Do not we expect that if user does not have token it will be logout automatically?

**Comment by klakhov** [comment]
@bsekachev Yes, but only after #5450 will be merged. Logout logic was replaced with tmp solution when Social authentication was not providing tokens. (and it havent been returned back :slightly_frowning_face:)

**Comment by namdvt** [comment]
Thank you. After logout/login, I can upload annotations now.
