### ISSUE TITLE
CVAT-CANVAS build FAILS running "yarn run build"

### ISSUE THREAD

**Issue by Dipsorum** [opencv/cvat#5564]
### My actions before raising this issue
- [ ] Searched [past issues](/issues)
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

cvat-canvas build fails in two different ways.

### Expected Behaviour

As it says in cvat/cvat-canvas/README.md I should be able to build the module from source using "yarn run build".

### Current Behaviour

Running "yarn run build" results in this error:
```
yarn run build

yarn run v1.22.19

$ tsc && webpack --config ./webpack.config.js

src/typescript/masksHandler.ts:244:32 - error TS2349: This expression is not callable.

  Each member of the union type '{ <K extends "toString" | "left" | "flipY" | "center" | "top" | "visible" | "canvas" | "data" | "clipPath" | "toggle" | "fill" | "group" | "type" | "angle" | "points" | "width" | "height" | ... 182 more ... | "snapThreshold">(key: K, value: Polygon[K] | ((value: Polygon[K]) => Polygon[K])): Object; (options: Partial...' has signatures, but none of those signatures are compatible with each other.



244                         object.set({ fill: color.toRgba() });

                                 
Found 1 error.

error Command failed with exit code 1.
```

Even if i comment out line 244 in src/typescript/masksHandler.ts the build command fails anyway:

```
yarn run build

yarn run v1.22.19

$ tsc && webpack --config ./webpack.config.js

../node_modules/@types/three/src/renderers/WebGLRenderer.d.ts(34,34): error TS2304: Cannot find name 'OffscreenCanvas'.

../node_modules/@types/three/src/renderers/WebGLRenderer.d.ts(34,34): error TS2304: Cannot find name 'OffscreenCanvas'.

asset cvat-canvas.8cbe634c66d0b5940f5d.js 576 KiB [emitted] [immutable] [minimized] [big] (name: cvat-canvas) 2 related assets

orphan modules 323 KiB [orphan] 20 modules

runtime modules 972 bytes 5 modules

cacheable modules 1.5 MiB

  modules by path ../node_modules/ 1.17 MiB

    ../node_modules/polylabel/polylabel.js 4.76 KiB [built] [code generated]

    ../node_modules/fabric/dist/fabric.js 987 KiB [built] [code generated]

    + 8 modules

  modules by path ./src/ 333 KiB

    ./src/typescript/canvas.ts + 20 modules 326 KiB [built] [code generated]

    ./src/scss/canvas.scss 685 bytes [built] [code generated]

    ../node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].use[1]!../node_modules/postcss-loader/src/index.js??ruleSet[1].rules[1].use[2]!../node_modules/sass-loader/dist/cjs.js!./src/scss/canvas.scss 5.93 KiB [built] [code generated]

  modules by path jsdom/lib/jsdom/ 30 bytes

    jsdom/lib/jsdom/living/generated/utils (ignored) 15 bytes [built] [code generated]

    jsdom/lib/jsdom/utils (ignored) 15 bytes [built] [code generated]

  jsdom (ignored) 15 bytes [built] [code generated]



LOG from e

<i> No entry point specified, using webpack config for entrypoint(s)

<w> Failed to create .d.ts Error: Compiled with errors

<w>     at checkDiagnosticsErrors (/home/edoardo/cvat/node_modules/dts-bundle-generator/dist/helpers/check-diagnostics-errors.js:21:11)

<w>     at checkProgramDiagnosticsErrors (/home/edoardo/cvat/node_modules/dts-bundle-generator/dist/helpers/check-diagnostics-errors.js:12:5)

<w>     at getDeclarationFiles (/home/edoardo/cvat/node_modules/dts-bundle-generator/dist/compile-dts.js:99:66)

<w>     at compileDts (/home/edoardo/cvat/node_modules/dts-bundle-generator/dist/compile-dts.js:35:20)

<w>     at generateDtsBundle (/home/edoardo/cvat/node_modules/dts-bundle-generator/dist/bundle-generator.js:27:43)

<w>     at e.<anonymous> (/home/edoardo/cvat/node_modules/bundle-declarations-webpack-plugin/lib/index.js:1:4697)

<w>     at /home/edoardo/cvat/node_modules/bundle-declarations-webpack-plugin/lib/index.js:1:2623

<w>     at Object.next (/home/edoardo/cvat/node_modules/bundle-declarations-webpack-plugin/lib/index.js:1:2728)

<w>     at a (/home/edoardo/cvat/node_modules/bundle-declarations-webpack-plugin/lib/index.js:1:1442)

<w>     at processTicksAndRejections (node:internal/process/task_queues:96:5)

+ 2 hidden lines



WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).

This can impact web performance.

Assets: 

  cvat-canvas.8cbe634c66d0b5940f5d.js (576 KiB)



WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.

Entrypoints:

  cvat-canvas (576 KiB)

      cvat-canvas.8cbe634c66d0b5940f5d.js





WARNING in webpack performance recommendations: 

You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.

For more info visit https://webpack.js.org/guides/code-splitting/



webpack 5.74.0 compiled with 3 warnings in 48021 ms



assets by status 3.15 MiB [cached] 1 asset

759 modules



LOG from e

<i> No entry point specified, using webpack config for entrypoint(s)

<w> Failed to create .d.ts Error: Compiled with errors

<w>     at checkDiagnosticsErrors (/home/edoardo/cvat/node_modules/dts-bundle-generator/dist/helpers/check-diagnostics-errors.js:21:11)

<w>     at checkProgramDiagnosticsErrors (/home/edoardo/cvat/node_modules/dts-bundle-generator/dist/helpers/check-diagnostics-errors.js:12:5)

<w>     at getDeclarationFiles (/home/edoardo/cvat/node_modules/dts-bundle-generator/dist/compile-dts.js:99:66)

<w>     at compileDts (/home/edoardo/cvat/node_modules/dts-bundle-generator/dist/compile-dts.js:35:20)

<w>     at generateDtsBundle (/home/edoardo/cvat/node_modules/dts-bundle-generator/dist/bundle-generator.js:27:43)

<w>     at e.<anonymous> (/home/edoardo/cvat/node_modules/bundle-declarations-webpack-plugin/lib/index.js:1:4697)

<w>     at /home/edoardo/cvat/node_modules/bundle-declarations-webpack-plugin/lib/index.js:1:2623

<w>     at Object.next (/home/edoardo/cvat/node_modules/bundle-declarations-webpack-plugin/lib/index.js:1:2728)

<w>     at a (/home/edoardo/cvat/node_modules/bundle-declarations-webpack-plugin/lib/index.js:1:1442)

<w>     at runMicrotasks (<anonymous>)

+ 2 hidden lines



WARNING in ../node_modules/ws/lib/buffer-util.js 113:23-44

Module not found: Error: Can't resolve 'bufferutil' in '/home/edoardo/cvat/node_modules/ws/lib'

 @ ../node_modules/ws/lib/websocket.js 31:21-45

 @ ../node_modules/ws/index.js 3:18-44

 @ ../node_modules/fabric/node_modules/jsdom/lib/jsdom/living/websockets/WebSocket-impl.js 7:18-31

 @ ../node_modules/fabric/node_modules/jsdom/lib/jsdom/browser/Window.js 21:22-83

 @ ../node_modules/fabric/node_modules/jsdom/lib/api.js 13:25-61

 @ ../node_modules/fabric/dist/fabric.js 24:14-30

 @ ./src/typescript/canvasView.ts 8:0-32 2661:18-38

 @ ./src/typescript/canvas.ts 9:0-46 24:20-34



WARNING in ../node_modules/ws/lib/validation.js 117:24-49

Module not found: Error: Can't resolve 'utf-8-validate' in '/home/edoardo/cvat/node_modules/ws/lib'

 @ ../node_modules/ws/lib/receiver.js 13:43-66

 @ ../node_modules/ws/index.js 7:21-46

 @ ../node_modules/fabric/node_modules/jsdom/lib/jsdom/living/websockets/WebSocket-impl.js 7:18-31

 @ ../node_modules/fabric/node_modules/jsdom/lib/jsdom/browser/Window.js 21:22-83

 @ ../node_modules/fabric/node_modules/jsdom/lib/api.js 13:25-61

 @ ../node_modules/fabric/dist/fabric.js 24:14-30

 @ ./src/typescript/canvasView.ts 8:0-32 2661:18-38

 @ ./src/typescript/canvas.ts 9:0-46 24:20-34



2 warnings have detailed information that is not shown.

Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.



ERROR in ../node_modules/canvas/build/Release/canvas.node 1:0

Module parse failed: Unexpected character '' (1:0)

You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

(Source code omitted for this binary file)

 @ ../node_modules/canvas/lib/bindings.js 3:17-56

 @ ../node_modules/canvas/index.js 7:17-42

 @ ../node_modules/fabric/node_modules/jsdom/lib/jsdom/utils.js 154:2-27 160:17-34

 @ ../node_modules/fabric/dist/fabric.js 35:22-61

 @ ./src/typescript/canvasView.ts 8:0-32 2661:18-38

 @ ./src/typescript/canvas.ts 9:0-46 24:20-34



webpack 5.74.0 compiled with 1 error and 2 warnings in 103789 ms

error Command failed with exit code 1.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Steps to Reproduce (for bugs)

To reproduce the first error:
1. Download the git repo in ~/cvat
2. cd ~/cvat/cvat-canvas
3. yarn install
4. yarn run build

To reproduce the second error:
1. Download the git repo in ~/cvat
2. cd ~/cvat/cvat-canvas
3. yarn install
4. comment line 244 of ~/cvat/cvat-canvas/src/typescript/masksHandler.ts
5. yarn run build

### Context

I was trying to build the canvas module alone to use the canvas elements defined by cvat itself in an external projects.

### Your Environment

- Git hash commit (`git log -1`): 
                     develop 7df2b2fded320eef43166fc9689b9026bf0d45d3
                     master 2c4676ace32a68572b38205f002a98e93af917d0
- Docker version `docker version` (e.g. Docker 17.0.05): building without docker.
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 22.04

**Comment by bsekachev** [comment]
@Dipsorum  Thank you for the report.
