### ISSUE TITLE
Cannot create super user

### ISSUE THREAD

**Issue by ArnaudBru** [opencv/cvat#5568]
### My actions before raising this issue
- [ x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x ] Searched [past issues](/issues)

### Expected Behaviour
I would like to be able to create a superuser

### Current Behaviour
I am trying to install cvat, so I am following the [Installation guide](https://opencv.github.io/cvat/docs/administration/basics/installation/#ubuntu-1804-x86_64amd64)

The first step run smoothly, however when I try to create a superuser with the command

`docker exec -it cvat_server bash -ic 'python3 ~/manage.py createsuperuser'`

After a few minutes, I get the following error:

```
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/opt/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/opt/venv/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection timed out
    Is the server running on host "cvat_db" (172.18.0.3) and accepting
    TCP/IP connections on port 5432?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/django/manage.py", line 21, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/venv/lib/python3.8/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 79, in execute
    return super().execute(*args, **options)
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/base.py", line 397, in execute
    self.check_migrations()
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/base.py", line 486, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/opt/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/opt/venv/lib/python3.8/site-packages/django/db/migrations/loader.py", line 53, in __init__
    self.build_graph()
  File "/opt/venv/lib/python3.8/site-packages/django/db/migrations/loader.py", line 220, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/opt/venv/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 77, in applied_migrations
    if self.has_table():
  File "/opt/venv/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 55, in has_table
    with self.connection.cursor() as cursor:
  File "/opt/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/opt/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/opt/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/opt/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/opt/venv/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not connect to server: Connection timed out
    Is the server running on host "cvat_db" (172.18.0.3) and accepting
    TCP/IP connections on port 5432?
```

### Steps to Reproduce (for bugs)
1. Follow the [Installation Guide](https://opencv.github.io/cvat/docs/administration/basics/installation/#ubuntu-1804-x86_64amd64)
2. Try to create a superuser

### Context
I am simply trying to install and use CVAT

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.22
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 22.04.1 LTS

**Comment by azhavoro** [comment]
@ArnaudBru Hi, please provide `docker ps` output and logs from cvat_server and cvat_db containers: `docker logs cvat_server > server.log`, `docker logs cvat_db > db.log`

**Comment by ntk97** [comment]
Even I am facing the same issue,  same steps are being followed.

<img width="466" alt="image" src="https://user-images.githubusercontent.com/74262887/212317808-380d6c66-6a49-4de9-aad5-bc650a8bf78c.png">

**Comment by azhavoro** [comment]
> Even I am facing the same issue, same steps are being followed.
> 
> Below is the screenshot of the docker logs
> 
> <img alt="image" width="466" src="https://user-images.githubusercontent.com/74262887/212317808-380d6c66-6a49-4de9-aad5-bc650a8bf78c.png">
> 
> Need a fix for this

@ntk97 Hi
![image](https://user-images.githubusercontent.com/41117609/212318821-67a01456-3031-4085-aa99-e342cac74c01.png)
follow this: https://opencv.github.io/cvat/docs/administration/advanced/upgrade_guide/#how-to-upgrade-postgresql-database-base-image
Also you using old cvat images, run `docker compose pull`

**Comment by ntk97** [comment]
I did` docker compose pull `  and then again up the docker containers but same issue.
 
<img width="804" alt="image" src="https://user-images.githubusercontent.com/74262887/212325530-dcf92dae-3637-46ee-9f00-f2264109f265.png">
<img width="547" alt="image" src="https://user-images.githubusercontent.com/74262887/212325623-0452fec0-19d4-4e86-9df8-4ad0da893038.png">
<img width="658" alt="image" src="https://user-images.githubusercontent.com/74262887/212325783-9e25de27-01b9-4e44-bb9b-2df5ad9146fb.png">

**Comment by ntk97** [comment]
DB is restarting again & again, how to fix it ?
 not able to take backup for existing DB

**Comment by ntk97** [comment]
@azhavoro what happens if I skip back up and import data steps while upgrading the pg_db ?

**Comment by azhavoro** [comment]
@ntk97 it's impossible to run (and back up the database data with `pg_dumpall` tool) if the data version and database version dont match. First you need to run Pestgres v10, make a backup using the pg_dumpall tool, change the image version to 15, and restore the database.
