### ISSUE TITLE
Could not export CVAT skeleton keypoints to COCO keypoints 1.0

### ISSUE THREAD

**Issue by mikalbre** [opencv/cvat#5600]
I cannot export COCO keypoints 1.0 for the skeleton feature in CVAT.  For some tiny tasks, I was able to export in this particular format, but more often than not it gets stuck with the error message displayed.

When deleting this frame, the error message pops up for another frame.

<img width="371" alt="Skjermbilde 2023-01-18 kl  13 23 43" src="https://user-images.githubusercontent.com/43048448/213170558-4438f372-634a-4f25-ab5c-810aa0ed5d1e.png">

**Comment by bsekachev** [comment]
@zhiltsov-max  Do you have any ideas?

```
Traceback (most recent call last):
  File "/home/django/cvat/apps/dataset_manager/views.py", line 82, in export
    export_fn(db_instance.id, temp_file, dst_format,
  File "/home/django/cvat/apps/dataset_manager/task.py", line 725, in export_job
    job.export(f, exporter, host=server_url, save_images=save_images)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 570, in export
    exporter(dst_file, job_data, **options)
  File "/home/django/cvat/apps/dataset_manager/formats/registry.py", line 37, in __call__
    f_or_cls(*args, **kwargs)
  File "/home/django/cvat/apps/dataset_manager/formats/coco.py", line 46, in _export
    dataset.export(temp_dir, 'coco_person_keypoints', save_images=save_images,
  File "/opt/venv/lib/python3.8/site-packages/datumaro/util/scope.py", line 158, in wrapped_func
    ret_val = func(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/datumaro/components/dataset.py", line 1111, in export
    raise e.__cause__
datumaro.components.errors.AnnotationExportError: Failed to export item ('frame_000082', 'default')
[2023-01-19 15:31:14,643] ERROR cvat.server.task_70876: [cvat.apps.dataset_manager.views @ export]: exception occurred
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/datumaro/plugins/coco_format/converter.py", line 765, in apply
    task_conv.save_annotations(item)
  File "/opt/venv/lib/python3.8/site-packages/datumaro/plugins/coco_format/converter.py", line 388, in save_annotations
    elem.update(self.convert_points_object(skeleton))
  File "/opt/venv/lib/python3.8/site-packages/datumaro/plugins/coco_format/converter.py", line 418, in convert_points_object
    elements[self._point_label_to_position[element.label]] = element
IndexError: list assignment index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/django/cvat/apps/dataset_manager/views.py", line 82, in export
    export_fn(db_instance.id, temp_file, dst_format,
  File "/home/django/cvat/apps/dataset_manager/task.py", line 725, in export_job
    job.export(f, exporter, host=server_url, save_images=save_images)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 570, in export
    exporter(dst_file, job_data, **options)
  File "/home/django/cvat/apps/dataset_manager/formats/registry.py", line 37, in __call__
    f_or_cls(*args, **kwargs)
  File "/home/django/cvat/apps/dataset_manager/formats/coco.py", line 46, in _export
    dataset.export(temp_dir, 'coco_person_keypoints', save_images=save_images,
  File "/opt/venv/lib/python3.8/site-packages/datumaro/util/scope.py", line 158, in wrapped_func
    ret_val = func(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/datumaro/components/dataset.py", line 1111, in export
    raise e.__cause__
datumaro.components.errors.AnnotationExportError: Failed to export item ('frame_000082', 'default')
```

**Comment by bsekachev** [comment]
@mikalbre 

Need to investigate. At least exporting in CVAT for Video works.

**Comment by mikalbre** [comment]
@bsekachev 
I'm still having the export issue. Manage to export 39 frames (1 object) using COCO keypoints, but not when tryingto export 50+ frames. Have tried multiple projects and created new tasks to see if that would make a difference, but it was the same.
