### ISSUE TITLE
Shared folder tree checks not being adhered to

### ISSUE THREAD

**Issue by webtop** [opencv/cvat#5621]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

When using a shared folder where there may be some files that have compression issues, encoding issues, etc., I wait until the browser tells me what file is causing a PIL issue and I uncheck the checkbox for that file. However, rerunning the task still attempts to process the file. This isn't always the case, but does happen sometimes.

### Expected Behaviour
Unchecking the checkbox next to a file which PIL is unable to process, then clicking Submit, should rerun the task but exclude that file.

### Current Behaviour
Unchecking the checkbox next to a file name does not (always) remove the file from the queue process, and so the same file is constantly being queued and then failing.
Error: PIL.UnidentifiedImageError: cannot identify image file "/home/django/share/bourbon/baker's/30F7E9B8CDD03FE52CBE4106228550399E43C564.jpeg"

### Possible Solution
I'm confused why this isn't already a feature, but it would be nice if these failures were simply flagged, and at the end a report of the failures was shown. That way the task could finish processing and gives the user the chance to decide what to do. The shared folder I'm trying to process is 13G in size (dataset/categories/brands/images), so it's untenable for me to wait till a file fails, uncheck it and then rerun the task. Hence the idea ofd a report instead of just quitting the job.
On that note it's not your job to make sure my images are all valid, so I'll write a PIL script to pre-validate and report on errors.

### Steps to Reproduce (for bugs)

1. Create a shared path folder
2. Create a sub-structure in the form root->subfolder->subfolder->images, where you know some of the images are invalid
3. Create a task which uses the shared folder, and select all of the images (see attached image)
4. Run the task to create the queue job
5. When it fails, uncheck the checkbox next to the failed file 
6. Run the task again 

### Context
I have a dataset that contains 7 folders, each of those contain between 80 and 140 subfolders, and each of those contain approx. 150 images each. I'm looking for a solution that allows me to annotate that much data (>100k images). This will be the backend for a new mobile app my team is creating.

### Your Environment

- Git hash commit (`git log -1`): `2c4676ace32a68572b38205f002a98e93af917d0`
- Docker version `docker version` (e.g. Docker 17.0.05): Docker version 20.10.22, build 3a2c30b
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Linux
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat_worker_default` container</summary>
```
2023-01-23 22:48:22,404 DEBG 'rqworker_default_1' stderr output:
[2023-01-23 22:48:22,404] INFO cvat.server: create task #14

2023-01-23 22:48:22,405 DEBG 'rqworker_default_1' stderr output:
INFO:cvat.server:create task #14

2023-01-23 22:48:24,846 DEBG 'rqworker_default_1' stderr output:
DEBUG:rq.worker:Handling failed execution of job /api/tasks/14

2023-01-23 22:48:24,885 DEBG 'rqworker_default_1' stderr output:
ERROR:rq.worker:Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/rq/worker.py", line 936, in perform_job
    rv = job.perform()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 684, in perform
    self._result = self._execute()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 690, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/django/cvat/apps/engine/task.py", line 610, in _create_thread
    manifest.create()
  File "/home/django/utils/dataset_manifest/core.py", line 339, in wrapper
    func(self, *args,  **kwargs)
  File "/home/django/utils/dataset_manifest/core.py", line 605, in create
    self._write_core_part(manifest_file, obj, _tqdm)
  File "/home/django/utils/dataset_manifest/core.py", line 593, in _write_core_part
    for image_properties in iterable_obj:
  File "/home/django/utils/dataset_manifest/core.py", line 196, in __iter__
    img = Image.open(image, mode='r')
  File "/opt/venv/lib/python3.8/site-packages/PIL/Image.py", line 3186, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file "/home/django/share/bourbon/baker's/5F168A392BEFDCCA758CB53F03B91F3BB4768592.jpeg"
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/rq/worker.py", line 936, in perform_job
    rv = job.perform()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 684, in perform
    self._result = self._execute()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 690, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/django/cvat/apps/engine/task.py", line 610, in _create_thread
    manifest.create()
  File "/home/django/utils/dataset_manifest/core.py", line 339, in wrapper
    func(self, *args,  **kwargs)
  File "/home/django/utils/dataset_manifest/core.py", line 605, in create
    self._write_core_part(manifest_file, obj, _tqdm)
  File "/home/django/utils/dataset_manifest/core.py", line 593, in _write_core_part
    for image_properties in iterable_obj:
  File "/home/django/utils/dataset_manifest/core.py", line 196, in __iter__
    img = Image.open(image, mode='r')
  File "/opt/venv/lib/python3.8/site-packages/PIL/Image.py", line 3186, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file "/home/django/share/bourbon/baker's/5F168A392BEFDCCA758CB53F03B91F3BB4768592.jpeg"

2023-01-23 22:48:24,886 DEBG 'rqworker_default_1' stderr output:
DEBUG:rq.worker:Invoking exception handler <function rq_handler at 0x7fd16dd415e0>
```
    </details>

Showing outer folder structure

![Screenshot 2023-01-23 at 1 35 05 PM](https://user-images.githubusercontent.com/707652/214173597-3e96df75-94e7-4a5d-a2b0-36984ba86844.png)

Showing inner folder structure

![Screenshot 2023-01-23 at 2 27 55 PM](https://user-images.githubusercontent.com/707652/214173691-4d5fa2aa-accc-4a68-b3d9-171646a5090d.png)

Showing that the failing file has already been uncheck, yet it was still processed

![Screenshot 2023-01-23 at 2 48 58 PM](https://user-images.githubusercontent.com/707652/214173710-a1744fa8-fb57-41d1-a47c-1778ebda70de.png)

On the last image, I had checked and unchecked that file multiple times (no console errors) but it was still included in the job.

Thanks - love the software

**Comment by webtop** [comment]
This simple script reported my failing files in ~30sec, so after I've removed them I'll try again

```
import os
import pathlib
from PIL import Image, UnidentifiedImageError

walk_dir = '/Users/paul.allsopp/Projects/beverage_classifier/dataset'
img = ''

for root, subdir, files in os.walk(walk_dir):
    for filename in files:
        file_path = os.path.join(root, filename)
        if pathlib.Path(file_path).suffix in ['.jpg', '.jpeg', '.png']:
            try:
                img = Image.open(file_path, 'r')
            except UnidentifiedImageError as err:
                print("Failed to open " + file_path + "\n")
            finally:
                img.close()

print("We are done!")

```

**Comment by SpecLad** [comment]
I couldn't reproduce this, on either 2.3.0 or the current development version. Is this still an issue for you?
