### ISSUE TITLE
Sorry, but this job was not found

### ISSUE THREAD

**Issue by danielserrao** [opencv/cvat#5624]
### My actions before raising this issue
Searched for this error on this repo issues section and on documentation but couldn't find any relevant documentation, but maybe I'm missing something since this is my first time using CVAT.

Recently I deployed CVAT into an AWS EC2 instance which is now being tested by multiple users. I was on the task page at `http://<cvat-host>:<port>/tasks/16` and clicked on `Job #16` link and wen't to page `http://<cvat-host>:<port>/tasks/16/jobs/16`
but got the error `Sorry, but this job was not found`.

### Expected Behaviour
Expected the job page to appear without any errors.

### Current Behaviour

When checking the logs on the cvat_server container I see the following logs:

```
2023-01-24 21:46:01,462 DEBG 'runserver' stderr output:
[Tue Jan 24 21:46:01.462250 2023] [wsgi:error] [pid 51:tid 139836499056384] [remote 172.18.0.5:48616] INFO:cvat.client:{"client_id":750709,"name":"Send user activity","time":"2023-01-24T21:45:57.949000Z","payload":{"working_time":7238},"is_active":true,"username":"daniel"}

2023-01-24 21:46:06,798 DEBG 'runserver' stderr output:
[Tue Jan 24 21:46:06.798270 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688] [2023-01-24 21:46:06,797] ERROR django.request: Internal Server Error: /api/jobs/16/annotations
[Tue Jan 24 21:46:06.798301 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688] Traceback (most recent call last):
[Tue Jan 24 21:46:06.798306 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
[Tue Jan 24 21:46:06.798310 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]     response = get_response(request)
[Tue Jan 24 21:46:06.798313 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
[Tue Jan 24 21:46:06.798316 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Tue Jan 24 21:46:06.798320 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]   File "/opt/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
[Tue Jan 24 21:46:06.798323 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]     return view_func(*args, **kwargs)
[Tue Jan 24 21:46:06.798326 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
[Tue Jan 24 21:46:06.798329 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]     return self.dispatch(request, *args, **kwargs)
[Tue Jan 24 21:46:06.798332 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
[Tue Jan 24 21:46:06.798336 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]     response = self.handle_exception(exc)
[Tue Jan 24 21:46:06.798339 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
[Tue Jan 24 21:46:06.798342 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]     self.raise_uncaught_exception(exc)
[Tue Jan 24 21:46:06.798345 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
[Tue Jan 24 21:46:06.798348 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]     raise exc
[Tue Jan 24 21:46:06.798351 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
[Tue Jan 24 21:46:06.798354 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]     response = handler(request, *args, **kwargs)
[Tue Jan 24 21:46:06.798357 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]   File "/home/django/cvat/apps/engine/views.py", line 1525, in annotations
[Tue Jan 24 21:46:06.798360 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]     return self.export_annotations(
[Tue Jan 24 21:46:06.798363 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]   File "/home/django/cvat/apps/engine/mixins.py", line 279, in export_annotations
[Tue Jan 24 21:46:06.798366 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]     data = get_data(pk)
[Tue Jan 24 21:46:06.798369 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]   File "/home/django/cvat/apps/profiler.py", line 11, in wrapped
[Tue Jan 24 21:46:06.798371 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]     return f(*args, **kwargs)
[Tue Jan 24 21:46:06.798374 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]   File "/usr/lib/python3.8/contextlib.py", line 75, in inner
[Tue Jan 24 21:46:06.798381 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]     return func(*args, **kwds)
[Tue Jan 24 21:46:06.798384 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]   File "/home/django/cvat/apps/dataset_manager/task.py", line 680, in get_job_data
[Tue Jan 24 21:46:06.798387 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]     annotation.init_from_db()
[Tue Jan 24 21:46:06.798390 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]   File "/home/django/cvat/apps/dataset_manager/task.py", line 556, in init_from_db

2023-01-24 21:46:06,798 DEBG 'runserver' stderr output:
[Tue Jan 24 21:46:06.798393 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]     self._init_shapes_from_db()
[Tue Jan 24 21:46:06.798398 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]   File "/home/django/cvat/apps/dataset_manager/task.py", line 442, in _init_shapes_from_db
[Tue Jan 24 21:46:06.798401 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]     self.db_attributes[db_shape.label_id]["all"].values())
[Tue Jan 24 21:46:06.798404 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688] KeyError: 540
[Tue Jan 24 21:46:06.798549 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688] ERROR:django.request:Internal Server Error: /api/jobs/16/annotations
[Tue Jan 24 21:46:06.798556 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688] Traceback (most recent call last):
[Tue Jan 24 21:46:06.798559 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
[Tue Jan 24 21:46:06.798562 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]     response = get_response(request)
[Tue Jan 24 21:46:06.798565 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
[Tue Jan 24 21:46:06.798568 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Tue Jan 24 21:46:06.798571 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]   File "/opt/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
[Tue Jan 24 21:46:06.798574 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]     return view_func(*args, **kwargs)
[Tue Jan 24 21:46:06.798576 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
[Tue Jan 24 21:46:06.798579 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]     return self.dispatch(request, *args, **kwargs)
[Tue Jan 24 21:46:06.798582 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
[Tue Jan 24 21:46:06.798585 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]     response = self.handle_exception(exc)
[Tue Jan 24 21:46:06.798588 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
[Tue Jan 24 21:46:06.798591 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]     self.raise_uncaught_exception(exc)
[Tue Jan 24 21:46:06.798593 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
[Tue Jan 24 21:46:06.798596 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]     raise exc
[Tue Jan 24 21:46:06.798599 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
[Tue Jan 24 21:46:06.798602 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]     response = handler(request, *args, **kwargs)
[Tue Jan 24 21:46:06.798605 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]   File "/home/django/cvat/apps/engine/views.py", line 1525, in annotations
[Tue Jan 24 21:46:06.798608 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]     return self.export_annotations(
[Tue Jan 24 21:46:06.798610 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]   File "/home/django/cvat/apps/engine/mixins.py", line 279, in export_annotations
[Tue Jan 24 21:46:06.798615 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]     data = get_data(pk)
[Tue Jan 24 21:46:06.798617 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]   File "/home/django/cvat/apps/profiler.py", line 11, in wrapped
[Tue Jan 24 21:46:06.798620 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]     return f(*args, **kwargs)
[Tue Jan 24 21:46:06.798623 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]   File "/usr/lib/python3.8/contextlib.py", line 75, in inner
[Tue Jan 24 21:46:06.798626 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]     return func(*args, **kwds)
[Tue Jan 24 21:46:06.798629 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]   File "/home/django/cvat/apps/dataset_manager/task.py", line 680, in get_job_data
[Tue Jan 24 21:46:06.798631 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]     annotation.init_from_db()
[Tue Jan 24 21:46:06.798634 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]   File "/home/django/cvat/apps/dataset_manager/task.py", line 556, in init_from_db
[Tue Jan 24 21:46:06.798637 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]     self._init_shapes_from_db()
[Tue Jan 24 21:46:06.798640 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]   File "/home/django/cvat/apps/dataset_manager/task.py", line 442, in _init_shapes_from_db
[Tue Jan 24 21:46:06.798643 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688]     self.db_attributes[db_shape.label_id]["all"].values())
[Tue Jan 24 21:46:06.798645 2023] [wsgi:error] [pid 51:tid 139836490663680] [remote 172.18.0.5:51688] KeyError: 540
```

### Your Environment

- Git hash commit (`git log -1`): 2dc741238beae0e49951920267461a236f646685
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.22, build 3a2c30b
- Are you using Docker Swarm or Kubernetes? None. Running inside EC2 instance.
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 22.04.1 LTS (Followed instructions at https://opencv.github.io/cvat/docs/administration/basics/installation/#ubuntu-1804-x86_64amd64)

Any help on this one would be really appreciated. Thanks.

**Comment by danielserrao** [comment]
I just confirmed that the images of this job didn't disappear and exist under folder `/home/django/data/16/raw` so the data didn't miss and I'm still trying to find the root cause of this issue.

**Comment by bsekachev** [comment]
Closed as outdated
