### ISSUE TITLE
There was a problem following the installation instructions

### ISSUE THREAD

**Issue by qinwang1023** [opencv/cvat#5641]
### My actions before raising this issue
- [x] Read/searched [the docs](https://opencv.github.io/cvat/docs/administration/basics/installation/#ubuntu-1804-x86_64amd64)

### Steps to reproduce

When I followed the installation guide, everything worked fine. But when I get to the create super admin step it fails.

<img width="839" alt="create" src="https://user-images.githubusercontent.com/84695031/215433391-0733e420-f6c2-4ae4-bd20-9c2e8a1016a0.png">

#### Error

```
~/cvat$ docker exec -it cvat_server bash -ic 'python3 ~/manage.py createsuperuser'

Traceback (most recent call last): 
File "/opt/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection self.connect() 
File "/opt/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner return func(*args, **kwargs) 
File "/opt/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect self.connection = self.get_new_connection(conn_params) 
File "/opt/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner return func(*args, **kwargs)
File "/opt/venv/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection connection = Database.connect(**conn_params) File "/opt/venv/lib/python3.8/site-packages/psycopg2/init.py", line 127, in connect conn = _connect(dsn, connection_factory=connection_factory, **kwasync) 
psycopg2.OperationalError: could not translate host name "cvat_db" to address: Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last): File "/home/django/manage.py", line 21, in execute_from_command_line(sys.argv) 
File "/opt/venv/lib/python3.8/site-packages/django/core/management/init.py", line 419, in execute_from_command_line utility.execute() File "/opt/venv/lib/python3.8/site-packages/django/core/management/init.py", line 413, in execute self.fetch_command(subcommand).run_from_argv(self.argv) 
File "/opt/venv/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv self.execute(*args, **cmd_options)
File "/opt/venv/lib/python3.8/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 79, in execute return super().execute(*args, **options) 
File "/opt/venv/lib/python3.8/site-packages/django/core/management/base.py", line 397, in execute self.check_migrations() 
File "/opt/venv/lib/python3.8/site-packages/django/core/management/base.py", line 486, in check_migrations executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS]) 
File "/opt/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 18, in init self.loader = MigrationLoader(self.connection) 
File "/opt/venv/lib/python3.8/site-packages/django/db/migrations/loader.py", line 53, in init self.build_graph() 
File "/opt/venv/lib/python3.8/site-packages/django/db/migrations/loader.py", line 220, in build_graph self.applied_migrations = recorder.applied_migrations() 
File "/opt/venv/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 77, in applied_migrations if self.has_table(): File "/opt/venv/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 55, in has_table with self.connection.cursor() as cursor: File "/opt/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner return func(*args, **kwargs) 
File "/opt/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 259, in cursor return self._cursor() 
File "/opt/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 235, in _cursor self.ensure_connection() 
File "/opt/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner return func(*args, **kwargs) 
File "/opt/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection self.connect() 
File "/opt/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in exit raise dj_exc_value.with_traceback(traceback) from exc_value File "/opt/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection self.connect() File "/opt/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner return func(*args, **kwargs) File "/opt/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect self.connection = self.get_new_connection(conn_params) File "/opt/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner return func(*args, **kwargs) File "/opt/venv/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection connection = Database.connect(**conn_params) 
File "/opt/venv/lib/python3.8/site-packages/psycopg2/init.py", line 127, in connect conn = _connect(dsn, connection_factory=connection_factory, **kwasync) 
django.db.utils.OperationalError: could not translate host name "cvat_db" to address: Temporary failure in name resolution
```

And I checked the service process and found that cvat_db is not enabled properly:

```
~/cvat$ sudo docker ps -a | grep cvat 
f90f8d90ceca postgres:15-alpine "docker-entrypoint.s…" 8 minutes ago Restarting (1) 44 seconds ago 
cvat_db 
da9845a98192 cvat/ui:dev "/docker-entrypoint.…" 21 minutes ago Up 21 minutes 80/tcp 
cvat_ui 
cee0024ad7e1 cvat/server:dev "/usr/bin/supervisor…" 21 minutes ago Up 21 minutes 8080/tcp 
cvat_worker_annotation 
976b0000ca25 cvat/server:dev "/usr/bin/supervisor…" 21 minutes ago Up 21 minutes 8080/tcp 
cvat_worker_import 
303a994102aa cvat/server:dev "/usr/bin/supervisor…" 21 minutes ago Up 21 minutes 8080/tcp 
cvat_server 
8c00ce976e21 cvat/server:dev "/usr/bin/supervisor…" 21 minutes ago Up 21 minutes 8080/tcp 
cvat_worker_webhooks 
51cb5622695 cvat/server:dev "/usr/bin/supervisor…" 21 minutes ago Up 21 minutes 8080/tcp 
cvat_utils 
018373cd6b37 cvat/server:dev "/usr/bin/supervisor…" 21 minutes ago Up 21 minutes 8080/tcp 
cvat_worker_export 
f7e0030d68ea redis:4.0-alpine "docker-entrypoint.s…" 21 minutes ago Up 21 minutes 6379/tcp 
cvat_redis 
bc468fc55a0c openpolicyagent/opa:0.45.0-rootless "/opa run --server -…" 21 minutes ago Up 21 minutes 
cvat_opa
```

#### PS
`Ubuntu version`: 20.04.4 LTS

I don't know how to solve this problem, I haven't done anything to modify docker-compose.yml file. Along the way, I installed them in strict order.

**Comment by qinwang1023** [comment]
And when I use the `docker logs --details f90f8d90ceca` , it prints:
```
FATAL: database files are incompatible with server
DETAIL: The data directory was initialized by PostgreSQL version 10, which is not compatible with this version 15.1
```

I tried to reformulate the cvat version according to the instructions in the documentation.
`CVAT_VERSION=(v2.3.0 or v2.2.0) docker compose up -d`
 It has the same problem, I don't know if it is the version I chose, but currently these are stable versions...

**Comment by azhavoro** [comment]
CVAT_VERSION doesn't affect version of PostgreSQL version https://github.com/opencv/cvat/blob/develop/docker-compose.yml#L8, so you need to use latest stable 10.x version of postgres or upgrade your database data as described here
https://opencv.github.io/cvat/docs/administration/advanced/upgrade_guide/#how-to-upgrade-postgresql-database-base-image

**Comment by qinwang1023** [comment]
When I tried to enter the ip address :8080 on another machine, the browser kept asking me, and then said I could not access the site.

**Comment by qinwang1023** [comment]
I'm sorry, this is caused by my internal server problem, which I have solved. Thanks again for your reply.

**Comment by iwasinnam** [comment]
@qinwang1023 I am facing the same problem. Can you provide some insight?

**Comment by qinwang1023** [comment]
> @qinwang1023 I am facing the same problem. Can you provide some insight?
Which the same problem ur facing?
a. Db error? If yes, just upgrade the database version according to the cvat manual or choose a lower stable version.
b. Not an access error? If yes, first make sure that u can access :8080 in the machine where cvat is deployed, and then check the ip set to ensure that it is an accessible LAN ip.

**Comment by qinwang1023** [comment]
> @qinwang1023 I am facing the same problem. Can you provide some insight?

Which the same problem ur facing?
a. Db error? If yes, just upgrade the database version according to the cvat manual or choose a lower stable version.
b. Not an access error? If yes, first make sure that u can access :8080 in the machine where cvat is deployed, and then check the ip set to ensure that it is an accessible LAN ip.
