### ISSUE TITLE
CVAT silently stops working when the disk usage is above 90 %

### ISSUE THREAD

**Issue by jf99** [opencv/cvat#5724]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation). However, the link from this issue template is broken.
- [x] Searched [past issues](/issues)
  By the way, https://github.com/opencv/cvat/issues/5449#issuecomment-1348394380 did not work for me.

CVAT silently stops working when the disk usage is above 90 %.

### Steps to Reproduce (for bugs)
1. Upload new data to CVAT until it occupies more than 90 % of the disk space.

### Expected Behaviour
It is good that CVAT detects if the disk is almost full, so that one can react, before 0 Bytes are left. However, CVAT should tell the user what is wrong through the web-interface. Also, it should not be possible to upload any new data when the disk usage is above the threshold – again, tell the user why his uploads are being rejected.

### Current Behaviour
A user can upload data even if less than 10 % of the disk are free. He does not recognize until he logs out from CVAT and tries to re-login. Not only is he then confronted with an unhelpful error message:
![cvat-error](https://user-images.githubusercontent.com/7962377/219625608-06a3cdc5-2664-4bda-bf49-ed9c9948fef5.png)
But also, the user has no chance to fix the problem, as he can no longer log in.

### Possible Solution
Prevent the user from uploading too much and tell him what's the problem.

### Context
I just wasted two hours on that and finally solved it by manually deleting files from CVAT's data directory.

### Your Environment
- Git hash commit (`git log -1`): v2.3.0 plus some minor (unrelated) modifications
- Docker version `docker version` (e.g. Docker 17.0.05): 23.0.1
- Are you using Docker Swarm or Kubernetes? No.
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 18.04.6 LTS

**Comment by rogvidarge** [comment]
Had the same issue. Was trying all sorts of fixes, but the issue was simply that I had 94% disk utilization.

**Comment by Meriipu** [comment]
wow I had a fresh install without any data and 120GB of free space (even if it is at 90-92%) and I had no idea why it was frozen at the spinning loading-page

the health check is called a warning so it did not indicate to me it is a fatal error
```
cvat_server             | 2023-02-21 23:59:12,622 DEBG 'runserver' stderr output:
cvat_server             | [Tue Feb 21 23:59:12.622412 2023] [wsgi:error] [pid 615:tid 139865173767936]     raise ServiceWarning(
cvat_server             | 
cvat_server             | 2023-02-21 23:59:12,624 DEBG 'runserver' stderr output:
cvat_server             | [Tue Feb 21 23:59:12.624603 2023] [wsgi:error] [pid 615:tid 139865173767936] health_check.exceptions.ServiceWarning: warning: 3aa2352dfb0f 90.7% disk usage exceeds 90%
```

though it later prints that an error was encountered (just not specifically what the error is or that the error is in fact the warning from above)
```
cvat_server             | [Tue Feb 21 23:59:12.644760 2023] [wsgi:error] [pid 615:tid 139869211059968] [remote 172.18.0.4:44710] [2023-02-21 23:59:12,644] ERROR django.request: Internal Server Error: /api/server/health/
```

**Comment by kbegiedza** [comment]
Just hit this issue with CVAT: 2.4.0
Mounted disk usage is ~25%.
![image](https://github.com/opencv/cvat/assets/8686134/c13a8138-b572-4e6d-be84-39dd025d7b08)

@nmanovic I think it's critical bug

**Comment by kbegiedza** [comment]
More context:
We're using k8s to host CVAT and using pvc and longhorn.
I'm afraid that CVAT is fetching disk size from host's `overlay` instead of mounted volumes.  
![image](https://github.com/opencv/cvat/assets/8686134/fa929795-9937-4153-8d31-dce19c59190c)

**Comment by JosephKL-Chan** [comment]
My disk usage is just 36%. When I uploaded my own model to as an auto-annotation model, I got the same issue.

**Comment by josauder** [comment]
Any update on this isssue? How can I resolve this without a new CVAT image?
I get the same error:
```ERROR:health-check:warning: d63313d5d360 92.3% disk usage exceeds 90%
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/health_check/backends.py", line 30, in run_check
    self.check_status()
  File "/opt/venv/lib/python3.10/site-packages/health_check/contrib/psutil/backends.py", line 21, in check_status
    raise ServiceWarning(
health_check.exceptions.ServiceWarning: warning: d63313d5d360 92.3% disk usage exceeds 90%```

This is even though `df -h` shows me a 71% usage with 550GB of free space.

**Comment by sezarxray** [comment]
I think this is a absolute bug. I just want run cvat. why 93.3% disk usage exceeds 90% ? Is 1TB of 10 TB not enough???

**Comment by bsekachev** [comment]
@azhavoro Should we throw  health check error if free disk space is less than 10%, but still many gigabytes?

**Comment by azhavoro** [comment]
For now, I think will be better to disable this check in the public repo, because on some hardware configurations it definitely gives false positives. Free disk space monitoring is the user's responsibility, not CVAT.

**Comment by siddagra** [comment]
Sadly it seems the main repo has not merged this yet? It is also a rather stupid check since one could have a 10tb hard drive with a full terabyte empty and it would still just not let you use the website at all.

**Comment by c0d3runn3r** [comment]
I just ran into this issue as well.   

#### **Analysis**
- The `health_check` app (specifically `health_check.contrib.psutil`) in CVAT raises a `ServiceWarning` when disk usage exceeds 90%.
- CVAT’s `/api/server/health/` endpoint turned this warning into a `500 Internal Server Error`, which broke the frontend (`cvat_ui`) with the "Cannot connect to the server" message.

CVAT’s API seems to treat any exception from the health check (including `ServiceWarning`) as a fatal error, resulting in a `500`. It should probably instead return a `200` or `503` with a JSON payload indicating the warning (e.g., `{"status": "warning", "message": "disk usage at 91.6%"}`).
 

Logs from the cvat_server (e.g. `docker compose logs cvat_server --since 5m`):
```
cvat_server  | 2025-03-18 05:30:21,506 DEBG 'uvicorn-0' stderr output:
cvat_server  | [2025-03-18 05:30:21,506] ERROR django.request: Internal Server Error: /api/server/health/
cvat_server  | 
cvat_server  | 2025-03-18 05:30:21,506 DEBG 'uvicorn-0' stdout output:
cvat_server  | INFO:     100.64.26.8:0 - "GET /api/server/health/?format=json&org= HTTP/1.0" 500 Internal Server Error
cvat_server  | 
cvat_server  | 2025-03-18 05:30:25,487 DEBG 'uvicorn-1' stderr output:
cvat_server  | [2025-03-18 05:30:25,486] ERROR health-check: warning: 268273a3f8c5 91.6% disk usage exceeds 90%
cvat_server  | Traceback (most recent call last):
cvat_server  |   File "/opt/venv/lib/python3.10/site-packages/health_check/backends.py", line 30, in run_check
cvat_server  |     self.check_status()
cvat_server  |   File "/opt/venv/lib/python3.10/site-packages/health_check/contrib/psutil/backends.py", line 21, in check_status
cvat_server  |     raise ServiceWarning(
cvat_server  | health_check.exceptions.ServiceWarning: warning: 268273a3f8c5 91.6% disk usage exceeds 90%
```
