### ISSUE TITLE
django.db.utils.ProgrammingError: relation "engine_jobcommit" does not exist

### ISSUE THREAD

**Issue by saifkhichi96** [opencv/cvat#5774]
I followed these [installation instructions](https://opencv.github.io/cvat/docs/administration/basics/installation/), and then set up `nuctl` for the semi-automatic annotation. I used the following command to start CVAT:
```
docker compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml up -d
```

I can create a new project, but when I try to add a new task inside the project, I keep getting this error:
> Could not create the task on the server. django.db.utils.ProgrammingError: relation "engine_jobcommit" does not exist
> LINE 1: INSERT INTO "engine_jobcommit" ("scope", "owner_id", "timest...

The `docker logs cvat_server` returns the following:

```
2023-02-27 10:16:10,360 INFO RPC interface 'supervisor' initialized
2023-02-27 10:16:10,360 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2023-02-27 10:16:10,360 INFO supervisord started with pid 1
2023-02-27 10:16:11,363 INFO spawned: 'clamav_update' with pid 7
2023-02-27 10:16:11,365 INFO spawned: 'runserver' with pid 8
2023-02-27 10:16:11,373 DEBG fd 7 closed, stopped monitoring <POutputDispatcher at 140331716764096 for <Subprocess at 140331716764192 with name clamav_update in state STARTING> (stdout)>
2023-02-27 10:16:11,373 DEBG fd 9 closed, stopped monitoring <POutputDispatcher at 140331716550960 for <Subprocess at 140331716764192 with name clamav_update in state STARTING> (stderr)>
2023-02-27 10:16:11,373 INFO exited: clamav_update (exit status 0; not expected)
2023-02-27 10:16:11,374 DEBG received SIGCHLD indicating a child quit
2023-02-27 10:16:11,377 DEBG 'runserver' stderr output:
wait-for-it.sh: waiting for cvat_db:5432 without a timeout

2023-02-27 10:16:11,386 DEBG 'runserver' stderr output:
wait-for-it.sh: cvat_db:5432 is available after 0 seconds

2023-02-27 10:16:11,389 DEBG 'runserver' stderr output:
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell

2023-02-27 10:16:12,391 INFO spawned: 'clamav_update' with pid 21
2023-02-27 10:16:12,392 INFO success: runserver entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-02-27 10:16:12,397 DEBG fd 11 closed, stopped monitoring <POutputDispatcher at 140331716550816 for <Subprocess at 140331716764192 with name clamav_update in state STARTING> (stderr)>
2023-02-27 10:16:12,397 DEBG fd 7 closed, stopped monitoring <POutputDispatcher at 140331716764096 for <Subprocess at 140331716764192 with name clamav_update in state STARTING> (stdout)>
2023-02-27 10:16:13,399 INFO success: clamav_update entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-02-27 10:16:13,399 INFO exited: clamav_update (exit status 0; expected)
2023-02-27 10:16:13,399 DEBG received SIGCHLD indicating a child quit
2023-02-27 10:16:22,211 DEBG 'runserver' stdout output:
Operations to perform:
  Apply all migrations: account, admin, auth, authtoken, contenttypes, dataset_repo, db, engine, organizations, sessions, sites, socialaccount, webhooks
Running migrations:
  No migrations to apply.

2023-02-27 10:16:24,158 DEBG 'runserver' stdout output:

164 static files copied to '/home/django/static'.

2023-02-27 10:16:30,920 DEBG 'runserver' stdout output:
Successfully ran command.

2023-02-27 10:16:30,925 DEBG 'runserver' stdout output:
Server URL         : http://localhost:8080/
Server Root        : /tmp/cvat-server
Server Conf        : /tmp/cvat-server/httpd.conf
Error Log File     : /dev/stderr (INFO)
Request Capacity   : 5 (1 process * 5 threads)
Request Timeout    : 60 (seconds)
Startup Timeout    : 15 (seconds)
Queue Backlog      : 100 (connections)
Queue Timeout      : 45 (seconds)
Server Capacity    : 20 (event/worker), 20 (prefork)
Server Backlog     : 500 (connections)
Locale Setting     : C.UTF-8

2023-02-27 10:16:31,021 DEBG 'runserver' stderr output:
[Mon Feb 27 10:16:31.021077 2023] [mpm_event:notice] [pid 8:tid 139700479573056] AH00489: Apache/2.4.41 (Ubuntu) mod_wsgi/4.7.1 Python/3.8 configured -- resuming normal operations

2023-02-27 10:16:31,021 DEBG 'runserver' stderr output:
[Mon Feb 27 10:16:31.021346 2023] [mpm_event:info] [pid 8:tid 139700479573056] AH00490: Server built: 2023-01-23T18:36:09
[Mon Feb 27 10:16:31.021360 2023] [core:notice] [pid 8:tid 139700479573056] AH00094: Command line: 'apache2 (mod_wsgi-express) -f /tmp/cvat-server/httpd.conf -D MOD_WSGI_MPM_ENABLE_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_WORKER_MODULE -D MOD_WSGI_MPM_EXISTS_PREFORK_MODULE -D FOREGROUND'

2023-02-27 10:16:31,023 DEBG 'runserver' stderr output:
[Mon Feb 27 10:16:31.023278 2023] [wsgi:info] [pid 103:tid 139700479573056] mod_wsgi (pid=103): Starting process 'localhost:8080' with threads=5.

2023-02-27 10:16:31,023 DEBG 'runserver' stderr output:
[Mon Feb 27 10:16:31.023854 2023] [wsgi:info] [pid 103:tid 139700479573056] mod_wsgi (pid=103): Python home /opt/venv.

2023-02-27 10:16:31,024 DEBG 'runserver' stderr output:
[Mon Feb 27 10:16:31.023930 2023] [wsgi:info] [pid 103:tid 139700479573056] mod_wsgi (pid=103): Initializing Python.

2023-02-27 10:16:31,061 DEBG 'runserver' stderr output:
[Mon Feb 27 10:16:31.061704 2023] [wsgi:info] [pid 103:tid 139700479573056] mod_wsgi (pid=103): Attach interpreter ''.

2023-02-27 10:16:31,067 DEBG 'runserver' stderr output:
[Mon Feb 27 10:16:31.067293 2023] [wsgi:info] [pid 103:tid 139700479573056] mod_wsgi (pid=103): Imported 'mod_wsgi'.

2023-02-27 10:16:31,067 DEBG 'runserver' stderr output:
[Mon Feb 27 10:16:31.067683 2023] [wsgi:info] [pid 103:tid 139700479573056] mod_wsgi (pid=103, process='localhost:8080', application=''): Loading Python script file '/tmp/cvat-server/handler.wsgi'.

2023-02-27 10:16:40,129 DEBG 'runserver' stderr output:
[Mon Feb 27 10:16:40.129225 2023] [wsgi:error] [pid 103:tid 139699641378560] ERROR:health-check:unknown error: 500 Server Error: Internal Server Error for url: http://opa:8181/health?bundles
[Mon Feb 27 10:16:40.129246 2023] [wsgi:error] [pid 103:tid 139699641378560] Traceback (most recent call last):
[Mon Feb 27 10:16:40.129250 2023] [wsgi:error] [pid 103:tid 139699641378560]   File "/home/django/cvat/apps/health/backends.py", line 19, in check_status
[Mon Feb 27 10:16:40.129254 2023] [wsgi:error] [pid 103:tid 139699641378560]     response.raise_for_status()
[Mon Feb 27 10:16:40.129257 2023] [wsgi:error] [pid 103:tid 139699641378560]   File "/opt/venv/lib/python3.8/site-packages/requests/models.py", line 953, in raise_for_status
[Mon Feb 27 10:16:40.129261 2023] [wsgi:error] [pid 103:tid 139699641378560]     raise HTTPError(http_error_msg, response=self)
[Mon Feb 27 10:16:40.129264 2023] [wsgi:error] [pid 103:tid 139699641378560] requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://opa:8181/health?bundles
[Mon Feb 27 10:16:40.129267 2023] [wsgi:error] [pid 103:tid 139699641378560] 
[Mon Feb 27 10:16:40.129271 2023] [wsgi:error] [pid 103:tid 139699641378560] During handling of the above exception, another exception occurred:
[Mon Feb 27 10:16:40.129274 2023] [wsgi:error] [pid 103:tid 139699641378560] 
[Mon Feb 27 10:16:40.129277 2023] [wsgi:error] [pid 103:tid 139699641378560] Traceback (most recent call last):
[Mon Feb 27 10:16:40.129281 2023] [wsgi:error] [pid 103:tid 139699641378560]   File "/opt/venv/lib/python3.8/site-packages/health_check/backends.py", line 30, in run_check
[Mon Feb 27 10:16:40.129284 2023] [wsgi:error] [pid 103:tid 139699641378560]     self.check_status()
[Mon Feb 27 10:16:40.129287 2023] [wsgi:error] [pid 103:tid 139699641378560]   File "/home/django/cvat/apps/health/backends.py", line 21, in check_status
[Mon Feb 27 10:16:40.129291 2023] [wsgi:error] [pid 103:tid 139699641378560]     raise HealthCheckException(str(e))
[Mon Feb 27 10:16:40.129294 2023] [wsgi:error] [pid 103:tid 139699641378560] health_check.exceptions.HealthCheckException: unknown error: 500 Server Error: Internal Server Error for url: http://opa:8181/health?bundles

2023-02-27 10:16:40,407 DEBG 'runserver' stderr output:
[Mon Feb 27 10:16:40.403295 2023] [wsgi:error] [pid 103:tid 139699803420416] [remote 172.23.0.3:45166] [2023-02-27 10:16:40,403] ERROR django.request: Internal Server Error: /api/server/health/

2023-02-27 10:16:40,408 DEBG 'runserver' stderr output:
[Mon Feb 27 10:16:40.407544 2023] [wsgi:error] [pid 103:tid 139699803420416] [remote 172.23.0.3:45166] ERROR:django.request:Internal Server Error: /api/server/health/

2023-02-27 10:16:43,167 DEBG 'runserver' stderr output:
[Mon Feb 27 10:16:43.162517 2023] [wsgi:error] [pid 103:tid 139699795027712] [remote 172.23.0.3:55678] [2023-02-27 10:16:43,162] WARNING django.request: Not Found: /api/user-agreements
[Mon Feb 27 10:16:43.162645 2023] [wsgi:error] [pid 103:tid 139699795027712] [remote 172.23.0.3:55678] WARNING:django.request:Not Found: /api/user-agreements
```

The `cvat_db` logs are as follows:

```
PostgreSQL Database directory appears to contain a database; Skipping initialization

2023-02-27 10:36:24.884 UTC [1] LOG:  starting PostgreSQL 15.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
2023-02-27 10:36:24.884 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-02-27 10:36:24.884 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2023-02-27 10:36:24.924 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-02-27 10:36:24.965 UTC [24] LOG:  database system was shut down at 2023-02-27 10:35:51 UTC
2023-02-27 10:36:24.988 UTC [1] LOG:  database system is ready to accept connections
2023-02-27 10:36:26.969 UTC [28] LOG:  incomplete startup packet
2023-02-27 10:37:19.902 UTC [64] ERROR:  relation "engine_jobcommit" does not exist at character 13
2023-02-27 10:37:19.902 UTC [64] STATEMENT:  INSERT INTO "engine_jobcommit" ("scope", "owner_id", "timestamp", "data", "job_id") VALUES ('create', 1, '2023-02-27T10:37:19.902387+00:00'::timestamptz, '{"stage": "annotation", "state": "new", "assignee": null}', 9) RETURNING "engine_jobcommit"."id"
```

And `docker ps` returns the following:

```
CONTAINER ID   IMAGE                                   COMMAND                  CREATED             STATUS                    PORTS                                                                                          NAMES
2136024068af   cvat/ui:dev                             "/docker-entrypoint.…"   16 minutes ago      Up 15 minutes             80/tcp                                                                                         cvat_ui
d31738e11120   cvat/server:dev                         "/usr/bin/supervisor…"   16 minutes ago      Up 15 minutes             8080/tcp, 0.0.0.0:9091->9091/tcp, :::9091->9091/tcp                                            cvat_worker_annotation
6403ca8dc004   cvat/server:dev                         "/usr/bin/supervisor…"   16 minutes ago      Up 15 minutes             8080/tcp, 0.0.0.0:9090->9090/tcp, :::9090->9090/tcp                                            cvat_server
e0e1859991f9   cvat/server:dev                         "/usr/bin/supervisor…"   16 minutes ago      Up 15 minutes             8080/tcp                                                                                       cvat_utils
325ce4a1ee20   cvat/server:dev                         "/usr/bin/supervisor…"   16 minutes ago      Up 15 minutes             8080/tcp, 0.0.0.0:9092->9092/tcp, :::9092->9092/tcp                                            cvat_worker_export
e15d182031d1   cvat/server:dev                         "/usr/bin/supervisor…"   16 minutes ago      Up 15 minutes             8080/tcp, 0.0.0.0:9093->9093/tcp, :::9093->9093/tcp                                            cvat_worker_import
34161e8ab5c8   cvat/server:dev                         "/usr/bin/supervisor…"   16 minutes ago      Up 15 minutes             8080/tcp                                                                                       cvat_worker_webhooks
b6d630ab8970   quay.io/nuclio/dashboard:1.8.14-amd64   "/docker-entrypoint.…"   16 minutes ago      Up 15 minutes (healthy)   80/tcp, 0.0.0.0:8070->8070/tcp, :::8070->8070/tcp                                              nuclio
4128cc98b2d1   openpolicyagent/opa:0.45.0-rootless     "/opa run --server -…"   16 minutes ago      Up 15 minutes             0.0.0.0:8181->8181/tcp, :::8181->8181/tcp                                                      cvat_opa
67abe9daeb58   redis:4.0-alpine                        "docker-entrypoint.s…"   16 minutes ago      Up 15 minutes             6379/tcp                                                                                       cvat_redis
a83fc2d92834   postgres:15-alpine                      "docker-entrypoint.s…"   16 minutes ago      Up 15 minutes             5432/tcp                                                                                       cvat_db
de5ce6597754   traefik:v2.9                            "/entrypoint.sh --pr…"   16 minutes ago      Up 15 minutes             0.0.0.0:8080->8080/tcp, :::8080->8080/tcp, 80/tcp, 0.0.0.0:8090->8090/tcp, :::8090->8090/tcp   traefik
1f9ef57d3a33   cvat/openvino.dextr:latest              "processor"              39 minutes ago      Up 39 minutes (healthy)   0.0.0.0:32768->8080/tcp, :::32768->8080/tcp                                                    nuclio-nuclio-openvino-dextr
0b3f0977869c   gcr.io/iguazio/alpine:3.15              "/bin/sh -c '/bin/sl…"   About an hour ago   Up About an hour                                                                                                         nuclio-local-storage-reader
```

**Comment by azhavoro** [comment]
This looks very strange, seems cvat codebase and database are inconsistent
Could you provide logs that contains traceback of the error from cvat_worker_import container as weel ?

**Comment by saifkhichi96** [comment]
They look something like this:

```
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "engine_jobcommit" does not exist
LINE 1: INSERT INTO "engine_jobcommit" ("scope", "owner_id", "timest...
                    ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/rq/worker.py", line 936, in perform_job
    rv = job.perform()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 684, in perform
    self._result = self._execute()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 690, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/django/cvat/apps/engine/task.py", line 723, in _create_thread
    _save_task_to_db(db_task, extractor)
  File "/home/django/cvat/apps/engine/task.py", line 121, in _save_task_to_db
    db_job.save()
  File "/home/django/cvat/apps/engine/models.py", line 499, in save
    db_commit.save()
  File "/opt/venv/lib/python3.8/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/opt/venv/lib/python3.8/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/opt/venv/lib/python3.8/site-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/opt/venv/lib/python3.8/site-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
  File "/opt/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/opt/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "engine_jobcommit" does not exist
LINE 1: INSERT INTO "engine_jobcommit" ("scope", "owner_id", "timest...
                    ^


2023-02-27 10:37:19,909 DEBG 'rqworker_import_0' stderr output:
DEBUG:rq.worker:Invoking exception handler <function rq_handler at 0x7f8f000fd940>

2023-02-27 10:37:19,917 DEBG 'rqworker_import_0' stderr output:
DEBUG:rq.worker:Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.

2023-02-27 10:37:19,917 DEBG 'rqworker_import_0' stderr output:
DEBUG:rq.worker:Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.

2023-02-27 10:37:19,917 DEBG 'rqworker_import_0' stderr output:
DEBUG:rq.worker:*** Listening on import...

2023-02-27 10:37:19,918 DEBG 'rqworker_import_0' stderr output:
DEBUG:rq.worker:Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.

2023-02-27 10:40:13,334 DEBG 'rqworker_import_1' stderr output:
INFO:rq.worker:import: cvat.apps.engine.task._create_thread(10, {'chunk_size': None, 'size': 0, 'image_quality': 70, 'start_frame': 0, 'sto...) (create:task.id10-by-admin)

2023-02-27 10:40:13,335 DEBG 'rqworker_import_1' stderr output:
DEBUG:rq.worker:Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.

2023-02-27 10:40:13,341 DEBG 'rqworker_import_1' stderr output:
DEBUG:rq.worker:Sent heartbeat to prevent worker timeout. Next one should arrive within 90 seconds.

2023-02-27 10:40:13,354 DEBG 'rqworker_import_1' stderr output:
[2023-02-27 10:40:13,354] INFO cvat.server: create task #10

2023-02-27 10:40:13,354 DEBG 'rqworker_import_1' stderr output:
INFO:cvat.server:create task #10

2023-02-27 10:40:13,368 DEBG 'rqworker_import_1' stderr output:
[2023-02-27 10:40:13,368] INFO cvat.server: Found frames 1 for Data #10

2023-02-27 10:40:13,368 DEBG 'rqworker_import_1' stderr output:
INFO:cvat.server:Found frames 1 for Data #10

2023-02-27 10:40:13,368 DEBG 'rqworker_import_1' stderr output:
[2023-02-27 10:40:13,368] INFO cvat.server: New segment for task #10: start_frame = 0,             stop_frame = 0

2023-02-27 10:40:13,368 DEBG 'rqworker_import_1' stderr output:
INFO:cvat.server:New segment for task #10: start_frame = 0,             stop_frame = 0

2023-02-27 10:40:13,376 DEBG 'rqworker_import_1' stderr output:
DEBUG:rq.worker:Handling failed execution of job create:task.id10-by-admin

2023-02-27 10:40:13,378 DEBG 'rqworker_import_1' stderr output:
ERROR:rq.worker:Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "engine_jobcommit" does not exist
LINE 1: INSERT INTO "engine_jobcommit" ("scope", "owner_id", "timest...
                    ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/rq/worker.py", line 936, in perform_job
    rv = job.perform()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 684, in perform
    self._result = self._execute()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 690, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/django/cvat/apps/engine/task.py", line 723, in _create_thread
    _save_task_to_db(db_task, extractor)
  File "/home/django/cvat/apps/engine/task.py", line 121, in _save_task_to_db
    db_job.save()
  File "/home/django/cvat/apps/engine/models.py", line 499, in save
    db_commit.save()
  File "/opt/venv/lib/python3.8/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/opt/venv/lib/python3.8/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/opt/venv/lib/python3.8/site-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/opt/venv/lib/python3.8/site-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
  File "/opt/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/opt/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "engine_jobcommit" does not exist
LINE 1: INSERT INTO "engine_jobcommit" ("scope", "owner_id", "timest...
```

**Comment by azhavoro** [comment]
```python
File "/home/django/cvat/apps/engine/models.py", line 499, in save
    db_commit.save()
```
Current develop branch doens't contain this code.
So, you run old containers with the new database schema
Try to update images with `docker compose pull` and after that run cvat as usual `docker compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml up -d`

**Comment by saifkhichi96** [comment]
Thanks, this fixed the problem for me.

I am actually using `docker compose -f docker-compose.yml` **`-f docker-compose.dev.yml`** `-f components/serverless/docker-compose.serverless.yml up -d --build` to bring up CVAT using the code in my own fork of this repository which has some changes, but my fork was not synced with the latest code from this repository, causing the mismatch that you mentioned.
