### ISSUE TITLE
UnicodeDecodeError when downloading annotations using CVAT API

### ISSUE THREAD

**Issue by emmeduz** [opencv/cvat#5779]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I wrote a script to automatically download completed tasks using CVAT API. However, when executing the script, an error occurs.
The issue is similar to this [gitter](https://matrix.to/#/!jFOmyyZSFzWLKAmcZn:gitter.im/$cpBVfnh4e1M5amxS4rq9ys7lOumOL_wHB6eo-iJmmUQ?via=gitter.im&via=matrix.org&via=hive-mind.network)

### Steps to Reproduce (for bugs)

1. use a remotely hosted CVAT application
2. create a task (my task is a video annotation task)
3. `pip install cvat_sdk` (latest version v2.3.0)
4. code to reproduce: https://gist.github.com/emmeduz/9f78c9d1bad6a951f09bc43ff1d97d08

### Expected Behaviour

The download starts with no issues

### Current Behaviour

when downloading annotations using `api_client.tasks_api.retrieve_annotations` I get the following error:

```
Traceback (most recent call last):
  File "download_completed_tasks.py", line 74, in <module>
    (data, response) = api_client.tasks_api.retrieve_annotations(
  File "C:\Users\user\Anaconda3\lib\site-packages\cvat_sdk\api_client\api\tasks_api.py", line 3534, in retrieve_annotations
    return self.retrieve_annotations_endpoint.call_with_http_info(**kwargs)
  File "C:\Users\user\Anaconda3\lib\site-packages\cvat_sdk\api_client\api_client.py", line 1052, in call_with_http_info
    return self.api_client.call_api(
  File "C:\Users\user\Anaconda3\lib\site-packages\cvat_sdk\api_client\api_client.py", line 495, in call_api
    return self.__call_api(**params)
  File "C:\Users\user\Anaconda3\lib\site-packages\cvat_sdk\api_client\api_client.py", line 280, in __call_api
    return_data = self.deserialize(
  File "C:\Users\user\Anaconda3\lib\site-packages\cvat_sdk\api_client\api_client.py", line 377, in deserialize
    response_data = response.data.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 10-11: invalid continuation byte
```

Furthermore, somethimes, by re-running the script, I also get:

```
Traceback (most recent call last):
  File "download_completed_tasks.py", line 74, in <module>
    (data, response) = api_client.tasks_api.retrieve_annotations(
  File "C:\Users\user\Anaconda3\lib\site-packages\cvat_sdk\api_client\api\tasks_api.py", line 3534, in retrieve_annotations
    return self.retrieve_annotations_endpoint.call_with_http_info(**kwargs)
  File "C:\Users\user\Anaconda3\lib\site-packages\cvat_sdk\api_client\api_client.py", line 1052, in call_with_http_info
    return self.api_client.call_api(
  File "C:\Users\user\Anaconda3\lib\site-packages\cvat_sdk\api_client\api_client.py", line 495, in call_api
    return self.__call_api(**params)
  File "C:\Users\user\Anaconda3\lib\site-packages\cvat_sdk\api_client\api_client.py", line 280, in __call_api
    return_data = self.deserialize(
  File "C:\Users\user\Anaconda3\lib\site-packages\cvat_sdk\api_client\api_client.py", line 387, in deserialize
    deserialized_data = validate_and_convert_types(
  File "C:\Users\user\Anaconda3\lib\site-packages\cvat_sdk\api_client\model_utils.py", line 1590, in validate_and_convert_types
    converted_instance = attempt_convert_item(
  File "C:\Users\user\Anaconda3\lib\site-packages\cvat_sdk\api_client\model_utils.py", line 1479, in attempt_convert_item
    raise conversion_exc
  File "C:\Users\user\Anaconda3\lib\site-packages\cvat_sdk\api_client\model_utils.py", line 1470, in attempt_convert_item
    return deserialize_model(input_value, valid_class,
  File "C:\Users\user\Anaconda3\lib\site-packages\cvat_sdk\api_client\model_utils.py", line 1386, in deserialize_model
    return model_class._new_from_openapi_data(model_data, **kw_args)
  File "C:\Users\user\Anaconda3\lib\site-packages\cvat_sdk\api_client\model_utils.py", line 51, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "C:\Users\user\Anaconda3\lib\site-packages\cvat_sdk\api_client\model_utils.py", line 355, in _new_from_openapi_data
    oneof_instance = get_oneof_instance(cls, model_kwargs, kwargs, model_arg=arg)
  File "C:\Users\user\Anaconda3\lib\site-packages\cvat_sdk\api_client\model_utils.py", line 1904, in get_oneof_instance
    raise ApiValueError(
cvat_sdk.api_client.exceptions.ApiValueError: Invalid inputs given to generate an instance of AnnotationsRead. Multiple oneOf schemas matched the inputs, but a max of one is allowed.
```

From a naive debugging, I noticed weird content in the variable "response.data" (api_client.py line 377), which is supposed to contain the json with all the annotations. Here's a snippet of the content:
`obj_train_data/frame_010917.txtPK\x01\x02\x14\x03\x14\x00\x00\x00\x00\x00\xf8{\\V\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1f\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa4\x81\x91\xfd\x03\x00`

### Possible Solution

The UnicodeDecodeError seems to occur when `action="download` is passed to the `retrieve_annotations` method.

### Context

I want to use a python script to download task annotations (specifically, only completed tasks updated after a certain date).
I am able to download an AnnotationRead object using API (https://my.cvat.host.com/api/tasks/30/annotations). The problem seems to be with the creation of the zip file client side.

### Your Environment

- Git hash commit (`git log -1`): CVAT release v2.3.0
- Operating System and version (e.g. Linux, Windows, MacOS): Windows and Linux (I also tested the script from Google Colab)
- Code example or link to GitHub repo or gist to reproduce problem: https://gist.github.com/emmeduz/9f78c9d1bad6a951f09bc43ff1d97d08
- Other diagnostic information / logs:
    <details>
    <summary>everything seems fine server side (no recent logs in any of the containers)</summary>
    </details>

**Comment by zhiltsov-max** [comment]
Hi, please use the `_parse_response=False` parameter for file downloads like [here](https://github.com/opencv/cvat/blob/develop/tests/python/rest_api/utils.py#L20-L34).

**Comment by emmeduz** [comment]
Thanks a lot for your reply. The error disappeared.
Can you also suggest the correct method to download annotations (without images) using the python SDK? (or pointing out the documentation for doing that?)

using the following lines nothing is downloaded. What am I missing?

```
(data, response) = api_client.tasks_api.retrieve_annotations(
                                                                    id=int(task['id']),
                                                                    action="download",
                                                                    _parse_response=False,
                                                                    format=args.export_format
                                                                    )
```

**Comment by GeorgePearse** [comment]
I always seem to get byte code when I try to download annotations with retrieve_annotations() (if I supply _parse_response=False) 

But then there's no way simple to convert it to json or a dictionary. Any tips or hints?

**Comment by GeorgePearse** [comment]
Hi @zhiltsov-max are there more instructions anywhere on how to do those 3 steps?

**Comment by amarzullo24** [comment]
Hi all,
I wrote an example script. It can't be used as it is, but I hope can help.

```
import os
import time
from pathlib import Path
from http import HTTPStatus
from urllib3 import HTTPResponse

from cvat_sdk.api_client import Configuration, ApiClient, exceptions
from cvat_sdk.api_client.api_client import Endpoint

def export_dataset(endpoint: Endpoint, file_name: Path, max_retries: int = 20, interval: float = 0.1, **kwargs) -> HTTPResponse:
    for _ in range(max_retries):
        (_, response) = endpoint.call_with_http_info(**kwargs, _parse_response=False)
        if response.status == HTTPStatus.CREATED:
            break
        if not response.status == HTTPStatus.ACCEPTED:
            raise Exception(f"response.status not {HTTPStatus.ACCEPTED}")
        time.sleep(interval)
    if not response.status == HTTPStatus.CREATED:
        raise Exception(f"response.status not {HTTPStatus.CREATED}")

    (_, response) = endpoint.call_with_http_info(**kwargs, action="download", _parse_response=False)
    
    if response.status == HTTPStatus.OK:
        save_zip(response, file_name)
        
    return response

# helper function
def save_zip(response, file_name, chunk_size=100):
    with open(f'{file_name}.zip', 'wb') as out:
        while True:
            data = response.read(chunk_size)
            if not data:
                break
            out.write(data)
    response.release_conn()

# helper function
def get_project_id_by_name(api_client: ApiClient, project_name: str, organization_name: str) -> int:
    """ Lists the available projects and returns the ID of the project with the given name """
    try:
        (project_data, response) = api_client.projects_api.list(org=organization_name)
        if response.status == 200:
            for project in project_data["results"]:
                if project["name"] == project_name:
                    return project["id"]
        raise exceptions.NotFoundError(f"Project {project_name} not found")
    except exceptions.ApiException as e:
        raise e

# Authenticate with CVAT
configuration = Configuration(host=CVAT_HOST, api_key={"tokenAuth": CVAT_TOKEN})

# create output directory
if not os.path.exists(args.export_dir):
    os.makedirs(args.export_dir)

with ApiClient(configuration) as api_client:
    try:
        # list all CVAT projects
        (data, response) = api_client.projects_api.list()
        if response.status == 200:
            project_id = get_project_id_by_name(api_client, args.project_name, args.organization_name)

            # retrieve all the tasks
            (data, response) = api_client.projects_api.list_tasks(id=project_id, org=args.organization_name, page_size=10000)

            # filter the response based on your need
            task_list = filter_response(data, filter_dict)

            paths = []
            for task in task_list:
                print(f"downloading task {task['id']}...")
                out_path = Path(args.export_dir, task.name)

                # https://github.com/opencv/cvat/issues/5779
                response = export_dataset(api_client.tasks_api.retrieve_annotations_endpoint, 
                                          id=int(task['id']), 
                                          file_name=out_path,
                                          format=args.export_format
                                          )
                status = response.status

                print("done.", status)
                paths.append(out_path)

            print("Download files located at", paths)

    except exceptions.ApiException as e:
        print("Exception when dowloading: %s\n" % e)
```
