### ISSUE TITLE
Unable import dataset / create project  from backup

### ISSUE THREAD

**Issue by IvanLunev** [opencv/cvat#5843]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. I backuped an existing project with annotation (Backup Project);
2. Created new project with different name;
3. Changed name of the project in the project.json in backup zip file to new one;
4. Tried to import dataset inside new project (Import Dataset);
5. Got error: 
datumaro.components.errors.DatasetNotFoundError: Failed to find dataset at '/home/django/data/projects/60/tmp/tmpt8tqjazv'

![image](https://user-images.githubusercontent.com/31960303/224656432-eee1096c-ab95-4702-b4b1-26b1cb32b4f3.png)

6. Then I tried to create project from backup (Create from backup);
7. And got the following error:
FileNotFoundError: [Errno 2] No such file or directory: '/home/django/share/manifest.jsonl'

![image](https://user-images.githubusercontent.com/31960303/224663515-fcbdafa2-31af-44d6-9abc-34d75377cabc.png)

### Expected Behaviour

Dataset imported, project created without errors.

### Current Behaviour

Got errors.

### Possible Solution

May be I don't understand correctly how to use "Import dataset" and "Create from dataset buttons".
Or updated docker-compose.yaml incorrectly, when was adding cvat_share volume (but it's working).

### Context

I am trying to migrate CVAT to another server. I have working 1.2.0 version on old one. I made backup of projects according to instructions (cvat_data.tar.gz and cvat_db.tar.gz). Then tried to run CVAT 1.2.0 according to instructions on the new server, but it didn't work. I ran the newest version 2.4.0 and added cvat_shared. Tried to add data from backup and it worked, but I got only one project fully working and other projects come with error, when I am trying to open a job:

![image](https://user-images.githubusercontent.com/31960303/224667709-faac73c9-0119-4ece-b044-fb8abb1cc37c.png)

So I made a backup of a project and got zip file with correct formats< data structure and annotations (according to the docs). Now I am trying to import the backup (for both projects: with correctly imported data and with error). 

### Your Environment

- Git hash commit (`git log -1`):
commit b9359479a5e48c72a962d93d83d343f52946be9c (HEAD -> develop, origin/develop, origin/HEAD)
Author: Anastasia Yasakova <yasakova_anastasiya@mail.ru>
Date:   Fri Mar 10 10:38:19 2023 +0200

    Fix test with adding skeleton (#5832)

- Docker version `docker version` (e.g. Docker 17.0.05): 23.0.1
- Operating System and version (e.g. Linux, Windows, MacOS): Linux Ubuntu 20.04
- Other diagnostic information / logs:
    <details>
    <summary> Logs from `cvat_worker_import` container </summary>

  2023-03-13 09:03:55,066 DEBG 'rqworker_import_0' stderr output:
  ERROR:rq.worker:Traceback (most recent call last):
    File "/opt/venv/lib/python3.8/site-packages/rq/worker.py", line 936, in perform_job
      rv = job.perform()
    File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 684, in perform
      self._result = self._execute()
    File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 690, in _execute
      return self.func(*self.args, **self.kwargs)
    File "/usr/lib/python3.8/contextlib.py", line 75, in inner
      return func(*args, **kwds)
    File "/home/django/cvat/apps/dataset_manager/project.py", line 174, in import_dataset_as_project
      project.import_dataset(f, importer, conv_mask_to_poly=conv_mask_to_poly)
    File "/home/django/cvat/apps/dataset_manager/project.py", line 154, in import_dataset
      importer(dataset_file, temp_dir, project_data, self.load_dataset_data, **options)
    File "/home/django/cvat/apps/dataset_manager/formats/registry.py", line 36, in __call__
      f_or_cls(*args, **kwargs)
    File "/home/django/cvat/apps/dataset_manager/formats/cvat.py", line 1442, in _import
      dataset = Dataset.import_from(temp_dir, 'cvat', env=dm_env)
    File "/opt/venv/lib/python3.8/site-packages/datumaro/components/dataset.py", line 1165, in import_from
      detected_sources = importer(path, **kwargs)
    File "/opt/venv/lib/python3.8/site-packages/datumaro/components/extractor.py", line 444, in __call__
      raise DatasetNotFoundError(path)
  datumaro.components.errors.DatasetNotFoundError: Failed to find dataset at '/home/django/data/projects/60/tmp/tmpt8tqjazv'
  Traceback (most recent call last):
    File "/opt/venv/lib/python3.8/site-packages/rq/worker.py", line 936, in perform_job
      rv = job.perform()
    File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 684, in perform
      self._result = self._execute()
    File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 690, in _execute
      return self.func(*self.args, **self.kwargs)
    File "/usr/lib/python3.8/contextlib.py", line 75, in inner
      return func(*args, **kwds)
    File "/home/django/cvat/apps/dataset_manager/project.py", line 174, in import_dataset_as_project
      project.import_dataset(f, importer, conv_mask_to_poly=conv_mask_to_poly)
    File "/home/django/cvat/apps/dataset_manager/project.py", line 154, in import_dataset
      importer(dataset_file, temp_dir, project_data, self.load_dataset_data, **options)
    File "/home/django/cvat/apps/dataset_manager/formats/registry.py", line 36, in __call__
      f_or_cls(*args, **kwargs)
    File "/home/django/cvat/apps/dataset_manager/formats/cvat.py", line 1442, in _import
      dataset = Dataset.import_from(temp_dir, 'cvat', env=dm_env)
    File "/opt/venv/lib/python3.8/site-packages/datumaro/components/dataset.py", line 1165, in import_from
      detected_sources = importer(path, **kwargs)
    File "/opt/venv/lib/python3.8/site-packages/datumaro/components/extractor.py", line 444, in __call__
      raise DatasetNotFoundError(path)
  datumaro.components.errors.DatasetNotFoundError: Failed to find dataset at '/home/django/data/projects/60/tmp/tmpt8tqjazv'

    </details>
    <details>
    <summary> Logs from `cvat_worker_import` container </summary>

    2023-03-13 09:38:00,227 DEBG 'rqworker_import_1' stderr output:
  ERROR:rq.worker:Traceback (most recent call last):
    File "/opt/venv/lib/python3.8/site-packages/rq/worker.py", line 936, in perform_job
      rv = job.perform()
    File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 684, in perform
      self._result = self._execute()
    File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 690, in _execute
      return self.func(*self.args, **self.kwargs)
    File "/usr/lib/python3.8/contextlib.py", line 75, in inner
      return func(*args, **kwds)
    File "/home/django/cvat/apps/engine/backup.py", line 752, in _import_project
      db_project = project_importer.import_project()
    File "/home/django/cvat/apps/engine/backup.py", line 744, in import_project
      self._import_tasks()
    File "/home/django/cvat/apps/engine/backup.py", line 734, in _import_tasks
      TaskImporter(
    File "/home/django/cvat/apps/engine/backup.py", line 625, in import_task
      self._import_task()
    File "/home/django/cvat/apps/engine/backup.py", line 607, in _import_task
      _create_thread(self._db_task.pk, data.copy(), isBackupRestore=True)
    File "/usr/lib/python3.8/contextlib.py", line 75, in inner
      return func(*args, **kwds)
    File "/home/django/cvat/apps/engine/task.py", line 428, in _create_thread
      manifest_file = _validate_manifest(
    File "/home/django/cvat/apps/engine/task.py", line 297, in _validate_manifest
      if is_manifest(full_manifest_path):
    File "/home/django/utils/dataset_manifest/core.py", line 724, in is_manifest
      return _is_video_manifest(full_manifest_path) or \
    File "/home/django/utils/dataset_manifest/core.py", line 729, in _is_video_manifest
      return validator.validate()
    File "/home/django/utils/dataset_manifest/core.py", line 642, in validate
      with open(self._manifest.path, 'r') as manifest:
  FileNotFoundError: [Errno 2] No such file or directory: '/home/django/share/manifest.jsonl'
  Traceback (most recent call last):
    File "/opt/venv/lib/python3.8/site-packages/rq/worker.py", line 936, in perform_job
      rv = job.perform()
    File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 684, in perform
      self._result = self._execute()
    File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 690, in _execute
      return self.func(*self.args, **self.kwargs)
    File "/usr/lib/python3.8/contextlib.py", line 75, in inner
      return func(*args, **kwds)
    File "/home/django/cvat/apps/engine/backup.py", line 752, in _import_project
      db_project = project_importer.import_project()
    File "/home/django/cvat/apps/engine/backup.py", line 744, in import_project
      self._import_tasks()
    File "/home/django/cvat/apps/engine/backup.py", line 734, in _import_tasks
      TaskImporter(
    File "/home/django/cvat/apps/engine/backup.py", line 625, in import_task
      self._import_task()
    File "/home/django/cvat/apps/engine/backup.py", line 607, in _import_task
      _create_thread(self._db_task.pk, data.copy(), isBackupRestore=True)
    File "/usr/lib/python3.8/contextlib.py", line 75, in inner
      return func(*args, **kwds)
    File "/home/django/cvat/apps/engine/task.py", line 428, in _create_thread
      manifest_file = _validate_manifest(
    File "/home/django/cvat/apps/engine/task.py", line 297, in _validate_manifest
      if is_manifest(full_manifest_path):
    File "/home/django/utils/dataset_manifest/core.py", line 724, in is_manifest
      return _is_video_manifest(full_manifest_path) or \
    File "/home/django/utils/dataset_manifest/core.py", line 729, in _is_video_manifest
      return validator.validate()
    File "/home/django/utils/dataset_manifest/core.py", line 642, in validate
      with open(self._manifest.path, 'r') as manifest:
  FileNotFoundError: [Errno 2] No such file or directory: '/home/django/share/manifest.jsonl'

    </details>

**Comment by IvanLunev** [comment]
Hi. Yes, the task data was placed in a shared drive. But now the same data is also on new shared drive.14.03.2023, 00:27, "Maxim Zhiltsov" ***@***.***>:
Hi, could you please specify where the task data was placed? It looks like the data was on a shared drive.

**Comment by zhiltsov-max** [comment]
Related https://github.com/opencv/cvat/issues/4989

**Comment by nmanovic** [comment]
@IvanLunev , it is a known issue. I will close the issue as a duplicate. Please follow the original one.

**Comment by petergro-hub** [comment]
@IvanLunev I got to the manifest.jsonl error as well. And indeed this is because of the shared drive. What fixed it for me was to create a manifest.jsonl file in the volume that is to be mounted (where the data is) based off of the project backup I did (which comes with a manifest.jsonl for each task). So you can just concatenate the contents of each manifest.jsonl (from the tasks backup) into one manifest.jsonl file in the shared drive. Just make sure to copy the version and type only once at the beginning of the file/list (for each type) e.g. {"version":"1.1"}{"type":"images"}.
It's very hacky and by no means a fix, but maybe it can help you as well.

**Comment by dwffls** [comment]
I wrote a small python script to create the manifest.jsonl, gonna put it here to help future me and others.

```python
import zipfile
import os

filename= "<YOUR PROJECT BACKUP GOES HERE>"
zip = zipfile.ZipFile(filename+ ".zip")

f = open("manifest.jsonl", "x")
f.write('{"version":"1.1"}\n')
f.write('{"type":"images"}\n')

for manifest in zip.namelist():
    if "manifest.jsonl" in manifest:
        lines = zip.open(manifest).readlines()
        for line in lines[2:]:
            f.write(line.decode())

f.close()
```
