### ISSUE TITLE
Getting error - missing 1 required positional argument: 'jobs' while trying to execute CVAT-CLI commands

### ISSUE THREAD

**Issue by kostromins** [opencv/cvat#5872]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. cvat-cli --server-host [HOST] --auth [AuthData] ls

### Expected Behaviour

List all tasks in terminal.

### Current Behaviour

Getting error message: `TypeError: _from_openapi_data() missing 1 required positional argument: 'jobs'`

### Your Environment

- Git hash commit (`git log -1`): commit 737ee712d27e558152203d19b8bd329071f7a182 (HEAD -> develop, origin/develop, origin/HEAD)
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.6
- Are you using Docker Swarm or Kubernetes? `Swarm: inactive` I suppose non of those
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-144-generic x86_64)
- Other diagnostic information / logs:
    <details>
    <summary>TraceBack</summary>    
      Traceback (most recent call last):
        File "/home/weedbot/miniconda3/envs/yolactedge/bin/cvat-cli", line 8, in <module>
          sys.exit(main())
        File "/home/weedbot/miniconda3/envs/yolactedge/lib/python3.7/site-packages/cvat_cli/__main__.py", line 67, in main
          actions[parsed_args.action](cli, **vars(action_args))
        File "/home/weedbot/miniconda3/envs/yolactedge/lib/python3.7/site-packages/cvat_cli/cli.py", line 30, in tasks_list
          results = self.client.tasks.list(return_json=use_json_output, **kwargs)
        File "/home/weedbot/miniconda3/envs/yolactedge/lib/python3.7/site-packages/cvat_sdk/core/proxies/model_proxy.py", line 156, in list
          results = get_paginated_collection(endpoint=self.api.list_endpoint, return_json=return_json)
        File "/home/weedbot/miniconda3/envs/yolactedge/lib/python3.7/site-packages/cvat_sdk/core/helpers.py", line 29, in get_paginated_collection
          (page_contents, response) = endpoint.call_with_http_info(**kwargs, page=page)
        File "/home/weedbot/miniconda3/envs/yolactedge/lib/python3.7/site-packages/cvat_sdk/api_client/api_client.py", line 1075, in call_with_http_info
          collection_formats=params['collection_format'])
        File "/home/weedbot/miniconda3/envs/yolactedge/lib/python3.7/site-packages/cvat_sdk/api_client/api_client.py", line 497, in call_api
          return self.__call_api(**params)
        File "/home/weedbot/miniconda3/envs/yolactedge/lib/python3.7/site-packages/cvat_sdk/api_client/api_client.py", line 285, in __call_api
          _check_type=_check_type
        File "/home/weedbot/miniconda3/envs/yolactedge/lib/python3.7/site-packages/cvat_sdk/api_client/api_client.py", line 395, in deserialize
          configuration=self.configuration
        File "/home/weedbot/miniconda3/envs/yolactedge/lib/python3.7/site-packages/cvat_sdk/api_client/model_utils.py", line 1598, in validate_and_convert_types
          check_type=_check_type
        File "/home/weedbot/miniconda3/envs/yolactedge/lib/python3.7/site-packages/cvat_sdk/api_client/model_utils.py", line 1472, in attempt_convert_item
          configuration, spec_property_naming)
        File "/home/weedbot/miniconda3/envs/yolactedge/lib/python3.7/site-packages/cvat_sdk/api_client/model_utils.py", line 1384, in deserialize_model
          return model_class._new_from_openapi_data(**kw_args)
        File "/home/weedbot/miniconda3/envs/yolactedge/lib/python3.7/site-packages/cvat_sdk/api_client/model_utils.py", line 51, in wrapped_init
          return fn(_self, *args, **kwargs)
        File "/home/weedbot/miniconda3/envs/yolactedge/lib/python3.7/site-packages/cvat_sdk/api_client/model_utils.py", line 379, in _new_from_openapi_data
          return cls._from_openapi_data(*args, **kwargs)
        File "/home/weedbot/miniconda3/envs/yolactedge/lib/python3.7/site-packages/cvat_sdk/api_client/model_utils.py", line 51, in wrapped_init
          return fn(_self, *args, **kwargs)
        File "/home/weedbot/miniconda3/envs/yolactedge/lib/python3.7/site-packages/cvat_sdk/api_client/model/paginated_task_read_list.py", line 254, in _from_openapi_data
          setattr(self, var_name, var_value)
        File "/home/weedbot/miniconda3/envs/yolactedge/lib/python3.7/site-packages/cvat_sdk/api_client/model_utils.py", line 197, in __setattr__
          self[attr] = value
        File "/home/weedbot/miniconda3/envs/yolactedge/lib/python3.7/site-packages/cvat_sdk/api_client/model_utils.py", line 518, in __setitem__
          self.set_attribute(name, value)
        File "/home/weedbot/miniconda3/envs/yolactedge/lib/python3.7/site-packages/cvat_sdk/api_client/model_utils.py", line 171, in set_attribute
          self._check_type, configuration=self._configuration)
        File "/home/weedbot/miniconda3/envs/yolactedge/lib/python3.7/site-packages/cvat_sdk/api_client/model_utils.py", line 1646, in validate_and_convert_types
          configuration=configuration
        File "/home/weedbot/miniconda3/envs/yolactedge/lib/python3.7/site-packages/cvat_sdk/api_client/model_utils.py", line 1598, in validate_and_convert_types
          check_type=_check_type
        File "/home/weedbot/miniconda3/envs/yolactedge/lib/python3.7/site-packages/cvat_sdk/api_client/model_utils.py", line 1472, in attempt_convert_item
          configuration, spec_property_naming)
        File "/home/weedbot/miniconda3/envs/yolactedge/lib/python3.7/site-packages/cvat_sdk/api_client/model_utils.py", line 1384, in deserialize_model
          return model_class._new_from_openapi_data(**kw_args)
        File "/home/weedbot/miniconda3/envs/yolactedge/lib/python3.7/site-packages/cvat_sdk/api_client/model_utils.py", line 51, in wrapped_init
          return fn(_self, *args, **kwargs)
        File "/home/weedbot/miniconda3/envs/yolactedge/lib/python3.7/site-packages/cvat_sdk/api_client/model_utils.py", line 379, in _new_from_openapi_data
          return cls._from_openapi_data(*args, **kwargs)
        File "/home/weedbot/miniconda3/envs/yolactedge/lib/python3.7/site-packages/cvat_sdk/api_client/model_utils.py", line 51, in wrapped_init
          return fn(_self, *args, **kwargs)
      TypeError: _from_openapi_data() missing 1 required positional argument: 'jobs'
    </details>

**Comment by zhiltsov-max** [comment]
Hi, please update `cvat-sdk` and `cvat-cli` up to the 2.4.0 version.

**Comment by fijackokresimir** [comment]
I have the same issue - which i solved by matching versions of cvat server and cvat-sdk.

cvat versions were bumped yesterday from 2.3.0 -> 2.4.0
in my case i installed cvat-sdk which pulled latest version (2.4.0) but for testing i was using older version (2.3.0)
i resolved this by downgrading cvat-sdk to 2.3.0 until i update cvat-server

**Comment by kostromins** [comment]
> 

Yeah... honestly yesterday was the first time I installed CLI and tried to use it. It seems that I installed it a little bit to late and I got the latest version 😄, while CVAT About page says that it is Server version 2.0.

Downgraded both SDK and CLI from 2.4.0 to 2.3.0 and error was gone.

Thanks!

**Comment by alijawad07** [comment]
This issue has appeared again in 
cvat-cli - 2.5.2
cvat-sdk - 2.5.2

in 2.4.0 job issue was fixed but it was throwing an error because there was no argument for organization
in 2.5.2 there is an argument for organization but again it starts asking for job argument
