### ISSUE TITLE
Fails to export task annotations with "save images" option when using shared storage

### ISSUE THREAD

**Issue by jspsv** [opencv/cvat#6017]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. Start cvat with shared storage option [docs](https://opencv.github.io/cvat/docs/administration/basics/installation/#share-path).
2. Create a project and complete annotation task.
3. Export annotations from "Tasks" page, with "Save Images" toggled.

### Expected Behaviour

1. Annotations (and images) are downloaded correctly when using using shared stoage.

### Current Behaviour

1. Fails to complete download with the following notification.

![Screenshot from 2023-04-13 08-22-38](https://user-images.githubusercontent.com/57749988/231674456-2458f109-3f0d-4440-a668-4dcb90e9d46a.png)

### Possible Solution

Maybe the `cvat_worker_export` service needs to also have access to the `cvat_share` volume. 

### Context

Fails to complete annotation export.

### Your Environment

- Git hash commit (`git log -1`): 61adec55d1eadc4bb37206a7e9f956f057f57928
- Docker version `docker version` (e.g. Docker 17.0.05): Docker 23.0.2
- Are you using Docker Swarm or Kubernetes?: No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 22.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
<details>
    <summary>Logs from `cvat_worker_export` container</summary>
<pre>
2023-04-13 06:46:11,289 DEBG 'rqworker_export_0' stderr output:
DEBUG:rq.worker:Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.

2023-04-13 06:46:11,300 DEBG 'rqworker_export_0' stderr output:
DEBUG:rq.worker:Sent heartbeat to prevent worker timeout. Next one should arrive within 90 seconds.

2023-04-13 06:46:11,651 DEBG 'rqworker_export_0' stderr output:
[2023-04-13 06:46:11,648] ERROR cvat.server.task_1: [cvat.apps.dataset_manager.views @ export]: exception occurred
Traceback (most recent call last):
  File "/home/django/cvat/apps/dataset_manager/views.py", line 84, in export
    export_fn(db_instance.id, temp_file, dst_format,
  File "/home/django/cvat/apps/dataset_manager/task.py", line 789, in export_task
    task.export(f, exporter, host=server_url, save_images=save_images)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 670, in export
    exporter(dst_file, temp_dir, task_data, **options)
  File "/home/django/cvat/apps/dataset_manager/formats/registry.py", line 36, in __call__
    f_or_cls(*args, **kwargs)
  File "/home/django/cvat/apps/dataset_manager/formats/cvat.py", line 1431, in _export_images
    _export_task_or_job(dst_file, temp_dir, instance_data,
  File "/home/django/cvat/apps/dataset_manager/formats/cvat.py", line 1397, in _export_task_or_job
    dump_media_files(instance_data, osp.join(temp_dir, 'images'))
  File "/home/django/cvat/apps/dataset_manager/formats/cvat.py", line 1381, in dump_media_files
    for frame_id, (frame_data, _) in zip(instance_data.rel_range, frames):
  File "/home/django/cvat/apps/engine/frame_provider.py", line 206, in get_frames
    yield self.get_frame(idx, quality=quality, out_type=out_type)
  File "/home/django/cvat/apps/engine/frame_provider.py", line 196, in get_frame
    chunk_reader = loader.load(chunk_number)
  File "/home/django/cvat/apps/engine/frame_provider.py", line 86, in load
    self.reader_class([self.get_chunk_path(chunk_id, self.quality, self.db_data)[0]]))
  File "/home/django/cvat/apps/engine/cache.py", line 46, in get_buf_chunk_with_mime
    item = self._get_or_set_cache_item(
  File "/home/django/cvat/apps/engine/cache.py", line 39, in _get_or_set_cache_item
    item = create_function()
  File "/home/django/cvat/apps/engine/cache.py", line 48, in <lambda>
    create_function=lambda: self._prepare_chunk_buff(db_data, quality, chunk_number),
  File "/home/django/cvat/apps/engine/cache.py", line 150, in _prepare_chunk_buff
    writer.save_as_chunk(images, buff)
  File "/home/django/cvat/apps/engine/media_extractors.py", line 646, in save_as_chunk
    zip_chunk.write(filename=image, arcname=arcname)
  File "/usr/lib/python3.8/zipfile.py", line 1741, in write
    zinfo = ZipInfo.from_file(filename, arcname,
  File "/usr/lib/python3.8/zipfile.py", line 523, in from_file
    st = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/django/share/fruits_dataset/fruits_001.jpg'
ERROR:cvat.server.task_1:[cvat.apps.dataset_manager.views @ export]: exception occurred
Traceback (most recent call last):
  File "/home/django/cvat/apps/dataset_manager/views.py", line 84, in export
    export_fn(db_instance.id, temp_file, dst_format,
  File "/home/django/cvat/apps/dataset_manager/task.py", line 789, in export_task
    task.export(f, exporter, host=server_url, save_images=save_images)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 670, in export
    exporter(dst_file, temp_dir, task_data, **options)
  File "/home/django/cvat/apps/dataset_manager/formats/registry.py", line 36, in __call__
    f_or_cls(*args, **kwargs)
  File "/home/django/cvat/apps/dataset_manager/formats/cvat.py", line 1431, in _export_images
    _export_task_or_job(dst_file, temp_dir, instance_data,
  File "/home/django/cvat/apps/dataset_manager/formats/cvat.py", line 1397, in _export_task_or_job
    dump_media_files(instance_data, osp.join(temp_dir, 'images'))
  File "/home/django/cvat/apps/dataset_manager/formats/cvat.py", line 1381, in dump_media_files
    for frame_id, (frame_data, _) in zip(instance_data.rel_range, frames):
  File "/home/django/cvat/apps/engine/frame_provider.py", line 206, in get_frames
    yield self.get_frame(idx, quality=quality, out_type=out_type)
  File "/home/django/cvat/apps/engine/frame_provider.py", line 196, in get_frame
    chunk_reader = loader.load(chunk_number)
  File "/home/django/cvat/apps/engine/frame_provider.py", line 86, in load
    self.reader_class([self.get_chunk_path(chunk_id, self.quality, self.db_data)[0]]))
  File "/home/django/cvat/apps/engine/cache.py", line 46, in get_buf_chunk_with_mime
    item = self._get_or_set_cache_item(
  File "/home/django/cvat/apps/engine/cache.py", line 39, in _get_or_set_cache_item
    item = create_function()
  File "/home/django/cvat/apps/engine/cache.py", line 48, in <lambda>
    create_function=lambda: self._prepare_chunk_buff(db_data, quality, chunk_number),
  File "/home/django/cvat/apps/engine/cache.py", line 150, in _prepare_chunk_buff
    writer.save_as_chunk(images, buff)
  File "/home/django/cvat/apps/engine/media_extractors.py", line 646, in save_as_chunk
    zip_chunk.write(filename=image, arcname=arcname)
  File "/usr/lib/python3.8/zipfile.py", line 1741, in write
    zinfo = ZipInfo.from_file(filename, arcname,
  File "/usr/lib/python3.8/zipfile.py", line 523, in from_file
    st = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/django/share/fruits_dataset/fruits_001.jpg'

2023-04-13 06:46:11,651 DEBG 'rqworker_export_0' stderr output:
DEBUG:rq.worker:Handling failed execution of job export:annotations-for-task.id1-in-CVAT_for_images_1.1-format

2023-04-13 06:46:11,652 DEBG 'rqworker_export_0' stderr output:
ERROR:rq.worker:Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/rq/worker.py", line 936, in perform_job
    rv = job.perform()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 684, in perform
    self._result = self._execute()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 690, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/django/cvat/apps/dataset_manager/views.py", line 117, in export_task_as_dataset
    return export(dst_format, task_id=task_id, server_url=server_url, save_images=True)
  File "/home/django/cvat/apps/dataset_manager/views.py", line 84, in export
    export_fn(db_instance.id, temp_file, dst_format,
  File "/home/django/cvat/apps/dataset_manager/task.py", line 789, in export_task
    task.export(f, exporter, host=server_url, save_images=save_images)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 670, in export
    exporter(dst_file, temp_dir, task_data, **options)
  File "/home/django/cvat/apps/dataset_manager/formats/registry.py", line 36, in __call__
    f_or_cls(*args, **kwargs)
  File "/home/django/cvat/apps/dataset_manager/formats/cvat.py", line 1431, in _export_images
    _export_task_or_job(dst_file, temp_dir, instance_data,
  File "/home/django/cvat/apps/dataset_manager/formats/cvat.py", line 1397, in _export_task_or_job
    dump_media_files(instance_data, osp.join(temp_dir, 'images'))
  File "/home/django/cvat/apps/dataset_manager/formats/cvat.py", line 1381, in dump_media_files
    for frame_id, (frame_data, _) in zip(instance_data.rel_range, frames):
  File "/home/django/cvat/apps/engine/frame_provider.py", line 206, in get_frames
    yield self.get_frame(idx, quality=quality, out_type=out_type)
  File "/home/django/cvat/apps/engine/frame_provider.py", line 196, in get_frame
    chunk_reader = loader.load(chunk_number)
  File "/home/django/cvat/apps/engine/frame_provider.py", line 86, in load
    self.reader_class([self.get_chunk_path(chunk_id, self.quality, self.db_data)[0]]))
  File "/home/django/cvat/apps/engine/cache.py", line 46, in get_buf_chunk_with_mime
    item = self._get_or_set_cache_item(
  File "/home/django/cvat/apps/engine/cache.py", line 39, in _get_or_set_cache_item
    item = create_function()
  File "/home/django/cvat/apps/engine/cache.py", line 48, in <lambda>
    create_function=lambda: self._prepare_chunk_buff(db_data, quality, chunk_number),
  File "/home/django/cvat/apps/engine/cache.py", line 150, in _prepare_chunk_buff
    writer.save_as_chunk(images, buff)
  File "/home/django/cvat/apps/engine/media_extractors.py", line 646, in save_as_chunk
    zip_chunk.write(filename=image, arcname=arcname)
  File "/usr/lib/python3.8/zipfile.py", line 1741, in write
    zinfo = ZipInfo.from_file(filename, arcname,
  File "/usr/lib/python3.8/zipfile.py", line 523, in from_file
    st = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/django/share/fruits_dataset/fruits_001.jpg'
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/rq/worker.py", line 936, in perform_job
    rv = job.perform()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 684, in perform
    self._result = self._execute()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 690, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/django/cvat/apps/dataset_manager/views.py", line 117, in export_task_as_dataset
    return export(dst_format, task_id=task_id, server_url=server_url, save_images=True)
  File "/home/django/cvat/apps/dataset_manager/views.py", line 84, in export
    export_fn(db_instance.id, temp_file, dst_format,
  File "/home/django/cvat/apps/dataset_manager/task.py", line 789, in export_task
    task.export(f, exporter, host=server_url, save_images=save_images)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 670, in export
    exporter(dst_file, temp_dir, task_data, **options)
  File "/home/django/cvat/apps/dataset_manager/formats/registry.py", line 36, in __call__
    f_or_cls(*args, **kwargs)
  File "/home/django/cvat/apps/dataset_manager/formats/cvat.py", line 1431, in _export_images
    _export_task_or_job(dst_file, temp_dir, instance_data,
  File "/home/django/cvat/apps/dataset_manager/formats/cvat.py", line 1397, in _export_task_or_job
    dump_media_files(instance_data, osp.join(temp_dir, 'images'))
  File "/home/django/cvat/apps/dataset_manager/formats/cvat.py", line 1381, in dump_media_files
    for frame_id, (frame_data, _) in zip(instance_data.rel_range, frames):
  File "/home/django/cvat/apps/engine/frame_provider.py", line 206, in get_frames
    yield self.get_frame(idx, quality=quality, out_type=out_type)
  File "/home/django/cvat/apps/engine/frame_provider.py", line 196, in get_frame
    chunk_reader = loader.load(chunk_number)
  File "/home/django/cvat/apps/engine/frame_provider.py", line 86, in load
    self.reader_class([self.get_chunk_path(chunk_id, self.quality, self.db_data)[0]]))
  File "/home/django/cvat/apps/engine/cache.py", line 46, in get_buf_chunk_with_mime
    item = self._get_or_set_cache_item(
  File "/home/django/cvat/apps/engine/cache.py", line 39, in _get_or_set_cache_item
    item = create_function()
  File "/home/django/cvat/apps/engine/cache.py", line 48, in <lambda>
    create_function=lambda: self._prepare_chunk_buff(db_data, quality, chunk_number),
  File "/home/django/cvat/apps/engine/cache.py", line 150, in _prepare_chunk_buff
    writer.save_as_chunk(images, buff)
  File "/home/django/cvat/apps/engine/media_extractors.py", line 646, in save_as_chunk
    zip_chunk.write(filename=image, arcname=arcname)
  File "/usr/lib/python3.8/zipfile.py", line 1741, in write
    zinfo = ZipInfo.from_file(filename, arcname,
  File "/usr/lib/python3.8/zipfile.py", line 523, in from_file
    st = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/django/share/fruits_dataset/fruits_001.jpg'

2023-04-13 06:46:11,652 DEBG 'rqworker_export_0' stderr output:
DEBUG:rq.worker:Invoking exception handler <function rq_exception_handler at 0x7f6310f0df70>

2023-04-13 06:46:11,653 DEBG 'rqworker_export_0' stderr output:
DEBUG:rq.worker:Invoking exception handler <function handle_rq_exception at 0x7f6310f59e50>

2023-04-13 06:46:11,663 DEBG 'rqworker_export_0' stderr output:
DEBUG:rq.worker:Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.
DEBUG:rq.worker:Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.

2023-04-13 06:46:11,664 DEBG 'rqworker_export_0' stderr output:
DEBUG:rq.worker:*** Listening on export...

2023-04-13 06:46:11,664 DEBG 'rqworker_export_0' stderr output:
DEBUG:rq.worker:Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.
</pre>
</details>

**Comment by cherrychengzi** [comment]
This problem is same with me.

**Comment by jspsv** [comment]
For me this is resolved when I mount `cvat_share` to `cvat_worker_export`.
```yml
cvat_worker_export:
    volumes:
      - cvat_share:/home/django/share:ro
```

**Comment by cherrychengzi** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by cherrychengzi** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
