### ISSUE TITLE
ImportError: numpy.core.multiarray failed to import on 2.4.2

### ISSUE THREAD

**Issue by RZetko** [opencv/cvat#6038]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)
1. `git checkout tags/v2.4.2 -b v.2.4.2`
2. `docker compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml up -d`

### Expected Behaviour
CVAT is accessible in browser

### Current Behaviour
I tried to update CVAT to version 2.4.2 due to SAM but after updating I can't access CVAT. Containers are up and running but API /api/server/health/?format=json&org= returns Bad gateway 502.

Successfully finished 2.4.0 migration guide beforehand and properly set environment variables ACME_EMAIL and CVAT_HOST.  When downgrading to 2.4.0 or 2.4.1 CVAT works as expected.

Output from docker exec -t cvat_server python manage.py health_check:

```
OpenBLAS blas_thread_init: pthread_create failed for thread 1 of 4: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 2 of 4: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 3 of 4: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "/home/django/manage.py", line 21, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/opt/venv/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/venv/lib/python3.10/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/opt/venv/lib/python3.10/site-packages/django/apps/config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/django/cvat/apps/engine/models.py", line 20, in <module>
    from cvat.apps.engine.utils import parse_specific_attributes
  File "/home/django/cvat/apps/engine/utils.py", line 6, in <module>
    import cv2 as cv
  File "/opt/venv/lib/python3.10/site-packages/cv2/__init__.py", line 8, in <module>
    from .cv2 import *
ImportError: numpy.core.multiarray failed to import
```

### Possible Solution
Probably updating/fixing dependencies in requirements.txt.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by bsekachev** [comment]
@RZetko

Hi, I've just tried to reproduce according to you steps and was unable to do it. 
If you can provide more specific details on the issue, please share.

**Comment by atto-js** [comment]
I experienced the same problem.

git clone https://github.com/opencv/cvat
cd cvat
docker-compose pull
docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d (or docker-compose up -d)

This will result in the just same error log output from import cv2

Docker version 20.10.17, build 100c701
CentOS Linux release 7.9.2009

**Comment by RZetko** [comment]
Unfortunately I can't right now, I'm away from computer for few days. When I get back I'll try to provide more details.

**Comment by lucasalvarezlacasa** [comment]
I have exactly the same problem. Have you found a solution?

**Comment by pfrenzel** [comment]
I have the same problem on one host. However, the problem does not occur on two other hosts. The host on which the setup does not work has Docker version 20.10.20. Another host has the same version and the setup is working here.
Version v.2.4.1 works on all hosts (ubuntu 20.04.6).

**Comment by lucasalvarezlacasa** [comment]
> I have the same problem on one host. However, the problem does not occur on two other hosts. The host on which the setup does not work has Docker version 20.10.20. Another host has the same version and the setup is working here. Version v.2.4.1 works on all hosts (ubuntu 20.04.6).

So the docker version is not the problem? I have `20.10.6 `in the host where the problem occurs. In my computer I have 23.0.5 and works normally.

**Comment by lucasalvarezlacasa** [comment]
I've solved the issue by updating the docker version to `23.05` in the host.

**Comment by pfrenzel** [comment]
The problem for me was the nvidia runtime, which was set as default. After updating the nvidia runtime, the issue was solved.

**Comment by bsekachev** [comment]
Looks like community found a reason. I will close the issue, do not hesitate to reopen if still experiencing it.

**Comment by zhouzhou0322** [comment]
`services:
  cvat_server:
    container_name: cvat_server
    image: cvat/server:${CVAT_VERSION:-dev}
    restart: always
    depends_on:
      <<: *backend-deps
      cvat_opa:
        condition:
          service_started
    environment:
      <<: *backend-env
      DJANGO_MODWSGI_EXTRA_ARGS: ''
      ALLOWED_HOSTS: '*'
      ADAPTIVE_AUTO_ANNOTATION: 'false'
      IAM_OPA_BUNDLE: '1'
      NUMPROCS: 2
      CVAT_ANALYTICS: 1
      CVAT_BASE_URL:
      ONE_RUNNING_JOB_IN_QUEUE_PER_USER:
      OPENBLAS_NUM_THREADS: 2
    command: init run server
    security_opt:
      - seccomp:unconfined
    labels:
      - traefik.enable=true
      - traefik.http.services.cvat.loadbalancer.server.port=8080
      - traefik.http.routers.cvat.rule=Host(`${CVAT_HOST:-localhost}`) &&
        PathPrefix(`/api/`, `/static/`, `/admin`, `/documentation/`, `/django-rq`)
      - traefik.http.routers.cvat.entrypoints=web
    volumes:
      - cvat_data:/home/django/data
      - cvat_keys:/home/django/keys
      - cvat_logs:/home/django/logs
    networks:
      cvat:
        aliases:
          - cvat-server
`

I modified the docker-compose.yml and solve the problem add  security_opt:- seccomp:unconfined and OPENBLAS_NUM_THREADS: 2 (the later one may not be necessary).  Inspireation for m https://github.com/HumanSignal/label-studio/issues/3070
