### ISSUE TITLE
ERROR:health-check:unavailable: Database is not ready

### ISSUE THREAD

**Issue by puren** [opencv/cvat#6110]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. I run `docker compose up -d`  as instructed in the installation guide.
1. Then to check if cvat runs correctly, I run `docker exec -t cvat_server python manage.py health_check`.

### Expected Behaviour

I should get an output saying "working". 

### Current Behaviour

It fails saying "ERROR:health-check:unavailable: Database is not ready".

### Context

 I try to install CVAT in our lab computer for image annotation. It is connected to the internet through a proxy. It set the docker proxy settings properly. But still it doesn't work.
I would first try to run it locally and make sure that it works. But for the future, I would like to use the lab computer as a server and connect the CVAT through a browser from another computer as well.

### Your Environment

- Git hash commit (`git log -1`): commit 5399f6e189c547dd7948bfac2b4ff61f5b907848
- Docker version `docker version` (e.g. Docker 17.0.05): Docker 23.0.5
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Linux Ubuntu 22.04.2
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat_server` container</summary>
ERROR:health-check:unavailable: Database is not ready
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/opt/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/opt/venv/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "cvat_db" (172.22.0.3), port 5432 failed: Connection timed out
        Is the server running on that host and accepting TCP/IP connections?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/health_check/contrib/migrations/backends.py", line 20, in check_status
    executor = MigrationExecutor(connections[db_alias])
  File "/opt/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/opt/venv/lib/python3.10/site-packages/django/db/migrations/loader.py", line 53, in __init__
    self.build_graph()
  File "/opt/venv/lib/python3.10/site-packages/django/db/migrations/loader.py", line 220, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/opt/venv/lib/python3.10/site-packages/django/db/migrations/recorder.py", line 77, in applied_migrations
    if self.has_table():
  File "/opt/venv/lib/python3.10/site-packages/django/db/migrations/recorder.py", line 55, in has_table
    with self.connection.cursor() as cursor:
  File "/opt/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/opt/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 218, in ensure_connection
    with self.wrap_database_errors:
  File "/opt/venv/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/opt/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/opt/venv/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: connection to server at "cvat_db" (172.22.0.3), port 5432 failed: Connection timed out
        Is the server running on that host and accepting TCP/IP connections?

ERROR:health-check:unknown error: HTTPConnectionPool(host='opa', port=8181): Max retries exceeded with url: /health?bundles (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f41add23d90>, 'Connection to opa timed out. (connect timeout=None)'))
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/opt/venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/opt/venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7f41add23d90>, 'Connection to opa timed out. (connect timeout=None)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/opt/venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='opa', port=8181): Max retries exceeded with url: /health?bundles (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f41add23d90>, 'Connection to opa timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/django/cvat/apps/health/backends.py", line 24, in check_status
    response = session.get(opa_health_url)
  File "/opt/venv/lib/python3.10/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/venv/lib/python3.10/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='opa', port=8181): Max retries exceeded with url: /health?bundles (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f41add23d90>, 'Connection to opa timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/health_check/backends.py", line 30, in run_check
    self.check_status()
  File "/home/django/cvat/apps/health/backends.py", line 27, in check_status
    raise HealthCheckException(str(e))
health_check.exceptions.HealthCheckException: unknown error: HTTPConnectionPool(host='opa', port=8181): Max retries exceeded with url: /health?bundles (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f41add23d90>, 'Connection to opa timed out. (connect timeout=None)'))
ERROR:health-check:unavailable: Database error
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/opt/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/opt/venv/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "cvat_db" (172.22.0.3), port 5432 failed: Connection timed out
        Is the server running on that host and accepting TCP/IP connections?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/health_check/db/backends.py", line 12, in check_status
    obj = TestModel.objects.create(title="test")
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1414, in execute_sql
    with self.connection.cursor() as cursor:
  File "/opt/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/opt/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 218, in ensure_connection
    with self.wrap_database_errors:
  File "/opt/venv/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/opt/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/opt/venv/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: connection to server at "cvat_db" (172.22.0.3), port 5432 failed: Connection timed out
        Is the server running on that host and accepting TCP/IP connections?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/health_check/backends.py", line 30, in run_check
    self.check_status()
  File "/opt/venv/lib/python3.10/site-packages/health_check/db/backends.py", line 19, in check_status
    raise ServiceUnavailable("Database error")
health_check.exceptions.ServiceUnavailable: unavailable: Database error
Cache backend: default   ... working
Cache backend: media     ... working
DatabaseBackend          ... unavailable: Database error
DiskUsage                ... working
MemoryUsage              ... working
MigrationsHealthCheck    ... unavailable: Database is not ready
OPAHealthCheck           ... unknown error: HTTPConnectionPool(host='opa', port=8181): Max retries exceeded with url: /health?bundles (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f41add23d90>, 'Connection to opa timed out. (connect timeout=None)'))
    </details>

**Comment by bsekachev** [comment]
@puren 

``docker ps`` output? 

From logs I see issues with database and open policy agent services. Could you please provide logs from them?

**Comment by puren** [comment]
`docker ps` output is as follows:


CONTAINER ID   IMAGE                                      COMMAND                  CREATED       STATUS          PORTS                                                                                          NAMES
4205931029f3   cvat/ui:dev                                "/docker-entrypoint.…"   5 hours ago   Up 5 hours      80/tcp                                                                                         cvat_ui
1bdebab95990   cvat/server:dev                            "/usr/bin/supervisor…"   5 hours ago   Up 5 hours      8080/tcp                                                                                       cvat_utils
df8247900db2   cvat/server:dev                            "/usr/bin/supervisor…"   5 hours ago   Up 5 hours      8080/tcp                                                                                       cvat_server
375ab2426d01   cvat/server:dev                            "/usr/bin/supervisor…"   5 hours ago   Up 5 hours      8080/tcp                                                                                       cvat_worker_annotation
fcc0cac3149a   cvat/server:dev                            "/usr/bin/supervisor…"   5 hours ago   Up 5 hours      8080/tcp                                                                                       cvat_worker_webhooks
3b20f6c21182   cvat/server:dev                            "/usr/bin/supervisor…"   5 hours ago   Up 5 hours      8080/tcp                                                                                       cvat_worker_export
d508a6afb331   cvat/server:dev                            "/usr/bin/supervisor…"   5 hours ago   Up 5 hours      8080/tcp                                                                                       cvat_worker_import
7dd073995a0d   timberio/vector:0.26.0-alpine              "/usr/local/bin/vect…"   3 days ago    Up 5 hours                                                                                                     cvat_vector
4ca2dbff6875   traefik:v2.9                               "/entrypoint.sh --pr…"   3 days ago    Up 5 hours      0.0.0.0:8080->8080/tcp, :::8080->8080/tcp, 80/tcp, 0.0.0.0:8090->8090/tcp, :::8090->8090/tcp   traefik
1434b346e6ac   redis:7.0-alpine                           "docker-entrypoint.s…"   3 days ago    Up 5 hours      6379/tcp                                                                                       cvat_redis
21b725d7fddb   postgres:15-alpine                         "docker-entrypoint.s…"   3 days ago    Up 5 hours      5432/tcp                                                                                       cvat_db
cad7c4b3e56f   clickhouse/clickhouse-server:22.3-alpine   "/entrypoint.sh"         3 days ago    Up 24 seconds   8123/tcp, 9000/tcp, 9009/tcp                                                                   cvat_clickhouse
e1091f41d803   openpolicyagent/opa:0.45.0-rootless        "/opa run --server -…"   3 days ago    Up 5 hours                                                                                                     cvat_opa
/

**Comment by bsekachev** [comment]
``docker logs cvat_opa`` and ``docker logs cvat_db``?

**Comment by puren** [comment]
output for `docker logs cvat_opa`:

{"level":"error","msg":"Bundle load failed: request failed: Get \"http://cvat-server:8080/api/auth/rules\": proxyconnect tcp: dial tcp 136.225.173.163:8080: i/o timeout","name":"cvat","plugin":"bundle","time":"2023-05-05T16:26:28Z"}
{"level":"error","msg":"Bundle load failed: request failed: Get \"http://cvat-server:8080/api/auth/rules\": proxyconnect tcp: dial tcp 136.225.173.163:8080: i/o timeout","name":"cvat","plugin":"bundle","time":"2023-05-05T16:26:58Z"}
{"level":"error","msg":"Bundle load failed: request failed: Get \"http://cvat-server:8080/api/auth/rules\": proxyconnect tcp: dial tcp 136.225.173.163:8080: i/o timeout","name":"cvat","plugin":"bundle","time":"2023-05-05T16:27:28Z"}
{"level":"error","msg":"Bundle load failed: request failed: Get \"http://cvat-server:8080/api/auth/rules\": proxyconnect tcp: dial tcp 136.225.173.163:8080: i/o timeout","name":"cvat","plugin":"bundle","time":"2023-05-05T16:27:58Z"}
{"level":"error","msg":"Bundle load failed: request failed: Get \"http://cvat-server:8080/api/auth/rules\": proxyconnect tcp: dial tcp 136.225.173.163:8080: i/o timeout","name":"cvat","plugin":"bundle","time":"2023-05-05T16:28:29Z"}
{"level":"error","msg":"Bundle load failed: request failed: Get \"http://cvat-server:8080/api/auth/rules\": proxyconnect tcp: dial tcp 136.225.173.163:8080: i/o timeout","name":"cvat","plugin":"bundle","time":"2023-05-05T16:28:59Z"}
{"level":"error","msg":"Bundle load failed: request failed: Get \"http://cvat-server:8080/api/auth/rules\": proxyconnect tcp: dial tcp 136.225.173.163:8080: i/o timeout","name":"cvat","plugin":"bundle","time":"2023-05-05T16:29:30Z"}
{"level":"error","msg":"Bundle load failed: request failed: Get \"http://cvat-server:8080/api/auth/rules\": proxyconnect tcp: dial tcp 136.225.173.163:8080: i/o timeout","name":"cvat","plugin":"bundle","time":"2023-05-05T16:30:02Z"}

output for `docker logs cvat_db`:

PostgreSQL Database directory appears to contain a database; Skipping initialization

2023-05-05 16:25:56.467 UTC [1] LOG:  starting PostgreSQL 15.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
2023-05-05 16:25:56.467 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-05-05 16:25:56.467 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2023-05-05 16:25:56.474 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-05-05 16:25:56.479 UTC [24] LOG:  database system was interrupted; last known up at 2023-05-05 16:23:37 UTC
2023-05-05 16:25:56.754 UTC [24] LOG:  database system was not properly shut down; automatic recovery in progress
2023-05-05 16:25:56.758 UTC [24] LOG:  redo starts at 0/1960FC8
2023-05-05 16:25:56.758 UTC [24] LOG:  invalid record length at 0/19610B0: wanted 24, got 0
2023-05-05 16:25:56.758 UTC [24] LOG:  redo done at 0/1961078 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2023-05-05 16:25:56.764 UTC [22] LOG:  checkpoint starting: end-of-recovery immediate wait
2023-05-05 16:25:56.776 UTC [22] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.004 s, sync=0.002 s, total=0.015 s; sync files=2, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=0 kB
2023-05-05 16:25:56.781 UTC [1] LOG:  database system is ready to accept connections
2023-05-05 16:30:18.951 UTC [1] LOG:  received fast shutdown request
2023-05-05 16:30:18.954 UTC [1] LOG:  aborting any active transactions
2023-05-05 16:30:18.955 UTC [1] LOG:  background worker "logical replication launcher" (PID 27) exited with exit code 1
2023-05-05 16:30:18.956 UTC [22] LOG:  shutting down
2023-05-05 16:30:18.958 UTC [22] LOG:  checkpoint starting: shutdown immediate
2023-05-05 16:30:18.966 UTC [22] LOG:  checkpoint complete: wrote 0 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.001 s, sync=0.001 s, total=0.011 s; sync files=0, longest=0.000 s, average=0.000 s; distance=0 kB, estimate=0 kB
2023-05-05 16:30:18.970 UTC [1] LOG:  database system is shut down

**Comment by bsekachev** [comment]
Unfortunately it could not be reproduced on our side. I will close the issue, not still it is relevant. If it is, please, reopen and provide some ideas how we can reproduce it.
