### ISSUE TITLE
(nuclio) Failed to deploy mask_rcnn_inception_resnet_v2_atrous_coco

### ISSUE THREAD

**Issue by zjx140** [opencv/cvat#6145]
### My actions before raising this issue
-  Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
-  Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

I input code below to deploy mask_rcnn_inception_resnet_v2_atrous_coco

```
 sudo nuctl deploy --project-name cvat   \
   --path serverless/openvino/omz/public/mask_rcnn_inception_resnet_v2_atrous_coco/nuclio   \
   --volume `pwd`/serverless/common:/opt/nuclio/common   --platform local
```
But failed to deploy and got this error
```
{"datetime": "2023-05-14 01:41:10,182", "level": "error", "message": "Caught unhandled exception while initializing", "with": {"err": "No module named 'skimage'", "traceback": "Traceback (most recent call last):  
File \"/opt/nuclio/_nuclio_wrapper.py\", line 409, in run_wrapper
    args.decode_event_strings)
File \"/opt/nuclio/_nuclio_wrapper.py\", line 71, in __init__
    self._entrypoint = self._load_entrypoint_from_handler(handler)
  File \"/opt/nuclio/_nuclio_wrapper.py\", line 195, in _load_entrypoint_from_handler
    module = __import__(module_name)
  File \"/opt/nuclio/main.py\", line 5, in <module>
   from model_handler import ModelHandler
  File \"/opt/nuclio/model_handler.py\", line 12, in <module>
    from skimage.measure import approximate_polygon, find_contours
ModuleNotFoundError: No module named 'skimage'
", "worker_id": "0"}}
23.05.14 01:41:10.203 sor.http.w0.python.logger (E) Unexpected termination of child process {"error": null, "status": "exit status 1"}
panic: Wrapper process for worker 0 exited unexpectedly with: exit status 1

goroutine 32 [running]:
github.com/nuclio/nuclio/pkg/processor/runtime/rpc.(*AbstractRuntime).watchWrapperProcess(0xc0005d8000)
        /nuclio/pkg/processor/runtime/rpc/abstract.go:471 +0x445
created by github.com/nuclio/nuclio/pkg/processor/runtime/rpc.(*AbstractRuntime).startWrapper
        /nuclio/pkg/processor/runtime/rpc/abstract.go:244 +0x1c5

    /nuclio/pkg/platform/local/platform.go:1168
Failed to deploy function
    ...//nuclio/pkg/platform/abstract/platform.go:197
```
How to solve it?
Thank you!

### Your Environment

- Docker version: 23.0.5
- OS: Windows11 WSL(Ubuntu22.04) 
- NUCTL: 1.8.14

**Comment by alejandrogarcia11** [comment]
Hi, how did you solve it? Thanks!
