### ISSUE TITLE
CVAT deploy errors - Could not fetch models meta information

### ISSUE THREAD

**Issue by 315386775** [opencv/cvat#6148]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

i have checked #5594

### Steps to Reproduce (for bugs)

1. docker-compose down
2. docker-compose -f docker-compose.yml -f components/analytics/docker-compose.analytics.yml up -d --build

### Current Behaviour

01. loggin error

![00](https://github.com/opencv/cvat/assets/12441747/6b5e2d9c-c1ea-4902-8cb1-177fe8e5b458)

02. cvat log

[cvat.log](https://github.com/opencv/cvat/files/11474372/cvat.log)

`WARNING:django.request:Unauthorized: /api/events`

### Your Environment

```
Server version: 2.5

Core version: 9.1.0

Canvas version: 2.16.5

UI version: 1.51.0
```

**Comment by bsekachev** [comment]
```
[Mon May 15 04:49:54.728024 2023] [wsgi:error] [pid 330:tid 140308697404992] [remote 172.18.0.7:58952] [2023-05-15 04:49:54,727] ERROR django.request: Internal Server Error: /api/events
[Mon May 15 04:49:54.728055 2023] [wsgi:error] [pid 330:tid 140308697404992] [remote 172.18.0.7:58952] Traceback (most recent call last):
[Mon May 15 04:49:54.728060 2023] [wsgi:error] [pid 330:tid 140308697404992] [remote 172.18.0.7:58952]   File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
[Mon May 15 04:49:54.728065 2023] [wsgi:error] [pid 330:tid 140308697404992] [remote 172.18.0.7:58952]     response = get_response(request)
[Mon May 15 04:49:54.728068 2023] [wsgi:error] [pid 330:tid 140308697404992] [remote 172.18.0.7:58952]   File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
[Mon May 15 04:49:54.728073 2023] [wsgi:error] [pid 330:tid 140308697404992] [remote 172.18.0.7:58952]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Mon May 15 04:49:54.728076 2023] [wsgi:error] [pid 330:tid 140308697404992] [remote 172.18.0.7:58952]   File "/opt/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
[Mon May 15 04:49:54.728080 2023] [wsgi:error] [pid 330:tid 140308697404992] [remote 172.18.0.7:58952]     return view_func(*args, **kwargs)
[Mon May 15 04:49:54.728083 2023] [wsgi:error] [pid 330:tid 140308697404992] [remote 172.18.0.7:58952]   File "/opt/venv/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
[Mon May 15 04:49:54.728087 2023] [wsgi:error] [pid 330:tid 140308697404992] [remote 172.18.0.7:58952]     return self.dispatch(request, *args, **kwargs)
[Mon May 15 04:49:54.728091 2023] [wsgi:error] [pid 330:tid 140308697404992] [remote 172.18.0.7:58952]   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
[Mon May 15 04:49:54.728094 2023] [wsgi:error] [pid 330:tid 140308697404992] [remote 172.18.0.7:58952]     response = self.handle_exception(exc)
[Mon May 15 04:49:54.728097 2023] [wsgi:error] [pid 330:tid 140308697404992] [remote 172.18.0.7:58952]   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
[Mon May 15 04:49:54.728101 2023] [wsgi:error] [pid 330:tid 140308697404992] [remote 172.18.0.7:58952]     self.raise_uncaught_exception(exc)
[Mon May 15 04:49:54.728104 2023] [wsgi:error] [pid 330:tid 140308697404992] [remote 172.18.0.7:58952]   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
[Mon May 15 04:49:54.728107 2023] [wsgi:error] [pid 330:tid 140308697404992] [remote 172.18.0.7:58952]     raise exc
[Mon May 15 04:49:54.728110 2023] [wsgi:error] [pid 330:tid 140308697404992] [remote 172.18.0.7:58952]   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
[Mon May 15 04:49:54.728114 2023] [wsgi:error] [pid 330:tid 140308697404992] [remote 172.18.0.7:58952]     self.initial(request, *args, **kwargs)
[Mon May 15 04:49:54.728117 2023] [wsgi:error] [pid 330:tid 140308697404992] [remote 172.18.0.7:58952]   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 415, in initial
[Mon May 15 04:49:54.728120 2023] [wsgi:error] [pid 330:tid 140308697404992] [remote 172.18.0.7:58952]     self.check_permissions(request)
[Mon May 15 04:49:54.728123 2023] [wsgi:error] [pid 330:tid 140308697404992] [remote 172.18.0.7:58952]   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 332, in check_permissions
[Mon May 15 04:49:54.728127 2023] [wsgi:error] [pid 330:tid 140308697404992] [remote 172.18.0.7:58952]     if not permission.has_permission(request, self):
[Mon May 15 04:49:54.728130 2023] [wsgi:error] [pid 330:tid 140308697404992] [remote 172.18.0.7:58952]   File "/home/django/cvat/apps/iam/permissions.py", line 1580, in has_permission
[Mon May 15 04:49:54.728133 2023] [wsgi:error] [pid 330:tid 140308697404992] [remote 172.18.0.7:58952]     return self.check_permission(request, view, None)
[Mon May 15 04:49:54.728143 2023] [wsgi:error] [pid 330:tid 140308697404992] [remote 172.18.0.7:58952]   File "/home/django/cvat/apps/iam/permissions.py", line 1573, in check_permission
[Mon May 15 04:49:54.728146 2023] [wsgi:error] [pid 330:tid 140308697404992] [remote 172.18.0.7:58952]     result = perm.check_access()
[Mon May 15 04:49:54.728150 2023] [wsgi:error] [pid 330:tid 140308697404992] [remote 172.18.0.7:58952]   File "/home/django/cvat/apps/iam/permissions.py", line 129, in check_access
[Mon May 15 04:49:54.728153 2023] [wsgi:error] [pid 330:tid 140308697404992] [remote 172.18.0.7:58952]     output = response.json()['result']
[Mon May 15 04:49:54.728156 2023] [wsgi:error] [pid 330:tid 140308697404992] [remote 172.18.0.7:58952] KeyError: 'result'
```

Be sure ``cvat_opa`` container is up and running with no errors (``docker logs cvat_opa``).

**Comment by bsekachev** [comment]
> @bsekachev docker logs cvat_opa infomation:

It does not look like full logs.

**Comment by bsekachev** [comment]
Have you just started the CVAT services?

**Comment by 315386775** [comment]
cvat_opa log:

```
{"level":"error","msg":"Bundle load failed: request failed: Get \"http://cvat-server:8080/api/auth/rules\": dial tcp 172.20.0.13:8080: connect: connection refused","name":"cvat","plugin":"bundle","time":"2023-05-15T07:30:32Z"}
{"level":"error","msg":"Bundle load failed: request failed: Get \"http://cvat-server:8080/api/auth/rules\": dial tcp 172.20.0.13:8080: connect: connection refused","name":"cvat","plugin":"bundle","time":"2023-05-15T07:30:32Z"}
{"level":"error","msg":"Bundle load failed: request failed: Get \"http://cvat-server:8080/api/auth/rules\": dial tcp 172.20.0.13:8080: connect: connection refused","name":"cvat","plugin":"bundle","time":"2023-05-15T07:30:32Z"}
{"level":"error","msg":"Bundle load failed: request failed: Get \"http://cvat-server:8080/api/auth/rules\": dial tcp 172.20.0.13:8080: connect: connection refused","name":"cvat","plugin":"bundle","time":"2023-05-15T07:30:32Z"}
{"level":"error","msg":"Bundle load failed: request failed: Get \"http://cvat-server:8080/api/auth/rules\": dial tcp 172.20.0.13:8080: connect: connection refused","name":"cvat","plugin":"bundle","time":"2023-05-15T07:30:33Z"}
{"level":"error","msg":"Bundle load failed: request failed: Get \"http://cvat-server:8080/api/auth/rules\": dial tcp 172.20.0.13:8080: connect: connection refused","name":"cvat","plugin":"bundle","time":"2023-05-15T07:30:34Z"}
{"level":"error","msg":"Bundle load failed: request failed: Get \"http://cvat-server:8080/api/auth/rules\": dial tcp 172.20.0.13:8080: connect: connection refused","name":"cvat","plugin":"bundle","time":"2023-05-15T07:30:35Z"}
{"level":"error","msg":"Bundle load failed: request failed: Get \"http://cvat-server:8080/api/auth/rules\": dial tcp 172.20.0.13:8080: connect: connection refused","name":"cvat","plugin":"bundle","time":"2023-05-15T07:30:36Z"}
{"level":"error","msg":"Bundle load failed: request failed: Get \"http://cvat-server:8080/api/auth/rules\": dial tcp 172.20.0.13:8080: connect: connection refused","name":"cvat","plugin":"bundle","time":"2023-05-15T07:30:39Z"}
{"level":"error","msg":"Bundle load failed: request failed: Get \"http://cvat-server:8080/api/auth/rules\": dial tcp 172.20.0.13:8080: connect: connection refused","name":"cvat","plugin":"bundle","time":"2023-05-15T07:30:43Z"}
{"level":"error","msg":"Bundle load failed: request failed: Get \"http://cvat-server:8080/api/auth/rules\": dial tcp 172.20.0.13:8080: connect: connection refused","name":"cvat","plugin":"bundle","time":"2023-05-15T07:30:51Z"}
{"level":"error","msg":"Bundle load failed: request failed: Get \"http://cvat-server:8080/api/auth/rules\": dial tcp 172.20.0.13:8080: connect: connection refused","name":"cvat","plugin":"bundle","time":"2023-05-15T07:30:59Z"}
{"level":"error","msg":"Bundle load failed: request failed: Get \"http://cvat-server:8080/api/auth/rules\": dial tcp 172.20.0.13:8080: connect: connection refused","name":"cvat","plugin":"bundle","time":"2023-05-15T07:31:16Z"}
{"level":"error","msg":"Bundle load failed: server replied with Not Found","name":"cvat","plugin":"bundle","time":"2023-05-15T07:31:40Z"}
{"level":"error","msg":"Bundle load failed: server replied with Not Found","name":"cvat","plugin":"bundle","time":"2023-05-15T07:31:54Z"}
{"level":"error","msg":"Bundle load failed: server replied with Not Found","name":"cvat","plugin":"bundle","time":"2023-05-15T07:32:09Z"}
{"level":"error","msg":"Bundle load failed: server replied with Not Found","name":"cvat","plugin":"bundle","time":"2023-05-15T07:32:26Z"}
{"level":"error","msg":"Bundle load failed: server replied with Not Found","name":"cvat","plugin":"bundle","time":"2023-05-15T07:32:40Z"}
{"level":"error","msg":"Bundle load failed: server replied with Not Found","name":"cvat","plugin":"bundle","time":"2023-05-15T07:32:56Z"}
{"level":"error","msg":"Bundle load failed: server replied with Not Found","name":"cvat","plugin":"bundle","time":"2023-05-15T07:33:11Z"}
{"level":"error","msg":"Bundle load failed: server replied with Not Found","name":"cvat","plugin":"bundle","time":"2023-05-15T07:33:27Z"}
{"level":"error","msg":"Bundle load failed: server replied with Not Found","name":"cvat","plugin":"bundle","time":"2023-05-15T07:33:42Z"}
{"level":"error","msg":"Bundle load failed: server replied with Not Found","name":"cvat","plugin":"bundle","time":"2023-05-15T07:33:55Z"}
{"level":"error","msg":"Bundle load failed: server replied with Not Found","name":"cvat","plugin":"bundle","time":"2023-05-15T07:34:09Z"}
{"level":"error","msg":"Bundle load failed: server replied with Not Found","name":"cvat","plugin":"bundle","time":"2023-05-15T07:34:22Z"}
{"level":"error","msg":"Bundle load failed: server replied with Not Found","name":"cvat","plugin":"bundle","time":"2023-05-15T07:34:35Z"}
{"level":"error","msg":"Bundle load failed: server replied with Not Found","name":"cvat","plugin":"bundle","time":"2023-05-15T07:34:50Z"}
{"level":"error","msg":"Bundle load failed: server replied with Not Found","name":"cvat","plugin":"bundle","time":"2023-05-15T07:35:03Z"}
```

**Comment by 315386775** [comment]
i have reinstalled it again and it works. thanks. 

Guided:
`
https://opencv.github.io/cvat/docs/administration/advanced/upgrade_guide/`
