### ISSUE TITLE
Cannot to create a task from a backup

### ISSUE THREAD

**Issue by azhavoro** [opencv/cvat#6149]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. Create a task from share
1. Backup the task
1. Try to create a task from the backup on new instance
1.

### Current Behaviour

```python
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/rq/worker.py", line 936, in perform_job
    rv = job.perform()
  File "/opt/venv/lib/python3.10/site-packages/rq/job.py", line 684, in perform
    self._result = self._execute()
  File "/opt/venv/lib/python3.10/site-packages/rq/job.py", line 690, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/django/cvat/apps/engine/backup.py", line 632, in _import_task
    db_task = task_importer.import_task()
  File "/home/django/cvat/apps/engine/backup.py", line 624, in import_task
    self._import_task()
  File "/home/django/cvat/apps/engine/backup.py", line 606, in _import_task
    _create_thread(self._db_task.pk, data.copy(), isBackupRestore=True)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/django/cvat/apps/engine/task.py", line 430, in _create_thread
    manifest_file = _validate_manifest(
  File "/home/django/cvat/apps/engine/task.py", line 297, in _validate_manifest
    if is_manifest(full_manifest_path):
  File "/home/django/utils/dataset_manifest/core.py", line 733, in is_manifest
    return _is_video_manifest(full_manifest_path) or \
  File "/home/django/utils/dataset_manifest/core.py", line 738, in _is_video_manifest
    return validator.validate()
  File "/home/django/utils/dataset_manifest/core.py", line 651, in validate
    with open(self._manifest.path, 'r') as manifest:
FileNotFoundError: [Errno 2] No such file or directory: '/home/django/share/manifest.jsonl'
```

### Current workarround:
Replace `"storage": "share"` with `"storage": "local"` in the task.json

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by davy-blavette** [comment]
up....the same for project.

Create a Project from share
Backup the Project
Try to create a project from the backup on new instance

```
Could not restore project backup.
FileNotFoundError: [Errno 2] No such file or directory: '/home/django/share/manifest.jsonl'
```
