### ISSUE TITLE
requests.exceptions.HTTPError: 408 for serverless automatic annotation

### ISSUE THREAD

**Issue by prnr** [opencv/cvat#6192]
### My actions before raising this issue
- [O] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [O] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. Compose with https://github.com/opencv/cvat/issues/4904 override option, serverless
2. ./serverless/deploy_gpu.sh serverless/tensorflow/matterport/mask_rcnn
     with    - kind: RUN \  value: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A4B469963BF863CC added function-gpu.yaml
3. Automatic annotation with 50,000/17,000/2,300 images
4. Try with cvat v2.4.0 to 2.4.4, nuclio v1.8.14/1.11.20, docker desktop 4.16.3 to 4.19.0
5. Try with 1~8 workers

### Current Behaviour

![sc 2023-05-24 190124](https://github.com/opencv/cvat/assets/22967869/552d511f-7c55-40e9-8102-64d319cb0710)

There is no logs in cvat_opa/cvat_server container.

Logs from `cvat_worker_annotation` container
[cvat_worker_annotation.txt](https://github.com/opencv/cvat/files/11553590/cvat_worker_annotation.txt)

Logs from `nuclio` container
[nuclio-dashboard.txt](https://github.com/opencv/cvat/files/11553591/nuclio-dashboard.txt)

Logs from `nuclio-nuclio-tf-matterport-mask-rcnn' container
[nuclio-mrcnn-tf-gpu.txt](https://github.com/opencv/cvat/files/11553593/nuclio-mrcnn-tf-gpu.txt)

<summary>docker ps</summary>
<details>
CONTAINER ID   IMAGE                                      COMMAND                  CREATED             STATUS
         PORTS                                                    NAMES
a7517fb2281d   cvat.tf.matterport.mask_rcnn:latest        "processor"              12 minutes ago      Up 12 minutes (healthy)   0.0.0.0:6949->8080/tcp                                   nuclio-nuclio-tf-matterport-mask-rcnn
b9b98dbb54d2   gcr.io/iguazio/alpine:3.17                 "/bin/sh -c '/bin/sl…"   49 minutes ago      Up 49 minutes                                                                      nuclio-local-storage-reader
a1bf2072d552   cvat/ui:dev                                "/docker-entrypoint.…"   About an hour ago   Up 49 minutes             80/tcp                                                   cvat_ui
b61e3a0f59ab   cvat/server:dev                            "/usr/bin/supervisor…"   About an hour ago   Up 10 minutes             8080/tcp, 0.0.0.0:9091->9091/tcp                         cvat_worker_annotation
72d68b839e01   cvat/server:dev                            "/usr/bin/supervisor…"   About an hour ago   Up 49 minutes             8080/tcp                                                 cvat_worker_webhooks
82b815bc0942   cvat/server:dev                            "/usr/bin/supervisor…"   About an hour ago   Up 49 minutes             8080/tcp                                                 cvat_utils
db08b691224c   cvat/server:dev                            "/usr/bin/supervisor…"   About an hour ago   Up 49 minutes             8080/tcp, 0.0.0.0:9090->9090/tcp                         cvat_server
18a73b3b5c67   cvat/server:dev                            "/usr/bin/supervisor…"   About an hour ago   Up 49 minutes             8080/tcp, 0.0.0.0:9093->9093/tcp                         cvat_worker_import
5de12f98e28d   cvat/server:dev                            "/usr/bin/supervisor…"   About an hour ago   Up 49 minutes             8080/tcp, 0.0.0.0:9092->9092/tcp                         cvat_worker_export
f925cf69adb5   timberio/vector:0.26.0-alpine              "/usr/local/bin/vect…"   About an hour ago   Up 49 minutes                                                                      cvat_vector
7455d7499990   quay.io/nuclio/dashboard:1.11.20-amd64     "/docker-entrypoint.…"   About an hour ago   Up 49 minutes (healthy)   80/tcp, 0.0.0.0:8070->8070/tcp                           nuclio
31a39920a230   postgres:15-alpine                         "docker-entrypoint.s…"   About an hour ago   Up 49 minutes             0.0.0.0:5432->5432/tcp                                   cvat_db
d7d821a766c3   traefik:v2.9                               "/entrypoint.sh --pr…"   About an hour ago   Up 49 minutes             0.0.0.0:8080->8080/tcp, 80/tcp, 0.0.0.0:8090->8090/tcp   traefik
9421629faef3   clickhouse/clickhouse-server:22.3-alpine   "/entrypoint.sh"         About an hour ago   Up 49 minutes             8123/tcp, 9000/tcp, 9009/tcp                             cvat_clickhouse
13758a12b35d   redis:7.0-alpine                           "docker-entrypoint.s…"   About an hour ago   Up 49 minutes             6379/tcp                                                 cvat_redis
5dbc5f799dba   openpolicyagent/opa:0.45.0-rootless        "/opa run --server -…"   About an hour ago   Up 11 minutes             0.0.0.0:8181->8181/tcp                                   cvat_opa
</details>

### Context

I've tried dozens of rebuilds, rebuilds, repository changes, vpn, and even hardware rebuilds, but no changes. I'm trying hard to send a message from nuclio but I'm in despair seeing no response from server or opa container.
Where the hell did it go wrong?

### Your Environment

- Git hash commit (`git log -1`):commit 157f7e3596b4638b4d5730baf087828522e25245 (HEAD -> develop, origin/develop, origin/HEAD)
- Docker version `docker version` (e.g. Docker 17.0.05): Docker Desktop 4.16.3 https://docs.docker.com/desktop/release-notes/#4163
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Windows, WSL2 with Ubuntu-20.04
- Other diagnostic information / logs:

**Comment by bsekachev** [comment]
Try to increase ``eventTimeout`` in function.yaml. Default value is ``30sec`` for this time it is expected that the serverless function returns result. But according to logs from ``[nuclio-mrcnn-tf-gpu.txt](https://github.com/opencv/cvat/files/11553593/nuclio-mrcnn-tf-gpu.txt)``, looks like time is not enough.

**Comment by prnr** [comment]
Well, I've increased the eventTimeout to 180 seconds (180,000 ms), but it still doesn't fix the problem. I actually get [processor.timeout] without waiting for 180 seconds `2023-05-25 11:37:00 23.05.25 02:37:00.180         processor.timeout (I) Restarting worker due to timeout {"trigger": 0, "worker": 2, "elapsed": "36.159806264s"}
`, but I don't know if communication between containers is a problem or not.

```2023-05-25 11:36:25 2023-05-25 02:36:25.830300: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2023-05-25 11:36:26 2023-05-25 02:36:26.094780: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2023-05-25 11:37:00 23.05.25 02:37:00.180         processor.timeout (I) Restarting worker due to timeout {"trigger": 0, "worker": 2, "elapsed": "36.159806264s"}
2023-05-25 11:37:00 23.05.25 02:37:00.181 sor.http.w2.python.logger (W) Stopping {"status": "ready", "wrapperProcess": {"Pid":22}}
2023-05-25 11:37:00 23.05.25 02:37:00.181 sor.http.w2.python.logger (W) Killing wrapper process {"wrapperProcessPid": 22}
2023-05-25 11:37:00 23.05.25 02:37:00.181 sor.http.w2.python.logger (D) Process watch cancelled. Returning {"pid": 22, "wid": 2}
2023-05-25 11:37:00 23.05.25 02:37:00.181 sor.http.w2.python.logger (D) Process terminated {"wid": 2, "process": {"Pid":22}}
2023-05-25 11:37:00 23.05.25 02:37:00.181 sor.http.w2.python.logger (W) Successfully stopped wrapper process
2023-05-25 11:37:00 23.05.25 02:37:00.181 sor.http.w2.python.logger (D) Creating listener socket {"path": "/tmp/nuclio-rpc-chncjj1vrfb96bmkfvvg.sock"}
2023-05-25 11:37:00 23.05.25 02:37:00.181 sor.http.w2.python.logger (D) Creating listener socket {"path": "/tmp/nuclio-rpc-chncjj1vrfb96bmkg000.sock"}
2023-05-25 11:37:00 23.05.25 02:37:00.181 sor.http.w2.python.logger (W) Python 3.6 runtime is deprecated and will soon not be supported. Migrate your code and use Python 3.9 runtime (`python:3.9`) or higher
2023-05-25 11:37:00 23.05.25 02:37:00.181 sor.http.w2.python.logger (D) Using Python wrapper script path {"path": "/opt/nuclio/_nuclio_wrapper.py"}
2023-05-25 11:37:00 23.05.25 02:37:00.181 sor.http.w2.python.logger (D) Using Python handler {"handler": "main:handler"}
2023-05-25 11:37:00 23.05.25 02:37:00.181 sor.http.w2.python.logger (D) Using Python executable {"path": "/usr/bin/python3"}
2023-05-25 11:37:00 23.05.25 02:37:00.181 sor.http.w2.python.logger (D) Setting PYTHONPATH {"value": "PYTHONPATH=/opt/nuclio"}
2023-05-25 11:37:00 23.05.25 02:37:00.181 sor.http.w2.python.logger (D) Running wrapper {"command": "/usr/bin/python3 -u /opt/nuclio/_nuclio_wrapper.py --handler main:handler --event-socket-path /tmp/nuclio-rpc-chncjj1vrfb96bmkfvvg.sock --control-socket-path /tmp/nuclio-rpc-chncjj1vrfb96bmkg000.sock --platform-kind local --namespace nuclio --worker-id 2 --trigger-kind http --trigger-name myHttpTrigger --decode-event-strings"}
2023-05-25 11:37:00 23.05.25 02:37:00.313 sor.http.w2.python.logger (W) Failed to read control message {"err": "Failed to read from event connection"}
2023-05-25 11:37:00 23.05.25 02:37:00.321 sor.http.w2.python.logger (W) Failed to read from event connection {"err": "EOF"}
2023-05-25 11:37:00 23.05.25 02:37:00.321 sor.http.w2.python.logger (W) Control output handler was canceled (Restart called?)
2023-05-25 11:37:00 23.05.25 02:37:00.321 sor.http.w2.python.logger (E) Panic caught while handling event wrapper output (Restart called?) {"err": "send on closed channel", "stack": "goroutine 89 [running]:\nruntime/debug.Stack()\n\t/opt/hostedtoolcache/go/1.19.9/x64/src/runtime/debug/stack.go:24 +0x65\ngithub.com/nuclio/nuclio/pkg/common.CatchAndLogPanicWithOptions({0x23f5618, 0xc00005e040}, {0x2406260, 0xc0003c66e0}, {0x1ef7808, 0x2f}, 0xc000537e90)\n\t/home/runner/work/nuclio/nuclio/pkg/common/helper.go:454 +0x86\npanic({0x1be7960, 0x23d7580})\n\t/opt/hostedtoolcache/go/1.19.9/x64/src/runtime/panic.go:884 +0x212\ngithub.com/nuclio/nuclio/pkg/processor/runtime/rpc.(*AbstractRuntime).eventWrapperOutputHandler(0xc00052e000, {0x23de040?, 0xc000632058?}, 0xc000632048?)\n\t/home/runner/work/nuclio/nuclio/pkg/processor/runtime/rpc/abstract.go:445 +0x652\ncreated by github.com/nuclio/nuclio/pkg/processor/runtime/rpc.(*AbstractRuntime).startWrapper\n\t/home/runner/work/nuclio/nuclio/pkg/processor/runtime/rpc/abstract.go:311 +0x4ea\n"}```

**Comment by prnr** [comment]
![image](https://github.com/opencv/cvat/assets/22967869/b911bac0-48a4-425e-a3b1-04e658950457)
Oh, this time ReadTimeout is coming at me. I think I've seen this message a few times while trying again. Considering that log recording is delayed every time on '2023-05-25 12:14:46 2023-05-25 03:14:46.866639: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7', is there a problem here?

**Comment by prnr** [comment]
> Try to increase `eventTimeout` in function.yaml. Default value is `30sec` for this time it is expected that the serverless function returns result. But according to logs from `[nuclio-mrcnn-tf-gpu.txt](https://github.com/opencv/cvat/files/11553593/nuclio-mrcnn-tf-gpu.txt)`, looks like time is not enough.

![image](https://github.com/opencv/cvat/assets/22967869/11b53050-fa47-42f0-9358-a336479dd7e1)

Oh, this time ReadTimeout is coming at me. I think I've seen this message a few times while trying again. Considering that log recording is delayed every time on '2023-05-25 12:14:46 2023-05-25 03:14:46.866639: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7', is there a problem here?

**Comment by bsekachev** [comment]
@prnr 

I do not have any ideas about CUDNN actually.
Are you able to run this model on WSL2 out of docker? 
What if you try to do it in Docker, but manually, going inside and running the model?

**Comment by prnr** [comment]
> @prnr
> 
> I do not have any ideas about CUDNN actually. Are you able to run this model on WSL2 out of docker? What if you try to do it in Docker, but manually, going inside and running the model?

What means 'run this model on WSL2 out of docker'? 
I think they want me to run it on docker terminal, but I don't know what to do. 
I'm not a professional developer, but I have a low understanding of the structure, and I don't know how. 
I'm sorry I'm Noob...
