### ISSUE TITLE
Auto annotation using yolov5

### ISSUE THREAD

**Issue by AhmedEmadEldinHussin** [opencv/cvat#6252]
1. i configures yolov5 for a custom yolov5 model 
2. I change the function.yaml
3. i cahnegd the main function

    model = torch.hub.load('ultralytics/yolov5', '/home/ahmed/cvat/serverless/pytorch/ultralytics/yolov5/mixed/weights/weights.best.pt', force_reload=True)

console output
Error: Inference status for the task 1 is failed. Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/opt/venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/opt/venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f3d09742470>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/opt/venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='host.docker.internal', port=32802): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3d09742470>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/rq/worker.py", line 936, in perform_job
    rv = job.perform()
  File "/opt/venv/lib/python3.10/site-packages/rq/job.py", line 684, in perform
    self._result = self._execute()
  File "/opt/venv/lib/python3.10/site-packages/rq/job.py", line 690, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/django/cvat/apps/lambda_manager/views.py", line 687, in __call__
    LambdaJob._call_detector(function, db_task, labels, quality,
  File "/home/django/cvat/apps/lambda_manager/views.py", line 525, in _call_detector
    annotations = function.invoke(db_task, data={
  File "/home/django/cvat/apps/lambda_manager/views.py", line 302, in invoke
    response = self.gateway.invoke(self, payload)
  File "/home/django/cvat/apps/lambda_manager/views.py", line 98, in invoke
    return invoke_method[settings.NUCLIO['INVOKE_METHOD']](func, payload)
  File "/home/django/cvat/apps/lambda_manager/views.py", line 116, in _invoke_directly
    reply = session.post(url, timeout=NUCLIO_TIMEOUT, json=payload)
  File "/opt/venv/lib/python3.10/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/venv/lib/python3.10/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='host.docker.internal', port=32802): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3d09742470>: Failed to establish a new connection: [Errno 111] Connection refused'))

and docker container logs

Traceback (most recent call last):
  File "/opt/nuclio/_nuclio_wrapper.py", line 432, in <module>
    run_wrapper()
  File "/opt/nuclio/_nuclio_wrapper.py", line 420, in run_wrapper
    loop.run_until_complete(wrapper_instance.initialize())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/opt/nuclio/_nuclio_wrapper.py", line 147, in initialize
    await self._initialize_context()
  File "/opt/nuclio/_nuclio_wrapper.py", line 158, in _initialize_context
    init_context_result = getattr(self._entrypoint_module, 'init_context')(self._context)
  File "/opt/nuclio/main.py", line 11, in init_context
    model = torch.hub.load('ultralytics/yolov5', '/home/ahmed/cvat/serverless/pytorch/ultralytics/yolov5/mixed/weights/weights.best.pt', force_reload=True)  # or yolov5m, yolov5l, yolov5x, custom
  File "/usr/local/lib/python3.10/dist-packages/torch/hub.py", line 558, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/hub.py", line 586, in _load_local
    entry = _load_entry_from_hubconf(hub_module, model)
  File "/usr/local/lib/python3.10/dist-packages/torch/hub.py", line 340, in _load_entry_from_hubconf
    raise RuntimeError('Cannot find callable {} in hubconf'.format(model))
RuntimeError: Cannot find callable /home/ahmed/cvat/serverless/pytorch/ultralytics/yolov5/mixed/weights/weights.best.pt in hubconf
23.06.06 11:15:29.776 sor.http.w0.python.logger (E) Exception raised while running init_context {"worker_id": "0"}
Traceback (most recent call last):
  File "/opt/nuclio/_nuclio_wrapper.py", line 432, in <module>
    run_wrapper()
  File "/opt/nuclio/_nuclio_wrapper.py", line 420, in run_wrapper
    loop.run_until_complete(wrapper_instance.initialize())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/opt/nuclio/_nuclio_wrapper.py", line 147, in initialize
    await self._initialize_context()
  File "/opt/nuclio/_nuclio_wrapper.py", line 158, in _initialize_context
    init_context_result = getattr(self._entrypoint_module, 'init_context')(self._context)
  File "/opt/nuclio/main.py", line 11, in init_context
    model = torch.hub.load('ultralytics/yolov5', '/home/ahmed/cvat/serverless/pytorch/ultralytics/yolov5/mixed/weights/weights.best.pt', force_reload=True)  # or yolov5m, yolov5l, yolov5x, custom
  File "/usr/local/lib/python3.10/dist-packages/torch/hub.py", line 558, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/hub.py", line 586, in _load_local
    entry = _load_entry_from_hubconf(hub_module, model)
  File "/usr/local/lib/python3.10/dist-packages/torch/hub.py", line 340, in _load_entry_from_hubconf
    raise RuntimeError('Cannot find callable {} in hubconf'.format(model))
RuntimeError: Cannot find callable /home/ahmed/cvat/serverless/pytorch/ultralytics/yolov5/mixed/weights/weights.best.pt in hubconf
23.06.06 11:15:29.798 sor.http.w1.python.logger (W) Failed to read from connection {"err": "EOF"}
23.06.06 11:15:29.799 sor.http.w1.python.logger (E) Unexpected termination of child process {"error": null, "status": "exit status 1"}
panic: Wrapper process for worker 1 exited unexpectedly with: exit status 1

**Comment by realtimshady1** [comment]
the script is running in a docker container which does not have access to the path that you have specified. you need to copy the weights file to the same folder as the main.py & function.yaml and then use torch.load('weights.best.pt') not torch.hub.load().

**Comment by AhmedEmadEldinHussin** [comment]
yes, Thanks 
I have just solved it

**Comment by HERIUN** [comment]
how did you solved it?

i replace main.py
```
 torch.hub.load(~~)=> torch.load('weights.best.pt').
```
but 'nuctl get function' building forever

**Comment by realtimshady1** [comment]
did you make sure the weights file is copied to the same folder as the main.py & function.yaml?
