### ISSUE TITLE
CVAT does not work due to clickhouse container fail

### ISSUE THREAD

**Issue by sazonovanton** [opencv/cvat#6254]
### Prerequisites 
Not really an issue, just question

Tried to spin up CVAT from v2.4.5 and v2.4.4 [releases](https://github.com/opencv/cvat/releases/) on a RHEL 8 server (docker version 24.0.2).  
CVAT is failing to start and clickhouse container is restarting (webpage on ip:8080 has error message about checking if everything is correct).  

Server does only have restricted internet access so docker images (for 2.4.5 and 2.4.4 versions) was loaded beforehand with `docker load --input xxxxx` command.  
Images was saved with `docker save -o xxxx.tar iiiiiii` from Ubuntu server where CVAT was working normally (this server has unrestricted internet access, docker version 24.0.1).  

Enviromental variables CVAT_HOST and CVAT_VERSION were exported correctly in each case with server IP and CVAT version that was tried.  Images and volumes were deleted between trying different versions.

### Question:  
What can be a problem?

### Some information:  

Output of `docker ps` example:
```
CONTAINER ID   IMAGE                                      COMMAND                  CREATED              STATUS              PORTS                                                                                          NAMES
93ea49b8d324   cvat/ui:v2.4.4                             "/docker-entrypoint.…"   About a minute ago   Up About a minute   80/tcp                                                                                         cvat_ui
4a370cc5a581   cvat/server:v2.4.4                         "/usr/bin/supervisor…"   About a minute ago   Up About a minute   8080/tcp                                                                                       cvat_worker_annotation
1cedc3de7dea   cvat/server:v2.4.4                         "/usr/bin/supervisor…"   About a minute ago   Up About a minute   8080/tcp                                                                                       cvat_server
89892c56061f   cvat/server:v2.4.4                         "/usr/bin/supervisor…"   About a minute ago   Up About a minute   8080/tcp                                                                                       cvat_worker_import
3b1926837288   cvat/server:v2.4.4                         "/usr/bin/supervisor…"   About a minute ago   Up About a minute   8080/tcp                                                                                       cvat_utils
d939eec9162f   cvat/server:v2.4.4                         "/usr/bin/supervisor…"   About a minute ago   Up About a minute   8080/tcp                                                                                       cvat_worker_webhooks
17c4945199ff   timberio/vector:0.26.0-alpine              "/usr/local/bin/vect…"   About a minute ago   Up About a minute                                                                                                  cvat_vector
259264fd2e84   cvat/server:v2.4.4                         "/usr/bin/supervisor…"   About a minute ago   Up About a minute   8080/tcp                                                                                       cvat_worker_export
d0c9e40a9e6a   clickhouse/clickhouse-server:22.3-alpine   "/entrypoint.sh"         About a minute ago   Up 3 seconds        8123/tcp, 9000/tcp, 9009/tcp                                                                   cvat_clickhouse
683577a8eae7   postgres:15-alpine                         "docker-entrypoint.s…"   About a minute ago   Up About a minute   5432/tcp                                                                                       cvat_db
ca3495cf9208   traefik:v2.9                               "/entrypoint.sh --pr…"   About a minute ago   Up About a minute   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp, 80/tcp, 0.0.0.0:8090->8090/tcp, :::8090->8090/tcp   traefik
69b9cbfb0715   redis:7.0-alpine                           "docker-entrypoint.s…"   About a minute ago   Up About a minute   6379/tcp                                                                                       cvat_redis
7da2fdb671e2   openpolicyagent/opa:0.45.0-rootless        "/opa run --server -…"   About a minute ago   Up About a minute                                                                                                  cvat_opa
```

Some output of `docker compose logs`:
```
cvat_clickhouse         | ClickHouse init process failed.
cvat_clickhouse exited with code 1
cvat_clickhouse         | /entrypoint.sh: create new user 'user' instead 'default'
cvat_clickhouse         | Processing configuration file '/etc/clickhouse-server/config.xml'.
cvat_clickhouse         | Merging configuration file '/etc/clickhouse-server/config.d/docker_related_config.xml'.
cvat_clickhouse         | Logging trace to /var/log/clickhouse-server/clickhouse-server.log
cvat_clickhouse         | Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
cvat_clickhouse         | Processing configuration file '/etc/clickhouse-server/config.xml'.
cvat_clickhouse         | Merging configuration file '/etc/clickhouse-server/config.d/docker_related_config.xml'.
cvat_clickhouse         | Saved preprocessed configuration to '/var/lib/clickhouse/preprocessed_configs/config.xml'.
cvat_clickhouse         | Processing configuration file '/etc/clickhouse-server/users.xml'.
cvat_clickhouse         | Merging configuration file '/etc/clickhouse-server/users.d/default-user.xml'.
cvat_clickhouse         | Saved preprocessed configuration to '/var/lib/clickhouse/preprocessed_configs/users.xml'.
cvat_opa                | {"level":"error","msg":"Bundle load failed: server replied with Gateway Timeout","name":"cvat","plugin":"bundle","time":"2023-06-06T17:38:03Z"}
```

Tried to set `CLICKHOUSE_INIT_TIMEOUT` to 60 in `docker-compose.yml`, nothing changed:
```
  cvat_clickhouse:
    container_name: cvat_clickhouse
    image: clickhouse/clickhouse-server:22.3-alpine
    restart: always
    environment:
      - CLICKHOUSE_DB=cvat
      - CLICKHOUSE_USER=user
      - CLICKHOUSE_PASSWORD=user
      - CLICKHOUSE_INIT_TIMEOUT=60
    networks:
      cvat:
        aliases:
          - clickhouse
    volumes:
      - ./components/analytics/clickhouse/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - cvat_events_db:/var/lib/clickhouse/
```

**Comment by bsekachev** [comment]
Unfortunately we can not help here, because the installation pipeline was custom.

**Comment by sazonovanton** [comment]
Sorry for long reply. Tried setting up CVAT v2.4.9. Here logs for server and clickhouse (saved with `docker logs __ > cvat___.log`):

[cvat_clickhouse.log](https://github.com/opencv/cvat/files/11969207/cvat_clickhouse.log)
[cvat_server.log](https://github.com/opencv/cvat/files/11969209/cvat_server.log)

**Comment by bsekachev** [comment]
@sazonovanton 

I see there are issues with Open Policy Agent container. 
So, check ``cvat_opa`` logs additionally. 

```
2023-07-06 14:20:17,342 DEBG 'uvicorn-1' stderr output:
ERROR:health-check:unknown error: 500 Server Error: Internal Server Error for url: http://opa:8181/health?bundles
Traceback (most recent call last):
  File "/home/django/cvat/apps/health/backends.py", line 25, in check_status
    response.raise_for_status()
  File "/opt/venv/lib/python3.10/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://opa:8181/health?bundles

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/health_check/backends.py", line 30, in run_check
    self.check_status()
  File "/home/django/cvat/apps/health/backends.py", line 27, in check_status
    raise HealthCheckException(str(e))
health_check.exceptions.HealthCheckException: unknown error: 500 Server Error: Internal Server Error for url: http://opa:8181/health?bundles
```

**Comment by sazonovanton** [comment]
Here is `cvat_opa` log
[cvat_opa.log](https://github.com/opencv/cvat/files/11970709/cvat_opa.log)

**Comment by sazonovanton** [comment]
Difference between systems where everything starts and don't work mainly in internet connection and OS.

**Comment by bsekachev** [comment]
I am not sure it is because of connection or OS.
Currently bundle with open policy agent rules can not be loaded:

```{"level":"error","msg":"Bundle load failed: server replied with Gateway Timeout","name":"cvat","plugin":"bundle","time":"2023-06-06T17:38:03Z"}```. It triggers health check fail. Need to understand why Open Policy Agent can not access CVAT main server when trying to get rules.

**Comment by bsekachev** [comment]
BTW, do you have ``cvat`` network setup in Docker? 

``docker network ls``

**Comment by sazonovanton** [comment]
`docker network ls` output:
```
NETWORK ID     NAME            DRIVER    SCOPE
b3034717a5bf   bridge          bridge    local
7f81d21e6983   cvat-249_cvat   bridge    local
7c30b791a012   host            host      local
e614000fff29   none            null      local
```

**Comment by sazonovanton** [comment]
Changed that.
`docker network ls`
```
NETWORK ID     NAME        DRIVER    SCOPE
b3034717a5bf   bridge      bridge    local
816408e875ff   cvat_cvat   bridge    local
7c30b791a012   host        host      local

e614000fff29   none        null      local
```
`docker compose logs` output in file.
[logs.txt](https://github.com/opencv/cvat/files/12050024/logs.txt)


I'll dig into problem further
