### ISSUE TITLE
CVAT taking too much space in my root directory

### ISSUE THREAD

**Issue by NevilleMthw** [opencv/cvat#6273]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. Unable to connect to CVAT application.
2. The root directory is getting full.

### Expected Behaviour

The CVAT application needs to connect to the server but I assume this is regarding my root directory getting full. I have tried to increase the storage on my root directory as well but that got filled up quickly for some unknown reason. I increased it from 20GB to another 20GB increase but there is only 2GB left free again. The application just takes too much space quickly. Could it be the docker container? Is there any specific command to fix the space?

![image](https://github.com/opencv/cvat/assets/18580821/beadcedf-ce34-4682-ac09-74c9f1e8d80b)

I tried to use the health check command too but no luck cause of the space issue.

```
Traceback (most recent call last):
  File "/home/django/manage.py", line 21, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 382, in execute
    settings.INSTALLED_APPS
  File "/opt/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/opt/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/django/cvat/settings/production.py", line 5, in <module>
    from .base import *
  File "/home/django/cvat/settings/base.py", line 446, in <module>
    os.makedirs(Path(IAM_OPA_BUNDLE_PATH).parent, exist_ok=True)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [Errno 28] No space left on device: '/home/django/static/opa'
```

### Your Environment

- Git hash commit (`git log -1`): N/A
- Docker version `docker version` (e.g. Docker 17.0.05): 24.0.2
- Are you using Docker Swarm or Kubernetes? Docker
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu Linux
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by NevilleMthw** [comment]
This issue is similar to what I am seeing at #5449.
