### ISSUE TITLE
Error: Could not get models from the server

### ISSUE THREAD

**Issue by hardikdava** [opencv/cvat#6346]
I have followed the serverless tutorial from building nuclio to starting docker using given instruction from latest develop branch. But I am getting following error while starting the annotation ui:
```
Could not get models from the server

Error: Request failed with status code 500. "\n<!doctype html>\n<html lang="en">\n<head>\n <title>Server Error (500)</title>\n</head>\n<body>\n <h1>Server Error (500)</h1><p></p>\n</body>\n</html>\n".
```
Further information:
- I was able to get nuclio dashboard running.
- I can see new implemented serverless function in dashboard.
- No error while building the server.
- But no model showing in "Models" tab in CVAT UI.

It was running fine before I update the develop branch locally. Any help would be appreciated.

**Comment by zhiltsov-max** [comment]
Hi, please attach server logs from `docker logs cvat_server`.

**Comment by hardikdava** [comment]
Hi @zhiltsov-max , I found this error in logs:

```
2023-06-21 08:48:47,724 DEBG 'uvicorn-1' stderr output:
[2023-06-21 08:48:47,724] ERROR django.request: Internal Server Error: /api/lambda/functions
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "/opt/venv/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/django/cvat/apps/lambda_manager/views.py", line 804, in func_wrapper
    data = func(*args, **kwargs)
  File "/home/django/cvat/apps/lambda_manager/views.py", line 850, in list
    return [f.to_dict() for f in gateway.list()]
  File "/home/django/cvat/apps/lambda_manager/views.py", line 91, in list
    response = [LambdaFunction(self, item) for item in data.values()]
  File "/home/django/cvat/apps/lambda_manager/views.py", line 91, in <listcomp>
    response = [LambdaFunction(self, item) for item in data.values()]
  File "/home/django/cvat/apps/lambda_manager/views.py", line 141, in __init__
    spec = json.loads(meta_anno.get('spec') or '[]')
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 3 column 3 (char 33)

2023-06-21 08:48:47,724 DEBG 'uvicorn-1' stderr output:
ERROR:django.request:Internal Server Error: /api/lambda/functions
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "/opt/venv/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/django/cvat/apps/lambda_manager/views.py", line 804, in func_wrapper
    data = func(*args, **kwargs)
  File "/home/django/cvat/apps/lambda_manager/views.py", line 850, in list
    return [f.to_dict() for f in gateway.list()]
  File "/home/django/cvat/apps/lambda_manager/views.py", line 91, in list
    response = [LambdaFunction(self, item) for item in data.values()]
  File "/home/django/cvat/apps/lambda_manager/views.py", line 91, in <listcomp>
    response = [LambdaFunction(self, item) for item in data.values()]
  File "/home/django/cvat/apps/lambda_manager/views.py", line 141, in __init__
    spec = json.loads(meta_anno.get('spec') or '[]')
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 3 column 3 (char 33)


```

**Comment by zhiltsov-max** [comment]
Could you please tell which functions are deployed? I assume, there is a function with invalid meta info.

**Comment by hardikdava** [comment]
@zhiltsov-max is error comes from serverless function or is it in cvat core function? I deployed yolov7 function

**Comment by zhiltsov-max** [comment]
I assume you're using `https://github.com/opencv/cvat/tree/develop/serverless/onnx/WongKinYiu/yolov7/nuclio`.
Did you change anything in `function.yaml` or `function-gpu.yaml`? Please make sure there are correct json documents for labels in the `metadata/annotations/spec` field in both files.

**Comment by hardikdava** [comment]
I found an error in meta file. Thanks for the help! Closing the issue.
