### ISSUE TITLE
create task from backup retruen error

### ISSUE THREAD

**Issue by papandadj** [opencv/cvat#6416]
I create task from backup file and Its return error code 500:
![image](https://github.com/opencv/cvat/assets/25424898/77f56ee7-25d5-45a7-8233-1e529726b06c)

This is log of import server:
```log
INFO:rq.worker:import: cvat.apps.engine.backup._import_task('/Users/po/github/papandadj/cvat/data/tmp/taskbk7036.zip', 1, None) (import:task.ed3a9209-e42a-4b43-8fa0-ae89ab866cc0-by-admin)
[2023-07-03 03:45:22,582] INFO cvat.server: create task #38
INFO:cvat.server:create task #38
[2023-07-03 03:45:22,588] WARNING cvat.server: Skip 'index.json' file (its mime type doesn't correspond to supported MIME file type)
WARNING:cvat.server:Skip 'index.json' file (its mime type doesn't correspond to supported MIME file type)
[2023-07-03 03:45:22,588] WARNING cvat.server: Skip 'images/.DS_Store' file (its mime type doesn't correspond to supported MIME file type)
WARNING:cvat.server:Skip 'images/.DS_Store' file (its mime type doesn't correspond to supported MIME file type)
[2023-07-03 03:45:22,589] WARNING cvat.server: Skip '__MACOSX/images/._.DS_Store' file (its mime type doesn't correspond to supported MIME file type)
WARNING:cvat.server:Skip '__MACOSX/images/._.DS_Store' file (its mime type doesn't correspond to supported MIME file type)
ERROR:rq.worker:Traceback (most recent call last):
  File "/Users/po/github/papandadj/cvat/.env/lib/python3.11/site-packages/rq/worker.py", line 936, in perform_job
    rv = job.perform()
         ^^^^^^^^^^^^^
  File "/Users/po/github/papandadj/cvat/.env/lib/python3.11/site-packages/rq/job.py", line 684, in perform
    self._result = self._execute()
                   ^^^^^^^^^^^^^^^
  File "/Users/po/github/papandadj/cvat/.env/lib/python3.11/site-packages/rq/job.py", line 690, in _execute
    return self.func(*self.args, **self.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/po/github/papandadj/cvat/cvat/apps/engine/backup.py", line 632, in _import_task
    db_task = task_importer.import_task()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/po/github/papandadj/cvat/cvat/apps/engine/backup.py", line 624, in import_task
    self._import_task()
  File "/Users/po/github/papandadj/cvat/cvat/apps/engine/backup.py", line 606, in _import_task
    _create_thread(self._db_task.pk, data.copy(), isBackupRestore=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/po/github/papandadj/cvat/cvat/apps/engine/task.py", line 757, in _create_thread
    raise Exception('Incorrect file mapping to manifest content')
Exception: Incorrect file mapping to manifest content
Traceback (most recent call last):
  File "/Users/po/github/papandadj/cvat/.env/lib/python3.11/site-packages/rq/worker.py", line 936, in perform_job
    rv = job.perform()
         ^^^^^^^^^^^^^
  File "/Users/po/github/papandadj/cvat/.env/lib/python3.11/site-packages/rq/job.py", line 684, in perform
    self._result = self._execute()
                   ^^^^^^^^^^^^^^^
  File "/Users/po/github/papandadj/cvat/.env/lib/python3.11/site-packages/rq/job.py", line 690, in _execute
    return self.func(*self.args, **self.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/po/github/papandadj/cvat/cvat/apps/engine/backup.py", line 632, in _import_task
    db_task = task_importer.import_task()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/po/github/papandadj/cvat/cvat/apps/engine/backup.py", line 624, in import_task
    self._import_task()
  File "/Users/po/github/papandadj/cvat/cvat/apps/engine/backup.py", line 606, in _import_task
    _create_thread(self._db_task.pk, data.copy(), isBackupRestore=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/po/github/papandadj/cvat/cvat/apps/engine/task.py", line 757, in _create_thread
    raise Exception('Incorrect file mapping to manifest content')
Exception: Incorrect file mapping to manifest content
```
This is my backup task file:
[taskbk7036.zip](https://github.com/opencv/cvat/files/11932737/taskbk7036.zip)

**Comment by bsekachev** [comment]
How did you get this file? 
It contains extra directory ``data/__MACOSX``. If you remove it, importing backup is successful.

**Comment by papandadj** [comment]
Thinks for your answer. I remove __MACOSX and use macos compress It's not work. I use LInux to compress zip file, It's work. This might be a macOS issue.
