### ISSUE TITLE
Bug: right clicking keypoints causes error

### ISSUE THREAD

**Issue by isobelm** [opencv/cvat#6558]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Right clicking keypoints in a skeleton causes the following error:

```
TypeError
Cannot read properties of undefined (reading 'isGroundTruth')

TypeError: Cannot read properties of undefined (reading 'isGroundTruth')
    at q5 (https://app.cvat.ai/assets/cvat-ui.38c7c7f55a8ddc11730e.min.js:2:8905415)
    at Ko (https://app.cvat.ai/assets/cvat-ui.38c7c7f55a8ddc11730e.min.js:2:5932062)
    at zi (https://app.cvat.ai/assets/cvat-ui.38c7c7f55a8ddc11730e.min.js:2:5940911)
    at ws (https://app.cvat.ai/assets/cvat-ui.38c7c7f55a8ddc11730e.min.js:2:5979186)
    at pl (https://app.cvat.ai/assets/cvat-ui.38c7c7f55a8ddc11730e.min.js:2:5970743)
    at dl (https://app.cvat.ai/assets/cvat-ui.38c7c7f55a8ddc11730e.min.js:2:5970668)
    at rl (https://app.cvat.ai/assets/cvat-ui.38c7c7f55a8ddc11730e.min.js:2:5967698)
    at https://app.cvat.ai/assets/cvat-ui.38c7c7f55a8ddc11730e.min.js:2:5919471
    at t.unstable_runWithPriority (https://app.cvat.ai/assets/cvat-ui.38c7c7f55a8ddc11730e.min.js:2:6128522)
    at Wa (https://app.cvat.ai/assets/cvat-ui.38c7c7f55a8ddc11730e.min.js:2:5919180)
```

### Steps to Reproduce (for bugs)

1.  Create keypoint skeleton
2.  Add skeleton shape to image/annotation
3.  Right click on a keypoint

### Your Environment

- OS: MacOS 13.2 
- Browser: Chrome Version 114.0.5735.198
- CVAT version
    - Server: 2.5.1
    - Core: 9.2.0
    - Canvas: 2.17.0
    - UI: 1.53.0

**Comment by bsekachev** [comment]
@isobelm 
Thank you for the report, we will investigate it.

**Comment by bsekachev** [comment]
Deployed, made new release.
