### ISSUE TITLE
Deploying CVAT on AWS EC2 fails 

### ISSUE THREAD

**Issue by il-nietos** [opencv/cvat#6564]
### My actions before raising this issue
- [x ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. Follow installation steps for Ubuntu in https://opencv.github.io/cvat/docs/administration/basics/installation/#ubuntu-1804-x86_64amd64

2. EC2 security group: Allow inbound traffic with the following specifications: 
type: Custom TCP
Protocol: TCP
Port range: 8080
Source: Anywhere IP

3. export CVAT_HOST=[public IPv4 address of EC2]

4. docker compose up -d

5. In chrome go to [public IPv4 address of EC2]:8080

### Expected Behaviour
For CVAT to run in the browser with [public IPv4 address of EC2]:8080

### Current Behaviour
When I go to chrome browser with [public IPv4 address of EC2]:8080, I get the message :
'```
Cannot connect to the server
Make sure the CVAT backend and all necessary services (Database, Redis and Open Policy Agent) are running and available. If you upgraded from version 2.2.0 or earlier, manual actions may be needed, see the [Upgrade Guide](https://opencv.github.io/cvat/docs/administration/advanced/upgrade_guide)'

```

### Context
I'm trying to deploy CVAT on an AWS EC2 with Ubuntu. 

### Your Environment
<!--- Include relevant details about the environment you experienced
the bug in -->
- Docker version: Docker version 24.0.5, build ced0996
- latest version of chrome
- Operating System and version: Ubuntu 20.04.6 LTS
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat_dv` container</summary>
PostgreSQL Database directory appears to contain a database; Skipping initialization

2023-07-26 15:18:17.216 UTC [1] LOG:  starting PostgreSQL 15.3 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit
2023-07-26 15:18:17.216 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-07-26 15:18:17.216 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2023-07-26 15:18:17.221 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-07-26 15:18:17.228 UTC [24] LOG:  database system was shut down at 2023-07-26 15:18:07 UTC
2023-07-26 15:18:17.234 UTC [1] LOG:  database system is ready to accept connections
2023-07-26 15:18:18.739 UTC [28] LOG:  incomplete startup packet
2023-07-26 15:18:38.873 UTC [32] LOG:  incomplete startup packet
2023-07-26 15:18:38.875 UTC [33] LOG:  incomplete startup packet
2023-07-26 15:23:17.327 UTC [22] LOG:  checkpoint starting: time
2023-07-26 15:23:17.845 UTC [22] LOG:  checkpoint complete: wrote 8 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.505 s, sync=0.004 s, total=0.518 s; sync files=8, longest=0.003 s, average=0.001 s; distance=22 kB, estimate=22 kB
2023-07-26 16:08:18.647 UTC [22] LOG:  checkpoint starting: time
2023-07-26 16:08:18.965 UTC [22] LOG:  checkpoint complete: wrote 4 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.303 s, sync=0.004 s, total=0.319 s; sync files=4, longest=0.003 s, average=0.001 s; distance=4 kB, estimate=20 kB

    </details>

    <details>
    <summary>Logs from `cvat_server` container</summary>
2023-07-26 16:04:43,257 DEBG 'uvicorn-1' stderr output:
ERROR:health-check:warning: e8026c27e08b 91.7% disk usage exceeds 90%
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/health_check/backends.py", line 30, in run_check
    self.check_status()
  File "/opt/venv/lib/python3.10/site-packages/health_check/contrib/psutil/backends.py", line 21, in check_status
    raise ServiceWarning(
health_check.exceptions.ServiceWarning: warning: e8026c27e08b 91.7% disk usage exceeds 90%

2023-07-26 16:04:43,317 DEBG 'uvicorn-1' stderr output:
[2023-07-26 16:04:43,316] ERROR django.request: Internal Server Error: /api/server/health/

INFO:     46.142.206.210:0 - "GET /api/server/health/?format=json&org= HTTP/1.0" 500 Internal Server Error
2023-07-26 16:04:43,317 DEBG 'uvicorn-1' stdout output:
INFO:     46.142.206.210:0 - "GET /api/server/health/?format=json&org= HTTP/1.0" 500 Internal Server Error

2023-07-26 16:04:43,317 DEBG 'uvicorn-1' stderr output:
ERROR:django.request:Internal Server Error: /api/server/health/

2023-07-26 16:04:46,386 DEBG 'uvicorn-1' stderr output:
ERROR:health-check:warning: e8026c27e08b 91.7% disk usage exceeds 90%
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/health_check/backends.py", line 30, in run_check
    self.check_status()
  File "/opt/venv/lib/python3.10/site-packages/health_check/contrib/psutil/backends.py", line 21, in check_status
    raise ServiceWarning(
health_check.exceptions.ServiceWarning: warning: e8026c27e08b 91.7% disk usage exceeds 90%

2023-07-26 16:04:46,450 DEBG 'uvicorn-1' stderr output:
[2023-07-26 16:04:46,450] ERROR django.request: Internal Server Error: /api/server/health/

INFO:     46.142.206.210:0 - "GET /api/server/health/?format=json&org= HTTP/1.0" 500 Internal Server Error
2023-07-26 16:04:46,450 DEBG 'uvicorn-1' stdout output:
INFO:     46.142.206.210:0 - "GET /api/server/health/?format=json&org= HTTP/1.0" 500 Internal Server Error

2023-07-26 16:04:46,450 DEBG 'uvicorn-1' stderr output:
ERROR:django.request:Internal Server Error: /api/server/health/

INFO:     172.23.0.2:0 - "GET /api/auth/rules HTTP/1.0" 304 Not Modified
2023-07-26 16:04:52,238 DEBG 'uvicorn-1' stdout output:
INFO:     172.23.0.2:0 - "GET /api/auth/rules HTTP/1.0" 304 Not Modified

2023-07-26 16:04:52,871 DEBG 'uvicorn-1' stderr output:
[2023-07-26 16:04:52,871] WARNING django.request: Unauthorized: /api/events

INFO:     46.142.206.210:0 - "POST /api/events?org= HTTP/1.0" 401 Unauthorized
2023-07-26 16:04:52,873 DEBG 'uvicorn-1' stdout output:
INFO:     46.142.206.210:0 - "POST /api/events?org= HTTP/1.0" 401 Unauthorized

2023-07-26 16:04:52,873 DEBG 'uvicorn-1' stderr output:
WARNING:django.request:Unauthorized: /api/events

INFO:     172.23.0.2:0 - "GET /api/auth/rules HTTP/1.0" 304 Not Modified
2023-07-26 16:05:03,448 DEBG 'uvicorn-1' stdout output:
INFO:     172.23.0.2:0 - "GET /api/auth/rules HTTP/1.0" 304 Not Modified

2023-07-26 16:05:07,841 DEBG 'uvicorn-1' stderr output:
[2023-07-26 16:05:07,841] WARNING django.request: Unauthorized: /api/events

2023-07-26 16:05:07,841 DEBG 'uvicorn-1' stderr output:
WARNING:django.request:Unauthorized: /api/events

INFO:     46.142.206.210:0 - "POST /api/events?org= HTTP/1.0" 401 Unauthorized
2023-07-26 16:05:07,841 DEBG 'uvicorn-1' stdout output:
INFO:     46.142.206.210:0 - "POST /api/events?org= HTTP/1.0" 401 Unauthorized

    </details>

**Comment by azhavoro** [comment]
As you can see the reason is 
```
health_check.exceptions.ServiceWarning: warning: e8026c27e08b 91.7% disk usage exceeds 90%
```
You need to increase storage size or free up disk space
