### ISSUE TITLE
Restore Container With Backup

### ISSUE THREAD

**Issue by rpl-zhichao-zheng** [opencv/cvat#6607]
I was trying to migrate cvat to another disk, following the instruction in 
https://opencv.github.io/cvat/docs/administration/advanced/backup_guide/#about-cvat-data-volumes

after restoring and compose up the docker server,  the docker server was keep restarting, and the error message was:

wait-for-it.sh: cvat_db:5432 is available after 0 seconds
Traceback (most recent call last):
  File "/home/django/manage.py", line 21, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 100, in handle
    self.check(databases=[database])
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/opt/venv/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/opt/venv/lib/python3.10/site-packages/django/core/checks/caches.py", line 65, in check_file_based_cache_is_absolute
    cache = caches[alias]
  File "/opt/venv/lib/python3.10/site-packages/django/utils/connection.py", line 62, in __getitem__
    conn = self.create_connection(alias)
  File "/opt/venv/lib/python3.10/site-packages/django/core/cache/__init__.py", line 52, in create_connection
    return backend_cls(location, params)
  File "/opt/venv/lib/python3.10/site-packages/diskcache/djangocache.py", line 31, in __init__
    self._cache = FanoutCache(directory, shards, timeout, **options)
  File "/opt/venv/lib/python3.10/site-packages/diskcache/fanout.py", line 42, in __init__
    self._shards = tuple(
  File "/opt/venv/lib/python3.10/site-packages/diskcache/fanout.py", line 43, in <genexpr>
    Cache(
  File "/opt/venv/lib/python3.10/site-packages/diskcache/core.py", line 499, in __init__
    sql(query, (key, value))
  File "/opt/venv/lib/python3.10/site-packages/diskcache/core.py", line 666, in _execute_with_retry
    return sql(statement, *args, **kwargs)
sqlite3.OperationalError: attempt to write a readonly database
wait-for-it.sh: waiting for cvat_db:5432 without a timeout
wait-for-it.sh: cvat_db:5432 is available after 0 seconds
Traceback (most recent call last):
  File "/home/django/manage.py", line 21, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 100, in handle
    self.check(databases=[database])
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/opt/venv/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/opt/venv/lib/python3.10/site-packages/django/core/checks/caches.py", line 65, in check_file_based_cache_is_absolute
    cache = caches[alias]
  File "/opt/venv/lib/python3.10/site-packages/django/utils/connection.py", line 62, in __getitem__
    conn = self.create_connection(alias)
  File "/opt/venv/lib/python3.10/site-packages/django/core/cache/__init__.py", line 52, in create_connection
    return backend_cls(location, params)
  File "/opt/venv/lib/python3.10/site-packages/diskcache/djangocache.py", line 31, in __init__
    self._cache = FanoutCache(directory, shards, timeout, **options)
  File "/opt/venv/lib/python3.10/site-packages/diskcache/fanout.py", line 42, in __init__
    self._shards = tuple(
  File "/opt/venv/lib/python3.10/site-packages/diskcache/fanout.py", line 43, in <genexpr>
    Cache(
  File "/opt/venv/lib/python3.10/site-packages/diskcache/core.py", line 499, in __init__
    sql(query, (key, value))
  File "/opt/venv/lib/python3.10/site-packages/diskcache/core.py", line 666, in _execute_with_retry
    return sql(statement, *args, **kwargs)
sqlite3.OperationalError: attempt to write a readonly database
wait-for-it.sh: waiting for cvat_db:5432 without a timeout
wait-for-it.sh: cvat_db:5432 is available after 0 seconds
Traceback (most recent call last):
  File "/home/django/manage.py", line 21, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 100, in handle
    self.check(databases=[database])
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/opt/venv/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/opt/venv/lib/python3.10/site-packages/django/core/checks/caches.py", line 65, in check_file_based_cache_is_absolute
    cache = caches[alias]
  File "/opt/venv/lib/python3.10/site-packages/django/utils/connection.py", line 62, in __getitem__
    conn = self.create_connection(alias)
  File "/opt/venv/lib/python3.10/site-packages/django/core/cache/__init__.py", line 52, in create_connection
    return backend_cls(location, params)
  File "/opt/venv/lib/python3.10/site-packages/diskcache/djangocache.py", line 31, in __init__
    self._cache = FanoutCache(directory, shards, timeout, **options)
  File "/opt/venv/lib/python3.10/site-packages/diskcache/fanout.py", line 42, in __init__
    self._shards = tuple(
  File "/opt/venv/lib/python3.10/site-packages/diskcache/fanout.py", line 43, in <genexpr>
    Cache(
  File "/opt/venv/lib/python3.10/site-packages/diskcache/core.py", line 499, in __init__
    sql(query, (key, value))
  File "/opt/venv/lib/python3.10/site-packages/diskcache/core.py", line 666, in _execute_with_retry
    return sql(statement, *args, **kwargs)
sqlite3.OperationalError: attempt to write a readonly database

**Comment by rpl-zhichao-zheng** [comment]
if I recover the /var/lib/docker with previous backup, it becomes:

2023-08-02 21:49:49,305 DEBG fd 7 closed, stopped monitoring <POutputDispatcher at 140686638396128 for <Subprocess at 140686638396032 with name ssh-agent in state STOPPING> (stdout)>
2023-08-02 21:49:49,305 DEBG fd 9 closed, stopped monitoring <POutputDispatcher at 140686638870592 for <Subprocess at 140686638396032 with name ssh-agent in state STOPPING> (stderr)>
2023-08-02 21:49:49,305 INFO stopped: ssh-agent (exit status 2)
2023-08-02 21:49:49,305 DEBG received SIGCHLD indicating a child quit
wait-for-it.sh: waiting for cvat_db:5432 without a timeout
wait-for-it.sh: cvat_db:5432 is available after 0 seconds
/bin/sh: 0: cannot open /home/django/backend_entrypoint.sh: Permission denied
/bin/sh: 0: cannot open /home/django/backend_entrypoint.sh: Permission denied
/bin/sh: 0: cannot open /home/django/backend_entrypoint.sh: Permission denied
/bin/sh: 0: cannot open /home/django/backend_entrypoint.sh: Permission denied
/bin/sh: 0: cannot open /home/django/backend_entrypoint.sh: Permission denied
/bin/sh: 0: cannot open /home/django/backend_entrypoint.sh: Permission denied
/bin/sh: 0: cannot open /home/django/backend_entrypoint.sh: Permission denied
/bin/sh: 0: cannot open /home/django/backend_entrypoint.sh: Permission denied
/bin/sh: 0: cannot open /home/django/backend_entrypoint.sh: Permission denied
/bin/sh: 0: cannot open /home/django/backend_entrypoint.sh: Permission denied

**Comment by azhavoro** [comment]
@rpl-zhichao-zheng regarding the first issue trying this:
```terminal
docker exec -it cvat_server bash
rm -rf /home/django/data/cache/*
```
for the second issue make sure that `backend_entrypoint.sh` file is executable

**Comment by rpl-zhichao-zheng** [comment]
![Screenshot from 2023-08-04 10-30-13](https://github.com/opencv/cvat/assets/132406686/33405626-b48e-439c-9aa7-a3558b07fd1d)
 container keep restarting, can't run any command

**Comment by rpl-zhichao-zheng** [comment]
![Screenshot from 2023-08-04 10-42-31](https://github.com/opencv/cvat/assets/132406686/2b01014f-8e4a-43b9-ac88-54d050db1e47)
Not able to make backend_entrypoint.sh executable as well due to the same reason
