### ISSUE TITLE
Got weird error with label config through SDK

### ISSUE THREAD

**Issue by panghanwu** [opencv/cvat#6652]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Hi there, I encounter a weird issue when I try to create a project with SDK.
Here is my CVAT version:
 Server: 2.6
 Core: 10.0.0
 Canvas: 2.17.2
 UI: 1.54.1

When I tried to create a project with customized skeleton labels through the SDK, I got this error message on the labels:
```
SyntaxError
Failed to execute 'querySelector' on 'Element': '[data-node-id=""9""]' is not a valid selector.

Error: Failed to execute 'querySelector' on 'Element': '[data-node-id=""9""]' is not a valid selector.
    at uX.setupEdge (http://localhost:8080/assets/cvat-ui.71591519f7f193333eda.min.js:2:11443272)
    at uX.setupSkeleton (http://localhost:8080/assets/cvat-ui.71591519f7f193333eda.min.js:2:11443064)
    at uX.componentDidMount (http://localhost:8080/assets/cvat-ui.71591519f7f193333eda.min.js:2:11448044)
    at ii (http://localhost:8080/assets/cvat-ui.71591519f7f193333eda.min.js:2:7262389)
    at gs (http://localhost:8080/assets/cvat-ui.71591519f7f193333eda.min.js:2:7280015)
    at n.unstable_runWithPriority (http://localhost:8080/assets/cvat-ui.71591519f7f193333eda.min.js:2:7416730)
    at Wo (http://localhost:8080/assets/cvat-ui.71591519f7f193333eda.min.js:2:7224118)
    at As (http://localhost:8080/assets/cvat-ui.71591519f7f193333eda.min.js:2:7276681)
    at as (http://localhost:8080/assets/cvat-ui.71591519f7f193333eda.min.js:2:7272835)
    at http://localhost:8080/assets/cvat-ui.71591519f7f193333eda.min.js:2:7224409
```
It seems I may have the "double quotation marks" in my labels config, but I actually cannot find it.
More weird thing is if I clear the Raw section on the UI side manually, and paste the exatly same config text onto it, then it work!

Could anyone kindly help me check out this? Thanks.

**Comment by panghanwu** [comment]
Here is my lable config. It's coco pose keypoints basically.

```
[
  {
    "name": "coco_pose",
    "id": 171,
    "color": "#5d43db",
    "type": "skeleton",
    "sublabels": [
      {
        "name": "1",
        "attributes": [],
        "type": "points",
        "color": "#d12345",
        "id": 172
      },
      {
        "name": "2",
        "attributes": [],
        "type": "points",
        "color": "#350dea",
        "id": 173
      },
      {
        "name": "3",
        "attributes": [],
        "type": "points",
        "color": "#479ffe",
        "id": 174
      },
      {
        "name": "4",
        "attributes": [],
        "type": "points",
        "color": "#4a649f",
        "id": 175
      },
      {
        "name": "5",
        "attributes": [],
        "type": "points",
        "color": "#478144",
        "id": 176
      },
      {
        "name": "6",
        "attributes": [],
        "type": "points",
        "color": "#57236b",
        "id": 177
      },
      {
        "name": "7",
        "attributes": [],
        "type": "points",
        "color": "#1cdda5",
        "id": 178
      },
      {
        "name": "8",
        "attributes": [],
        "type": "points",
        "color": "#e2bc6e",
        "id": 179
      },
      {
        "name": "9",
        "attributes": [],
        "type": "points",
        "color": "#f067db",
        "id": 180
      },
      {
        "name": "10",
        "attributes": [],
        "type": "points",
        "color": "#63bbfa",
        "id": 181
      },
      {
        "name": "11",
        "attributes": [],
        "type": "points",
        "color": "#22b16f",
        "id": 182
      },
      {
        "name": "12",
        "attributes": [],
        "type": "points",
        "color": "#daddec",
        "id": 183
      },
      {
        "name": "13",
        "attributes": [],
        "type": "points",
        "color": "#2ac791",
        "id": 184
      },
      {
        "name": "14",
        "attributes": [],
        "type": "points",
        "color": "#de22a0",
        "id": 185
      },
      {
        "name": "15",
        "attributes": [],
        "type": "points",
        "color": "#a7a570",
        "id": 186
      },
      {
        "name": "16",
        "attributes": [],
        "type": "points",
        "color": "#74db1b",
        "id": 187
      },
      {
        "name": "17",
        "attributes": [],
        "type": "points",
        "color": "#aaa246",
        "id": 188
      }
    ],
    "svg": "<line x1=&quot;71.57190704345703&quot; y1=&quot;36.02503204345703&quot; x2=&quot;74.24748992919922&quot; y2=&quot;48.73406219482422&quot; stroke=&quot;black&quot; data-type=&quot;edge&quot; data-node-from=&quot;9&quot; stroke-width=&quot;0.5&quot; data-node-to=&quot;11&quot;></line><line x1=&quot;57.52508544921875&quot; y1=&quot;25.65713882446289&quot; x2=&quot;71.57190704345703&quot; y2=&quot;36.02503204345703&quot; stroke=&quot;black&quot; data-type=&quot;edge&quot; data-node-from=&quot;7&quot; stroke-width=&quot;0.5&quot; data-node-to=&quot;9&quot;></line><line x1=&quot;27.759197235107422&quot; y1=&quot;36.192256927490234&quot; x2=&quot;23.913043975830078&quot; y2=&quot;47.39626693725586&quot; stroke=&quot;black&quot; data-type=&quot;edge&quot; data-node-from=&quot;8&quot; stroke-width=&quot;0.5&quot; data-node-to=&quot;10&quot;></line><line x1=&quot;37.95986557006836&quot; y1=&quot;26.49325942993164&quot; x2=&quot;27.759197235107422&quot; y2=&quot;36.192256927490234&quot; stroke=&quot;black&quot; data-type=&quot;edge&quot; data-node-from=&quot;6&quot; stroke-width=&quot;0.5&quot; data-node-to=&quot;8&quot;></line><line x1=&quot;55.35116958618164&quot; y1=&quot;56.76081848144531&quot; x2=&quot;56.68896484375&quot; y2=&quot;63.951454162597656&quot; stroke=&quot;black&quot; data-type=&quot;edge&quot; data-node-from=&quot;15&quot; stroke-width=&quot;0.5&quot; data-node-to=&quot;17&quot;></line><line x1=&quot;39.79933166503906&quot; y1=&quot;56.76081848144531&quot; x2=&quot;38.12709045410156&quot; y2=&quot;63.951454162597656&quot; stroke=&quot;black&quot; data-type=&quot;edge&quot; data-node-from=&quot;14&quot; stroke-width=&quot;0.5&quot; data-node-to=&quot;16&quot;></line><line x1=&quot;55.518394470214844&quot; y1=&quot;42.21232223510742&quot; x2=&quot;55.35116958618164&quot; y2=&quot;56.76081848144531&quot; stroke=&quot;black&quot; data-type=&quot;edge&quot; data-node-from=&quot;13&quot; stroke-width=&quot;0.5&quot; data-node-to=&quot;15&quot;></line><line x1=&quot;38.79598617553711&quot; y1=&quot;43.04844284057617&quot; x2=&quot;39.79933166503906&quot; y2=&quot;56.76081848144531&quot; stroke=&quot;black&quot; data-type=&quot;edge&quot; data-node-from=&quot;12&quot; stroke-width=&quot;0.5&quot; data-node-to=&quot;14&quot;></line><line x1=&quot;55.518394470214844&quot; y1=&quot;42.21232223510742&quot; x2=&quot;57.52508544921875&quot; y2=&quot;25.65713882446289&quot; stroke=&quot;black&quot; data-type=&quot;edge&quot; data-node-from=&quot;13&quot; stroke-width=&quot;0.5&quot; data-node-to=&quot;7&quot;></line><line x1=&quot;38.79598617553711&quot; y1=&quot;43.04844284057617&quot; x2=&quot;55.518394470214844&quot; y2=&quot;42.21232223510742&quot; stroke=&quot;black&quot; data-type=&quot;edge&quot; data-node-from=&quot;12&quot; stroke-width=&quot;0.5&quot; data-node-to=&quot;13&quot;></line><line x1=&quot;37.95986557006836&quot; y1=&quot;26.49325942993164&quot; x2=&quot;38.79598617553711&quot; y2=&quot;43.04844284057617&quot; stroke=&quot;black&quot; data-type=&quot;edge&quot; data-node-from=&quot;6&quot; stroke-width=&quot;0.5&quot; data-node-to=&quot;12&quot;></line><line x1=&quot;37.95986557006836&quot; y1=&quot;26.49325942993164&quot; x2=&quot;39.29765701293945&quot; y2=&quot;17.630382537841797&quot; stroke=&quot;black&quot; data-type=&quot;edge&quot; data-node-from=&quot;6&quot; stroke-width=&quot;0.5&quot; data-node-to=&quot;4&quot;></line><line x1=&quot;57.52508544921875&quot; y1=&quot;25.65713882446289&quot; x2=&quot;37.95986557006836&quot; y2=&quot;26.49325942993164&quot; stroke=&quot;black&quot; data-type=&quot;edge&quot; data-node-from=&quot;7&quot; stroke-width=&quot;0.5&quot; data-node-to=&quot;6&quot;></line><line x1=&quot;57.02341079711914&quot; y1=&quot;17.797607421875&quot; x2=&quot;57.52508544921875&quot; y2=&quot;25.65713882446289&quot; stroke=&quot;black&quot; data-type=&quot;edge&quot; data-node-from=&quot;5&quot; stroke-width=&quot;0.5&quot; data-node-to=&quot;7&quot;></line><line x1=&quot;52.67558670043945&quot; y1=&quot;12.27921199798584&quot; x2=&quot;57.02341079711914&quot; y2=&quot;17.797607421875&quot; stroke=&quot;black&quot; data-type=&quot;edge&quot; data-node-from=&quot;3&quot; stroke-width=&quot;0.5&quot; data-node-to=&quot;5&quot;></line><line x1=&quot;42.97658920288086&quot; y1=&quot;13.11533260345459&quot; x2=&quot;39.29765701293945&quot; y2=&quot;17.630382537841797&quot; stroke=&quot;black&quot; data-type=&quot;edge&quot; data-node-from=&quot;2&quot; stroke-width=&quot;0.5&quot; data-node-to=&quot;4&quot;></line><line x1=&quot;42.97658920288086&quot; y1=&quot;13.11533260345459&quot; x2=&quot;52.67558670043945&quot; y2=&quot;12.27921199798584&quot; stroke=&quot;black&quot; data-type=&quot;edge&quot; data-node-from=&quot;2&quot; stroke-width=&quot;0.5&quot; data-node-to=&quot;3&quot;></line><line x1=&quot;47.32441329956055&quot; y1=&quot;19.302623748779297&quot; x2=&quot;52.67558670043945&quot; y2=&quot;12.27921199798584&quot; stroke=&quot;black&quot; data-type=&quot;edge&quot; data-node-from=&quot;1&quot; stroke-width=&quot;0.5&quot; data-node-to=&quot;3&quot;></line><line x1=&quot;42.97658920288086&quot; y1=&quot;13.11533260345459&quot; x2=&quot;47.32441329956055&quot; y2=&quot;19.302623748779297&quot; stroke=&quot;black&quot; data-type=&quot;edge&quot; data-node-from=&quot;2&quot; stroke-width=&quot;0.5&quot; data-node-to=&quot;1&quot;></line><circle r=&quot;1.5&quot; stroke=&quot;black&quot; fill=&quot;#b3b3b3&quot; cx=&quot;47.32441329956055&quot; cy=&quot;19.302623748779297&quot; stroke-width=&quot;0.1&quot; data-type=&quot;element node&quot; data-element-id=&quot;1&quot; data-node-id=&quot;1&quot; data-label-id=&quot;82&quot;></circle><circle r=&quot;1.5&quot; stroke=&quot;black&quot; fill=&quot;#b3b3b3&quot; cx=&quot;42.97658920288086&quot; cy=&quot;13.11533260345459&quot; stroke-width=&quot;0.1&quot; data-type=&quot;element node&quot; data-element-id=&quot;2&quot; data-node-id=&quot;2&quot; data-label-id=&quot;83&quot;></circle><circle r=&quot;1.5&quot; stroke=&quot;black&quot; fill=&quot;#b3b3b3&quot; cx=&quot;52.67558670043945&quot; cy=&quot;12.27921199798584&quot; stroke-width=&quot;0.1&quot; data-type=&quot;element node&quot; data-element-id=&quot;3&quot; data-node-id=&quot;3&quot; data-label-id=&quot;84&quot;></circle><circle r=&quot;1.5&quot; stroke=&quot;black&quot; fill=&quot;#b3b3b3&quot; cx=&quot;39.29765701293945&quot; cy=&quot;17.630382537841797&quot; stroke-width=&quot;0.1&quot; data-type=&quot;element node&quot; data-element-id=&quot;4&quot; data-node-id=&quot;4&quot; data-label-id=&quot;85&quot;></circle><circle r=&quot;1.5&quot; stroke=&quot;black&quot; fill=&quot;#b3b3b3&quot; cx=&quot;57.02341079711914&quot; cy=&quot;17.797607421875&quot; stroke-width=&quot;0.1&quot; data-type=&quot;element node&quot; data-element-id=&quot;5&quot; data-node-id=&quot;5&quot; data-label-id=&quot;86&quot;></circle><circle r=&quot;1.5&quot; stroke=&quot;black&quot; fill=&quot;#b3b3b3&quot; cx=&quot;37.95986557006836&quot; cy=&quot;26.49325942993164&quot; stroke-width=&quot;0.1&quot; data-type=&quot;element node&quot; data-element-id=&quot;6&quot; data-node-id=&quot;6&quot; data-label-id=&quot;87&quot;></circle><circle r=&quot;1.5&quot; stroke=&quot;black&quot; fill=&quot;#b3b3b3&quot; cx=&quot;57.52508544921875&quot; cy=&quot;25.65713882446289&quot; stroke-width=&quot;0.1&quot; data-type=&quot;element node&quot; data-element-id=&quot;7&quot; data-node-id=&quot;7&quot; data-label-id=&quot;88&quot;></circle><circle r=&quot;1.5&quot; stroke=&quot;black&quot; fill=&quot;#b3b3b3&quot; cx=&quot;27.759197235107422&quot; cy=&quot;36.192256927490234&quot; stroke-width=&quot;0.1&quot; data-type=&quot;element node&quot; data-element-id=&quot;8&quot; data-node-id=&quot;8&quot; data-label-id=&quot;89&quot;></circle><circle r=&quot;1.5&quot; stroke=&quot;black&quot; fill=&quot;#b3b3b3&quot; cx=&quot;71.57190704345703&quot; cy=&quot;36.02503204345703&quot; stroke-width=&quot;0.1&quot; data-type=&quot;element node&quot; data-element-id=&quot;9&quot; data-node-id=&quot;9&quot; data-label-id=&quot;90&quot;></circle><circle r=&quot;1.5&quot; stroke=&quot;black&quot; fill=&quot;#b3b3b3&quot; cx=&quot;23.913043975830078&quot; cy=&quot;47.39626693725586&quot; stroke-width=&quot;0.1&quot; data-type=&quot;element node&quot; data-element-id=&quot;10&quot; data-node-id=&quot;10&quot; data-label-id=&quot;91&quot;></circle><circle r=&quot;1.5&quot; stroke=&quot;black&quot; fill=&quot;#b3b3b3&quot; cx=&quot;74.24748992919922&quot; cy=&quot;48.73406219482422&quot; stroke-width=&quot;0.1&quot; data-type=&quot;element node&quot; data-element-id=&quot;11&quot; data-node-id=&quot;11&quot; data-label-id=&quot;92&quot;></circle><circle r=&quot;1.5&quot; stroke=&quot;black&quot; fill=&quot;#b3b3b3&quot; cx=&quot;38.79598617553711&quot; cy=&quot;43.04844284057617&quot; stroke-width=&quot;0.1&quot; data-type=&quot;element node&quot; data-element-id=&quot;12&quot; data-node-id=&quot;12&quot; data-label-id=&quot;93&quot;></circle><circle r=&quot;1.5&quot; stroke=&quot;black&quot; fill=&quot;#b3b3b3&quot; cx=&quot;55.518394470214844&quot; cy=&quot;42.21232223510742&quot; stroke-width=&quot;0.1&quot; data-type=&quot;element node&quot; data-element-id=&quot;13&quot; data-node-id=&quot;13&quot; data-label-id=&quot;94&quot;></circle><circle r=&quot;1.5&quot; stroke=&quot;black&quot; fill=&quot;#b3b3b3&quot; cx=&quot;39.79933166503906&quot; cy=&quot;56.76081848144531&quot; stroke-width=&quot;0.1&quot; data-type=&quot;element node&quot; data-element-id=&quot;14&quot; data-node-id=&quot;14&quot; data-label-id=&quot;95&quot;></circle><circle r=&quot;1.5&quot; stroke=&quot;black&quot; fill=&quot;#b3b3b3&quot; cx=&quot;55.35116958618164&quot; cy=&quot;56.76081848144531&quot; stroke-width=&quot;0.1&quot; data-type=&quot;element node&quot; data-element-id=&quot;15&quot; data-node-id=&quot;15&quot; data-label-id=&quot;96&quot;></circle><circle r=&quot;1.5&quot; stroke=&quot;black&quot; fill=&quot;#b3b3b3&quot; cx=&quot;38.12709045410156&quot; cy=&quot;63.951454162597656&quot; stroke-width=&quot;0.1&quot; data-type=&quot;element node&quot; data-element-id=&quot;16&quot; data-node-id=&quot;16&quot; data-label-id=&quot;97&quot;></circle><circle r=&quot;1.5&quot; stroke=&quot;black&quot; fill=&quot;#b3b3b3&quot; cx=&quot;56.68896484375&quot; cy=&quot;63.951454162597656&quot; stroke-width=&quot;0.1&quot; data-type=&quot;element node&quot; data-element-id=&quot;17&quot; data-node-id=&quot;17&quot; data-label-id=&quot;98&quot;></circle>",
    "attributes": []
  }
]
```

**Comment by bsekachev** [comment]
@panghanwu 

You have some issues with provided svg template for skeleton:

```html
<line x1="71.57190704345703" y1="36.02503204345703" x2="74.24748992919922" y2="48.73406219482422" stroke="black" data-type="edge" data-node-from="9" stroke-width="0.5" data-node-to="11"></line>
<line x1="57.52508544921875" y1="25.65713882446289" x2="71.57190704345703" y2="36.02503204345703" stroke="black" data-type="edge" data-node-from="7" stroke-width="0.5" data-node-to="9"></line>
<line x1="27.759197235107422" y1="36.192256927490234" x2="23.913043975830078" y2="47.39626693725586" stroke="black" data-type="edge" data-node-from="8" stroke-width="0.5" data-node-to="10"></line>
<line x1="37.95986557006836" y1="26.49325942993164" x2="27.759197235107422" y2="36.192256927490234" stroke="black" data-type="edge" data-node-from="6" stroke-width="0.5" data-node-to="8"></line>
<line x1="55.35116958618164" y1="56.76081848144531" x2="56.68896484375" y2="63.951454162597656" stroke="black" data-type="edge" data-node-from="15" stroke-width="0.5" data-node-to="17"></line>
<line x1="39.79933166503906" y1="56.76081848144531" x2="38.12709045410156" y2="63.951454162597656" stroke="black" data-type="edge" data-node-from="14" stroke-width="0.5" data-node-to="16"></line>
<line x1="55.518394470214844" y1="42.21232223510742" x2="55.35116958618164" y2="56.76081848144531" stroke="black" data-type="edge" data-node-from="13" stroke-width="0.5" data-node-to="15"></line>
<line x1="38.79598617553711" y1="43.04844284057617" x2="39.79933166503906" y2="56.76081848144531" stroke="black" data-type="edge" data-node-from="12" stroke-width="0.5" data-node-to="14"></line>
<line x1="55.518394470214844" y1="42.21232223510742" x2="57.52508544921875" y2="25.65713882446289" stroke="black" data-type="edge" data-node-from="13" stroke-width="0.5" data-node-to="7"></line>
<line x1="38.79598617553711" y1="43.04844284057617" x2="55.518394470214844" y2="42.21232223510742" stroke="black" data-type="edge" data-node-from="12" stroke-width="0.5" data-node-to="13"></line>
<line x1="37.95986557006836" y1="26.49325942993164" x2="38.79598617553711" y2="43.04844284057617" stroke="black" data-type="edge" data-node-from="6" stroke-width="0.5" data-node-to="12"></line>
<line x1="37.95986557006836" y1="26.49325942993164" x2="39.29765701293945" y2="17.630382537841797" stroke="black" data-type="edge" data-node-from="6" stroke-width="0.5" data-node-to="4"></line>
<line x1="57.52508544921875" y1="25.65713882446289" x2="37.95986557006836" y2="26.49325942993164" stroke="black" data-type="edge" data-node-from="7" stroke-width="0.5" data-node-to="6"></line>
<line x1="57.02341079711914" y1="17.797607421875" x2="57.52508544921875" y2="25.65713882446289" stroke="black" data-type="edge" data-node-from="5" stroke-width="0.5" data-node-to="7"></line>
<line x1="52.67558670043945" y1="12.27921199798584" x2="57.02341079711914" y2="17.797607421875" stroke="black" data-type="edge" data-node-from="3" stroke-width="0.5" data-node-to="5"></line>
<line x1="42.97658920288086" y1="13.11533260345459" x2="39.29765701293945" y2="17.630382537841797" stroke="black" data-type="edge" data-node-from="2" stroke-width="0.5" data-node-to="4"></line>
<line x1="42.97658920288086" y1="13.11533260345459" x2="52.67558670043945" y2="12.27921199798584" stroke="black" data-type="edge" data-node-from="2" stroke-width="0.5" data-node-to="3"></line>
<line x1="47.32441329956055" y1="19.302623748779297" x2="52.67558670043945" y2="12.27921199798584" stroke="black" data-type="edge" data-node-from="1" stroke-width="0.5" data-node-to="3"></line>
<line x1="42.97658920288086" y1="13.11533260345459" x2="47.32441329956055" y2="19.302623748779297" stroke="black" data-type="edge" data-node-from="2" stroke-width="0.5" data-node-to="1"></line>
<circle r="1.5" stroke="black" fill="#b3b3b3" cx="47.32441329956055" cy="19.302623748779297" stroke-width="0.1" data-type="element node" data-element-id="1" data-node-id="1" data-label-id="82"></circle>
<circle r="1.5" stroke="black" fill="#b3b3b3" cx="42.97658920288086" cy="13.11533260345459" stroke-width="0.1" data-type="element node" data-element-id="2" data-node-id="2" data-label-id="83"></circle>
<circle r="1.5" stroke="black" fill="#b3b3b3" cx="52.67558670043945" cy="12.27921199798584" stroke-width="0.1" data-type="element node" data-element-id="3" data-node-id="3" data-label-id="84"></circle>
<circle r="1.5" stroke="black" fill="#b3b3b3" cx="39.29765701293945" cy="17.630382537841797" stroke-width="0.1" data-type="element node" data-element-id="4" data-node-id="4" data-label-id="85"></circle>
<circle r="1.5" stroke="black" fill="#b3b3b3" cx="57.02341079711914" cy="17.797607421875" stroke-width="0.1" data-type="element node" data-element-id="5" data-node-id="5" data-label-id="86"></circle>
<circle r="1.5" stroke="black" fill="#b3b3b3" cx="37.95986557006836" cy="26.49325942993164" stroke-width="0.1" data-type="element node" data-element-id="6" data-node-id="6" data-label-id="87"></circle>
<circle r="1.5" stroke="black" fill="#b3b3b3" cx="57.52508544921875" cy="25.65713882446289" stroke-width="0.1" data-type="element node" data-element-id="7" data-node-id="7" data-label-id="88"></circle>
<circle r="1.5" stroke="black" fill="#b3b3b3" cx="27.759197235107422" cy="36.192256927490234" stroke-width="0.1" data-type="element node" data-element-id="8" data-node-id="8" data-label-id="89"></circle>
<circle r="1.5" stroke="black" fill="#b3b3b3" cx="71.57190704345703" cy="36.02503204345703" stroke-width="0.1" data-type="element node" data-element-id="9" data-node-id="9" data-label-id="90"></circle>
<circle r="1.5" stroke="black" fill="#b3b3b3" cx="23.913043975830078" cy="47.39626693725586" stroke-width="0.1" data-type="element node" data-element-id="10" data-node-id="10" data-label-id="91"></circle>
<circle r="1.5" stroke="black" fill="#b3b3b3" cx="74.24748992919922" cy="48.73406219482422" stroke-width="0.1" data-type="element node" data-element-id="11" data-node-id="11" data-label-id="92"></circle>
<circle r="1.5" stroke="black" fill="#b3b3b3" cx="38.79598617553711" cy="43.04844284057617" stroke-width="0.1" data-type="element node" data-element-id="12" data-node-id="12" data-label-id="93"></circle>
<circle r="1.5" stroke="black" fill="#b3b3b3" cx="55.518394470214844" cy="42.21232223510742" stroke-width="0.1" data-type="element node" data-element-id="13" data-node-id="13" data-label-id="94"></circle>
<circle r="1.5" stroke="black" fill="#b3b3b3" cx="39.79933166503906" cy="56.76081848144531" stroke-width="0.1" data-type="element node" data-element-id="14" data-node-id="14" data-label-id="95"></circle>
<circle r="1.5" stroke="black" fill="#b3b3b3" cx="55.35116958618164" cy="56.76081848144531" stroke-width="0.1" data-type="element node" data-element-id="15" data-node-id="15" data-label-id="96"></circle>
<circle r="1.5" stroke="black" fill="#b3b3b3" cx="38.12709045410156" cy="63.951454162597656" stroke-width="0.1" data-type="element node" data-element-id="16" data-node-id="16" data-label-id="97"></circle>
<circle r="1.5" stroke="black" fill="#b3b3b3" cx="56.68896484375" cy="63.951454162597656" stroke-width="0.1" data-type="element node" data-element-id="17" data-node-id="17" data-label-id="98"></circle>
```

At least I see data-label-id="82 ... 98", but you do not have such labels in your skeleton. You have like 172..188.

When you first create the skeleton on the server, instead of ``data-label-id``, you need to use data-label-name with skeleton node name (because IDs don't exist yet), it will match on the server automatically and replace ``data-label-name`` to corresponding ``data-label-id`` after such IDs created

**Comment by bsekachev** [comment]
@panghanwu 

> More weird thing is if I clear the Raw section on the UI side manually, and paste the exatly same config text onto it, then it work!

When you paste text to Raw editor config, it does magic for you and do different things, one of them is changing ``data-label-id `` to ``data-label-name`` as I described, automatically.

**Comment by bsekachev** [comment]
FYI: https://github.com/opencv/cvat/blob/13bfb0555b074b620daee69ca2e35bcb49811bb3/cvat-ui/src/components/labels-editor/raw-viewer.tsx#L24
