### ISSUE TITLE
Can't upload annotations in any way (REST, SDK, CLI)

### ISSUE THREAD

**Issue by denisb411** [opencv/cvat#6678]
Hello,

Currently I successfully could create task and upload annotations using REST, but I needed to upload some COCO format annotations too. Firstly I tried to upload annotations using REST following the documentation. I came with the following code:

```python
print("SENDING annotations:")

file_path = "./annotations/instances_default.json"
file_name = file_path.split("/")[-1]

tasks_annotations_endpoint = (
    f"{cvat_api_address}/tasks/{task_id}/annotations?org={organization}&use_default_location=true&format=COCO+1.0&filename={file_name}&conv_mask_to_poly=true"
)

headers = {
    "Authorization": auth_token,
    "Upload-Filename": file_name,
    "Upload-Metadata": f"filename {(base64.b64encode(file_name.encode())).decode('utf-8')},filetype {base64.b64encode('application/json'.encode()).decode('utf-8')}",
    "Content-Type": "application/json",
}

with open(file_path, "rb") as f:

    payload = {
        "annotation_file": json.load(f),
    }

    response = requests.post(
        tasks_annotations_endpoint, headers=headers, data=json.dumps(payload)
    )


print(response.status_code)
print(response.text)
print(response.headers)

print(f"Task annotations uploaded")
```

And the following is printed:

```
400
"No such file were uploaded"
{'Allow': 'GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS', 'Content-Length': '28', 'Content-Type': 'application/vnd.cvat+json', 'Cross-Origin-Opener-Policy': 'same-origin', 'Date': 'Tue, 15 Aug 2023 16:58:24 GMT', 'Referrer-Policy': 'same-origin', 'Server': 'nginx/1.18.0 (Ubuntu)', 'Set-Cookie': 'csrftoken=FtVEI1yfW2q8E8VzDFEPtMUz5PJGQL9e; expires=Tue, 13 Aug 2024 16:58:24 GMT; Max-Age=31449600; Path=/; SameSite=Lax, sessionid=1zrnhf4qji0xaxmaokzrvi04ayirhbxu; expires=Tue, 29 Aug 2023 16:58:24 GMT; HttpOnly; Max-Age=1209600; Path=/; SameSite=Lax', 'Vary': 'Accept, Cookie, Origin', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'DENY', 'X-Request-Id': '26aee976-6272-453b-917b-2f660a75c3f3'}
Task annotations uploaded
```

Knowing this, I tried to use the cvat-sdk, but unfortunately it seems that the sdk version is not correctly synced with my CVAT deploy version. I use the following code:

```python
    annotation_file = "./annotations/instances_default.json"
    id = created_task.id # int | A unique integer value identifying this task.
    format = "COCO 1.0" # str | Input format name You can get the list of supported formats at: /server/annotation/formats (optional)
    task_annotations_update_request = TaskAnnotationsUpdateRequest()
    task_annotations_update_request.annotation_file = annotation_file

    try:
        api_client.tasks_api.update_annotations(
            id,
            format=format,
            task_annotations_update_request=task_annotations_update_request,
        )
    except exceptions.ApiException as e:
        print("Exception when calling TasksApi.update_annotations(): %s\n" % e)
```

And I get:
```
cvat_sdk.api_client.exceptions.ApiTypeError: Invalid type for variable 'annotation_file'. Required value type is IOBase and passed type was str at ['annotation_file']
```

If I import io.IOBase and use it on request, it gives:

```python
cvat_sdk.api_client.exceptions.ApiTypeError: Invalid type for variable 'annotation_file'. Required value type is one of [NoneType, bool, date, datetime, dict, float, int, list, str] and passed type was IOBase at ['annotation_file']
```

As one more tentative, I tried to use the CVAT cli with:

```bash
cvat-cli --server-host xxxxx --server-port 8080 --auth xxxxxx --debug upload 746 ./annotations/instances_default.json
```

And gives:
```
[2023-08-15 14:51:06] CRITICAL: Status Code: 404
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Allow': 'GET, PATCH, DELETE, HEAD, OPTIONS', 'Content-Length': '23', 'Content-Type': 'application/vnd.cvat+json', 'Cross-Origin-Opener-Policy': 'same-origin', 'Date': 'Tue, 15 Aug 2023 17:51:06 GMT', 'Referrer-Policy': 'same-origin', 'Server': 'nginx/1.18.0 (Ubuntu)', 'Vary': 'Accept, Origin', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'DENY', 'X-Request-Id': 'e308ea34-96c8-4409-a89e-29f9b95fc01c'})
HTTP response body: {"detail":"Not found."}
```

So I currently with no more ideas of which way I can make it work. Downgrading the CVAT deploy is not an alternative.

Could you please help me?

**Comment by zhiltsov-max** [comment]
Hi! Please try to use the high-level API instead. It seems, low-level API or bare requests are too complicated for now (since 2.3.0), and the only uploading method available now is via the TUS protocol:

```python
import json
import os
from cvat_sdk import make_client, models

with make_client("localhost", port=8080, credentials=("admin", "password")) as client:
    job = client.jobs.retrieve(42)

    annotations_filename = f"job_{job.id}_annotations-coco-1.0.zip"
    job.export_dataset("COCO 1.0", annotations_filename, include_images=False)

    job.import_annotations("COCO 1.0", annotations_filename, status_check_period=0.1)
```

**Comment by denisb411** [comment]
@zhiltsov-max Unfortunately it gives the following exception:

```
Traceback (most recent call last):
  File "/home/vntdeca@venturus.local/coccidiose/tests-api-cvat/create-task-sdk.py", line 122, in <module>
    created_task.export_dataset("COCO 1.0", annotations_filename, include_images=False)
  File "/home/vntdeca@venturus.local/anaconda3/envs/tf-od-210-310/lib/python3.10/site-packages/cvat_sdk/api_client/model_utils.py", line 201, in __getattr__
    return self.__getitem__(attr)
  File "/home/vntdeca@venturus.local/anaconda3/envs/tf-od-210-310/lib/python3.10/site-packages/cvat_sdk/api_client/model_utils.py", line 532, in __getitem__
    raise ApiAttributeError(
cvat_sdk.api_client.exceptions.ApiAttributeError: TaskRead has no attribute 'export_dataset' at ['['received_data']']['export_dataset']
```

**Comment by zhiltsov-max** [comment]
The error tells that the `created_task` is of the type `cvat_sdk.models.TaskRead`, while it needs to be of the type `cvat_sdk.core.proxies.tasks.Task`. How you obtain the `created_task` object? You can convert the first one to the second one using this line:

```python
from cvat_sdk.core.proxies.tasks import Task
...
highlevel_task = Task(client, created_task)
highlevel_task.import_annotations(...)
```

> When you mentioned the zip file, it's the zip file in COCO format that I use to upload the dataset?

In the sample - yes, it's downloaded right before uploading. You should be able to upload a single json file instead, if needed.

**Comment by denisb411** [comment]
I tried with:

```python
    print("Sending annotations")

    annotations_filename = f"./annotations/instances_default.json"

    task = api_client.tasks.retrieve(created_task.id)
    task.import_annotations('COCO 1.0', annotations_filename, status_check_period=0.1)
```

And it gave me:

```
Sending annotations
Traceback (most recent call last):
  File "/home/vntdeca@venturus.local/coccidiose/tests-api-cvat/create-task-sdk.py", line 126, in <module>
    task = api_client.tasks.retrieve(created_task.id)
  File "/home/vntdeca@venturus.local/anaconda3/envs/tf-od-210-310/lib/python3.10/site-packages/cvat_sdk/api_client/api_client.py", line 780, in __getattr__
    api_instance, api_klassname = self._apis.get(key, notfound)
TypeError: cannot unpack non-iterable object object
```

**Comment by denisb411** [comment]
Thanks!

I tried with:
```
with make_client('172.25.40.107', port='8080', credentials=('xxxxx', 'xxxxxx')) as client:

    print("Sending annotations")

    annotations_filename = f"./annotations/instances_default.json"

    task = client.tasks.retrieve(created_task.id)
    task.import_annotations('COCO 1.0', annotations_filename, status_check_period=0.1)
    
```

And it worked :)

**Comment by zhiltsov-max** [comment]
@Marishka17, could you please check if we can restore support for simple file uploading?

**Comment by subika-sri** [comment]
@zhiltsov-max what is I have to use 'https://app.cvat.ai/api' instead of "localhost", port=8080,

**Comment by zhiltsov-max** [comment]
@subika-sri, please use the SDK or CLI for this, as discussed above.

**Comment by subika-sri** [comment]
@zhiltsov-max, In that case if I want to use the link https://app.cvat.ai/ and login through my credentials instead of "localhost", port=8080 to upload the annotations. how can I do it?

**Comment by zhiltsov-max** [comment]
@subika-sri, the ways to login with SDK and specify the host are described [here](https://docs.cvat.ai/docs/api_sdk/sdk/highlevel-api/#client). If you want to upload to the platform, specify it's url when creating the `Client` object.

```python
import sys

from cvat_sdk import make_client
from cvat_sdk.core.helpers import DeferredTqdmProgressReporter


def main(argv=None):
    with make_client("https://app.cvat.ai", port=443, credentials=("user", "password")) as client:
        # client.organization_slug = ""
        client.config.status_check_period = 2

        task = client.tasks.retrieve(your_task_id)

        filename = f"task-{task.id}-cvat_for_images.zip"
        task.import_annotations("CVAT 1.1", filename=filename,
            pbar=DeferredTqdmProgressReporter()
        )


main(sys.argv)
```

**Comment by subika-sri** [comment]
@zhiltsov-max Thank you for your response and it worked. but if I want to do the same from cloud, how can I do it?

**Comment by zhiltsov-max** [comment]
@subika-sri, please check this [function](https://github.com/cvat-ai/cvat/blob/deb9681c6923d56768f82cd478dcd930553312c0/tests/python/shared/utils/resource_import_export.py#L104) and tests in the file.

**Comment by subika-sri** [comment]
from pprint import pprint

from cvat_sdk.api_client import Configuration, ApiClient, exceptions
from cvat_sdk.api_client.models import *

# Set up an API client
# Read Configuration class docs for more info about parameters and authentication methods
configuration = Configuration(
    host="https://app.cvat.ai",
    username='admin-RM',
    password='RemoteMicro@123',
)

with ApiClient(configuration) as api_client:
    job_id = 978149  # int | A unique integer value identifying this job.
    # action = "download"  # str | Used to start downloading process locally after annotation file has been created (optional)
    cloud_storage_id = 1758  # int | Storage id (optional)
    # filename = "annotation1"  # str | Desired output file name (optional)
    format = "COCO 1.0"  # str | Desired output format name
    location = "cloud_storage"  # str | Where to save downloaded annotation (optional)
    use_default_location = False  # bool | Use the location that was configured in the task to export annotation (optional)

    try:
        # Call the correct method with appropriate parameters
        (data, response) = api_client.jobs_api.retrieve_annotations(
            job_id,
            # action=action,
            cloud_storage_id=cloud_storage_id,
            # filename=filename,
            format=format,
            location=location,
            use_default_location=use_default_location,
        )
        pprint(data)
    except exceptions.ApiException as e:
        print("Exception when calling JobsApi.retrieve_annotations(): %s\n" % e)
        
        
        
   Can't I use this. If I use the above code, it is creating a file without any extention in s3 also I am getting the below error.
cvat_sdk.api_client.exceptions.ApiValueError: Invalid inputs given to generate an instance of AnnotationsRead. Multiple oneOf schemas matched the inputs, but a max of one is allowed.

**Comment by subika-sri** [comment]
`from pprint import pprint

from cvat_sdk.api_client import Configuration, ApiClient, exceptions
from cvat_sdk.api_client.models import *

configuration = Configuration(
    host="https://app.cvat.ai",
    username='admin-RM',
    password='RemoteMicro@123',
)

with ApiClient(configuration) as api_client:
    job_id = 978149
    cloud_storage_id = 1758
    format = "COCO 1.0" 
    location = "cloud_storage" 
    use_default_location = False

    try:
        # Call the correct method with appropriate parameters
        (data, response) = api_client.jobs_api.retrieve_annotations(
            job_id,
            # action=action,
            cloud_storage_id=cloud_storage_id,
            # filename=filename,
            format=format,
            location=location,
            use_default_location=use_default_location,
        )
        pprint(data)
    except exceptions.ApiException as e:
        print("Exception when calling JobsApi.retrieve_annotations(): %s\n" % e)`

**Comment by subika-sri** [comment]
Actually I tried to use the below code, when I run this code I can see a file without any extension in my AWS S3 also I am getting the following error.

cvat_sdk.api_client.exceptions.ApiValueError: Invalid inputs given to generate an instance of AnnotationsRead. Multiple oneOf schemas matched the inputs, but a max of one is allowed.

```from pprint import pprint

from cvat_sdk.api_client import Configuration, ApiClient, exceptions
from cvat_sdk.api_client.models import *

configuration = Configuration(
    host="https://app.cvat.ai",
    username='xxxx',
    password='xxxx',
)

with ApiClient(configuration) as api_client:
    job_id = 978149
    cloud_storage_id = 1758
    format = "COCO 1.0" 
    location = "cloud_storage" 
    use_default_location = False

    try:
        # Call the correct method with appropriate parameters
        (data, response) = api_client.jobs_api.retrieve_annotations(
            job_id,
            # action=action,
            cloud_storage_id=cloud_storage_id,
            # filename=filename,
            format=format,
            location=location,
            use_default_location=use_default_location,
        )
        pprint(data)
    except exceptions.ApiException as e:
        print("Exception when calling JobsApi.retrieve_annotations(): %s\n" % e)
