### ISSUE TITLE
Reset password failed

### ISSUE THREAD

**Issue by may109** [opencv/cvat#6709]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

When reset password from the login UI and click "Send", it reports error and fails to send email.

### Steps to Reproduce (for bugs)

1. go to home page
2. click "Forgot password?"
3. fill out email address
4. click "Send"

### Expected Behaviour
email sent and password can be reset from there.

### Current Behaviour
After clicking "Send", it reports error. In the log, here is the error trace.
```
cvat_server                    | 2023-08-20 16:21:21,712 DEBG 'uvicorn-1' stderr output:
cvat_server                    | [2023-08-20 16:21:21,711] ERROR django.request: Internal Server Error: /api/auth/password/reset
cvat_server                    | Traceback (most recent call last):
cvat_server                    |   File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 534, in thread_handler
cvat_server                    |     raise exc_info[1]
cvat_server                    |   File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
cvat_server                    |     response = await get_response(request)
cvat_server                    |   File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
cvat_server                    |     response = await wrapped_callback(
cvat_server                    |   File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 479, in __call__
cvat_server                    |     ret: _R = await loop.run_in_executor(
cvat_server                    |   File "/opt/venv/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 40, in run
cvat_server                    |     result = self.fn(*self.args, **self.kwargs)
cvat_server                    |   File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 538, in thread_handler
cvat_server                    |     return func(*args, **kwargs)
cvat_server                    |   File "/opt/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
cvat_server                    |     return view_func(*args, **kwargs)
cvat_server                    |   File "/opt/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
cvat_server                    |     return self.dispatch(request, *args, **kwargs)
cvat_server                    |   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
cvat_server                    |     response = self.handle_exception(exc)
cvat_server                    |   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
cvat_server                    |     self.raise_uncaught_exception(exc)
cvat_server                    |   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
cvat_server                    |     raise exc
cvat_server                    |   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
cvat_server                    |     response = handler(request, *args, **kwargs)
cvat_server                    |   File "/opt/venv/lib/python3.10/site-packages/dj_rest_auth/views.py", line 255, in post
cvat_server                    |     serializer.save()
cvat_server                    |   File "/opt/venv/lib/python3.10/site-packages/dj_rest_auth/serializers.py", line 260, in save
cvat_server                    |     self.reset_form.save(**opts)
cvat_server                    |   File "/home/django/cvat/apps/iam/forms.py", line 46, in save
cvat_server                    |     get_adapter(request).send_mail(email_template_prefix, email, context)
cvat_server                    |   File "/opt/venv/lib/python3.10/site-packages/allauth/account/adapter.py", line 140, in send_mail
cvat_server                    |     msg.send()
cvat_server                    |   File "/opt/venv/lib/python3.10/site-packages/django/core/mail/message.py", line 298, in send
cvat_server                    |     return self.get_connection(fail_silently).send_messages([self])
cvat_server                    |   File "/opt/venv/lib/python3.10/site-packages/django/core/mail/backends/smtp.py", line 127, in send_messages
cvat_server                    |     new_conn_created = self.open()
cvat_server                    |   File "/opt/venv/lib/python3.10/site-packages/django/core/mail/backends/smtp.py", line 85, in open
cvat_server                    |     self.connection = self.connection_class(
cvat_server                    |   File "/usr/lib/python3.10/smtplib.py", line 255, in __init__
cvat_server                    |     (code, msg) = self.connect(host, port)
cvat_server                    |   File "/usr/lib/python3.10/smtplib.py", line 341, in connect
cvat_server                    |     self.sock = self._get_socket(host, port, self.timeout)
cvat_server                    |   File "/usr/lib/python3.10/smtplib.py", line 312, in _get_socket
cvat_server                    |     return socket.create_connection((host, port), timeout,
cvat_server                    |   File "/usr/lib/python3.10/socket.py", line 845, in create_connection
cvat_server                    |     raise err
cvat_server                    |   File "/usr/lib/python3.10/socket.py", line 833, in create_connection
cvat_server                    |     sock.connect(sa)
cvat_server                    | OSError: [Errno 99] Cannot assign requested address
```

### Possible Solution
Hoping to hear back.

### Your Environment
- Git hash commit (`git log -1`):
Using v2.6.0
- Docker version `docker version` (e.g. Docker 17.0.05):
Docker 20.10.22
- Are you using Docker Swarm or Kubernetes?
No.
- Operating System and version (e.g. Linux, Windows, MacOS):
Linux.
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:

![Screen Shot 2023-08-20 at 10 21 51 AM](https://github.com/opencv/cvat/assets/35074568/7580e436-e053-4707-8f8f-16f1c7bb59fc)

**Comment by bsekachev** [comment]
Have you configured email server? 
Some tips can be found here: https://opencv.github.io/cvat/docs/administration/basics/installation/#email-verification
