### ISSUE TITLE
Analytics is stop working after clear disk space from cache

### ISSUE THREAD

**Issue by sourabh0207** [opencv/cvat#6724]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

My AWS server disk space was full so delete the cache using the following commands:

- `docker exec -it cvat_server bash -c 'rm -r data/*/*/export_cache/'`

- `docker exec -it cvat_server bash -c 'rm -r data/cache/'`

### Expected Behaviour

After this, I am unable to get any data in analytics, As shown in the screenshot

![Screenshot from 2023-08-21 10-59-33](https://github.com/opencv/cvat/assets/5680400/e3064a68-b8da-45b7-ac6a-ca145f617927)

### Expected Behaviour

The analytics page should show the analytics data at  `analytics/app/kibana`

### Your Environment
- Docker version `docker version` 20.10.23:
- Operating System and version: (Linux Ubuntu 22.04.1)
- - Are you using Docker Swarm or Kubernetes? No
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat_server` </summary>
        <p dir="auto">[2023-08-21 05:12:57,296] WARNING django.request: Unauthorized: /analytics</p>
        <p dir="auto">[2023-08-21 05:13:12,308] WARNING django.request: Unauthorized: /analytics</p>
        <p dir="auto">[2023-08-21 05:13:26,928] WARNING django.request: Unauthorized: /analytics</p>
        <p dir="auto">[2023-08-21 07:19:35,074] WARNING django.request: Not Found: /api/user-agreements</p>
        <p dir="auto">[2023-08-21 07:19:35,462] WARNING django.request: Forbidden: /api/lambda/requests</p>
        <p dir="auto">[2023-08-21 07:19:38,266] ERROR django.request: Internal Server Error: /api/jobs/131/preview</p>
         <p dir="auto"> Traceback (most recent call last):
            File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
              response = get_response(request)
            File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
              response = wrapped_callback(request, *callback_args, **callback_kwargs)
            File "/opt/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
              return view_func(*args, **kwargs)
            File "/opt/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
              return self.dispatch(request, *args, **kwargs)
            File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
              response = self.handle_exception(exc)
            File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
              self.raise_uncaught_exception(exc)
            File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
              raise exc
            File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
            response = handler(request, *args, **kwargs)
          File "/home/django/cvat/apps/engine/views.py", line 1790, in preview
            return data_getter(request, self._object.segment.start_frame,
          File "/home/django/cvat/apps/engine/views.py", line 692, in __call__
            buf, mime = cache.get_local_preview_with_mime(self.number, db_data)
          File "/home/django/cvat/apps/engine/cache.py", line 50, in get_local_preview_with_mime
            item = self._get_or_set_cache_item(
          File "/home/django/cvat/apps/engine/cache.py", line 36, in _get_or_set_cache_item
            item = create_function()
          File "/home/django/cvat/apps/engine/cache.py", line 52, in <lambda>
            create_function=lambda: self._prepare_local_preview(frame_number, db_data),
          File "/home/django/cvat/apps/engine/cache.py", line 150, in _prepare_local_preview
            buff, mime_type = frame_provider.get_preview(frame_number)
          File "/home/django/cvat/apps/engine/frame_provider.py", line 176, in get_preview
            preview, _ = self.get_frame(frame_number, self.Quality.COMPRESSED, self.Type.PIL)
          File "/home/django/cvat/apps/engine/frame_provider.py", line 196, in get_frame
            chunk_reader = loader.load(chunk_number)
          File "/home/django/cvat/apps/engine/frame_provider.py", line 86, in load
            self.reader_class([self.get_chunk_path(chunk_id, self.quality, self.db_data)[0]]))
          File "/home/django/cvat/apps/engine/cache.py", line 42, in get_buf_chunk_with_mime
            item = self._get_or_set_cache_item(
          File "/home/django/cvat/apps/engine/cache.py", line 36, in _get_or_set_cache_item
            item = create_function()
          File "/home/django/cvat/apps/engine/cache.py", line 44, in <lambda>
            create_function=lambda: self._prepare_chunk_buff(db_data, quality, chunk_number),
          File "/home/django/cvat/apps/engine/cache.py", line 121, in _prepare_chunk_buff
            cloud_storage_instance = get_cloud_storage_instance(cloud_provider=db_cloud_storage.provider_type, **details)
          File "/home/django/cvat/apps/engine/cloud_provider.py", line 171, in get_cloud_storage_instance
            instance = AWS_S3(
          File "/home/django/cvat/apps/engine/cloud_provider.py", line 226, in __init__
          self._s3 = boto3.resource(
          File "/opt/venv/lib/python3.8/site-packages/boto3/__init__.py", line 102, in resource
          return _get_default_session().resource(*args, **kwargs)
          File "/opt/venv/lib/python3.8/site-packages/boto3/session.py", line 384, in resource
            client = self.client(
          File "/opt/venv/lib/python3.8/site-packages/boto3/session.py", line 258, in client
            return self._session.create_client(
          File "/opt/venv/lib/python3.8/site-packages/botocore/session.py", line 840, in create_client
            endpoint_resolver = self._get_internal_component('endpoint_resolver')
          File "/opt/venv/lib/python3.8/site-packages/botocore/session.py", line 713, in _get_internal_component
            return self._internal_components.get_component(name)
          File "/opt/venv/lib/python3.8/site-packages/botocore/session.py", line 941, in get_component
            del self._deferred[name]</p>
         <p dir="auto"> KeyError: 'endpoint_resolver'
          [2023-08-21 07:19:38,266] ERROR django.request: Internal Server Error: /api/jobs/141/preview
          Traceback (most recent call last):
            File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
              response = get_response(request)
            File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
              response = wrapped_callback(request, *callback_args, **callback_kwargs)
            File "/opt/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
              return view_func(*args, **kwargs)
            File "/opt/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
              return self.dispatch(request, *args, **kwargs)
            File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
              response = self.handle_exception(exc)
            File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
              self.raise_uncaught_exception(exc)
            File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
              raise exc
            File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
              response = handler(request, *args, **kwargs)
            File "/home/django/cvat/apps/engine/views.py", line 1790, in preview
              return data_getter(request, self._object.segment.start_frame,
            File "/home/django/cvat/apps/engine/views.py", line 692, in __call__
              buf, mime = cache.get_local_preview_with_mime(self.number, db_data)
            File "/home/django/cvat/apps/engine/cache.py", line 50, in get_local_preview_with_mime
              item = self._get_or_set_cache_item(
            File "/home/django/cvat/apps/engine/cache.py", line 36, in _get_or_set_cache_item
              item = create_function()
            File "/home/django/cvat/apps/engine/cache.py", line 52, in <lambda>
              create_function=lambda: self._prepare_local_preview(frame_number, db_data),
            File "/home/django/cvat/apps/engine/cache.py", line 150, in _prepare_local_preview
              buff, mime_type = frame_provider.get_preview(frame_number)
            File "/home/django/cvat/apps/engine/frame_provider.py", line 176, in get_preview
              preview, _ = self.get_frame(frame_number, self.Quality.COMPRESSED, self.Type.PIL)
            File "/home/django/cvat/apps/engine/frame_provider.py", line 196, in get_frame
              chunk_reader = loader.load(chunk_number)
            File "/home/django/cvat/apps/engine/frame_provider.py", line 86, in load
              self.reader_class([self.get_chunk_path(chunk_id, self.quality, self.db_data)[0]]))
            File "/home/django/cvat/apps/engine/cache.py", line 42, in get_buf_chunk_with_mime
              item = self._get_or_set_cache_item(
            File "/home/django/cvat/apps/engine/cache.py", line 36, in _get_or_set_cache_item
              item = create_function()
            File "/home/django/cvat/apps/engine/cache.py", line 44, in <lambda>
              create_function=lambda: self._prepare_chunk_buff(db_data, quality, chunk_number),
            File "/home/django/cvat/apps/engine/cache.py", line 121, in _prepare_chunk_buff
              cloud_storage_instance = get_cloud_storage_instance(cloud_provider=db_cloud_storage.provider_type, **details)
            File "/home/django/cvat/apps/engine/cloud_provider.py", line 171, in get_cloud_storage_instance
              instance = AWS_S3(
            File "/home/django/cvat/apps/engine/cloud_provider.py", line 226, in __init__
              self._s3 = boto3.resource(
            File "/opt/venv/lib/python3.8/site-packages/boto3/__init__.py", line 102, in resource
              return _get_default_session().resource(*args, **kwargs)
            File "/opt/venv/lib/python3.8/site-packages/boto3/session.py", line 384, in resource
              client = self.client(
            File "/opt/venv/lib/python3.8/site-packages/boto3/session.py", line 258, in client
              return self._session.create_client(
            File "/opt/venv/lib/python3.8/site-packages/botocore/session.py", line 840, in create_client
              endpoint_resolver = self._get_internal_component('endpoint_resolver')
            File "/opt/venv/lib/python3.8/site-packages/botocore/session.py", line 713, in _get_internal_component
              return self._internal_components.get_component(name)
            File "/opt/venv/lib/python3.8/site-packages/botocore/session.py", line 941, in get_component
              del self._deferred[name]</p>
          <p dir="auto">KeyError: 'endpoint_resolver'</p>
            <p dir="auto">[2023-08-21 07:57:55,669] WARNING django.request: Not Found: /api/user-agreements</p>
            <p dir="auto">[2023-08-21 07:57:58,004] WARNING django.request: Forbidden: /api/lambda/requests</p>
            <p dir="auto">[2023-08-21 08:34:47,055] WARNING django.request: Forbidden: /api/lambda/requests</p>
            <p dir="auto">[2023-08-21 08:34:47,244] WARNING django.request: Forbidden: /api/lambda/requests</p>
            <p dir="auto">[2023-08-21 08:34:47,781] WARNING django.request: Forbidden: /api/lambda/requests</p>
            <p dir="auto">[2023-08-21 09:06:06,217] WARNING django.request: Not Found: /api/user-agreements</p>
            <p dir="auto">[2023-08-21 09:06:06,815] WARNING django.request: Forbidden: /api/lambda/requests</p>
            <p dir="auto">[2023-08-21 09:06:13,550] INFO cvat.server.task_55: get repository request</p>
            <p dir="auto">[2023-08-21 09:06:19,847] WARNING django.request: Forbidden: /api/lambda/requests</p>
            <p dir="auto">[2023-08-21 09:06:24,408] INFO cvat.server.task_57: get repository request</p>
            <p dir="auto">[2023-08-21 09:06:28,399] WARNING django.request: Forbidden: /api/lambda/requests</p>
            <p dir="auto">[2023-08-21 09:06:35,266] INFO cvat.server.task_54: get repository request</p>
            <p dir="auto">[2023-08-21 09:06:41,226] WARNING django.request: Forbidden: /api/lambda/requests</p>
            <p dir="auto">[2023-08-21 09:07:39,127] INFO cvat.server.task_52: get repository request</p>
            <p dir="auto">[2023-08-21 09:07:43,562] WARNING django.request: Forbidden: /api/lambda/requests</p>
            <p dir="auto">[2023-08-21 09:07:46,131] INFO cvat.server.task_59: get repository request</p>
            <p dir="auto">[2023-08-21 09:08:02,199] WARNING django.request: Forbidden: /api/lambda/requests</p>
            <p dir="auto">[2023-08-21 09:09:35,563] WARNING django.request: Forbidden: /api/lambda/requests</p>
            <p dir="auto">[2023-08-21 10:14:50,609] WARNING django.request: Not Found: /api/user-agreements</p>
            <p dir="auto">[2023-08-21 10:14:50,927] WARNING django.request: Forbidden: /api/lambda/requests</p>
            <p dir="auto">[2023-08-21 11:16:14,609] WARNING django.request: Not Found: /api/user-agreements</p>
            <p dir="auto">[2023-08-21 14:04:22,798] WARNING django.request: Not Found: /api/user-agreements</p>
            <p dir="auto">[2023-08-21 14:04:23,275] WARNING django.request: Forbidden: /api/lambda/requests</p>
            <p dir="auto">[2023-08-21 14:40:46,124] WARNING django.request: Not Found: /api/user-agreements</p>
            <p dir="auto">[2023-08-21 14:40:46,357] WARNING django.request: Forbidden: /api/jobs/58</p>
            <p dir="auto">[2023-08-21 15:39:16,353] WARNING django.request: Not Found: /api/user-agreements</p>
            <p dir="auto">[2023-08-21 16:18:12,746] WARNING django.request: Not Found: /api/user-agreements</p>
            <p dir="auto">[2023-08-21 16:20:58,656] WARNING django.request: Not Found: /api/user-agreements</p>
            <p dir="auto">[2023-08-21 16:32:15,486] WARNING django.request: Not Found: /api/user-agreements</p>
            <p dir="auto">[2023-08-21 16:32:16,166] WARNING django.request: Forbidden: /api/lambda/requests</p>
            <p dir="auto">[2023-08-21 16:32:26,945] INFO cvat.server.task_59: get repository request</p>
            <p dir="auto">[2023-08-21 16:32:33,692] WARNING django.request: Forbidden: /api/lambda/requests</p>
            <p dir="auto">[2023-08-21 16:32:41,257] WARNING django.request: Forbidden: /api/lambda/requests</p>
            <p dir="auto">[2023-08-21 16:32:45,275] INFO cvat.server.task_59: get repository request</p>
            <p dir="auto">[2023-08-21 16:33:03,502] WARNING django.request: Forbidden: /api/lambda/requests</p>
            <p dir="auto">[2023-08-21 17:29:35,421] WARNING django.request: Not Found: /api/user-agreements</p>
            <p dir="auto">[2023-08-21 17:33:23,784] WARNING django.request: Not Found: /api/user-agreements</p>
            <p dir="auto">[2023-08-22 01:40:16,317] WARNING django.request: Not Found: /api/user-agreements</p>
            <p dir="auto">[2023-08-22 03:35:43,996] WARNING django.request: Not Found: /api/user-agreements</p>
            <p dir="auto">[2023-08-22 03:36:35,936] WARNING django.request: Not Found: /api/user-agreements</p>
            <p dir="auto">[2023-08-22 03:37:14,246] WARNING django.request: Not Found: /api/user-agreements</p>
            <p dir="auto">[2023-08-22 05:33:32,147] WARNING django.request: Not Found: /api/user-agreements</p>
            <p dir="auto">[2023-08-22 05:33:35,182] WARNING django.request: Forbidden: /api/lambda/requests</p>
            <p dir="auto">[2023-08-22 05:43:03,470] WARNING django.request: Not Found: /api/user-agreements</p>
    </details>

**Comment by bsekachev** [comment]
```
[2023-08-21 05:13:12,308] WARNING django.request: Unauthorized: /analytics
```

Try to logout/login. If does not help, try to open in private browser tab.

**Comment by sourabh0207** [comment]
> ```
> [2023-08-21 05:13:12,308] WARNING django.request: Unauthorized: /analytics
> ```
> 
> Try to logout/login. If does not help, try to open in private browser tab.

Just tried in the Incognito window, Unable to get any data in the kibana dashboard

**Comment by sourabh0207** [comment]
Still facing the same issue

**Comment by bsekachev** [comment]
Unfortunately, we can't help somehow.

Version you are using is outdated, we upgraded analytics several releases ago. And this is really not clear how to reproduce (I do not think removing volumes is a reason).
