### ISSUE TITLE
"Annotation has failed" for auto_annotation

### ISSUE THREAD

**Issue by peyman-sabouri** [opencv/cvat#674]
My openvino model is imported and working properly for small dataset. However, when I select a large image dataset i.e.  than > 500 images, Annotation completed 100% but at the end I get this error" Annotation has failed". I tried to use segment size = 200 and overlap to compress data... but it did not help.

**Comment by nmanovic** [comment]
@azhavoro , could you please take a look?

**Comment by azhavoro** [comment]
@peyman-sabouri Hello, could you please post  logs from CVAT container after auto annotation has failed? `docker logs cvat`

**Comment by peyman-sabouri** [comment]
@azhavoro 
[2019-08-29 19:35:28,410] ERROR cvat.server.task_43: exception was occurred during auto annotation of the task
Traceback (most recent call last):
  File "/home/django/cvat/apps/auto_annotation/model_manager.py", line 262, in run_inference_thread
    if serializer.is_valid(raise_exception=True):
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/serializers.py", line 244, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'shapes': [{}, {}, ..., {}]}

2019-08-29 19:35:28,417 DEBG 'rqworker_low' stderr output:
19:35:28 rest_framework.exceptions.ValidationError: {'shapes': [{}, {}, ..., {}]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rq/worker.py", line 812, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 588, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 594, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/django/cvat/apps/auto_annotation/model_manager.py", line 276, in run_inference_thread
    raise e
  File "/home/django/cvat/apps/auto_annotation/model_manager.py", line 262, in run_inference_thread
    if serializer.is_valid(raise_exception=True):
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/serializers.py", line 244, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'shapes': [{}, {}, {}, {}, {}, {'shapes': [{}, {}, ..., {}]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rq/worker.py", line 812, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 588, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 594, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/django/cvat/apps/auto_annotation/model_manager.py", line 276, in run_inference_thread
    raise e
  File "/home/django/cvat/apps/auto_annotation/model_manager.py", line 262, in run_inference_thread
    if serializer.is_valid(raise_exception=True):
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/serializers.py", line 244, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'shapes': [{}, {}, ..., {}]}

2019-08-29 19:35:28,426 DEBG 'rqworker_low' stderr output:
19:35:28 Cleaning registries for queue: low



{'shapes': [{}, {}, ..., {}]}

**Comment by peyman-sabouri** [comment]
Sorry, I found the problem and it was becouse of one detection had negative value for xmin.

**Comment by azhavoro** [comment]
@peyman-sabouri Ok, then I close the issue for now.
