### ISSUE TITLE
error when importing tasks

### ISSUE THREAD

**Issue by Lee4396** [opencv/cvat#6741]
a random error happened when importing tasks:

![40d357e4-3230-42d7-b34c-1bdcd82d0777](https://github.com/opencv/cvat/assets/43795612/f3a25b0c-ace8-41df-8f4d-a4fcfd8a4d29)

and the import worker gives the following log:

INFO:rq.worker:import: cvat.apps.engine.task._create_thread(38, {'chunk_size': None, 'size': 0, 'image_quality': 100, 'start_frame': 0, 'st...) (create:task.id38-by-linevognsen)

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 109, in emit
    self.flush()
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 68, in flush
    self.stream.flush()
OSError: [Errno 116] Stale file handle
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 109, in emit
    self.flush()
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 68, in flush
    self.stream.flush()
OSError: [Errno 116] Stale file handle
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 109, in emit
    self.flush()
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 68, in flush
    self.stream.flush()
OSError: [Errno 116] Stale file handle
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 109, in emit
    self.flush()
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 68, in flush
    self.stream.flush()
OSError: [Errno 116] Stale file handle
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 109, in emit
    self.flush()
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 68, in flush
    self.stream.flush()
OSError: [Errno 116] Stale file handle
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 109, in emit
    self.flush()
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 68, in flush
    self.stream.flush()
OSError: [Errno 116] Stale file handle
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 109, in emit
    self.flush()
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 68, in flush
    self.stream.flush()
OSError: [Errno 116] Stale file handle
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 109, in emit
    self.flush()
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 68, in flush
    self.stream.flush()
OSError: [Errno 116] Stale file handle
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 109, in emit
    self.flush()
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 68, in flush
    self.stream.flush()
OSError: [Errno 116] Stale file handle
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 109, in emit
    self.flush()
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 68, in flush
    self.stream.flush()
OSError: [Errno 116] Stale file handle
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 109, in emit
    self.flush()
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 68, in flush
    self.stream.flush()
OSError: [Errno 116] Stale file handle
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 109, in emit
    self.flush()
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 68, in flush
    self.stream.flush()
OSError: [Errno 116] Stale file handle
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 109, in emit
    self.flush()
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 68, in flush
    self.stream.flush()
OSError: [Errno 116] Stale file handle
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 109, in emit
    self.flush()
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 68, in flush
    self.stream.flush()
OSError: [Errno 116] Stale file handle
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 109, in emit
    self.flush()
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 68, in flush
    self.stream.flush()
OSError: [Errno 116] Stale file handle
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 109, in emit
    self.flush()
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 68, in flush
    self.stream.flush()
OSError: [Errno 116] Stale file handle
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 109, in emit
    self.flush()
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 68, in flush
    self.stream.flush()
OSError: [Errno 116] Stale file handle
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 109, in emit
    self.flush()
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 68, in flush
    self.stream.flush()
OSError: [Errno 116] Stale file handle
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 109, in emit
    self.flush()
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 68, in flush
    self.stream.flush()
OSError: [Errno 116] Stale file handle
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 109, in emit
    self.flush()
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 68, in flush
    self.stream.flush()
OSError: [Errno 116] Stale file handle
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 109, in emit
    self.flush()
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 68, in flush
    self.stream.flush()
OSError: [Errno 116] Stale file handle
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 109, in emit
    self.flush()
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 68, in flush
    self.stream.flush()
OSError: [Errno 116] Stale file handle
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 109, in emit
    self.flush()
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 68, in flush
    self.stream.flush()
OSError: [Errno 116] Stale file handle
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 109, in emit
    self.flush()
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 68, in flush
    self.stream.flush()
OSError: [Errno 116] Stale file handle
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 109, in emit
    self.flush()
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 68, in flush
    self.stream.flush()
OSError: [Errno 116] Stale file handle
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 109, in emit
    self.flush()
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 68, in flush
    self.stream.flush()
OSError: [Errno 116] Stale file handle
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 109, in emit
    self.flush()
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 68, in flush
    self.stream.flush()
OSError: [Errno 116] Stale file handle
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 109, in emit
    self.flush()
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 68, in flush
    self.stream.flush()
OSError: [Errno 116] Stale file handle
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 109, in emit
    self.flush()
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 68, in flush
    self.stream.flush()
OSError: [Errno 116] Stale file handle
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 109, in emit
    self.flush()

**Comment by Lee4396** [comment]
> Hi @Lee4396
> 
> Network error means client lost connection with the sever. This is not CVAT issue.
> 
> About the second one, we didn't meet that, any steps to reproduce?

yeah the second one is actually the error log for the first network issue, the problem is this network issue happens extremely randomly and we are not able to reproduce it on call. But as we observe that the more resource we give cvat (cpu or memory), the less likely for the network issue to occur.

**Comment by jpig18** [comment]
Hi @Lee4396. Were you able to resolve this?

**Comment by Lee4396** [comment]
> Hi @Lee4396. Were you able to resolve this?

We raised the size of our ec2 instance and the problem was gone
