### ISSUE TITLE
Deploy a model with nuclio successful, but status unhealthy

### ISSUE THREAD

**Issue by Petros626** [opencv/cvat#6790]
Hey guys,

I followed this helpful video here to make auto annotation wth deployed models (localhost:8070) possible https://www.youtube.com/watch?v=uKMKM5o5vUw

The problem which occurs after I get the message is successfully deployed is the status for each model. 
I haven't tried in CVAT, if I can use a model without getting any problem.

![image](https://github.com/opencv/cvat/assets/62354721/72233ffc-7f6a-491f-8ca0-666f98be898e)

![image](https://github.com/opencv/cvat/assets/62354721/12f3ab6f-7b3f-42ae-8035-0cefe23a293f)

Thanks in advance to clarify this issue for all

**Comment by bsekachev** [comment]
Any logs?

**Comment by Petros626** [comment]
I use a project with my own predefined labels, I've read, that this can't work.

These are the chrome browser logs with predefined labels:

```html
cvat-app.tsx:355 Error: Inference status for the task 4 is failed. Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 461, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/opt/venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/venv/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 461, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/rq/worker.py", line 936, in perform_job
    rv = job.perform()
  File "/opt/venv/lib/python3.10/site-packages/rq/job.py", line 684, in perform
    self._result = self._execute()
  File "/opt/venv/lib/python3.10/site-packages/rq/job.py", line 690, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/django/cvat/apps/lambda_manager/views.py", line 687, in __call__
    LambdaJob._call_detector(function, db_task, labels, quality,
  File "/home/django/cvat/apps/lambda_manager/views.py", line 525, in _call_detector
    annotations = function.invoke(db_task, data={
  File "/home/django/cvat/apps/lambda_manager/views.py", line 302, in invoke
    response = self.gateway.invoke(self, payload)
  File "/home/django/cvat/apps/lambda_manager/views.py", line 98, in invoke
    return invoke_method[settings.NUCLIO['INVOKE_METHOD']](func, payload)
  File "/home/django/cvat/apps/lambda_manager/views.py", line 116, in _invoke_directly
    reply = session.post(url, timeout=NUCLIO_TIMEOUT, json=payload)
  File "/opt/venv/lib/python3.10/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/venv/lib/python3.10/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

These are the chrome browser logs with NO predefined labels:
```html
cvat-app.tsx:355 Error: Inference status for the task 5 is failed. Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/opt/venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/opt/venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f9cadf492d0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/opt/venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='host.docker.internal', port=53495): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9cadf492d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/rq/worker.py", line 936, in perform_job
    rv = job.perform()
  File "/opt/venv/lib/python3.10/site-packages/rq/job.py", line 684, in perform
    self._result = self._execute()
  File "/opt/venv/lib/python3.10/site-packages/rq/job.py", line 690, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/django/cvat/apps/lambda_manager/views.py", line 687, in __call__
    LambdaJob._call_detector(function, db_task, labels, quality,
  File "/home/django/cvat/apps/lambda_manager/views.py", line 525, in _call_detector
    annotations = function.invoke(db_task, data={
  File "/home/django/cvat/apps/lambda_manager/views.py", line 302, in invoke
    response = self.gateway.invoke(self, payload)
  File "/home/django/cvat/apps/lambda_manager/views.py", line 98, in invoke
    return invoke_method[settings.NUCLIO['INVOKE_METHOD']](func, payload)
  File "/home/django/cvat/apps/lambda_manager/views.py", line 116, in _invoke_directly
    reply = session.post(url, timeout=NUCLIO_TIMEOUT, json=payload)
  File "/opt/venv/lib/python3.10/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/venv/lib/python3.10/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='host.docker.internal', port=53495): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9cadf492d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by bsekachev** [comment]
Could you provide build logs?

**Comment by Petros626** [comment]
`docker build -t cvat . > build-logs.txt` is fine?

https://drive.google.com/file/d/1IcDyof8VGAJ84OPdARdnvODP5Q1URR95/view?usp=sharing

**Comment by bsekachev** [comment]
I mean logs you get when building serverless function.

**Comment by Petros626** [comment]
my bad, here we go again:

https://drive.google.com/file/d/1WzV0MRjcurWW-rsNU6q9PyZRGL5vc1FA/view?usp=sharing

**Comment by bsekachev** [comment]
@Petros626 

For example for ``pth-ultralytics-yolov5`` there is an error in init_context:

```
23.09.04 12:59:01.097  [37msor.http.w1.python.logger [0m  [34m(I) [0m Init context...  0% {"worker_id": "1"}
23.09.04 12:59:01.336  [37msor.http.w0.python.logger [0m  [31m(E) [0m Exception raised while running init_context {"worker_id": "0"}
23.09.04 12:59:01.372  [37msor.http.w1.python.logger [0m  [31m(E) [0m Exception raised while running init_context {"worker_id": "1"}
``` 

It is why the function is unhealthy. Build is successful, but the function could not startup.

**Comment by Petros626** [comment]
Okay I see, but then the actual `function.yaml` files do not work for everyone? Sometimes the format has to been reformatted, after that it seemed ok, but I end with this unhealthy status messages.

The code inside is:
```yaml
metadata:
  name: pth-ultralytics-yolov5
  namespace: cvat
  annotations:
    name: YOLO v5
    type: detector
    framework: pytorch
    spec: |
      [
        { "id": 0, "name": "person" },
        { "id": 1, "name": "bicycle" },
        { "id": 2, "name": "car" },
        { "id": 3, "name": "motorbike" },
        { "id": 4, "name": "aeroplane" },
        { "id": 5, "name": "bus" },
        { "id": 6, "name": "train" },
        { "id": 7, "name": "truck" },
        { "id": 8, "name": "boat" },
        { "id": 9, "name": "traffic light" },
        { "id": 10, "name": "fire hydrant" },
        { "id": 11, "name": "stop sign" },
        { "id": 12, "name": "parking meter" },
        { "id": 13, "name": "bench" },
        { "id": 14, "name": "bird" },
        { "id": 15, "name": "cat" },
        { "id": 16, "name": "dog" },
        { "id": 17, "name": "horse" },
        { "id": 18, "name": "sheep" },
        { "id": 19, "name": "cow" },
        { "id": 20, "name": "elephant" },
        { "id": 21, "name": "bear" },
        { "id": 22, "name": "zebra" },
        { "id": 23, "name": "giraffe" },
        { "id": 24, "name": "backpack" },
        { "id": 25, "name": "umbrella" },
        { "id": 26, "name": "handbag" },
        { "id": 27, "name": "tie" },
        { "id": 28, "name": "suitcase" },
        { "id": 29, "name": "frisbee" },
        { "id": 30, "name": "skis" },
        { "id": 31, "name": "snowboard" },
        { "id": 32, "name": "sports ball" },
        { "id": 33, "name": "kite" },
        { "id": 34, "name": "baseball bat" },
        { "id": 35, "name": "baseball glove" },
        { "id": 36, "name": "skateboard" },
        { "id": 37, "name": "surfboard" },
        { "id": 38, "name": "tennis racket" },
        { "id": 39, "name": "bottle" },
        { "id": 40, "name": "wine glass" },
        { "id": 41, "name": "cup" },
        { "id": 42, "name": "fork" },
        { "id": 43, "name": "knife" },
        { "id": 44, "name": "spoon" },
        { "id": 45, "name": "bowl" },
        { "id": 46, "name": "banana" },
        { "id": 47, "name": "apple" },
        { "id": 48, "name": "sandwich" },
        { "id": 49, "name": "orange" },
        { "id": 50, "name": "broccoli" },
        { "id": 51, "name": "carrot" },
        { "id": 52, "name": "hot dog" },
        { "id": 53, "name": "pizza" },
        { "id": 54, "name": "donut" },
        { "id": 55, "name": "cake" },
        { "id": 56, "name": "chair" },
        { "id": 57, "name": "sofa" },
        { "id": 58, "name": "pottedplant" },
        { "id": 59, "name": "bed" },
        { "id": 60, "name": "diningtable" },
        { "id": 61, "name": "toilet" },
        { "id": 62, "name": "tvmonitor" },
        { "id": 63, "name": "laptop" },
        { "id": 64, "name": "mouse" },
        { "id": 65, "name": "remote" },
        { "id": 66, "name": "keyboard" },
        { "id": 67, "name": "cell phone" },
        { "id": 68, "name": "microwave" },
        { "id": 69, "name": "oven" },
        { "id": 70, "name": "toaster" },
        { "id": 71, "name": "sink" },
        { "id": 72, "name": "refrigerator" },
        { "id": 73, "name": "book" },
        { "id": 74, "name": "clock" },
        { "id": 75, "name": "vase" },
        { "id": 76, "name": "scissors" },
        { "id": 77, "name": "teddy bear" },
        { "id": 78, "name": "hair drier" },
        { "id": 79, "name": "toothbrush" }
      ]

spec:
  description: YOLO v5 via pytorch hub
  runtime: 'python:3.6'
  handler: main:handler
  eventTimeout: 30s
  build:
    image: cvat.pth.ultralytics.yolov5
    baseImage: ultralytics/yolov5:latest-cpu

    directives:
      preCopy:
        - kind: USER
          value: root
        - kind: RUN
          value: apt update && apt install --no-install-recommends -y libglib2.0-0
        - kind: WORKDIR
          value: /opt/nuclio

  triggers:
    myHttpTrigger:
      maxWorkers: 2
      kind: 'http'
      workerAvailabilityTimeoutMilliseconds: 10000
      attributes:
        maxRequestBodySize: 33554432 # 32MB

  platform:
    attributes:
      restartPolicy:
        name: always
        maximumRetryCount: 3
      mountMode: volume
```

**Comment by bsekachev** [comment]
You can try..except init_context body and log the error message.
I do not think there were issues with yaml file. But for now we already removed this function because ultralytics changed license that became incompatible with our.

**Comment by Petros626** [comment]
With the newest version of CVAT the problem with the models were solved, or are there still issues?

The current version I get showed from `localhost:8080` is:

![image](https://github.com/opencv/cvat/assets/62354721/8c016afb-d3cf-4003-90e5-b1dc2a0f9262)
