### ISSUE TITLE
Can not restore project from backup

### ISSUE THREAD

**Issue by tadejsv** [opencv/cvat#6859]
I can not restore project from backup file. I get this error (this occurs when backup uploading is finished)

```
[2023-09-14 08:30:28,612] ERROR cvat.server.engine: Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/rq/worker.py", line 936, in perform_job
    rv = job.perform()
  File "/opt/venv/lib/python3.10/site-packages/rq/job.py", line 684, in perform
    self._result = self._execute()
  File "/opt/venv/lib/python3.10/site-packages/rq/job.py", line 690, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/django/cvat/apps/engine/utils.py", line 260, in import_resource_with_clean_up_after
    result = func(filename, *args, **kwargs)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/django/cvat/apps/engine/backup.py", line 885, in _import_project
    project_importer = ProjectImporter(filename, user, org_id)
  File "/home/django/cvat/apps/engine/backup.py", line 821, in __init__
    self._manifest, self._annotation_guide, self._assets = self._read_meta()
  File "/home/django/cvat/apps/engine/backup.py", line 830, in _read_meta
    with ZipFile(self._filename, 'r') as input_file:
  File "/usr/lib/python3.10/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/django/data/tmp/cvat-backup-proj.zip-by-tadejs7cmcxo4.zip'
```

The strange thing is that when I inspect the path (`/home/django/data/tmp/cvat-backup-proj.zip-by-tadejs7cmcxo4.zip`), the backup is there.

### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by tadejsv** [comment]
Never mind - this issue was that I changed the docker volume `cvat_data` to a bind mount for `cvat_server`, but forgot to do it for the other services.
