### ISSUE TITLE
During deployment, the display service has been restarting continuously

### ISSUE THREAD

**Issue by jsxyhelu** [opencv/cvat#6888]
During deployment, the display service has been restarting continuously

```
TypeError
o.map is not a function

TypeError: o.map is not a function
    at ZF (http://localhost:8080/assets/cvat-ui.670c9fbf5e666677a8aa.min.js:2:9510034)
    at Kr (http://localhost:8080/assets/cvat-ui.670c9fbf5e666677a8aa.min.js:2:5640240)
    at Ni (http://localhost:8080/assets/cvat-ui.670c9fbf5e666677a8aa.min.js:2:5649089)
    at Li (http://localhost:8080/assets/cvat-ui.670c9fbf5e666677a8aa.min.js:2:5648908)
    at ji (http://localhost:8080/assets/cvat-ui.670c9fbf5e666677a8aa.min.js:2:5648591)
    at yl (http://localhost:8080/assets/cvat-ui.670c9fbf5e666677a8aa.min.js:2:5689673)
    at ps (http://localhost:8080/assets/cvat-ui.670c9fbf5e666677a8aa.min.js:2:5678921)
    at ds (http://localhost:8080/assets/cvat-ui.670c9fbf5e666677a8aa.min.js:2:5678846)
    at os (http://localhost:8080/assets/cvat-ui.670c9fbf5e666677a8aa.min.js:2:5675876)
    at http://localhost:8080/assets/cvat-ui.670c9fbf5e666677a8aa.min.js:2:5627649
```

docker ps

```
elu@helu-virtual-machine:~/AITools/cvat$ sudo docker ps
CONTAINER ID   IMAGE                                 COMMAND                   CREATED         STATUS                          PORTS                                                                                          NAMES
4bd1eabd3fde   cvat/ui:dev                           "/docker-entrypoint.…"   9 minutes ago   Up 9 minutes                    80/tcp                                                                                         cvat_ui
add6769308f3   cvat/server:dev                       "./backend_entrypoin…"   9 minutes ago   Restarting (1) 51 seconds ago                                                                                                  cvat_server
5b0ecdab385f   cvat/server:dev                       "./backend_entrypoin…"   9 minutes ago   Restarting (1) 47 seconds ago                                                                                                  cvat_worker_low
2d80845194b3   cvat/server:dev                       "./backend_entrypoin…"   9 minutes ago   Restarting (1) 47 seconds ago                                                                                                  cvat_utils
ce30527df89a   cvat/server:dev                       "./backend_entrypoin…"   9 minutes ago   Restarting (1) 47 seconds ago                                                                                                  cvat_worker_default
aceb44aa69fe   openpolicyagent/opa:0.34.2-rootless   "/opa run --server -…"   9 minutes ago   Up 9 minutes                    0.0.0.0:8181->8181/tcp, :::8181->8181/tcp                                                      cvat_opa
79499be78138   traefik:v2.4                          "/entrypoint.sh --pr…"   9 minutes ago   Up 9 minutes                    0.0.0.0:8080->8080/tcp, :::8080->8080/tcp, 80/tcp, 0.0.0.0:8090->8090/tcp, :::8090->8090/tcp   traefik
ed5c41175049   postgres:10-alpine                    "docker-entrypoint.s…"   9 minutes ago   Up 9 minutes                    5432/tcp                                                                                       cvat_db
b75d5c60e7de   redis:4.0-alpine                      "docker-entrypoint.s…"   9 minutes ago   Up 9 minutes                    6379/tcp                                                                                       cvat_redis
```
backend_entrypoint.sh: unknown subcommand: -c

```
helu@helu-virtual-machine:~/AITools/cvat$ sudo docker logs -f --tail=100 cvat_utils
./backend_entrypoint.sh: unknown subcommand: -c
./backend_entrypoint.sh: unknown subcommand: -c
./backend_entrypoint.sh: unknown subcommand: -c
./backend_entrypoint.sh: unknown subcommand: -c
./backend_entrypoint.sh: unknown subcommand: -c
./backend_entrypoint.sh: unknown subcommand: -c
./backend_entrypoint.sh: unknown subcommand: -c
./backend_entrypoint.sh: unknown subcommand: -c
./backend_entrypoint.sh: unknown subcommand: -c
./backend_entrypoint.sh: unknown subcommand: -c
./backend_entrypoint.sh: unknown subcommand: -c
./backend_entrypoint.sh: unknown subcommand: -c
./backend_entrypoint.sh: unknown subcommand: -c
./backend_entrypoint.sh: unknown subcommand: -c
./backend_entrypoint.sh: unknown subcommand: -c
./backend_entrypoint.sh: unknown subcommand: -c
./backend_entrypoint.sh: unknown subcommand: -c
./backend_entrypoint.sh: unknown subcommand: -c
./backend_entrypoint.sh: unknown subcommand: -c
```

**Comment by jsxyhelu** [comment]
CVAT version
Server:
Core: 11.1.0
Canvas: 2.17.5
UI: 1.56.1

**Comment by jsxyhelu** [comment]
mark it!

**Comment by torta24x** [comment]
I am facing the same issue , any update or solution ?

**Comment by jsxyhelu** [comment]
change ubuntu20 can change this problem

**Comment by azhavoro** [comment]
What is output of `git log -1`?

**Comment by bsekachev** [comment]
There are apparently some problems with how you built it. 
But without precise steps and logs it is not possible to suggest anything.
I will close the issue for now since you did not provide any details

**Comment by torta24x** [comment]
In our case, the issue was space on the partition.

CVAT requires a minimum of 10% free space on the partition on which the docker is running.
Freeing up the space and restarting the docker work for us.
