### ISSUE TITLE
CVAT launches on local server, but cannot sign up: 405 Error

### ISSUE THREAD

**Issue by bedanar** [opencv/cvat#7210]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

I have Ubuntu 22.04 and I installed CVAT there going through Installation Guide provided at the website: https://opencv.github.io/cvat/docs/administration/basics/installation/

When I launch CVAT with `docker compose up` and click **sign up**, the following error comes out:
`TypeError
o.map is not a function

TypeError: o.map is not a function
    at PF (http://192.168.102.102:8080/assets/cvat-ui.876032e4fd65a1083e93.min.js:2:9693836)
    at Kr (http://192.168.102.102:8080/assets/cvat-ui.876032e4fd65a1083e93.min.js:2:5651498)
    at Fl (http://192.168.102.102:8080/assets/cvat-ui.876032e4fd65a1083e93.min.js:2:5660347)
    at Nl (http://192.168.102.102:8080/assets/cvat-ui.876032e4fd65a1083e93.min.js:2:5660166)
    at jl (http://192.168.102.102:8080/assets/cvat-ui.876032e4fd65a1083e93.min.js:2:5659849)
    at yi (http://192.168.102.102:8080/assets/cvat-ui.876032e4fd65a1083e93.min.js:2:5700931)
    at ps (http://192.168.102.102:8080/assets/cvat-ui.876032e4fd65a1083e93.min.js:2:5690179)
    at ds (http://192.168.102.102:8080/assets/cvat-ui.876032e4fd65a1083e93.min.js:2:5690104)
    at os (http://192.168.102.102:8080/assets/cvat-ui.876032e4fd65a1083e93.min.js:2:5687134)
    at http://192.168.102.102:8080/assets/cvat-ui.876032e4fd65a1083e93.min.js:2:5638907`

<img width="1175" alt="Screenshot 2023-12-01 at 1 22 56 PM" src="https://github.com/opencv/cvat/assets/57563409/6868212a-1e42-40e5-9849-e9d0b200e898">

Therefore in console I have the following logs:
<img width="1470" alt="Screenshot 2023-12-01 at 1 24 28 PM" src="https://github.com/opencv/cvat/assets/57563409/dd088c4f-60c3-4ceb-a602-40df01ca5c45">

I tried to change the traefik label value in docker-compose.yml,  but nothing changed. (According to this error: https://github.com/traefik/traefik/issues/7738)

### Expected Behavior

I want the CVAT to open and be able to sign in/up, create tasks and annotate.

### Environment

```Markdown
`
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:07:41 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:07:41 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.25
  GitCommit:        d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
`


`
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
`
```

**Comment by bsekachev** [comment]
Errors you see in the browser console mean that the server was improperly configured.  
So, provide any changes you done to run.

**Comment by bedanar** [comment]
I had this kind of error: https://github.com/opencv/cvat/issues/7153#issuecomment-1817807018 and added the following strings in docker-compose.yml:
 ```
 - '--providers.docker.exposedByDefault=false'
  - '--providers.docker.network=cvat'
  - '--entryPoints.web.address=:8080'
  - '--providers.file.directory=/etc/traefik/rules'
```
 
Here are the logs from cvat_server:
<img width="1011" alt="Screenshot 2023-12-02 at 10 53 33 AM" src="https://github.com/opencv/cvat/assets/57563409/e0cedea9-27ac-41cc-baa7-8440846e5898">
[logs_cvat-server .odt](https://github.com/opencv/cvat/files/13533760/logs_cvat-server.odt)

**Comment by bsekachev** [comment]
``docker ps``? 

From logs we can see, that there are some issues with redis service. 
Try also restarting all the services with ``docker compose restart`` command, providing the same ``-f`` arguments as you used when build.

**Comment by bedanar** [comment]
<img width="1454" alt="Screenshot 2023-12-02 at 4 30 24 PM" src="https://github.com/opencv/cvat/assets/57563409/fedfa659-b698-4afa-a37c-43c8a25e408f">
Here cvat_redis in continuously restarting. What can I do with that?

**Comment by bedanar** [comment]
@egortech so should I just change the version? Can you please provide the exact command?

**Comment by bedanar** [comment]
@egortech thank you a lot! It really worked out!

**Comment by bsekachev** [comment]
One more way without downgrading keydb:

```
docker compose -f docker-compose.yml down
docker volume rm cvat_cvat_cache_db -f
docker compose -f docker-compose.yml up -d
```

Do not forget all ``-f`` arguments you need in both ``down`` and ``up`` commands.
