### ISSUE TITLE
Cannot create task with images larger than ~900kb

### ISSUE THREAD

**Issue by vskubriev** [opencv/cvat#722]
We faced with problem. Additional information is on screenshoot:

![image](https://user-images.githubusercontent.com/4639077/65052303-f7e52700-d972-11e9-8fab-3afa749e3531.png)

**Comment by cvadim4two** [comment]
And i've got an issue with the amount of files >1k get and error https://monosnap.com/file/PmcmkZwTFzf53uhkt6wGiOamrIK5jg

**Comment by vskubriev** [comment]
Corresponded traceback:

```
2019-09-17 14:15:11,267 DEBG 'rqworker_default_1' stderr output:
[2019-09-17 14:15:11,267] INFO cvat.server: create task #7

2019-09-17 14:15:41,529 DEBG 'rqworker_default_1' stderr output:
14:15:41 OSError: image file is truncated (21 bytes not processed)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rq/worker.py", line 812, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 588, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 594, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/django/cvat/apps/engine/task.py", line 283, in _create_thread
    width, height = extractor.save_image(frame, image_dest_path)
  File "/home/django/cvat/apps/engine/media_extractors.py", line 68, in save_image
    image = image.convert('RGB')
  File "/usr/local/lib/python3.5/dist-packages/PIL/Image.py", line 879, in convert
    self.load()
  File "/usr/local/lib/python3.5/dist-packages/PIL/ImageFile.py", line 228, in load
    "(%d bytes not processed)" % len(b))
OSError: image file is truncated (21 bytes not processed)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rq/worker.py", line 812, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 588, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 594, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/django/cvat/apps/engine/task.py", line 283, in _create_thread
    width, height = extractor.save_image(frame, image_dest_path)
  File "/home/django/cvat/apps/engine/media_extractors.py", line 68, in save_image
    image = image.convert('RGB')
  File "/usr/local/lib/python3.5/dist-packages/PIL/Image.py", line 879, in convert
    self.load()
  File "/usr/local/lib/python3.5/dist-packages/PIL/ImageFile.py", line 228, in load
    "(%d bytes not processed)" % len(b))
OSError: image file is truncated (21 bytes not processed)

2019-09-17 14:15:41,647 DEBG 'rqworker_default_1' stderr output:
14:15:41 Cleaning registries for queue: default
```

**Comment by bsekachev** [comment]
@vskubriev 

Could you send us this file for investigating?

**Comment by bsekachev** [comment]
@cvadim4two

I suppose your case isn't related with image size. Just the whole request body is too large. 
Try to use share to create a task with this set of files.

**Comment by bsekachev** [comment]
@nmanovic 
Also, I suppose it would be better to handle case of @cvadim4two. At least by showing better message. 
Something like: "Too much data to upload thought a browser. Try to create this task via a shared file storage"

**Comment by vskubriev** [comment]
> @cvadim4two
> 
> I suppose your case isn't related with image size. Just the whole request body is too large.
> Try to use share to create a task with this set of files.

Can you suggest: where is `request body size` should be increased in cvat (deployed with docker-compose) ?

**Comment by bsekachev** [comment]
@vskubriev 
You can try this: ``cvat/settings/base.py`` (the latest 4 lines are responsible for that)

**Comment by nmanovic** [comment]
@vskubriev , if you can share with us some files (generated or original) to reproduce the issue it will be easy for us to fix.

**Comment by vskubriev** [comment]
@nmanovic A manager do not have time now for search those images. We will do it later. Please wait.

**Comment by cvadim4two** [comment]
451 files to reproduce https://drive.google.com/drive/folders/1hXbCafBqGyxBvovdmRYlkO9s0uX3BNKn?usp=sharing.
Stable got an error if I try to upload it via local

**Comment by cvadim4two** [comment]
Checked, the issues can be closed.
Thanks!
