### ISSUE TITLE
Cvat-cli dump error - CRITICAL: Status Code: 500 - Reason: Internal Server Error - appears randomly for different tasks

### ISSUE THREAD

**Issue by user-log1n** [opencv/cvat#7257]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

Example single task error:

user="USERNAME"
pass="SECRETPASS"
hname=example.cvat.domain.local
ID=1111

cvat-cli --auth "$user:$pass" --server-host $hname dump --format "CVAT for video 1.1" $ID "$ID-task.zip"

**Console error**

```py
[2023-12-11 12:55:19] INFO: Waiting for the server to prepare the file...
[2023-12-11 12:55:21] CRITICAL: Status Code: 500
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'Content-Length': '145', 'Content-Type': 'text/html; charset=utf-8', 'Cross-Origin-Opener-Policy': 'same-origin', 'Date': 'Mon, 11 Dec 2023 11:55:11 GMT', 'Referrer-Policy': 'same-origin', 'Server': 'nginx/1.18.0 (Ubuntu)', 'Vary': 'Origin', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'DENY', 'X-Request-Id': '5843629b-9fb7-4341-a5f1-6367df7ebeab'})
```

**docker logs cvat_server**

```py
2023-12-11 12:55:24,585 DEBG 'uvicorn-1' stdout output:
INFO:     10.16.55.11:0 - "GET /api/server/about HTTP/1.0" 200 OK

2023-12-11 12:55:24,894 DEBG 'uvicorn-1' stdout output:
INFO:     10.16.55.11:0 - "POST /api/auth/login HTTP/1.0" 200 OK

2023-12-11 12:55:24,906 DEBG 'uvicorn-1' stdout output:
INFO:     10.16.55.11:0 - "GET /api/server/about HTTP/1.0" 200 OK

2023-12-11 12:55:24,938 DEBG 'uvicorn-1' stdout output:
INFO:     10.16.55.11:0 - "GET /api/tasks/1111 HTTP/1.0" 200 OK

2023-12-11 12:55:25,686 DEBG 'uvicorn-1' stdout output:
INFO:     172.11.22.33:0 - "GET /api/auth/rules HTTP/1.0" 304 Not Modified

2023-12-11 12:55:26,976 DEBG 'uvicorn-1' stdout output:
INFO:     10.16.55.11:0 - "GET /api/tasks/1111/annotations/?format=CVAT+for+video+1.1 HTTP/1.0" 202 Accepted

2023-12-11 12:55:27,065 DEBG 'uvicorn-0' stdout output:
INFO:     10.16.55.11:0 - "GET /analytics HTTP/1.0" 200 OK

2023-12-11 12:55:29,095 DEBG 'uvicorn-0' stderr output:
[2023-12-11 12:55:29,092] ERROR django.request: Internal Server Error: /api/tasks/1111/annotations/
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "/opt/venv/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/django/cvat/apps/engine/views.py", line 1333, in annotations
    return self.export_annotations(
  File "/home/django/cvat/apps/engine/mixins.py", line 405, in export_annotations
    return export_func(db_instance=self._object,
  File "/home/django/cvat/apps/engine/views.py", line 3011, in _export_annotations
    if osp.exists(file_path):
  File "/usr/lib/python3.10/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

2023-12-11 12:55:29,097 DEBG 'uvicorn-0' stdout output:
INFO:     10.16.55.11:0 - "GET /api/tasks/1111/annotations/?format=CVAT+for+video+1.1 HTTP/1.0" 500 Internal Server Error
```

### Expected Behavior

The goal is to keep cvat-cli dump running stably as in the version 2.8.2.

### Possible Solution

The problem may be related to cvat cache db.

### Context

After updating cvat from version 2.8.2 to 2.9.1 cvat-cli dump doesn't work as before.

We use cvat-cli dump for backup xml annotations for selected tasks. 

Dumping annotation (cvat version 2.9.1) for task cause error - sometimes only for a few random tasks , other times, for each task.

The appearance of an error for a given task on a given day does not mean that it will appear in this task on the next day.

If an error occurs for a given task, then any attempt to call the command cvat-cli dump again for this task (at intervals of a few minutes) ends with the same error.

The cvat-cli dump error disappears for a given task if you open this task in the browser and scroll few frames. There are no problems with downloading annotations from web browser.

All tasks are properly created.

### Environment

```Markdown
OS: Ubuntu 22.04
Docker version 24.0.7
Server version: 2.9.1
Core version: 12.1.0
Canvas version: 2.19.0
UI version: 1.59.0
cvat-cli version 2.9.1
```

**Comment by user-log1n** [comment]
Since the last update to version 2.9.2, the problem does not occur.
