### ISSUE TITLE
Error 99 connecting to localhost:6379

### ISSUE THREAD

**Issue by MyCreativityOutlet** [opencv/cvat#7282]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

clone the github repository
export CVAT_HOST=ip
change to cvat folder
run docker compose up

**Currently I get the following message:**
![error](https://github.com/opencv/cvat/assets/62733830/8648dbb3-7188-48fd-ad21-494a535be040)

### Looking at the console when I connect i see this message repeated a lot

```
cvat_utils                     | Error: Format string '%(ENV_HOME)s/wait-for-it.sh %(ENV_CVAT_REDIS_HOST)s:6379 -t 0 -- bash -c \\\n"python3 ~/rqscheduler.py --host %(ENV_CVAT_REDIS_HOST)s --password \'%(ENV_CVAT_REDIS_PASSWORD)s\' -i 30 --path \'%(ENV_HOME)s\'"' for 'program:rqscheduler.command' contains names ('ENV_CVAT_REDIS_HOST') which cannot be expanded. Available names: ENV_CLICKHOUSE_HOST, ENV_CVAT_POSTGRES_HOST, ENV_CVAT_REDIS_INMEM_HOST, ENV_CVAT_REDIS_INMEM_PASSWORD, ENV_CVAT_REDIS_INMEM_PORT, ENV_CVAT_REDIS_ONDISK_HOST, ENV_CVAT_REDIS_ONDISK_PORT, ENV_DJANGO_LOG_SERVER_HOST, ENV_DJANGO_LOG_SERVER_PORT, ENV_DJANGO_SETTINGS_MODULE, ENV_HOME, ENV_HOSTNAME, ENV_LANG, ENV_LC_ALL, ENV_NUMPROCS, ENV_PATH, ENV_PWD, ENV_SHLVL, ENV_SMOKESCREEN_OPTS, ENV_TERM, ENV_TZ, ENV_USER, ENV_http_proxy, ENV_https_proxy, ENV_no_proxy, ENV_socks_proxy, group_name, here, host_node_name, numprocs, process_num, program_name in section 'program:rqscheduler' (file: 'supervisord/utils.conf')
cvat_utils                     | For help, use /usr/bin/supervisord -h
cvat_worker_import             | Error: Format string '%(ENV_HOME)s/wait-for-it.sh %(ENV_CVAT_REDIS_HOST)s:6379 -t 0 -- bash -c " \\\nexec python3 %(ENV_HOME)s/manage.py rqworker -v 3 import \\\n--worker-class cvat.rqworker.DefaultWorker \\\n"' for 'program:rqworker-import.command' contains names ('ENV_CVAT_REDIS_HOST') which cannot be expanded. Available names: ENV_CLICKHOUSE_HOST, ENV_CVAT_POSTGRES_HOST, ENV_CVAT_REDIS_INMEM_HOST, ENV_CVAT_REDIS_INMEM_PORT, ENV_CVAT_REDIS_ONDISK_HOST, ENV_CVAT_REDIS_ONDISK_PORT, ENV_DJANGO_LOG_SERVER_HOST, ENV_DJANGO_LOG_SERVER_PORT, ENV_DJANGO_SETTINGS_MODULE, ENV_HOME, ENV_HOSTNAME, ENV_LANG, ENV_LC_ALL, ENV_NUMPROCS, ENV_PATH, ENV_PWD, ENV_SHLVL, ENV_SMOKESCREEN_OPTS, ENV_TERM, ENV_TZ, ENV_USER, ENV_http_proxy, ENV_https_proxy, ENV_no_proxy, ENV_socks_proxy, group_name, here, host_node_name, numprocs, process_num, program_name in section 'program:rqworker-import' (file: 'supervisord/worker.import.conf')
cvat_worker_import             | For help, use /usr/bin/supervisord -h
cvat_utils exited with code 2
cvat_worker_quality_reports    | Error: Format string '%(ENV_HOME)s/wait-for-it.sh %(ENV_CVAT_REDIS_HOST)s:6379 -t 0 -- bash -c " \\\nexec python3 %(ENV_HOME)s/manage.py rqworker -v 3 quality_reports \\\n--worker-class cvat.rqworker.DefaultWorker \\\n"' for 'program:rqworker-quality-reports.command' contains names ('ENV_CVAT_REDIS_HOST') which cannot be expanded. Available names: ENV_CLICKHOUSE_HOST, ENV_CVAT_POSTGRES_HOST, ENV_CVAT_REDIS_INMEM_HOST, ENV_CVAT_REDIS_INMEM_PORT, ENV_CVAT_REDIS_ONDISK_HOST, ENV_CVAT_REDIS_ONDISK_PORT, ENV_DJANGO_LOG_SERVER_HOST, ENV_DJANGO_LOG_SERVER_PORT, ENV_DJANGO_SETTINGS_MODULE, ENV_HOME, ENV_HOSTNAME, ENV_LANG, ENV_LC_ALL, ENV_NUMPROCS, ENV_PATH, ENV_PWD, ENV_SHLVL, ENV_SMOKESCREEN_OPTS, ENV_TERM, ENV_TZ, ENV_USER, ENV_http_proxy, ENV_https_proxy, ENV_no_proxy, ENV_socks_proxy, group_name, here, host_node_name, numprocs, process_num, program_name in section 'program:rqworker-quality-reports' (file: 'supervisord/worker.quality_reports.conf')
cvat_worker_quality_reports    | For help, use /usr/bin/supervisord -h
cvat_worker_import exited with code 2
cvat_worker_quality_reports exited with code 2
cvat_worker_webhooks           | Error: Format string '%(ENV_HOME)s/wait-for-it.sh %(ENV_CVAT_REDIS_HOST)s:6379 -t 0 -- bash -c \\\n"exec python3 %(ENV_HOME)s/manage.py rqworker -v 3 webhooks \\\n--worker-class cvat.rqworker.DefaultWorker \\\n"' for 'program:rqworker-webhooks.command' contains names ('ENV_CVAT_REDIS_HOST') which cannot be expanded. Available names: ENV_CLICKHOUSE_HOST, ENV_CVAT_POSTGRES_HOST, ENV_CVAT_REDIS_INMEM_HOST, ENV_CVAT_REDIS_INMEM_PORT, ENV_CVAT_REDIS_ONDISK_HOST, ENV_CVAT_REDIS_ONDISK_PORT, ENV_DJANGO_LOG_SERVER_HOST, ENV_DJANGO_LOG_SERVER_PORT, ENV_DJANGO_SETTINGS_MODULE, ENV_HOME, ENV_HOSTNAME, ENV_LANG, ENV_LC_ALL, ENV_NUMPROCS, ENV_PATH, ENV_PWD, ENV_SHLVL, ENV_SMOKESCREEN_OPTS, ENV_TERM, ENV_TZ, ENV_USER, ENV_http_proxy, ENV_https_proxy, ENV_no_proxy, ENV_socks_proxy, group_name, here, host_node_name, numprocs, process_num, program_name in section 'program:rqworker-webhooks' (file: 'supervisord/worker.webhooks.conf')
cvat_worker_webhooks           | For help, use /usr/bin/supervisord -h
cvat_server                    | 2023-12-20 10:02:35,717 INFO success: smokescreen entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
cvat_server                    | 2023-12-20 10:02:35,718 DEBG fd 7 closed, stopped monitoring <PInputDispatcher at 139636401140256 for <Subprocess at 139636401129264 with name uvicorn-0 in state STARTING> (stdin)>
cvat_server                    | 2023-12-20 10:02:35,719 INFO spawned: 'uvicorn-0' with pid 1126
cvat_server                    | 2023-12-20 10:02:35,719 INFO success: uvicorn-1 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
cvat_db                        | 2023-12-20 10:02:35.992 UTC [74] LOG:  incomplete startup packet
cvat_db                        | 2023-12-20 10:02:35.992 UTC [75] LOG:  incomplete startup packet
cvat_worker_webhooks exited with code 2
cvat_worker_analytics_reports  | Error: Format string '%(ENV_HOME)s/wait-for-it.sh %(ENV_CVAT_REDIS_HOST)s:6379 -t 0 -- bash -c " \\\nexec python3 %(ENV_HOME)s/manage.py rqworker -v 3 analytics_reports \\\n--worker-class cvat.rqworker.DefaultWorker \\\n"' for 'program:rqworker-analytics-reports.command' contains names ('ENV_CVAT_REDIS_HOST') which cannot be expanded. Available names: ENV_CLICKHOUSE_HOST, ENV_CVAT_POSTGRES_HOST, ENV_CVAT_REDIS_INMEM_HOST, ENV_CVAT_REDIS_INMEM_PORT, ENV_CVAT_REDIS_ONDISK_HOST, ENV_CVAT_REDIS_ONDISK_PORT, ENV_DJANGO_LOG_SERVER_HOST, ENV_DJANGO_LOG_SERVER_PORT, ENV_DJANGO_SETTINGS_MODULE, ENV_HOME, ENV_HOSTNAME, ENV_LANG, ENV_LC_ALL, ENV_NUMPROCS, ENV_PATH, ENV_PWD, ENV_SHLVL, ENV_SMOKESCREEN_OPTS, ENV_TERM, ENV_TZ, ENV_USER, ENV_http_proxy, ENV_https_proxy, ENV_no_proxy, ENV_socks_proxy, group_name, here, host_node_name, numprocs, process_num, program_name in section 'program:rqworker-analytics-reports' (file: 'supervisord/worker.analytics_reports.conf')
cvat_worker_analytics_reports  | For help, use /usr/bin/supervisord -h
cvat_worker_export             | Error: Format string '%(ENV_HOME)s/wait-for-it.sh %(ENV_CVAT_REDIS_HOST)s:6379 -t 0 -- bash -c " \\\nexec python3 %(ENV_HOME)s/manage.py rqworker -v 3 export \\\n--worker-class cvat.rqworker.DefaultWorker \\\n"' for 'program:rqworker-export.command' contains names ('ENV_CVAT_REDIS_HOST') which cannot be expanded. Available names: ENV_CLICKHOUSE_HOST, ENV_CVAT_POSTGRES_HOST, ENV_CVAT_REDIS_INMEM_HOST, ENV_CVAT_REDIS_INMEM_PORT, ENV_CVAT_REDIS_ONDISK_HOST, ENV_CVAT_REDIS_ONDISK_PORT, ENV_DJANGO_LOG_SERVER_HOST, ENV_DJANGO_LOG_SERVER_PORT, ENV_DJANGO_SETTINGS_MODULE, ENV_HOME, ENV_HOSTNAME, ENV_LANG, ENV_LC_ALL, ENV_NUMPROCS, ENV_PATH, ENV_PWD, ENV_SHLVL, ENV_SMOKESCREEN_OPTS, ENV_TERM, ENV_TZ, ENV_USER, ENV_http_proxy, ENV_https_proxy, ENV_no_proxy, ENV_socks_proxy, group_name, here, host_node_name, numprocs, process_num, program_name in section 'program:rqworker-export' (file: 'supervisord/worker.export.conf')
cvat_worker_export             | For help, use /usr/bin/supervisord -h
cvat_worker_analytics_reports exited with code 2
cvat_worker_annotation         | Error: Format string '%(ENV_HOME)s/wait-for-it.sh %(ENV_CVAT_REDIS_HOST)s:6379 -t 0 -- bash -c " \\\nexec python3 %(ENV_HOME)s/manage.py rqworker -v 3 annotation \\\n--worker-class cvat.rqworker.DefaultWorker \\\n"' for 'program:rqworker-annotation.command' contains names ('ENV_CVAT_REDIS_HOST') which cannot be expanded. Available names: ENV_CLICKHOUSE_HOST, ENV_CVAT_POSTGRES_HOST, ENV_CVAT_REDIS_INMEM_HOST, ENV_CVAT_REDIS_INMEM_PORT, ENV_CVAT_REDIS_ONDISK_HOST, ENV_CVAT_REDIS_ONDISK_PORT, ENV_DJANGO_LOG_SERVER_HOST, ENV_DJANGO_LOG_SERVER_PORT, ENV_DJANGO_SETTINGS_MODULE, ENV_HOME, ENV_HOSTNAME, ENV_LANG, ENV_LC_ALL, ENV_NUMPROCS, ENV_PATH, ENV_PWD, ENV_SHLVL, ENV_SMOKESCREEN_OPTS, ENV_TERM, ENV_TZ, ENV_USER, ENV_http_proxy, ENV_https_proxy, ENV_no_proxy, ENV_socks_proxy, group_name, here, host_node_name, numprocs, process_num, program_name in section 'program:rqworker-annotation' (file: 'supervisord/worker.annotation.conf')
```

### I tried running the health command but it crashes with the following error:

```
docker exec -t cvat_server python manage.py health_check
[2023-12-20 09:58:48,144] ERROR health-check: Unexpected Error!
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/redis/connection.py", line 698, in connect
    sock = self.retry.call_with_retry(
  File "/opt/venv/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/opt/venv/lib/python3.10/site-packages/redis/connection.py", line 699, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/opt/venv/lib/python3.10/site-packages/redis/connection.py", line 987, in _connect
    raise err
  File "/opt/venv/lib/python3.10/site-packages/redis/connection.py", line 975, in _connect
    sock.connect(socket_address)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/health_check/backends.py", line 30, in run_check
    self.check_status()
  File "/home/django/cvat/apps/health/backends.py", line 44, in check_status
    cache.set("djangohealtcheck_test", "itworks")
  File "/opt/venv/lib/python3.10/site-packages/django/core/cache/backends/redis.py", line 191, in set
    self._cache.set(key, value, self.get_backend_timeout(timeout))
  File "/opt/venv/lib/python3.10/site-packages/django/core/cache/backends/redis.py", line 108, in set
    client.set(key, value, ex=timeout)
  File "/opt/venv/lib/python3.10/site-packages/redis/commands/core.py", line 2302, in set
    return self.execute_command("SET", *pieces, **options)
  File "/opt/venv/lib/python3.10/site-packages/redis/client.py", line 1255, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/opt/venv/lib/python3.10/site-packages/redis/connection.py", line 1442, in get_connection
    connection.connect()
  File "/opt/venv/lib/python3.10/site-packages/redis/connection.py", line 704, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 99 connecting to localhost:6379. Cannot assign requested address.
[2023-12-20 09:58:48,152] ERROR health-check: unknown error: 500 Server Error: Internal Server Error for url: http://opa:8181/health?bundles
Traceback (most recent call last):
  File "/home/django/cvat/apps/health/backends.py", line 25, in check_status
    response.raise_for_status()
  File "/opt/venv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://opa:8181/health?bundles

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/health_check/backends.py", line 30, in run_check
    self.check_status()
  File "/home/django/cvat/apps/health/backends.py", line 27, in check_status
    raise HealthCheckException(str(e))
health_check.exceptions.HealthCheckException: unknown error: 500 Server Error: Internal Server Error for url: http://opa:8181/health?bundles
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/redis/connection.py", line 698, in connect
    sock = self.retry.call_with_retry(
  File "/opt/venv/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/opt/venv/lib/python3.10/site-packages/redis/connection.py", line 699, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/opt/venv/lib/python3.10/site-packages/redis/connection.py", line 987, in _connect
    raise err
  File "/opt/venv/lib/python3.10/site-packages/redis/connection.py", line 975, in _connect
    sock.connect(socket_address)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/django/manage.py", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/opt/venv/lib/python3.10/site-packages/health_check/management/commands/health_check.py", line 13, in handle
    errors = self.errors
  File "/opt/venv/lib/python3.10/site-packages/health_check/mixins.py", line 16, in errors
    self._errors = self.run_check()
  File "/opt/venv/lib/python3.10/site-packages/health_check/mixins.py", line 44, in run_check
    for plugin in executor.map(_run, self.plugins):
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/venv/lib/python3.10/site-packages/health_check/mixins.py", line 35, in _run
    plugin.run_check()
  File "/opt/venv/lib/python3.10/site-packages/health_check/backends.py", line 30, in run_check
    self.check_status()
  File "/home/django/cvat/apps/health/backends.py", line 44, in check_status
    cache.set("djangohealtcheck_test", "itworks")
  File "/opt/venv/lib/python3.10/site-packages/django/core/cache/backends/redis.py", line 191, in set
    self._cache.set(key, value, self.get_backend_timeout(timeout))
  File "/opt/venv/lib/python3.10/site-packages/django/core/cache/backends/redis.py", line 108, in set
    client.set(key, value, ex=timeout)
  File "/opt/venv/lib/python3.10/site-packages/redis/commands/core.py", line 2302, in set
    return self.execute_command("SET", *pieces, **options)
  File "/opt/venv/lib/python3.10/site-packages/redis/client.py", line 1255, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/opt/venv/lib/python3.10/site-packages/redis/connection.py", line 1442, in get_connection
    connection.connect()
  File "/opt/venv/lib/python3.10/site-packages/redis/connection.py", line 704, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 99 connecting to localhost:6379. Cannot assign requested address.
```

### Expected Behavior

I can connect to the cvat from a web browser and login

### Environment

```Markdown
I am trying to install this on a Gentoo based linux server.
However, I also tried through WSL and Docker desktop on Windows and encountered the same issue.
This is trying to install the latest version 2.9.2
```

**Comment by aboccag** [comment]
Hello, I've the same error using docker

**Comment by nkinnaird** [comment]
I'm getting the same error with the most recent version 2.9.2.

**Comment by ScottSWu** [comment]
I was also hitting this error, on Ubuntu 18.04 LTS. I found the latest working version was `CVAT_VERSION=v2.6.1`.

**Comment by aboccag** [comment]
Any reason why it has been closed?

**Comment by blueclowd** [comment]
I have encountered the same issue and the workable version on my side is v2.9.2 while v2.5.0 and v2.6.1 don't work.
I am working on MacOS Monterey.
