### ISSUE TITLE
Could not create task for annotating 3D point cloud

### ISSUE THREAD

**Issue by AJAY31797** [opencv/cvat#7322]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. Open the CVAT home page
2. Go to the page for creating a new annotation task (from CVAT home page, click 'Try it Now')
3. Click '+' icon  and then click on 'Create new task'
4. On the 'Create a new task' window, enter the name of the task and the labels. 
5. In the 'Select File' section, Select the zip file containing the point clouds to be annotated (I tried with the individual files as well). I am trying to upload the files stored on my computer.  
6. Click 'Submit and open'.

### Expected Behavior

The task should be created. 
However, it shows the following error in case of the zip file:
`cvat-ui.458741b2860df2418acd.min.js:2 Error: Could not create task. Data processing failed. Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/rq/worker.py", line 1428, in perform_job
    rv = job.perform()
  File "/opt/venv/lib/python3.10/site-packages/rq/job.py", line 1278, in perform
    self._result = self._execute()
  File "/opt/venv/lib/python3.10/site-packages/rq/job.py", line 1315, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/django/cvat/apps/engine/task.py", line 757, in _create_thread
    extractor = MEDIA_TYPES[media_type]['extractor'](**details)
  File "/home/django/cvat/apps/engine/media_extractors.py", line 333, in __init__
    super().__init__(file_list,
  File "/home/django/cvat/apps/engine/media_extractors.py", line 156, in __init__
    raise Exception('No image found')
Exception: No image found
e @ cvat-ui.458741b2860df2418acd.min.js:2`

If I try with the individual files. I get the following error: 
`cvat-ui.458741b2860df2418acd.min.js:2 Error: Could not create task. Data processing failed. Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/rq/worker.py", line 1428, in perform_job
    rv = job.perform()
  File "/opt/venv/lib/python3.10/site-packages/rq/job.py", line 1278, in perform
    self._result = self._execute()
  File "/opt/venv/lib/python3.10/site-packages/rq/job.py", line 1315, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/django/cvat/apps/engine/task.py", line 652, in _create_thread
    media, task_mode = _validate_data(media, manifest_files)
  File "/home/django/cvat/apps/engine/task.py", line 266, in _validate_data
    raise ValueError('No media data found')
ValueError: No media data found`

### Possible Solution

I am not sure. Is it because I am trying to upload point clouds? But I saw some YouTube videos showing that CVAT supports point cloud annotation as well. So, it should not be the reason. 

### Context

I am trying to use CVAT for annotation of point cloud files (in .xyz format) for deep learning tasks. I could not attach the .xyz file as it is not supported here. 

### Environment

```Markdown
I am using the Windows 10 operating system and trying to use CVAT online on the Google Chrome browser.
```

**Comment by AJAY31797** [comment]
I figured it out. Thanks.
