### ISSUE TITLE
 I want to specify an IP address for CVAT_HOST.

### ISSUE THREAD

**Issue by Shin-ichi-Takayama** [opencv/cvat#7344]
I am trying to host CVAT on Virtul Machine in Azure.

### Operating environment
- Virtual Machine in Azure (Ubuntu20.04)
- I opened the incoming ports 80, 443, and 8080 of Virtual Machine.

### CVAT installation procedure
```
git clone https://github.com/opencv/cvat
cd cvat
export CVAT_HOST=20.243.17.158
export ACME_EMAIL=hoge@piyo.com
docker compose -f docker-compose.yml -f docker-compose.https.yml up -d
```

### Running the cvat-cli command
I ran the following cvat-cli command.
> cvat-cli --server-host https://20.243.17.158 --server-port 443 --auth user:password ls

However, the following error occurred.
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 666, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 377, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1001, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f73087abf10>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/cvat-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/cvat_cli/__main__.py", line 71, in main
    cli = CLI(client=client, credentials=parsed_args.auth)
  File "/usr/local/lib/python3.8/dist-packages/cvat_cli/cli.py", line 23, in __init__
    self.client.login(credentials)
  File "/usr/local/lib/python3.8/dist-packages/cvat_sdk/core/client.py", line 188, in login
    (auth, _) = self.api_client.auth_api.create_login(
  File "/usr/local/lib/python3.8/dist-packages/cvat_sdk/api_client/api/auth_api.py", line 558, in create_login
    return self.create_login_endpoint.call_with_http_info(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/cvat_sdk/api_client/api_client.py", line 1070, in call_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.8/dist-packages/cvat_sdk/api_client/api_client.py", line 501, in call_api
    return self.__call_api(**params)
  File "/usr/local/lib/python3.8/dist-packages/cvat_sdk/api_client/api_client.py", line 269, in __call_api
    response = self.request(
  File "/usr/local/lib/python3.8/dist-packages/cvat_sdk/api_client/api_client.py", line 533, in request
    return self.rest_client.POST(url,
  File "/usr/local/lib/python3.8/dist-packages/cvat_sdk/api_client/rest.py", line 256, in POST
    return self.request("POST", url,
  File "/usr/local/lib/python3.8/dist-packages/cvat_sdk/api_client/rest.py", line 144, in request
    r = self.pool_manager.request(
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 79, in request
    return self.request_encode_body(
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 748, in urlopen
    return self.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 748, in urlopen
    return self.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 748, in urlopen
    return self.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 720, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='20.243.17.158', port=443): Max retries exceeded with url: /api/auth/login (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f73087abf10>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

If I used the domain name for CVAT_HOST, no error occurred.
```
git clone https://github.com/opencv/cvat
cd cvat
export CVAT_HOST=cvat-pipeline.japaneast.cloudapp.azure.com
export ACME_EMAIL=hoge@piyo.com
docker compose -f docker-compose.yml -f docker-compose.https.yml up -d
```

> cvat-cli --server-host https://cvat-pipeline.japaneast.cloudapp.azure.com --auth user:password ls

How do I specify an IP address for CVAT_HOST?
Best regards.

**Comment by joshuasv** [comment]
Any updates?

**Comment by Shin-ichi-Takayama** [comment]
No updates. However, we no longer need to resolve this issue. I would like to know how to address this for the future.

**Comment by nmanovic** [comment]
@Shin-ichi-Takayama , we use let's encrypt to get a SSL certificate. IP address isn't supported by the service: https://community.letsencrypt.org/t/ssl-on-a-ip-instead-of-domain/90635
