### ISSUE TITLE
cvat_server container failing when deploying serverless component

### ISSUE THREAD

**Issue by jlwhelan28** [opencv/cvat#7378]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. Pull latest cvat release
```bash
curl -SL https://github.com/opencv/cvat/archive/refs/tags/v2.10.1.tar.gz -o cvat-2.10.1.tar.gz
tar -xvf cvat-2.10.1.tar.gz
cd cvat-2.10.1
```
2. Prune docker images/containers/volumes
```bash
docker system prune -a
docker volume prune
```
4. Deploy cvat w/o serverless component to confirm working (also using https)
```bash
export CVAT_HOST=< my fqdn >
export ACME_EMAIL=< my email >
docker compose -f docker-compose.yml -f docker-compose.https.yml up -d
docker container ps
```
```bash
NAME                            IMAGE                                       COMMAND                  SERVICE                         CREATED          STATUS                    PORTS
cvat_clickhouse                 clickhouse/clickhouse-server:23.11-alpine   "/entrypoint.sh"         cvat_clickhouse                 21 seconds ago   Up 20 seconds             8123/tcp, 9000/tcp, 9009/tcp
cvat_db                         postgres:15-alpine                          "docker-entrypoint.s…"   cvat_db                         21 seconds ago   Up 20 seconds             5432/tcp
cvat_opa                        openpolicyagent/opa:0.45.0-rootless         "/opa run --server -…"   cvat_opa                        21 seconds ago   Up 20 seconds
cvat_redis_inmem                redis:7.2.3-alpine                          "docker-entrypoint.s…"   cvat_redis_inmem                21 seconds ago   Up 20 seconds             6379/tcp
cvat_redis_ondisk               apache/kvrocks:2.7.0                        "kvrocks -c /var/lib…"   cvat_redis_ondisk               21 seconds ago   Up 20 seconds (healthy)   6666/tcp
cvat_server                     cvat/server:v2.10.1                         "./backend_entrypoin…"   cvat_server                     21 seconds ago   Up 17 seconds             8080/tcp
cvat_ui                         cvat/ui:v2.10.1                             "/docker-entrypoint.…"   cvat_ui                         21 seconds ago   Up 17 seconds             80/tcp
cvat_utils                      cvat/server:v2.10.1                         "./backend_entrypoin…"   cvat_utils                      21 seconds ago   Up 18 seconds             8080/tcp
cvat_vector                     timberio/vector:0.26.0-alpine               "/usr/local/bin/vect…"   cvat_vector                     21 seconds ago   Up 19 seconds
cvat_worker_analytics_reports   cvat/server:v2.10.1                         "./backend_entrypoin…"   cvat_worker_analytics_reports   21 seconds ago   Up 17 seconds             8080/tcp
cvat_worker_annotation          cvat/server:v2.10.1                         "./backend_entrypoin…"   cvat_worker_annotation          21 seconds ago   Up 18 seconds             8080/tcp
cvat_worker_export              cvat/server:v2.10.1                         "./backend_entrypoin…"   cvat_worker_export              21 seconds ago   Up 17 seconds             8080/tcp
cvat_worker_import              cvat/server:v2.10.1                         "./backend_entrypoin…"   cvat_worker_import              21 seconds ago   Up 19 seconds             8080/tcp
cvat_worker_quality_reports     cvat/server:v2.10.1                         "./backend_entrypoin…"   cvat_worker_quality_reports     21 seconds ago   Up 18 seconds             8080/tcp
cvat_worker_webhooks            cvat/server:v2.10.1                         "./backend_entrypoin…"   cvat_worker_webhooks            21 seconds ago   Up 18 seconds             8080/tcp
traefik                         traefik:v2.9                                "/entrypoint.sh trae…"   traefik                         21 seconds ago   Up 19 seconds             0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp, 0.0.0.0:8080->8080/tcp, :::8080->8080/tcp, 0.0.0.0:8090->8090/tcp, :::8090->8090/tcp
```

5. Deploy cvat with serverless component, `cvat_server` gets stuck in restart loop
Note: I did attempt to bump to the latest nuclio dashboard image, but got the same result... below container ps shows the more recent version instead of the currently configured 1.11.x
```bash
docker compose -f docker-compose.yml -f docker-compose.https.yml down
docker system prune -a
docker volume prune
docker compose -f docker-compose.yml -f docker-compose.https.yml -f components/serverless/docker-compose.serverless.yml up -d
```
```
AME                            IMAGE                                       COMMAND                  SERVICE                         CREATED          STATUS                          PORTS
cvat_clickhouse                 clickhouse/clickhouse-server:23.11-alpine   "/entrypoint.sh"         cvat_clickhouse                 14 minutes ago   Up 14 minutes                   8123/tcp, 9000/tcp, 9009/tcp
cvat_db                         postgres:15-alpine                          "docker-entrypoint.s…"   cvat_db                         14 minutes ago   Up 14 minutes                   5432/tcp
cvat_opa                        openpolicyagent/opa:0.45.0-rootless         "/opa run --server -…"   cvat_opa                        14 minutes ago   Up 14 minutes
cvat_redis_inmem                redis:7.2.3-alpine                          "docker-entrypoint.s…"   cvat_redis_inmem                14 minutes ago   Up 14 minutes                   6379/tcp
cvat_redis_ondisk               apache/kvrocks:2.7.0                        "kvrocks -c /var/lib…"   cvat_redis_ondisk               14 minutes ago   Up 14 minutes (healthy)         6666/tcp
cvat_server                     cvat/server:v2.10.1                         "./backend_entrypoin…"   cvat_server                     14 minutes ago   Restarting (1) 52 seconds ago
cvat_ui                         cvat/ui:v2.10.1                             "/docker-entrypoint.…"   cvat_ui                         14 minutes ago   Up 13 minutes                   80/tcp
cvat_utils                      cvat/server:v2.10.1                         "./backend_entrypoin…"   cvat_utils                      14 minutes ago   Up 14 minutes                   8080/tcp
cvat_vector                     timberio/vector:0.26.0-alpine               "/usr/local/bin/vect…"   cvat_vector                     14 minutes ago   Up 13 minutes
cvat_worker_analytics_reports   cvat/server:v2.10.1                         "./backend_entrypoin…"   cvat_worker_analytics_reports   14 minutes ago   Up 13 minutes                   8080/tcp
cvat_worker_annotation          cvat/server:v2.10.1                         "./backend_entrypoin…"   cvat_worker_annotation          14 minutes ago   Up 14 minutes                   8080/tcp
cvat_worker_export              cvat/server:v2.10.1                         "./backend_entrypoin…"   cvat_worker_export              14 minutes ago   Up 13 minutes                   8080/tcp
cvat_worker_import              cvat/server:v2.10.1                         "./backend_entrypoin…"   cvat_worker_import              14 minutes ago   Up 13 minutes                   8080/tcp
cvat_worker_quality_reports     cvat/server:v2.10.1                         "./backend_entrypoin…"   cvat_worker_quality_reports     14 minutes ago   Up 14 minutes                   8080/tcp
cvat_worker_webhooks            cvat/server:v2.10.1                         "./backend_entrypoin…"   cvat_worker_webhooks            14 minutes ago   Up 13 minutes                   8080/tcp
nuclio                          quay.io/nuclio/dashboard:1.12.11-amd64      "/docker-entrypoint.…"   nuclio                          14 minutes ago   Up 14 minutes (healthy)         80/tcp, 0.0.0.0:8070->8070/tcp, :::8070->8070/tcp
traefik                         traefik:v2.9                                "/entrypoint.sh trae…"   traefik                         14 minutes ago   Up 14 minutes                   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp, 0.0.0.0:8080->8080/tcp, :::8080->8080/tcp, 0.0.0.0:8090->8090/tcp, :::8090->8090/tcp
```
7. Viewing cvat_server logs - Error suggests to me that something is manipulating CVAT_ANALYTICS env var normally set to 1 by `docker-compose.yml` 
```bash
docker logs cvat_server
```
```bash
wait-for-it.sh: waiting for cvat_db:5432 without a timeout
wait-for-it.sh: cvat_db:5432 is available after 0 seconds
Traceback (most recent call last):
  File "/home/django/manage.py", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 382, in execute
    settings.INSTALLED_APPS
  File "/opt/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/opt/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/django/cvat/settings/production.py", line 5, in <module>
    from .base import *
  File "/home/django/cvat/settings/base.py", line 182, in <module>
    if to_bool(os.getenv('CVAT_ANALYTICS', False)):
  File "/opt/venv/lib/python3.10/site-packages/attr/converters.py", line 155, in to_bool
    raise ValueError("Cannot convert value to bool: {}".format(val))
ValueError: Cannot convert value to bool: %!s(int=1)
wait-for-it.sh: waiting for cvat_db:5432 without a timeout
wait-for-it.sh: cvat_db:5432 is available after 0 seconds
Traceback (most recent call last):
  File "/home/django/manage.py", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 382, in execute
    settings.INSTALLED_APPS
  File "/opt/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/opt/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/django/cvat/settings/production.py", line 5, in <module>
    from .base import *
  File "/home/django/cvat/settings/base.py", line 182, in <module>
    if to_bool(os.getenv('CVAT_ANALYTICS', False)):
  File "/opt/venv/lib/python3.10/site-packages/attr/converters.py", line 155, in to_bool
    raise ValueError("Cannot convert value to bool: {}".format(val))
ValueError: Cannot convert value to bool: %!s(int=1)
wait-for-it.sh: waiting for cvat_db:5432 without a timeout
wait-for-it.sh: cvat_db:5432 is available after 0 seconds
Traceback (most recent call last):
  File "/home/django/manage.py", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 382, in execute
    settings.INSTALLED_APPS
  File "/opt/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/opt/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/django/cvat/settings/production.py", line 5, in <module>
    from .base import *
  File "/home/django/cvat/settings/base.py", line 182, in <module>
    if to_bool(os.getenv('CVAT_ANALYTICS', False)):
  File "/opt/venv/lib/python3.10/site-packages/attr/converters.py", line 155, in to_bool
    raise ValueError("Cannot convert value to bool: {}".format(val))
ValueError: Cannot convert value to bool: %!s(int=1)
```

### Expected Behavior

cvat_server runs normally

### Environment

```Markdown
- Release 2.10.1 (a33f7f5)
- Running on an AWS EC2 (g4dn.xlarge)
- Amazon deep learning AMI (built on Amazon Linux 2)
- docker compose: v2.24.0
- docker: 20.10.25
```

**Comment by jlwhelan28** [comment]
Editing `docker-compose.yml` to force strings for the env variables fixes this issue, which based on the `%!s(int=1)` value seems to be coming from some interaction with go-lang? Not knowledgeable at all with Go on what might be happening, but changing `CVAT_ANALYTICS` to `'1'` instead of `1` in `docker-compose.yml` (and nothing else) gives me a healthy stack. I'd be happy to submit a PR to cleanup the yamls to ensure the env vars are strings.

**Comment by bsekachev** [comment]
Hello, 

It is not clear why exactly this error happened on your side, but in general, environment variables in docker compose files not obligatory to have a string type. 
And on our side we did not meet such the error. Let's look if somebody else has something like this. 

For now I will close the issue.

**Comment by mpolinowski** [comment]
Finally had a chance to update:

```
docker-compose version
> Docker Compose version 2.24.3
```

Everything works again 👍🏻 

![2024-01-29_14-35](https://github.com/opencv/cvat/assets/18694428/4dfaac76-897e-4553-9720-4d164da365da)
