### ISSUE TITLE
Exporting of Object Detection Annotations are failing intermittently

### ISSUE THREAD

**Issue by rajesh-thinkdeeply** [opencv/cvat#7409]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. Go to Projects->Tasks->Job
2. Export Annotations (Select Save Images, Enter Custom name, Use default Settings)
3. Fails with 500 error with following exception
```
cvat_server  | 2024-01-30T07:30:13.306092294Z [2024-01-30 07:30:13,299] ERROR django.request: Internal Server Error: /api/jobs/16/dataset
cvat_server  | 2024-01-30T07:30:13.306098038Z Traceback (most recent call last):
cvat_server  | 2024-01-30T07:30:13.306102645Z   File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 534, in thread_handler
cvat_server  | 2024-01-30T07:30:13.306107458Z     raise exc_info[1]
cvat_server  | 2024-01-30T07:30:13.306111943Z   File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
cvat_server  | 2024-01-30T07:30:13.306116766Z     response = await get_response(request)
cvat_server  | 2024-01-30T07:30:13.306121355Z   File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
cvat_server  | 2024-01-30T07:30:13.306126507Z     response = await wrapped_callback(
cvat_server  | 2024-01-30T07:30:13.306130960Z   File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 479, in __call__
cvat_server  | 2024-01-30T07:30:13.306135615Z     ret: _R = await loop.run_in_executor(
cvat_server  | 2024-01-30T07:30:13.306139904Z   File "/opt/venv/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 40, in run
cvat_server  | 2024-01-30T07:30:13.306144318Z     result = self.fn(*self.args, **self.kwargs)
cvat_server  | 2024-01-30T07:30:13.306148603Z   File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 538, in thread_handler
cvat_server  | 2024-01-30T07:30:13.306153135Z     return func(*args, **kwargs)
cvat_server  | 2024-01-30T07:30:13.306157394Z   File "/opt/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
cvat_server  | 2024-01-30T07:30:13.306161891Z     return view_func(*args, **kwargs)
cvat_server  | 2024-01-30T07:30:13.306181755Z   File "/opt/venv/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
cvat_server  | 2024-01-30T07:30:13.306186766Z     return self.dispatch(request, *args, **kwargs)
cvat_server  | 2024-01-30T07:30:13.306191038Z   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
cvat_server  | 2024-01-30T07:30:13.306195421Z     response = self.handle_exception(exc)
cvat_server  | 2024-01-30T07:30:13.306199893Z   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
cvat_server  | 2024-01-30T07:30:13.306204434Z     self.raise_uncaught_exception(exc)
cvat_server  | 2024-01-30T07:30:13.306208821Z   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
cvat_server  | 2024-01-30T07:30:13.306213291Z     raise exc
cvat_server  | 2024-01-30T07:30:13.306218001Z   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
cvat_server  | 2024-01-30T07:30:13.306222400Z     response = handler(request, *args, **kwargs)
cvat_server  | 2024-01-30T07:30:13.306226714Z   File "/home/django/cvat/apps/engine/views.py", line 1871, in dataset_export
cvat_server  | 2024-01-30T07:30:13.306231077Z     return self.export_annotations(
cvat_server  | 2024-01-30T07:30:13.306235428Z   File "/home/django/cvat/apps/engine/mixins.py", line 405, in export_annotations
cvat_server  | 2024-01-30T07:30:13.306241925Z     return export_func(db_instance=self._object,
cvat_server  | 2024-01-30T07:30:13.306246327Z   File "/home/django/cvat/apps/engine/views.py", line 3011, in _export_annotations
cvat_server  | 2024-01-30T07:30:13.306251267Z     if osp.exists(file_path):
cvat_server  | 2024-01-30T07:30:13.306255674Z   File "/usr/lib/python3.10/genericpath.py", line 19, in exists
cvat_server  | 2024-01-30T07:30:13.306260040Z     os.stat(path)
cvat_server  | 2024-01-30T07:30:13.306264314Z TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

### Expected Behavior

Export should work

### Environment

```Markdown
Server version: 2.10.0

Core version: 12.1.1

Canvas version: 2.19.0

UI version: 1.59.1
```

**Comment by bsekachev** [comment]
Hello, Just try to export one more time

**Comment by rajesh-thinkdeeply** [comment]
Either I get the above error or I get the below error:

```
[2024-01-30 01:03:30] INFO: Waiting for the server to prepare the file...
[2024-01-30 01:04:34] CRITICAL: Status Code: 504
Reason: Gateway Timeout
HTTP response headers: HTTPHeaderDict({'Content-Length': '176', 'Content-Type': 'text/html', 'Date': 'Tue, 30 Jan 2024 08:04:34 GMT', 'Server': 'nginx/1.18.0 (Ubuntu)'})
HTTP response body: b'<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx/1.18.0 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n'
```
I have followed instructions from https://github.com/opencv/cvat/issues/5885#issuecomment-1519180463
to increase the timeout by creating a customsuperviserd.conf 
I am oscillating the error between 500 and 504

**Comment by rajesh-thinkdeeply** [comment]
I get same error again

```
cvat_server  | 2024-01-30T09:00:52.527298389Z [2024-01-30 09:00:52,526] ERROR django.request: Internal Server Error: /api/jobs/10/annotations
cvat_server  | 2024-01-30T09:00:52.527303812Z Traceback (most recent call last):
cvat_server  | 2024-01-30T09:00:52.527308738Z   File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 534, in thread_handler
cvat_server  | 2024-01-30T09:00:52.527313605Z     raise exc_info[1]
cvat_server  | 2024-01-30T09:00:52.527531407Z   File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
cvat_server  | 2024-01-30T09:00:52.527548791Z     response = await get_response(request)
cvat_server  | 2024-01-30T09:00:52.527554036Z   File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
cvat_server  | 2024-01-30T09:00:52.527558572Z     response = await wrapped_callback(
cvat_server  | 2024-01-30T09:00:52.527563204Z   File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 479, in __call__
cvat_server  | 2024-01-30T09:00:52.527567628Z     ret: _R = await loop.run_in_executor(
cvat_server  | 2024-01-30T09:00:52.527572046Z   File "/opt/venv/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 40, in run
cvat_server  | 2024-01-30T09:00:52.527657113Z     result = self.fn(*self.args, **self.kwargs)
cvat_server  | 2024-01-30T09:00:52.527702314Z   File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 538, in thread_handler
cvat_server  | 2024-01-30T09:00:52.527727857Z     return func(*args, **kwargs)
cvat_server  | 2024-01-30T09:00:52.527768412Z   File "/opt/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
cvat_server  | 2024-01-30T09:00:52.527795491Z     return view_func(*args, **kwargs)
cvat_server  | 2024-01-30T09:00:52.527841164Z   File "/opt/venv/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
cvat_server  | 2024-01-30T09:00:52.527867810Z     return self.dispatch(request, *args, **kwargs)
cvat_server  | 2024-01-30T09:00:52.527892676Z   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
cvat_server  | 2024-01-30T09:00:52.527914982Z     response = self.handle_exception(exc)
cvat_server  | 2024-01-30T09:00:52.527938740Z   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
cvat_server  | 2024-01-30T09:00:52.527960684Z     self.raise_uncaught_exception(exc)
cvat_server  | 2024-01-30T09:00:52.527981505Z   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
cvat_server  | 2024-01-30T09:00:52.528004999Z     raise exc
cvat_server  | 2024-01-30T09:00:52.528027853Z   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
cvat_server  | 2024-01-30T09:00:52.528051287Z     response = handler(request, *args, **kwargs)
cvat_server  | 2024-01-30T09:00:52.528073157Z   File "/home/django/cvat/apps/engine/views.py", line 1774, in annotations
cvat_server  | 2024-01-30T09:00:52.528093690Z     return self.export_annotations(
cvat_server  | 2024-01-30T09:00:52.528117650Z   File "/home/django/cvat/apps/engine/mixins.py", line 405, in export_annotations
cvat_server  | 2024-01-30T09:00:52.528160754Z     return export_func(db_instance=self._object,
cvat_server  | 2024-01-30T09:00:52.528190612Z   File "/home/django/cvat/apps/engine/views.py", line 3011, in _export_annotations
cvat_server  | 2024-01-30T09:00:52.528212980Z     if osp.exists(file_path):
cvat_server  | 2024-01-30T09:00:52.528235182Z   File "/usr/lib/python3.10/genericpath.py", line 19, in exists
cvat_server  | 2024-01-30T09:00:52.528260747Z     os.stat(path)
cvat_server  | 2024-01-30T09:00:52.528282639Z TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Comment by rajesh-thinkdeeply** [comment]
Hello,
Any suggestions? It no longer happens intermittently. It is happening most of the time

```
cvat_server  | 2024-01-31T23:11:37.868117246Z 2024-01-31 23:11:37,867 DEBG 'uvicorn-1' stderr output:
cvat_server  | 2024-01-31T23:11:37.868148393Z [2024-01-31 23:11:37,866] ERROR django.request: Internal Server Error: /api/jobs/11/annotations
cvat_server  | 2024-01-31T23:11:37.868154102Z Traceback (most recent call last):
cvat_server  | 2024-01-31T23:11:37.868158973Z   File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 534, in thread_handler
cvat_server  | 2024-01-31T23:11:37.868163783Z     raise exc_info[1]
cvat_server  | 2024-01-31T23:11:37.868170106Z   File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
cvat_server  | 2024-01-31T23:11:37.868175286Z     response = await get_response(request)
cvat_server  | 2024-01-31T23:11:37.868180196Z   File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
cvat_server  | 2024-01-31T23:11:37.868185510Z     response = await wrapped_callback(
cvat_server  | 2024-01-31T23:11:37.868188788Z   File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 479, in __call__
cvat_server  | 2024-01-31T23:11:37.868193756Z     ret: _R = await loop.run_in_executor(
cvat_server  | 2024-01-31T23:11:37.868198500Z   File "/opt/venv/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 40, in run
cvat_server  | 2024-01-31T23:11:37.868203320Z     result = self.fn(*self.args, **self.kwargs)
cvat_server  | 2024-01-31T23:11:37.868207870Z   File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 538, in thread_handler
cvat_server  | 2024-01-31T23:11:37.868210573Z     return func(*args, **kwargs)
cvat_server  | 2024-01-31T23:11:37.868214972Z   File "/opt/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
cvat_server  | 2024-01-31T23:11:37.868220257Z     return view_func(*args, **kwargs)
cvat_server  | 2024-01-31T23:11:37.868225868Z   File "/opt/venv/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
cvat_server  | 2024-01-31T23:11:37.868228570Z     return self.dispatch(request, *args, **kwargs)
cvat_server  | 2024-01-31T23:11:37.868232948Z   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
cvat_server  | 2024-01-31T23:11:37.868237591Z     response = self.handle_exception(exc)
cvat_server  | 2024-01-31T23:11:37.868241916Z   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
cvat_server  | 2024-01-31T23:11:37.868246447Z     self.raise_uncaught_exception(exc)
cvat_server  | 2024-01-31T23:11:37.868250734Z   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
cvat_server  | 2024-01-31T23:11:37.868255292Z     raise exc
cvat_server  | 2024-01-31T23:11:37.868259600Z   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
cvat_server  | 2024-01-31T23:11:37.868280694Z     response = handler(request, *args, **kwargs)
cvat_server  | 2024-01-31T23:11:37.868285728Z   File "/home/django/cvat/apps/engine/views.py", line 1774, in annotations
cvat_server  | 2024-01-31T23:11:37.868290169Z     return self.export_annotations(
cvat_server  | 2024-01-31T23:11:37.868294499Z   File "/home/django/cvat/apps/engine/mixins.py", line 405, in export_annotations
cvat_server  | 2024-01-31T23:11:37.868300457Z     return export_func(db_instance=self._object,
cvat_server  | 2024-01-31T23:11:37.868306168Z   File "/home/django/cvat/apps/engine/views.py", line 3011, in _export_annotations
cvat_server  | 2024-01-31T23:11:37.868309249Z     if osp.exists(file_path):
cvat_server  | 2024-01-31T23:11:37.868315389Z   File "/usr/lib/python3.10/genericpath.py", line 19, in exists
cvat_server  | 2024-01-31T23:11:37.868318182Z     os.stat(path)
cvat_server  | 2024-01-31T23:11:37.868324469Z TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
cvat_server  | 2024-01-31T23:11:37.868328872Z 
cvat_server  | 2024-01-31T23:11:37.870329695Z 2024-01-31 23:11:37,870 DEBG 'uvicorn-1' stdout output:
cvat_server  | 2024-01-31T23:11:37.870368617Z INFO:     97.121.217.219:0 - "GET /api/jobs/11/annotations?org=td&use_default_location=false&location=local&filename=cmi_sample7.zip&format=COCO+1.0 HTTP/1.0" 500 Internal Server Error
```

**Comment by bsekachev** [comment]
It is not clear how to reproduce it. 
We met this error before, but now we don't. 

I may only suggest upgrade your CVAT to [v2.10.2](https://github.com/opencv/cvat/releases/tag/v2.10.2)

**Comment by rookiehelm** [comment]
upgrade to v2.10.2 helped.
