### ISSUE TITLE
Helm charts failing to deploy onto AWS EKS as is

### ISSUE THREAD

**Issue by rookiehelm** [opencv/cvat#7433]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. Provisioned EKS (k8s engine: v1.25)
2. Provisioned a node with 8vcpu & 32gb RAM
3. Run `helm dependency update` inside charts directory
4. Composed override YAML (see below for content)
5. Provisioned a PVC named `cvat-pvc` for 50Gi
6. Issue deployment command as per [official docs](https://opencv.github.io/cvat/docs/administration/advanced/k8s_deployment_with_helm/#with-overrides)
7. `cvat_server` fails and stays in `Error` state
8. Post configuration deployment also fails with error saying the desired python file `secret.py` does not exist
9. When I enter the pod and look at the `/home/django/keys` directory, it is empty.

### Expected Behavior

Deployment should complete successfully and all pods are running. 
Current behaviour: all pods are running except backend server which is failling with error message as shown in logs below.

### Context

values.override.yaml

```
analytics:
  enabled: false
cvat:
  backend:
    disableDistinctCachePerService: true
    permissionFix:
      enabled: false
    defaultStorage:
      enabled: false
    server:
      additionalVolumes:
        - name: cvat-backend-data
          persistentVolumeClaim:
            claimName: cvat-pvc
    worker:
      export:
        additionalVolumes:
          - name: cvat-backend-data
            persistentVolumeClaim:
              claimName: cvat-pvc
      import:
        additionalVolumes:
          - name: cvat-backend-data
            persistentVolumeClaim:
              claimName: cvat-pvc
      annotation:
        additionalVolumes:
          - name: cvat-backend-data
            persistentVolumeClaim:
              claimName: cvat-pvc

```

Logs of `cvat_server` pod:
```
Traceback (most recent call last):
  File "/home/django/cvat/settings/base.py", line 82, in <module>
    from keys.secret_key import SECRET_KEY # pylint: disable=unused-import
ModuleNotFoundError: No module named 'keys.secret_key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/django/manage.py", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 382, in execute
    settings.INSTALLED_APPS
  File "/opt/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/opt/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/django/cvat/settings/production.py", line 5, in <module>
    from .base import *
  File "/home/django/cvat/settings/base.py", line 84, in <module>
    generate_secret_key()
  File "/home/django/cvat/settings/base.py", line 63, in generate_secret_key
    with tempfile.NamedTemporaryFile(
  File "/usr/lib/python3.10/tempfile.py", line 698, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,
  File "/usr/lib/python3.10/tempfile.py", line 695, in opener
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/lib/python3.10/tempfile.py", line 395, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
PermissionError: [Errno 13] Permission denied: '/home/django/keys/secret_key.py.fwrq33fy'
```

When trying to create super user or health check, fails with below error:
```
Traceback (most recent call last):
  File "/home/django/cvat/settings/base.py", line 82, in <module>
    from keys.secret_key import SECRET_KEY # pylint: disable=unused-import
ModuleNotFoundError: No module named 'keys.secret_key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/django/manage.py", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 382, in execute
    settings.INSTALLED_APPS
  File "/opt/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/opt/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/django/cvat/settings/production.py", line 5, in <module>
    from .base import *
  File "/home/django/cvat/settings/base.py", line 84, in <module>
    generate_secret_key()
  File "/home/django/cvat/settings/base.py", line 63, in generate_secret_key
    with tempfile.NamedTemporaryFile(
  File "/usr/lib/python3.10/tempfile.py", line 698, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,
  File "/usr/lib/python3.10/tempfile.py", line 695, in opener
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/lib/python3.10/tempfile.py", line 395, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
PermissionError: [Errno 13] Permission denied: '/home/django/keys/secret_key.py.y0frzayq'
command terminated with exit code 1
```

### Environment

```Markdown
- On branch `release-2.7.1`
- EKS kubernetes engine version v1.25
```

**Comment by bsekachev** [comment]
Hello, please, try the latest release first.

**Comment by crisdaner** [comment]
Hello, I am having the same problems in EKS, I am testing in release 2.14.3.
permissionFix  Should it be false?

**Comment by cnsv-gft** [comment]
Hello, I am having the same problems in EKS, I am testing in release 2.14.3.
