### ISSUE TITLE
cvat-cli create cannot create task from local media and manifest.jsonl

### ISSUE THREAD

**Issue by antortjim** [opencv/cvat#7437]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

https://opencv.github.io/cvat/docs/manual/advanced/data_on_fly/
https://opencv.github.io/cvat/docs/api_sdk/cli/

### Steps to Reproduce

**labels.json**

```
[
    {
        "name": "foo",
        "attributes": []
    }
]
```

**manifest.jsonl**
```
{"version": "1.0"}
{"type": "images"}
{"name": "dataset/image", "extension": ".png", "width": 100, "height": 100 , "meta": {"related_images": []}, "checksum": "c2bc34648c583e6b9959c60bf51a4eff"}
```

Recreate dataset
```
mkdir dataset
wget -O dataset/image.png https://en.wikipedia.org/static/images/icons/wikipedia.png
```

```
cvat-cli   --server-host "http://0.0.0.0"  --server-port 8080 create task --labels labels.json --use_cache --filename_pattern "*" local manifest.jsonl
```

### Expected Behavior

I expected cvat-cli to 
1) Create a task in my locally running cvat instance
2) Upload the image.png file to the instance and attach it to the task 

Only 1) is carried out (I see the task created in the CVAT GUI), but the image is not, because I get the following error:

```
cvat-cli --server-host "http://0.0.0.0" --server-port 8080 create task --labels labels.json --use_cache --filename_pattern "*" local manifest.jsonl 
Password: 
[2024-02-04 20:17:52] INFO: Created task ID: 108 NAME: task
Uploading data: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 196/196 [00:00<00:00, 2.40kB/s]
[2024-02-04 20:17:52] INFO: Awaiting for task 108 creation...
[2024-02-04 20:17:54] INFO: Task 108 creation status: Failed (message=Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/rq/worker.py", line 1428, in perform_job
    rv = job.perform()
  File "/opt/venv/lib/python3.10/site-packages/rq/job.py", line 1278, in perform
    self._result = self._execute()
  File "/opt/venv/lib/python3.10/site-packages/rq/job.py", line 1315, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/django/cvat/apps/engine/task.py", line 651, in _create_thread
    media, task_mode = _validate_data(media, manifest_files)
  File "/home/django/cvat/apps/engine/task.py", line 265, in _validate_data
    raise ValueError('No media data found')
ValueError: No media data found)
[2024-02-04 20:17:54] CRITICAL: Status Code: 200
Reason: OK
HTTP response headers: HTTPHeaderDict({'Allow': 'GET, HEAD, OPTIONS', 'Content-Length': '846', 'Content-Type': 'application/vnd.cvat+json', 'Cross-Origin-Opener-Policy': 'same-origin', 'Date': 'Sun, 04 Feb 2024 20:17:54 GMT', 'Referrer-Policy': 'same-origin', 'Server': 'nginx/1.18.0 (Ubuntu)', 'Vary': 'Accept, Accept-Encoding, Origin', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'DENY, deny', 'X-Request-Id': 'e5858ebf-e54a-4cb8-b0c0-89d7f05f5c62'})
HTTP response body: b'{"state":"Failed","message":"Traceback (most recent call last):\\n  File \\"/opt/venv/lib/python3.10/site-packages/rq/worker.py\\", line 1428, in perform_job\\n    rv = job.perform()\\n  File \\"/opt/venv/lib/python3.10/site-packages/rq/job.py\\", line 1278, in perform\\n    self._result = self._execute()\\n  File \\"/opt/venv/lib/python3.10/site-packages/rq/job.py\\", line 1315, in _execute\\n    result = self.func(*self.args, **self.kwargs)\\n  File \\"/usr/lib/python3.10/contextlib.py\\", line 79, in inner\\n    return func(*args, **kwds)\\n  File \\"/home/django/cvat/apps/engine/task.py\\", line 651, in _create_thread\\n    media, task_mode = _validate_data(media, manifest_files)\\n  File \\"/home/django/cvat/apps/engine/task.py\\", line 265, in _validate_data\\n    raise ValueError(\'No media data found\')\\nValueError: No media data found","progress":0.0}'
```

I really don't get it, since the image is clearly there

```
tree  dataset/
dataset/
└── image.png

0 directories, 1 file
```

### Possible Solution

My workaround for now is to specify the images in manifest.jsonl separately i.e. to run

```
cvat-cli --server-host "http://0.0.0.0"  --server-port 8080 create task --labels labels.json local dataset/image.png #  dataset/image2.png dataset/image3.png # if there are more images
```

**EDIT**

Actually, it is possible to pass the list of images using `find` + `xargs`

```
find dataset/ -regex .*png | xargs cvat-cli --server-host "http://0.0.0.0"  --server-port 8080 create task --labels labels.json local 
```

But I was wondering if there is a better way. Also, I noticed cvat limits the number of frames per task to a few hundred. Can this limit be controlled?

### Context

I need to upload multiple (thousands) images at once, and I am afraid just adding them all to the command line may not be an option, because I may get a `Too many arguments error` or something like that. Besides, it should be possible to just upload a folder of images, just like one can upload a video (which is a container of images).

### Environment

I am using cvat with commit `a33f7f57088744bab61f18e8a8cf6528a0c22fd2`  (tag: `v2.10.1`) on Docker

```Markdown

Client:
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.1
 Git commit:        20.10.21-0ubuntu1~22.04.3
 Built:             Thu Apr 27 05:57:17 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.1
  Git commit:       20.10.21-0ubuntu1~22.04.3
  Built:            Thu Apr 27 05:37:25 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.12-0ubuntu1~22.04.3
  GitCommit:        
 runc:
  Version:          1.1.7-0ubuntu1~22.04.2
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        

```

Environment:
Python 3.10.11 (mamba environment)
cvat_cli `2.10.1`
cvat_sdk `2.10.1`

OS:
Ubuntu 22.04.2 LTS

docker logs cvat_ui:

```
cvat_server                      | 2024-02-04 20:27:35,462 DEBG 'uvicorn-1' stdout output:
cvat_server                      | INFO:     172.20.0.1:0 - "POST /api/auth/login HTTP/1.0" 200 OK
cvat_server                      | 
traefik                          | {"ClientAddr":"172.20.0.1:36248","ClientHost":"172.20.0.1","ClientPort":"36248","ClientUsername":"-","DownstreamContentSize":50,"DownstreamStatus":200,"Duration":146339063,"OriginContentSize":50,"OriginDuration":146276161,"OriginStatus":200,"Overhead":62902,"RequestAddr":"0.0.0.0:8080","RequestContentSize":52,"RequestCount":277,"RequestHost":"0.0.0.0","RequestMethod":"POST","RequestPath":"/api/auth/login","RequestPort":"8080","RequestProtocol":"HTTP/1.1","RequestScheme":"http","RetryAttempts":0,"RouterName":"cvat@docker","ServiceAddr":"172.20.0.10:8080","ServiceName":"cvat@docker","ServiceURL":{"Scheme":"http","Opaque":"","User":null,"Host":"172.20.0.10:8080","Path":"","RawPath":"","OmitHost":false,"ForceQuery":false,"RawQuery":"","Fragment":"","RawFragment":""},"StartLocal":"2024-02-04T20:27:35.316800436Z","StartUTC":"2024-02-04T20:27:35.316800436Z","entryPointName":"web","level":"info","msg":"","time":"2024-02-04T20:27:35Z"}
traefik                          | {"ClientAddr":"172.20.0.1:36248","ClientHost":"172.20.0.1","ClientPort":"36248","ClientUsername":"-","DownstreamContentSize":450,"DownstreamStatus":200,"Duration":15345823,"OriginContentSize":450,"OriginDuration":15299043,"OriginStatus":200,"Overhead":46780,"RequestAddr":"0.0.0.0:8080","RequestContentSize":0,"RequestCount":278,"RequestHost":"0.0.0.0","RequestMethod":"GET","RequestPath":"/api/server/about","RequestPort":"8080","RequestProtocol":"HTTP/1.1","RequestScheme":"http","RetryAttempts":0,"RouterName":"cvat@docker","ServiceAddr":"172.20.0.10:8080","ServiceName":"cvat@docker","ServiceURL":{"Scheme":"http","Opaque":"","User":null,"Host":"172.20.0.10:8080","Path":"","RawPath":"","OmitHost":false,"ForceQuery":false,"RawQuery":"","Fragment":"","RawFragment":""},"StartLocal":"2024-02-04T20:27:35.464562219Z","StartUTC":"2024-02-04T20:27:35.464562219Z","entryPointName":"web","level":"info","msg":"","time":"2024-02-04T20:27:35Z"}
cvat_server                      | 2024-02-04 20:27:35,480 DEBG 'uvicorn-0' stdout output:
cvat_server                      | INFO:     172.20.0.1:0 - "GET /api/server/about HTTP/1.0" 200 OK
cvat_server                      | 
cvat_server                      | 2024-02-04 20:27:35,521 DEBG 'uvicorn-0' stderr output:
cvat_server                      | [2024-02-04 20:27:35,521] INFO cvat.apps.engine.serializers: [Task.id=113] label:create Label id:405 for spec:OrderedDict([('name', 'foo'), ('color', '#ddfb36')]) with sublabels:[], parent_label:None
cvat_server                      | 
cvat_server                      | 2024-02-04 20:27:35,544 DEBG 'uvicorn-0' stdout output:
cvat_server                      | INFO:     172.20.0.1:0 - "POST /api/tasks HTTP/1.0" 201 Created
cvat_server                      | 
traefik                          | {"ClientAddr":"172.20.0.1:36248","ClientHost":"172.20.0.1","ClientPort":"36248","ClientUsername":"-","DownstreamContentSize":652,"DownstreamStatus":201,"Duration":63032638,"OriginContentSize":652,"OriginDuration":63006598,"OriginStatus":201,"Overhead":26040,"RequestAddr":"0.0.0.0:8080","RequestContentSize":63,"RequestCount":279,"RequestHost":"0.0.0.0","RequestMethod":"POST","RequestPath":"/api/tasks","RequestPort":"8080","RequestProtocol":"HTTP/1.1","RequestScheme":"http","RetryAttempts":0,"RouterName":"cvat@docker","ServiceAddr":"172.20.0.10:8080","ServiceName":"cvat@docker","ServiceURL":{"Scheme":"http","Opaque":"","User":null,"Host":"172.20.0.10:8080","Path":"","RawPath":"","OmitHost":false,"ForceQuery":false,"RawQuery":"","Fragment":"","RawFragment":""},"StartLocal":"2024-02-04T20:27:35.48123049Z","StartUTC":"2024-02-04T20:27:35.48123049Z","entryPointName":"web","level":"info","msg":"","time":"2024-02-04T20:27:35Z"}
cvat_server                      | 2024-02-04 20:27:35,595 DEBG 'uvicorn-0' stdout output:
cvat_server                      | INFO:     172.20.0.1:0 - "POST /api/tasks/113/data/ HTTP/1.0" 202 Accepted
cvat_server                      | 
traefik                          | {"ClientAddr":"172.20.0.1:36248","ClientHost":"172.20.0.1","ClientPort":"36248","ClientUsername":"-","DownstreamContentSize":0,"DownstreamStatus":202,"Duration":48416031,"OriginContentSize":0,"OriginDuration":48382407,"OriginStatus":202,"Overhead":33624,"RequestAddr":"0.0.0.0:8080","RequestContentSize":0,"RequestCount":280,"RequestHost":"0.0.0.0","RequestMethod":"POST","RequestPath":"/api/tasks/113/data/","RequestPort":"8080","RequestProtocol":"HTTP/1.1","RequestScheme":"http","RetryAttempts":0,"RouterName":"cvat@docker","ServiceAddr":"172.20.0.10:8080","ServiceName":"cvat@docker","ServiceURL":{"Scheme":"http","Opaque":"","User":null,"Host":"172.20.0.10:8080","Path":"","RawPath":"","OmitHost":false,"ForceQuery":false,"RawQuery":"","Fragment":"","RawFragment":""},"StartLocal":"2024-02-04T20:27:35.54712414Z","StartUTC":"2024-02-04T20:27:35.54712414Z","entryPointName":"web","level":"info","msg":"","time":"2024-02-04T20:27:35Z"}
cvat_server                      | 2024-02-04 20:27:35,634 DEBG 'uvicorn-1' stdout output:
cvat_server                      | INFO:     172.20.0.1:0 - "POST /api/tasks/113/data/ HTTP/1.0" 200 OK
cvat_server                      | 
traefik                          | {"ClientAddr":"172.20.0.1:36248","ClientHost":"172.20.0.1","ClientPort":"36248","ClientUsername":"-","DownstreamContentSize":0,"DownstreamStatus":200,"Duration":36320719,"OriginContentSize":0,"OriginDuration":36284740,"OriginStatus":200,"Overhead":35979,"RequestAddr":"0.0.0.0:8080","RequestContentSize":614,"RequestCount":281,"RequestHost":"0.0.0.0","RequestMethod":"POST","RequestPath":"/api/tasks/113/data/","RequestPort":"8080","RequestProtocol":"HTTP/1.1","RequestScheme":"http","RetryAttempts":0,"RouterName":"cvat@docker","ServiceAddr":"172.20.0.10:8080","ServiceName":"cvat@docker","ServiceURL":{"Scheme":"http","Opaque":"","User":null,"Host":"172.20.0.10:8080","Path":"","RawPath":"","OmitHost":false,"ForceQuery":false,"RawQuery":"","Fragment":"","RawFragment":""},"StartLocal":"2024-02-04T20:27:35.59875809Z","StartUTC":"2024-02-04T20:27:35.59875809Z","entryPointName":"web","level":"info","msg":"","time":"2024-02-04T20:27:35Z"}
cvat_worker_import               | 2024-02-04 20:27:35,686 DEBG 'rqworker-import-0' stderr output:
cvat_worker_import               | [2024-02-04 20:27:35,686] DEBUG rq.worker: Dequeued job create:task.id113 from import
cvat_worker_import               | 
cvat_worker_import               | 2024-02-04 20:27:35,687 DEBG 'rqworker-import-0' stderr output:
cvat_worker_import               | [2024-02-04 20:27:35,686] INFO rq.worker: import: cvat.apps.engine.task._create_thread(113, {'chunk_size': None, 'size': 0, 'image_quality': 70, 'start_frame': 0, 'sto...) (create:task.id113)
cvat_worker_import               | 
cvat_worker_import               | 2024-02-04 20:27:35,687 DEBG 'rqworker-import-0' stderr output:
cvat_worker_import               | [2024-02-04 20:27:35,687] DEBUG rq.worker: Sent heartbeat to prevent worker timeout. Next one should arrive in 480 seconds.
cvat_worker_import               | 
cvat_server                      | 2024-02-04 20:27:35,688 DEBG 'uvicorn-1' stdout output:
cvat_server                      | INFO:     172.20.0.1:0 - "POST /api/tasks/113/data/ HTTP/1.0" 202 Accepted
cvat_server                      | 
traefik                          | {"ClientAddr":"172.20.0.1:36248","ClientHost":"172.20.0.1","ClientPort":"36248","ClientUsername":"-","DownstreamContentSize":426,"DownstreamStatus":202,"Duration":52363274,"OriginContentSize":426,"OriginDuration":52289322,"OriginStatus":202,"Overhead":73952,"RequestAddr":"0.0.0.0:8080","RequestContentSize":147,"RequestCount":282,"RequestHost":"0.0.0.0","RequestMethod":"POST","RequestPath":"/api/tasks/113/data/","RequestPort":"8080","RequestProtocol":"HTTP/1.1","RequestScheme":"http","RetryAttempts":0,"RouterName":"cvat@docker","ServiceAddr":"172.20.0.10:8080","ServiceName":"cvat@docker","ServiceURL":{"Scheme":"http","Opaque":"","User":null,"Host":"172.20.0.10:8080","Path":"","RawPath":"","OmitHost":false,"ForceQuery":false,"RawQuery":"","Fragment":"","RawFragment":""},"StartLocal":"2024-02-04T20:27:35.636223294Z","StartUTC":"2024-02-04T20:27:35.636223294Z","entryPointName":"web","level":"info","msg":"","time":"2024-02-04T20:27:35Z"}
cvat_worker_import               | 2024-02-04 20:27:35,703 DEBG 'rqworker-import-0' stderr output:
cvat_worker_import               | [2024-02-04 20:27:35,703] DEBUG rq.worker: Started Job Registry set.
cvat_worker_import               | 
cvat_worker_import               | 2024-02-04 20:27:35,703 DEBG 'rqworker-import-0' stderr output:
cvat_worker_import               | [2024-02-04 20:27:35,703] DEBUG rq.worker: Preparing for execution of Job ID create:task.id113
cvat_worker_import               | 
cvat_worker_import               | 2024-02-04 20:27:35,704 DEBG 'rqworker-import-0' stderr output:
cvat_worker_import               | [2024-02-04 20:27:35,704] DEBUG rq.worker: Sent heartbeat to prevent worker timeout. Next one should arrive in 90 seconds.
cvat_worker_import               | 
cvat_worker_import               | 2024-02-04 20:27:35,706 DEBG 'rqworker-import-0' stderr output:
cvat_worker_import               | [2024-02-04 20:27:35,706] DEBUG rq.worker: Job preparation finished.
cvat_worker_import               | 
cvat_worker_import               | 2024-02-04 20:27:35,706 DEBG 'rqworker-import-0' stderr output:
cvat_worker_import               | [2024-02-04 20:27:35,706] DEBUG rq.worker: Performing Job...
cvat_worker_import               | 
cvat_worker_import               | 2024-02-04 20:27:35,718 DEBG 'rqworker-import-0' stderr output:
cvat_worker_import               | [2024-02-04 20:27:35,718] INFO cvat.apps.engine.task: create task #113
cvat_worker_import               | 
cvat_worker_import               | 2024-02-04 20:27:35,720 DEBG 'rqworker-import-0' stderr output:
cvat_worker_import               | [2024-02-04 20:27:35,720] DEBUG rq.worker: Job create:task.id113 raised an exception.
cvat_worker_import               | 
cvat_worker_import               | 2024-02-04 20:27:35,721 DEBG 'rqworker-import-0' stderr output:
cvat_worker_import               | [2024-02-04 20:27:35,721] DEBUG rq.worker: Handling failed execution of job create:task.id113
cvat_worker_import               | 
cvat_worker_import               | 2024-02-04 20:27:35,723 DEBG 'rqworker-import-0' stderr output:
cvat_worker_import               | [2024-02-04 20:27:35,723] DEBUG rq.worker: Handling exception for create:task.id113.
cvat_worker_import               | 
cvat_worker_import               | 2024-02-04 20:27:35,723 DEBG 'rqworker-import-0' stderr output:
cvat_worker_import               | [2024-02-04 20:27:35,723] ERROR rq.worker: [Job create:task.id113]: exception raised while executing (cvat.apps.engine.task._create_thread)
cvat_worker_import               | Traceback (most recent call last):
cvat_worker_import               |   File "/opt/venv/lib/python3.10/site-packages/rq/worker.py", line 1428, in perform_job
cvat_worker_import               |     rv = job.perform()
cvat_worker_import               |   File "/opt/venv/lib/python3.10/site-packages/rq/job.py", line 1278, in perform
cvat_worker_import               |     self._result = self._execute()
cvat_worker_import               |   File "/opt/venv/lib/python3.10/site-packages/rq/job.py", line 1315, in _execute
cvat_worker_import               |     result = self.func(*self.args, **self.kwargs)
cvat_worker_import               |   File "/usr/lib/python3.10/contextlib.py", line 79, in inner
cvat_worker_import               |     return func(*args, **kwds)
cvat_worker_import               |   File "/home/django/cvat/apps/engine/task.py", line 651, in _create_thread
cvat_worker_import               |     media, task_mode = _validate_data(media, manifest_files)
cvat_worker_import               |   File "/home/django/cvat/apps/engine/task.py", line 265, in _validate_data
cvat_worker_import               |     raise ValueError('No media data found')
cvat_worker_import               | ValueError: No media data found
cvat_worker_import               | 
cvat_worker_import               | 
cvat_worker_import               | 2024-02-04 20:27:35,724 DEBG 'rqworker-import-0' stderr output:
cvat_worker_import               | [2024-02-04 20:27:35,723] DEBUG rq.worker: Invoking exception handler <function rq_exception_handler at 0x7f4764402560>
cvat_worker_import               | 
cvat_worker_import               | 2024-02-04 20:27:35,724 DEBG 'rqworker-import-0' stderr output:
cvat_worker_import               | [2024-02-04 20:27:35,724] DEBUG rq.worker: Invoking exception handler <function handle_rq_exception at 0x7f48492cf6d0>
cvat_worker_import               | 
cvat_worker_import               | 2024-02-04 20:27:35,744 DEBG 'rqworker-import-0' stderr output:
cvat_worker_import               | [2024-02-04 20:27:35,744] DEBUG rq.worker: Sent heartbeat to prevent worker timeout. Next one should arrive in 480 seconds.
cvat_worker_import               | 
cvat_worker_import               | 2024-02-04 20:27:35,744 DEBG 'rqworker-import-0' stderr output:
cvat_worker_import               | [2024-02-04 20:27:35,744] DEBUG rq.worker: Sent heartbeat to prevent worker timeout. Next one should arrive in 480 seconds.
cvat_worker_import               | 
cvat_worker_import               | 2024-02-04 20:27:35,745 DEBG 'rqworker-import-0' stderr output:
cvat_worker_import               | [2024-02-04 20:27:35,745] DEBUG rq.worker: *** Listening on import...
cvat_worker_import               | 
cvat_worker_import               | 2024-02-04 20:27:35,745 DEBG 'rqworker-import-0' stderr output:
cvat_worker_import               | [2024-02-04 20:27:35,745] DEBUG rq.worker: Sent heartbeat to prevent worker timeout. Next one should arrive in 480 seconds.
cvat_worker_import               | 
cvat_worker_import               | 2024-02-04 20:27:35,745 DEBG 'rqworker-import-0' stderr output:
cvat_worker_import               | [2024-02-04 20:27:35,745] DEBUG rq.worker: Dequeueing jobs on queues import and timeout 405
cvat_worker_import               | 
cvat_redis_inmem                 | 1:M 04 Feb 2024 20:27:35.764 * 100 changes in 60 seconds. Saving...
cvat_redis_inmem                 | 1:M 04 Feb 2024 20:27:35.764 * Background saving started by pid 41
cvat_redis_inmem                 | 41:C 04 Feb 2024 20:27:35.769 * DB saved on disk
cvat_redis_inmem                 | 41:C 04 Feb 2024 20:27:35.769 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
cvat_redis_inmem                 | 1:M 04 Feb 2024 20:27:35.865 * Background saving terminated with success
cvat_server                      | 2024-02-04 20:27:37,725 DEBG 'uvicorn-1' stdout output:
cvat_server                      | INFO:     172.20.0.1:0 - "GET /api/tasks/113/status HTTP/1.0" 200 OK
cvat_server                      | 
traefik                          | {"ClientAddr":"172.20.0.1:36248","ClientHost":"172.20.0.1","ClientPort":"36248","ClientUsername":"-","DownstreamContentSize":846,"DownstreamStatus":200,"Duration":33580691,"OriginContentSize":846,"OriginDuration":33531176,"OriginStatus":200,"Overhead":49515,"RequestAddr":"0.0.0.0:8080","RequestContentSize":0,"RequestCount":283,"RequestHost":"0.0.0.0","RequestMethod":"GET","RequestPath":"/api/tasks/113/status","RequestPort":"8080","RequestProtocol":"HTTP/1.1","RequestScheme":"http","RetryAttempts":0,"RouterName":"cvat@docker","ServiceAddr":"172.20.0.10:8080","ServiceName":"cvat@docker","ServiceURL":{"Scheme":"http","Opaque":"","User":null,"Host":"172.20.0.10:8080","Path":"","RawPath":"","OmitHost":false,"ForceQuery":false,"RawQuery":"","Fragment":"","RawFragment":""},"StartLocal":"2024-02-04T20:27:37.692386328Z","StartUTC":"2024-02-04T20:27:37.692386328Z","entryPointName":"web","level":"info","msg":"","time":"2024-02-04T20:27:37Z"}
cvat_server                      | 2024-02-04 20:27:44,743 DEBG 'uvicorn-1' stdout output:
cvat_server                      | INFO:     172.20.0.7:0 - "GET /api/auth/rules HTTP/1.0" 304 Not Modified
cvat_server                      | 
cvat_server                      | 2024-02-04 20:27:55,633 DEBG 'uvicorn-1' stdout output:
cvat_server                      | INFO:     172.20.0.7:0 - "GET /api/auth/rules HTTP/1.0" 304 Not Modified
cvat_server                      | 
cvat_server                      | 2024-02-04 20:28:08,369 DEBG 'uvicorn-1' stdout output:
cvat_server                      | INFO:     172.20.0.7:0 - "GET /api/auth/rules HTTP/1.0" 304 Not Modified
cvat_server                      | 
cvat_db                          | 2024-02-04 20:28:09.155 UTC [22] LOG:  checkpoint starting: time
cvat_db                          | 2024-02-04 20:28:13.981 UTC [22] LOG:  checkpoint complete: wrote 52 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=4.814 s, sync=0.005 s, total=4.826 s; sync files=47, longest=0.003 s, average=0.001 s; distance=100 kB, estimate=211 kB
cvat_grafana                     | logger=cleanup t=2024-02-04T20:28:14.994597339Z level=info msg="Completed cleanup jobs" duration=19.019678ms
cvat_grafana                     | logger=grafana.update.checker t=2024-02-04T20:28:15.01149483Z level=info msg="Update check succeeded" duration=12.737237ms
cvat_grafana                     | logger=plugins.update.checker t=2024-02-04T20:28:15.066506865Z level=info msg="Update check succeeded" duration=37.658164ms
cvat_server                      | 2024-02-04 20:28:16,383 DEBG 'uvicorn-0' stdout output:
cvat_server                      | INFO:     172.20.0.7:0 - "GET /api/auth/rules HTTP/1.0" 304 Not Modified
cvat_server                      | 

```
```

**Comment by bsekachev** [comment]
Hello, 

From local you may only upload flat list of files. 
If you need hierarchy structure, zip this structure and upload ZIP archive.

**Comment by stiv-yakovenko** [comment]
Documentation missleadingly says its possible to specify folder after **local**:

cvat-cli --auth user-2 task create "task from dataset_1" --labels labels.json \
--bug_tracker https://bug-tracker.com/0001 --image_quality 75 --annotation_path annotation.xml \
--annotation_format "CVAT 1.1" local dataset_1/images/

https://docs.cvat.ai/docs/api_sdk/cli/

is it possible to fix it in the documentation or better in cvat-cli?
