### ISSUE TITLE
Consistent 500 (Internal server error)

### ISSUE THREAD

**Issue by Waynium** [opencv/cvat#7444]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

Hey guys. So I'm reporting this error (500 Internal server error) because I've already went through (https://github.com/opencv/cvat/issues/4664) a similar issue. I tried solving this error using the suggested solution in the comment section, but that didn't solve the cvat problem for me. 
I think you guys also need to know my runtime environment before you help, so you at least have an idea of where to start. I'm using windows, but I'm not using the docker for windows, as the cvat installation guide normally suggests. I'm rather using wsl, and I installed docker via the wsl terminal. So cvat is running on a docker image, which runs in wsl.

The problem is so bad, that I can't even continue using cvat anymore (I can't continue with annotation because it can't save my annotations due to the server error) I can't export, import or annotate. I've spent a whole day trying to delete and restart cvat docker images, and it's not helping.

### Expected Behavior

Here's the error when I track the logs on docker:

2024-02-05 13:59:38,608 DEBG 'uvicorn-0' stderr output:
[2024-02-05 13:59:38,607] ERROR django.request: Internal Server Error: /api/tasks/12/dataset
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/redis/connection.py", line 698, in connect
    sock = self.retry.call_with_retry(
  File "/opt/venv/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/opt/venv/lib/python3.10/site-packages/redis/connection.py", line 699, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/opt/venv/lib/python3.10/site-packages/redis/connection.py", line 955, in _connect
    for res in socket.getaddrinfo(
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "/opt/venv/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/django/cvat/apps/engine/views.py", line 1512, in dataset_export
    return self.export_annotations(
  File "/home/django/cvat/apps/engine/mixins.py", line 414, in export_annotations
    return export_func(db_instance=self._object,
  File "/home/django/cvat/apps/engine/views.py", line 2949, in _export_annotations
    rq_job = queue.fetch_job(rq_id)
  File "/opt/venv/lib/python3.10/site-packages/rq/queue.py", line 329, in fetch_job
    job = self.job_class.fetch(job_id, connection=self.connection, serializer=self.serializer)
  File "/opt/venv/lib/python3.10/site-packages/rq/job.py", line 591, in fetch
    job.refresh()
  File "/opt/venv/lib/python3.10/site-packages/rq/job.py", line 989, in refresh
    data = self.connection.hgetall(self.key)
  File "/opt/venv/lib/python3.10/site-packages/redis/commands/core.py", line 4867, in hgetall
    return self.execute_command("HGETALL", name)
  File "/opt/venv/lib/python3.10/site-packages/redis/client.py", line 1255, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/opt/venv/lib/python3.10/site-packages/redis/connection.py", line 1442, in get_connection
    connection.connect()
  File "/opt/venv/lib/python3.10/site-packages/redis/connection.py", line 704, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error -3 connecting to cvat_redis_inmem:6379. Temporary failure in name resolution.

### Possible Solution

This is how I tried to solve the server [problem](https://github.com/opencv/cvat/issues/4664#issuecomment-1926926644)

### Context

![Screenshot 2024-02-05 153632](https://github.com/opencv/cvat/assets/61937463/4e5fada7-794f-475b-a839-e2827dd3e381)

### Environment

```Markdown
- Docker version 25.0.2
- Operating System: Windows 11 Pro
- wsl (windows subsystem linux) - Ubuntu
```

**Comment by bsekachev** [comment]
`docker ps`?

**Comment by bsekachev** [comment]
container `cvat_redis_inmem` can't start

You may check its logs using `docker logs cvat_redis_inmem`

**Comment by devwasabi** [comment]
> container `cvat_redis_inmem` can't start
> 
> You may check its logs using `docker logs cvat_redis_inmem`

![image](https://github.com/opencv/cvat/assets/159067732/31f54161-d68d-4c3a-a01f-8c3ef4a6783c)

**Comment by bsekachev** [comment]
It looks like, redis inmem db is corrupted

1. stop all containers `docker compose down`
2. remove docker volume `cvat_cvat_inmem_db`
3. start all containers `docker compose up`

**Comment by Waynium** [comment]
> It looks like, redis inmem db is corrupted
> 
> 1. stop all containers `docker compose down`
> 2. remove docker volume `cvat_cvat_inmem_db`
> 3. start all containers `docker compose up`

Does docker volume remove all memory? I'd like to keep my work that I've done so far.

**Comment by Waynium** [comment]
Thank you so much! The commands you gave me worked.
