### ISSUE TITLE
Trying to implement custom yolov8 segmentation model for automatic labeling on serverless.

### ISSUE THREAD

**Issue by UffeLauge** [opencv/cvat#7503]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. Installed CVAT serverless on windows 10 with WSL.
2. Install Nuclio v. 1.11.24
3. Created custom yolov8 model inspired by: https://github.com/opencv/cvat/pull/6491
4. Deployed the model and model is running in Docker
5. This error appears in CVAT, after deploying model: 
![Screenshot 2024-02-21 085957](https://github.com/opencv/cvat/assets/87972098/ec33e30b-6d37-4927-9a64-4a80b59613b2)
6. When testing the model in Localhost:8070, it get this error:  "error": "Failed to invoke function: Post 'http://0.0.0.0:59561': dial tcp 0.0.0.0:59561: connect: connection refused"

### Context

I am trying to use my custom trained model to auto annotate in CVAT Serverless. 
I have placed my model files in: cvat/serverless/pytorch/ultralytics/yolov8.
In this folder i have placed: function.yaml, function_cpu.yaml, main.py and best.pt (the yolov8 weight file) 
main.py:
`import json
import base64
from PIL import Image
import io
import torch
import numpy as np
from ultralytics import YOLO
import supervision as sv
from skimage.measure import approximate_polygon, find_contours

def to_cvat_mask(box: list, mask):
    xtl, ytl, xbr, ybr = box
    flattened = mask[ytl:ybr + 1, xtl:xbr + 1].flat[:].tolist()
    flattened.extend([xtl, ytl, xbr, ybr])
    return flattened

def init_context(context):
    context.logger.info("Init context...  0%")

    model_path = "/opt/nuclio/best.pt"

    model = YOLO(model_path, task="segment")

    # Read the DL model
    context.user_data.model = model

    context.logger.info("Init context...100%")

def handler(context, event):
    context.logger.info("Run yolo-v8 model")
    data = event.body
    buf = io.BytesIO(base64.b64decode(data["image"]))
    threshold = float(data.get("threshold", 0.5))
    context.user_data.model.conf = threshold
    image = Image.open(buf)

    yolo_results = context.user_data.model(image, conf=threshold)[0]
    labels = yolo_results.names
    detections = sv.Detections.from_yolov8(yolo_results)
    detections = detections[detections.confidence > threshold]

    results = []
    if len(detections) > 0:

        for xyxy, mask, confidence, class_id, _ in detections:
            mask = mask.astype(np.uint8)

            xtl = int(xyxy[0])
            ytl = int(xyxy[1])
            xbr = int(xyxy[2])
            ybr = int(xyxy[3])

            label = int(class_id)
            cvat_mask = to_cvat_mask((xtl, ytl, xbr, ybr), mask)

            contours = find_contours(mask, 0.5)
            contour = contours[0]
            contour = np.flip(contour, axis=1)
            polygons = approximate_polygon(contour, tolerance=2.5)

            results.append({
                "confidence": str(confidence),
                "label": labels.get(class_id, "unknown"),
                "type": "mask",
                "points": polygons.ravel().tolist(),
                "mask": cvat_mask,
            })

    return context.Response(body=json.dumps(results), headers={},
                            content_type='application/json', status_code=200)`

function.yaml:
`
 metadata:
  name: pth-qr-code-and-objects-yolov8-segment
  namespace: cvat
  annotations:
    name: YOLO v8 Segment
    type: detector
    framework: pytorch
    spec: |
      [
        { "id": 0, "name": "QR" },
        { "id": 1, "name": "object" },
      ]
spec:
  description: YOLO v8 Segment via pytorch
  runtime: 'python:3.9'
  handler: main:handler
  eventTimeout: 30s
  build:
    image: cvat.pth.ultralytics.yolov8.segment
    baseImage: ultralytics/ultralytics:latest-cpu

    directives:
      preCopy:
        - kind: USER
          value: root
        - kind: RUN
          value: apt update && apt install --no-install-recommends -y libglib2.0-0
        - kind: RUN
          value: pip install supervision ultralytics scikit-image 
`

**Comment by bsekachev** [comment]
It does not look like your model was healthy deployed. 
I would suggest to check docker container and its logs.

**Comment by bsekachev** [comment]
You should start from checking this error: 

```
nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
```

Go to cvat container and check permissions for that file.
You may login as root inside the container: `docker exec -u root -it cvat_server bash`

**Comment by bsekachev** [comment]
But I am not sure that is the reason.
Somewhy `cvat_opa` can't get bundle from `cvat_server` container. However I do not see something else suspicious in provided `cvat_server` logs. 

``
http://cvat-server:8080/api/auth/rules
``

**Comment by UffeLauge** [comment]
> You should start from checking this error:
> 
> ```
> nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
> ```
> 
> Go to cvat container and check permissions for that file. You may login as root inside the container: `docker exec -u root -it cvat_server bash`

I have investigated the permissions, with the following result:
![image](https://github.com/opencv/cvat/assets/87972098/11c86570-dc0f-48c9-b196-a7ef3d1d8904)

**Comment by bsekachev** [comment]
> I have investigated the permissions, with the following result:

Try to remove this file maybe, it should be re-created with correct permissions

**Comment by UffeLauge** [comment]
> > I have investigated the permissions, with the following result:
> 
> Try to remove this file maybe, it should be re-created with correct permissions

I tried deleting the file and restarting the CVAT Dockers, it just recreated the file with the same permissions.

**Comment by bsekachev** [comment]
And you still do not see any errors in `docker logs cvat_server`?

**Comment by bsekachev** [comment]
``www-data`` and ``adm`` don't correspond to `django` user and `django` group, we use by default.
So, I may conclude you are using a modified version of CVAT.

**Comment by UffeLauge** [comment]
> `www-data` and `adm` don't correspond to `django` user and `django` group, we use by default. So, I may conclude you are using a modified version of CVAT.

That sound weird to me. All I have done is to follow your installation guide from: https://opencv.github.io/cvat/docs/administration/basics/installation/
And followed this guide afterwards: https://opencv.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/

**Comment by UffeLauge** [comment]
> And you still do not see any errors in `docker logs cvat_server`?

I still get the same errors as in my initial comment. Removing the /var/log/nginx/error.log didn't seem to have any effect.

**Comment by bsekachev** [comment]
Okay, never mind.

To suggest something, I need the full log from `cvat_server`, not just a short fragment.

**Comment by khursani8** [comment]
Not sure this will help
For me, i just chmod 777 for that file(bad practice)
After that i can see the error better which is related to my serverless container
After fix serverless code no issue anymore

This is just my assumption, the reason for new error log got different username probably because the server that got 500 error user is www-data(maybe)

**Comment by ak-ironix** [comment]
Hey @bsekachev could you please help me out if you were able to achieve this? I am trying to do the same thing.

**Comment by felixkarevo** [comment]
@bsekachev You marked this thread as completed. @UffeLauge Did you manage to solve the issue? I am trying to use a custom yolov8n-seg.pt model for auto annotation in CVAT. I installed nuclio and the serverless functions for CVAT. Segment anything (SAM) already works fine and I can use it in CVAT. 

Somehow my model is not found. I checked a few times alread. It is definitely there. And I also set the appropriate read permissions (chmod 644 path/to/model.pt). Last week it was still found. But I could not get masks or polygons. Only bounding boxes.

Any ideas?

**Error message:**

```
24.05.21 10:45:01.394 (I) cessor.healthcheck.server Listening {"listenAddress": ":8082"}
24.05.21 10:45:01.394 (D)            processor.http Creating worker pool {"num": 1}
24.05.21 10:45:01.394 (D) sor.http.w0.python.logger Creating listener socket {"path": "/tmp/nuclio-rpc-cp67mb9nmm5c73ci9k1g.sock"}
24.05.21 10:45:01.394 (D) sor.http.w0.python.logger Creating listener socket {"path": "/tmp/nuclio-rpc-cp67mb9nmm5c73ci9k20.sock"}
24.05.21 10:45:01.394 (D) sor.http.w0.python.logger Using Python wrapper script path {"path": "/opt/nuclio/_nuclio_wrapper.py"}
24.05.21 10:45:01.394 (D) sor.http.w0.python.logger Using Python handler {"handler": "main:handler"}
24.05.21 10:45:01.394 (D) sor.http.w0.python.logger Using Python executable {"path": "/opt/conda/bin/python3"}
24.05.21 10:45:01.394 (D) sor.http.w0.python.logger Setting PYTHONPATH {"value": "PYTHONPATH=/opt/nuclio"}
24.05.21 10:45:01.394 (D) sor.http.w0.python.logger Running wrapper {"command": "/opt/conda/bin/python3 -u /opt/nuclio/_nuclio_wrapper.py --handler main:handler --event-socket-path /tmp/nuclio-rpc-cp67mb9nmm5c73ci9k1g.sock --control-socket-path /tmp/nuclio-rpc-cp67mb9nmm5c73ci9k20.sock --platform-kind local --namespace nuclio --worker-id 0 --trigger-kind http --trigger-name myHttpTrigger --decode-event-strings"}
24.05.21 10:45:02.252 (I) sor.http.w0.python.logger Wrapper connected {"wid": 0, "pid": 25}
24.05.21 10:45:02.252 (D) sor.http.w0.python.logger Creating control connection {"wid": 0}
24.05.21 10:45:02.252 (D) sor.http.w0.python.logger Control connection created {"wid": 0}
24.05.21 10:45:02.252 (D) sor.http.w0.python.logger Waiting for start
24.05.21 10:45:02.252 (I) sor.http.w0.python.logger Init context...  0% {"worker_id": "0"}
24.05.21 10:45:02.252 (E) sor.http.w0.python.logger Exception raised while running init_context {"worker_id": "0"}
Traceback (most recent call last):
  File "/opt/nuclio/_nuclio_wrapper.py", line 567, in <module>
    run_wrapper()
  File "/opt/nuclio/_nuclio_wrapper.py", line 555, in run_wrapper
    loop.run_until_complete(wrapper_instance.initialize())
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/nuclio/_nuclio_wrapper.py", line 199, in initialize
    await self._initialize_context()
  File "/opt/nuclio/_nuclio_wrapper.py", line 225, in _initialize_context
    init_context_result = getattr(self._entrypoint_module, 'init_context')(self._context)
  File "/opt/nuclio/main.py", line 23, in init_context
    raise FileNotFoundError(f"Model file not found at {model_path}")
FileNotFoundError: Model file not found at /path/to/my/custom/model/custom_yolov8nseg.pt
24.05.21 10:45:02.337 (W) sor.http.w0.python.logger Failed to read control message {"errRootCause": "EOF"}
24.05.21 10:45:02.338 (D) sor.http.w0.python.logger Control connection was closed
24.05.21 10:45:02.411 (W) sor.http.w0.python.logger Failed to read from event connection {"err": "EOF"}
24.05.21 10:45:02.411 (E) sor.http.w0.python.logger Unexpected termination of child process {"error": null, "status": "exit status 1"}
panic: Wrapper process for worker 0 exited unexpectedly with: exit status 1

goroutine 72 [running]:
github.com/nuclio/nuclio/pkg/processor/runtime/rpc.(*AbstractRuntime).watchWrapperProcess(0xc00025ab60)
        /home/runner/work/nuclio/nuclio/pkg/processor/runtime/rpc/abstract.go:663 +0x434
created by github.com/nuclio/nuclio/pkg/processor/runtime/rpc.(*AbstractRuntime).startWrapper in goroutine 71
        /home/runner/work/nuclio/nuclio/pkg/processor/runtime/rpc/abstract.go:318 +0x1f1

    /nuclio/pkg/platform/local/platform.go:1312
Failed to deploy function
    ...//nuclio/pkg/platform/abstract/platform.go:227
```


**This is my function-gpu.yaml script:**

```
metadata:
  name: pth-ultralytics-yolov8-segment
  namespace: cvat
  annotations:
    name: YOLO v8 Segment
    type: detector
    framework: pytorch
    spec: |
    spec: |
      [
        {"id": 1, "name": "Potato"},
        {"id": 2, "name": "clod"},
        {"id": 3, "name": "stone"}
      ]

spec:
  description: YOLO v8 Segment via pytorch
  runtime: 'python:3.10'
  handler: main:handler
  eventTimeout: 30s
  build:
    image: cvat.pth.ultralytics.yolov8.segment
    baseImage: ultralytics/ultralytics:latest

    directives:
      preCopy:
        - kind: USER
          value: root
        - kind: RUN
          value: apt update && apt install --no-install-recommends -y libglib2.0-0
        - kind: RUN
          value: pip install supervision ultralytics
        - kind: WORKDIR
          value: /opt/nuclio

  triggers:
    myHttpTrigger:
      maxWorkers: 1
      kind: 'http'
      workerAvailabilityTimeoutMilliseconds: 10000
      attributes:
        maxRequestBodySize: 33554432 # 32MB

  resources:
    limits:
      nvidia.com/gpu: 1

  platform:
    attributes:
      restartPolicy:
        name: always
        maximumRetryCount: 3
      mountMode: volume
```

**This is my main.py code:**

```
import json
import base64
from PIL import Image
import io

import numpy as np
from ultralytics import YOLO
import supervision as sv
from skimage.measure import approximate_polygon, find_contours

def to_cvat_mask(box: list, mask):
    xtl, ytl, xbr, ybr = box
    flattened = mask[ytl:ybr + 1, xtl:xbr + 1].flat[:].tolist()
    flattened.extend([xtl, ytl, xbr, ybr])
    return flattened

def init_context(context):
    context.logger.info("Init context...  0%")

    model_path = "custom-yolov8n-seg.pt"

    model = YOLO(model_path, task="segment")

    # Read the DL model
    context.user_data.model = model

    context.logger.info("Init context...100%")

def handler(context, event):
    context.logger.info("Run yolo-v8 model")
    data = event.body
    buf = io.BytesIO(base64.b64decode(data["image"]))
    threshold = float(data.get("threshold", 0.5))
    context.user_data.model.conf = threshold
    image = Image.open(buf)

    yolo_results = context.user_data.model(image, conf=threshold)[0]
    labels = yolo_results.names
    detections = sv.Detections.from_ultralytics(yolo_results)

    detections = detections[detections.confidence > threshold]

    results = []
    if len(detections) > 0:
        # Adjusted unpacking to match the structure of Detections
        for detection in detections:
            mask = detection.mask
            xyxy = detection.xyxy
            class_id = detection.class_id
            confidence = detection.confidence

            mask = mask.astype(np.uint8)

            xtl = int(xyxy[0])
            ytl = int(xyxy[1])
            xbr = int(xyxy[2])
            ybr = int(xyxy[3])

            label = int(class_id)
            cvat_mask = to_cvat_mask((xtl, ytl, xbr, ybr), mask)


            contours = find_contours(mask, 0.5)
            contour = contours[0]
            contour = np.flip(contour, axis=1)
            polygons = approximate_polygon(contour, tolerance=2.5)

            results.append({
                    "confidence": str(confidence),
                    "label": labels.get(class_id, "unknown"),
                    "type": "mask",
                    "points": polygons.ravel().tolist(),
                    "mask": cvat_mask,
            })

    return context.Response(body=json.dumps(results), headers={},
                            content_type='application/json', status_code=200)
```

**Comment by felixkarevo** [comment]
Solved it myself. The issue was that I did not handle the `Detections` object correctly. I was  treating detection as if it has the xyxy attribute directly, but detection is actually a tuple.

**This is the corrected handler function:**

``
def handler(context, event):
    context.logger.info("Run yolo-v8 model")
    data = event.body
    buf = io.BytesIO(base64.b64decode(data["image"]))
    threshold = float(data.get("threshold", 0.5))
    context.user_data.model.conf = threshold
    image = Image.open(buf)

    yolo_results = context.user_data.model(image, conf=threshold)[0]
    labels = yolo_results.names
    detections = sv.Detections.from_ultralytics(yolo_results)
    detections = detections[detections.confidence > threshold]

    results = []
    if len(detections) > 0:
        for i in range(len(detections)):
            xyxy = detections.xyxy[i]
            mask = detections.mask[i]
            confidence = detections.confidence[i]
            class_id = detections.class_id[i]

            mask = mask.astype(np.uint8)

            xtl = int(xyxy[0])
            ytl = int(xyxy[1])
            xbr = int(xyxy[2])
            ybr = int(xyxy[3])

            label = int(class_id)
            cvat_mask = to_cvat_mask((xtl, ytl, xbr, ybr), mask)

            contours = find_contours(mask, 0.5)
            contour = contours[0]
            contour = np.flip(contour, axis=1)
            polygons = approximate_polygon(contour, tolerance=2.5)

            results.append({
                "confidence": str(confidence),
                "label": labels.get(class_id, "unknown"),
                "type": "mask",
                "points": polygons.ravel().tolist(),
                "mask": cvat_mask,
            })

    return context.Response(body=json.dumps(results), headers={},
                            content_type='application/json', status_code=200)
``

**Comment by felixkarevo** [comment]
I created a repository: https://github.com/felixkarevo/CVAT-custom-yolov8-segmentation-auto-annotation

**Comment by APeFerreira** [comment]
In case someone else encounters this confusion: I initially misunderstood and assumed there was a distinct "segment" model type to configure. I didn't understand why everyone defined their segmentation models under the detection configuration. However, using @felixkarevo's code resolves the issue perfectly, i.e., using a segmentation model defined as detection for automatic segmentation annotation.
