### ISSUE TITLE
Migrate from 2.8.2 to 2.10.3 / "Could not receive image data" in allready existing tasks

### ISSUE THREAD

**Issue by RoseDeSable** [opencv/cvat#7504]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

Hello,
 we worked with 2.8.2. In the past we successfully created a lot of tasks, jobs and their images with this release. Today we installed 2.10.3. After starting I logged in and see no images. If I go into a job, I receive the following message in my browser

--------------

Could not receive image data
<!doctype html> <html lang="en"> <head> <title>Server Error (500)</title> </head> <body> <h1>Server Error (500)</h1><p></p> </body> </html> .

--------------

But I can successfully create a task with images and has no problems to access the images.

We find no TO-DOES like migrating the postgres dbase. 

What can we do ? What did we overlook ?

Best Regards
Rose

**Comment by RoseDeSable** [comment]
Ok,
 I speak with my collegues. It could take a long time, until I will inform you.

**Comment by RoseDeSable** [comment]
Ok,
 we running CVAT in a docker environment. Here is an interesting part of the log:

 2024-02-22 12:58:58,653 DEBG 'uvicorn-0' stdout output:
 INFO:     192.168.208.1:0 - "GET /api/jobs/138/data/meta?org=myOrganisation HTTP/1.0" 200 OK

 2024-02-22 12:58:58,717 DEBG 'uvicorn-1' stderr output:
 [2024-02-22 12:58:58,717] INFO cvat.apps.engine.cache: Starting to get chunk from cache: key 83_0_Quality.COMPRESSED

 2024-02-22 12:58:58,718 DEBG 'uvicorn-1' stderr output:
 [2024-02-22 12:58:58,718] INFO cvat.apps.engine.cache: Ending to get chunk from cache: key 83_0_Quality.COMPRESSED, is_cached False

 2024-02-22 12:58:58,719 DEBG 'uvicorn-1' stderr output:
 [2024-02-22 12:58:58,718] INFO cvat.apps.engine.cache: Starting to prepare chunk: key 83_0_Quality.COMPRESSED

 2024-02-22 12:58:58,722 DEBG 'uvicorn-1' stderr output:
 [2024-02-22 12:58:58,721] ERROR django.request: Internal Server Error: /api/jobs/138/data
 Traceback (most recent call last):

This is a unsuccessful access of an image, that was loaded under 2.8.2 before the upgrade to 2.10.3.

**Comment by bsekachev** [comment]
You  did not provide the most valuable part - traceback.

**Comment by RoseDeSable** [comment]
Good Morning,
 the situation is more complex. We aren' t able to read the images, that are imported with the other version. When we goes back to 2.8.2, we see the images, that we imported under this version, but aren' able to read these, that we imported under 2.10.13. Under 2.10.13 these is reverse. 
 Here is the trace:

2024-02-22 14:19:51,722 DEBG 'uvicorn-0' stdout output:
INFO:     192.168.240.1:0 - "GET /api/jobs/140/data/meta?org=our-enterprise HTTP/1.0" 200 OK

2024-02-22 14:19:51,855 DEBG 'uvicorn-1' stdout output:
INFO:     192.168.240.1:0 - "GET /api/jobs/140/data/meta?org=our-enterprise HTTP/1.0" 200 OK

2024-02-22 14:19:51,936 DEBG 'uvicorn-0' stderr output:
[2024-02-22 14:19:51,935] INFO cvat.apps.engine.cache: Starting to get chunk from cache: key 85_0_Quality.COMPRESSED

2024-02-22 14:19:51,937 DEBG 'uvicorn-0' stderr output:
[2024-02-22 14:19:51,937] INFO cvat.apps.engine.cache: Ending to get chunk from cache: key 85_0_Quality.COMPRESSED, is_cached False

2024-02-22 14:19:51,937 DEBG 'uvicorn-0' stderr output:
[2024-02-22 14:19:51,937] INFO cvat.apps.engine.cache: Starting to prepare chunk: key 85_0_Quality.COMPRESSED

2024-02-22 14:19:51,945 DEBG 'uvicorn-0' stderr output:
[2024-02-22 14:19:51,942] ERROR django.request: Internal Server Error: /api/jobs/140/data
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "/opt/venv/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/django/cvat/apps/engine/views.py", line 1905, in data
    return data_getter(request, db_job.segment.start_frame,
  File "/home/django/cvat/apps/engine/views.py", line 729, in __call__
    return super().__call__(request, start, stop, db_data)
  File "/home/django/cvat/apps/engine/views.py", line 659, in __call__
    buff, mime_type = frame_provider.get_chunk(self.number, self.quality)
  File "/home/django/cvat/apps/engine/frame_provider.py", line 188, in get_chunk
    return self._loaders[quality].get_chunk_path(chunk_number, quality, self._db_data)
  File "/home/django/cvat/apps/engine/cache.py", line 60, in get_task_chunk_data_with_mime
    item = self._get_or_set_cache_item(
  File "/home/django/cvat/apps/engine/cache.py", line 52, in _get_or_set_cache_item
    item = create_function()
  File "/home/django/cvat/apps/engine/cache.py", line 62, in <lambda>
    create_function=lambda: self._prepare_task_chunk(db_data, quality, chunk_number),
  File "/home/django/cvat/apps/engine/cache.py", line 205, in _prepare_task_chunk
    with self._get_images(db_data, chunk_number, self._dimension) as images:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/django/cvat/apps/engine/cache.py", line 140, in _get_images
    reader = ImageDatasetManifestReader(manifest_path=db_data.get_manifest_path(),
  File "/home/django/cvat/apps/engine/media_extractors.py", line 522, in __init__
    self._manifest = ImageManifestManager(manifest_path)
  File "/home/django/utils/dataset_manifest/core.py", line 546, in __init__
    super().__init__(manifest_path, create_index, upload_dir)
  File "/home/django/utils/dataset_manifest/core.py", line 336, in __init__
    self._index = _Index(os.path.dirname(self._manifest.path))
  File "/home/django/utils/dataset_manifest/core.py", line 264, in __init__
    assert path and os.path.isdir(path), 'No index directory path'
AssertionError: No index directory path

2024-02-22 14:19:51,945 DEBG 'uvicorn-0' stdout output:
INFO:     192.168.240.1:0 - "GET /api/jobs/140/data?org=our-enterprise&quality=compressed&type=chunk&number=0 HTTP/1.0" 500 Internal Server Error

**Comment by bsekachev** [comment]
From the stacktrace I see, that lines where some functions called, do not correspond to lines with these calls in code of this repository for version 2.10.3

So, I may suggest that the code is modified, is that true?

**Comment by RoseDeSable** [comment]
Yes
 this trace is from 2.8.2, where I unsuccessfully accessed an image, that I uploaded in 2.10.3

**Comment by bsekachev** [comment]
Downgrading is not supported. 
Let's return to the case when old data can not be opened in newer version.

**Comment by RoseDeSable** [comment]
Ok,
 I send you this kind of trace from 2.10.3 as soon as possible.

**Comment by RoseDeSable** [comment]
Hello,
 here is the trace, that was created under 2.10.3

[2024-02-22 12:45:24,455] ERROR django.request: Internal Server Error: /api/jobs/138/data
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "/opt/venv/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/django/cvat/apps/engine/views.py", line 1903, in data
    return data_getter(request, db_job.segment.start_frame,
  File "/home/django/cvat/apps/engine/views.py", line 727, in __call__
    return super().__call__(request, start, stop, db_data)
  File "/home/django/cvat/apps/engine/views.py", line 657, in __call__
    buff, mime_type = frame_provider.get_chunk(self.number, self.quality)
  File "/home/django/cvat/apps/engine/frame_provider.py", line 207, in get_chunk
    return self._loaders[quality].get_chunk_path(chunk_number, quality, self._db_data)
  File "/home/django/cvat/apps/engine/cache.py", line 80, in get_task_chunk_data_with_mime
    item = self._get_or_set_cache_item(
  File "/home/django/cvat/apps/engine/cache.py", line 68, in _get_or_set_cache_item
    item = create_item()
  File "/home/django/cvat/apps/engine/cache.py", line 50, in create_item
    item = create_function()
  File "/home/django/cvat/apps/engine/cache.py", line 82, in <lambda>
    create_function=lambda: self._prepare_task_chunk(db_data, quality, chunk_number),
  File "/home/django/cvat/apps/engine/cache.py", line 225, in _prepare_task_chunk
    with self._get_images(db_data, chunk_number, self._dimension) as images:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/django/cvat/apps/engine/cache.py", line 160, in _get_images
    reader = ImageDatasetManifestReader(manifest_path=db_data.get_manifest_path(),
  File "/home/django/cvat/apps/engine/media_extractors.py", line 522, in __init__
    self._manifest = ImageManifestManager(manifest_path)
  File "/home/django/utils/dataset_manifest/core.py", line 546, in __init__
    super().__init__(manifest_path, create_index, upload_dir)
  File "/home/django/utils/dataset_manifest/core.py", line 336, in __init__
    self._index = _Index(os.path.dirname(self._manifest.path))
  File "/home/django/utils/dataset_manifest/core.py", line 264, in __init__
    assert path and os.path.isdir(path), 'No index directory path'
AssertionError: No index directory path

**Comment by RoseDeSable** [comment]
And here another trace

[2024-02-23 09:27:32,075] ERROR django.request: Internal Server Error: /api/tasks/36/preview
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "/opt/venv/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/django/cvat/apps/engine/views.py", line 1540, in preview
    return data_getter(request, self._object.data.start_frame,
  File "/home/django/cvat/apps/engine/views.py", line 669, in __call__
    buf, mime = cache.get_local_preview_with_mime(self.number, db_data)
  File "/home/django/cvat/apps/engine/cache.py", line 96, in get_local_preview_with_mime
    item = self._get_or_set_cache_item(
  File "/home/django/cvat/apps/engine/cache.py", line 68, in _get_or_set_cache_item
    item = create_item()
  File "/home/django/cvat/apps/engine/cache.py", line 50, in create_item
    item = create_function()
  File "/home/django/cvat/apps/engine/cache.py", line 98, in <lambda>
    create_function=lambda: self._prepare_local_preview(frame_number, db_data),
  File "/home/django/cvat/apps/engine/cache.py", line 292, in _prepare_local_preview
    buff, mime_type = frame_provider.get_preview(frame_number)
  File "/home/django/cvat/apps/engine/frame_provider.py", line 194, in get_preview
    preview, _ = self.get_frame(frame_number, self.Quality.COMPRESSED, self.Type.PIL)
  File "/home/django/cvat/apps/engine/frame_provider.py", line 214, in get_frame
    chunk_reader = loader.load(chunk_number)
  File "/home/django/cvat/apps/engine/frame_provider.py", line 100, in load
    self.reader_class([self.get_chunk_path(chunk_id, self.quality, self.db_data)[0]]))
  File "/home/django/cvat/apps/engine/cache.py", line 80, in get_task_chunk_data_with_mime
    item = self._get_or_set_cache_item(
  File "/home/django/cvat/apps/engine/cache.py", line 68, in _get_or_set_cache_item
    item = create_item()
  File "/home/django/cvat/apps/engine/cache.py", line 50, in create_item
    item = create_function()
  File "/home/django/cvat/apps/engine/cache.py", line 82, in <lambda>
    create_function=lambda: self._prepare_task_chunk(db_data, quality, chunk_number),
  File "/home/django/cvat/apps/engine/cache.py", line 225, in _prepare_task_chunk
    with self._get_images(db_data, chunk_number, self._dimension) as images:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/django/cvat/apps/engine/cache.py", line 160, in _get_images
    reader = ImageDatasetManifestReader(manifest_path=db_data.get_manifest_path(),
  File "/home/django/cvat/apps/engine/media_extractors.py", line 522, in __init__
    self._manifest = ImageManifestManager(manifest_path)
  File "/home/django/utils/dataset_manifest/core.py", line 546, in __init__
    super().__init__(manifest_path, create_index, upload_dir)
  File "/home/django/utils/dataset_manifest/core.py", line 336, in __init__
    self._index = _Index(os.path.dirname(self._manifest.path))
  File "/home/django/utils/dataset_manifest/core.py", line 264, in __init__
    assert path and os.path.isdir(path), 'No index directory path'
AssertionError: No index directory path

2024-02-23 09:27:32,078 DEBG 'uvicorn-1' stdout output:
INFO:     172.17.0.1:0 - "GET /api/tasks/36/preview?org=SHSTest HTTP/1.0" 500 Internal Server Error

What for a version of unicorn must we use. With 1 it seems to exist some problems with zip-files, how I find in Google in a quick way

**Comment by bsekachev** [comment]
Did you solve the issue? 
Actually, I do not have any ideas regarding this because even when we migrated app.cvat.ai with huge number of tasks, we did not meet something like this.

**Comment by RoseDeSable** [comment]
No,
 we try,  but we cannot solve.

**Comment by nmanovic** [comment]
@RoseDeSable , we have the Enterprise support (https://www.cvat.ai/pricing/on-prem). Please consider it. I will close the issue because it is a problem of your specific deployment.

**Comment by RoseDeSable** [comment]
Hi,
 we believe, that we have found the problem. Each change to another release create a new data storage. Therefore we cannot access pictures from tasks, that we created in another version. Here you see the actual listing


local     cvat-282_cvat_cache_db
local     cvat-282_cvat_data
local     cvat-282_cvat_db
local     cvat-282_cvat_events_db
local     cvat-282_cvat_keys
local     cvat-282_cvat_logs
local     cvat-282_cvat_share
local     cvat-282_models
local     cvat-2103_cvat_cache_db
local     cvat-2103_cvat_data
local     cvat-2103_cvat_db
local     cvat-2103_cvat_events_db
local     cvat-2103_cvat_inmem_db
local     cvat-2103_cvat_keys
local     cvat-2103_cvat_logs
local     cvat-2103_cvat_share
local     cvat-2103_models
local     cvat-2110_cvat_cache_db
local     cvat-2110_cvat_data
local     cvat-2110_cvat_db
local     cvat-2110_cvat_events_db
local     cvat-2110_cvat_inmem_db
local     cvat-2110_cvat_keys
local     cvat-2110_cvat_logs
local     cvat-2110_cvat_share
local     cvat-2110_models
local     cvat_cvat_cache_db
local     cvat_cvat_data
local     cvat_cvat_events_db
local     cvat_cvat_keys
local     cvat_cvat_logs
local     cvat_cvat_share
local     cvat_models

Have you a solution for this problem ?

**Comment by bsekachev** [comment]
We do not have such problem in our code. It is a customization issue, so, unfortunately we can't help.

**Comment by RoseDeSable** [comment]
Thanks,
 I believe also. But now we have an evidence.

**Comment by RoseDeSable** [comment]
Hello, 
very good news: We found the problem:

In the case of docker compose, the volumes of the docker will named by the project name. The project name should be given from us. But we didn't. 
  In this case the name of the volume is the name of the directory were the software of the cvat version is located and started. For example: cvat-2.9.2 istthe directory of cvat, then the data volume has the name cvat-2.9.2. The new version was copied in the directory cvat-2.10.0. So the new volume for this version had the name cvat-2.10.0. The pictures of 2.9.2 weren't accessible. After the next step to cvat 2.11.0 we couldn't access any pictures of the both earlier versions, because the volume of the new version has the name cvat-2.11.0.
 After creating a project name we can access the picture of all versions.

Best Regards
Rose

**Comment by bsekachev** [comment]
Thanks for sharing your thoughts. Maybe it will help somebody

**Comment by RoseDeSable** [comment]
To help others. This was the intension.
