### ISSUE TITLE
Couldn't access localhost:8080, receive Service Error (500).

### ISSUE THREAD

**Issue by doublelipeng** [opencv/cvat#819]
I installed the cvat in Ubuntu, and runs good. But after about 2 weeks unused, I found I couldn't access the localhost:8080, the chrome would give bad gate. I tried to use command : docker-compose down, and then docker-compose up -d. But it still doesn't work. So I uninstalled the docker and reinstalled docker and cvat. But it only turned my chrome of localhost:8080 to Service error (500). I tried to reboot the computer, but still it doesn't work.

Here is the logs of cvat:

<details>
l@llp:~/cvat$ docker logs cvat
2019-11-06 10:31:42,924 INFO RPC interface 'supervisor' initialized
2019-11-06 10:31:42,924 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2019-11-06 10:31:42,925 INFO supervisord started with pid 1
2019-11-06 10:31:43,926 INFO spawned: 'ssh-agent' with pid 8
2019-11-06 10:31:43,928 INFO spawned: 'git_status_updater' with pid 9
2019-11-06 10:31:43,929 INFO spawned: 'rqworker_low' with pid 10
2019-11-06 10:31:43,930 INFO spawned: 'runserver' with pid 11
2019-11-06 10:31:43,931 INFO spawned: 'rqworker_default_0' with pid 12
2019-11-06 10:31:43,932 INFO spawned: 'rqworker_default_1' with pid 14
2019-11-06 10:31:43,938 DEBG 'ssh-agent' stdout output:
SSH_AUTH_SOCK=/tmp/ssh-agent.sock; export SSH_AUTH_SOCK;
echo Agent pid 18;

2019-11-06 10:31:43,938 DEBG 'ssh-agent' stderr output:
debug2: fd 3 setting O_NONBLOCK

2019-11-06 10:31:43,939 DEBG 'runserver' stderr output:
wait-for-it.sh: waiting for db:5432 without a timeout

2019-11-06 10:31:43,940 DEBG 'rqworker_low' stderr output:
wait-for-it.sh: waiting for redis:6379 without a timeout

2019-11-06 10:31:43,940 DEBG 'git_status_updater' stderr output:
wait-for-it.sh: waiting for redis:6379 without a timeout

2019-11-06 10:31:43,940 DEBG 'rqworker_default_1' stderr output:
wait-for-it.sh: waiting for redis:6379 without a timeout

2019-11-06 10:31:43,941 DEBG 'rqworker_default_0' stderr output:
wait-for-it.sh: waiting for redis:6379 without a timeout

2019-11-06 10:31:43,941 DEBG 'runserver' stderr output:
wait-for-it.sh: db:5432 is available after 0 seconds

2019-11-06 10:31:43,942 DEBG 'rqworker_default_1' stderr output:
wait-for-it.sh: redis:6379 is available after 0 seconds

2019-11-06 10:31:43,942 DEBG 'git_status_updater' stderr output:
wait-for-it.sh: redis:6379 is available after 0 seconds

2019-11-06 10:31:43,942 DEBG 'rqworker_low' stderr output:
wait-for-it.sh: redis:6379 is available after 0 seconds

2019-11-06 10:31:43,943 DEBG 'runserver' stderr output:
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell

2019-11-06 10:31:43,943 DEBG 'rqworker_default_1' stderr output:
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell

2019-11-06 10:31:43,943 DEBG 'git_status_updater' stderr output:
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell

2019-11-06 10:31:43,943 DEBG 'rqworker_default_0' stderr output:
wait-for-it.sh: redis:6379 is available after 0 seconds

2019-11-06 10:31:43,944 DEBG 'rqworker_low' stderr output:
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell

2019-11-06 10:31:43,944 DEBG 'rqworker_default_0' stderr output:
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell

2019-11-06 10:31:44,006 DEBG 'ssh-agent' stderr output:
debug2: fd 4 setting O_NONBLOCK
debug1: XXX shrink: 3 < 4

2019-11-06 10:31:44,008 DEBG 'ssh-agent' stderr output:
debug2: fd 4 setting O_NONBLOCK
debug1: type 11

2019-11-06 10:31:44,008 DEBG 'ssh-agent' stderr output:
debug1: XXX shrink: 3 < 4

2019-11-06 10:31:44,010 DEBG 'ssh-agent' stderr output:
debug2: fd 4 setting O_NONBLOCK

2019-11-06 10:31:44,012 DEBG 'ssh-agent' stderr output:
debug1: type 17

2019-11-06 10:31:44,014 DEBG 'git_status_updater' stderr output:
Identity added: /home/django/.ssh/id_rsa (/home/django/.ssh/id_rsa)

2019-11-06 10:31:44,015 DEBG 'ssh-agent' stderr output:
debug1: XXX shrink: 3 < 4

2019-11-06 10:31:44,017 DEBG 'ssh-agent' stderr output:
debug2: fd 4 setting O_NONBLOCK

2019-11-06 10:31:44,019 DEBG 'ssh-agent' stderr output:
debug1: type 17

2019-11-06 10:31:44,021 DEBG 'ssh-agent' stderr output:
debug1: XXX shrink: 3 < 4

2019-11-06 10:31:44,023 DEBG 'ssh-agent' stderr output:
debug2: fd 4 setting O_NONBLOCK
debug1: type 11

2019-11-06 10:31:44,023 DEBG 'ssh-agent' stderr output:
debug1: XXX shrink: 3 < 4

2019-11-06 10:31:44,025 DEBG 'ssh-agent' stderr output:
debug2: fd 4 setting O_NONBLOCK

2019-11-06 10:31:44,026 DEBG 'ssh-agent' stderr output:
debug1: type 17

2019-11-06 10:31:44,027 DEBG 'ssh-agent' stderr output:
debug1: XXX shrink: 3 < 4

2019-11-06 10:31:44,029 DEBG 'ssh-agent' stderr output:
debug2: fd 4 setting O_NONBLOCK
debug1: type 11

2019-11-06 10:31:44,029 DEBG 'ssh-agent' stderr output:
debug1: XXX shrink: 3 < 4

2019-11-06 10:31:44,030 DEBG 'ssh-agent' stderr output:
debug2: fd 4 setting O_NONBLOCK

2019-11-06 10:31:44,031 DEBG 'ssh-agent' stderr output:
debug1: type 17

2019-11-06 10:31:44,033 DEBG 'ssh-agent' stderr output:
debug1: XXX shrink: 3 < 4

2019-11-06 10:31:44,034 DEBG 'ssh-agent' stderr output:
debug2: fd 4 setting O_NONBLOCK
debug1: type 11

2019-11-06 10:31:44,034 DEBG 'ssh-agent' stderr output:
debug1: XXX shrink: 3 < 4

2019-11-06 10:31:44,036 DEBG 'ssh-agent' stderr output:
debug2: fd 4 setting O_NONBLOCK

2019-11-06 10:31:44,037 DEBG 'ssh-agent' stderr output:
debug1: type 17

2019-11-06 10:31:44,038 DEBG 'ssh-agent' stderr output:
debug1: XXX shrink: 3 < 4

2019-11-06 10:31:44,040 DEBG 'ssh-agent' stderr output:
debug2: fd 4 setting O_NONBLOCK
debug1: type 11

2019-11-06 10:31:44,040 DEBG 'ssh-agent' stderr output:
debug1: XXX shrink: 3 < 4

2019-11-06 10:31:44,679 DEBG 'rqworker_default_1' stderr output:
System check identified some issues:

WARNINGS:
?: (2_0.W001) Your URL pattern 'api/swagger.<slug:format>$' [name='schema-json'] has a route that contains '(?P<', begins with a '^', or ends with a '$'. This was likely an oversight when migrating to django.urls.path().
10:31:44 RQ worker 'rq:worker:cef3370827b3430fb41ae1c1aeac6bad' started, version 1.0

2019-11-06 10:31:44,679 DEBG 'rqworker_default_1' stderr output:
10:31:44 *** Listening on default...

2019-11-06 10:31:44,679 DEBG 'rqworker_default_1' stderr output:
10:31:44 Cleaning registries for queue: default

2019-11-06 10:31:44,702 DEBG 'rqworker_default_0' stderr output:
System check identified some issues:

WARNINGS:
?: (2_0.W001) Your URL pattern 'api/swagger.<slug:format>$' [name='schema-json'] has a route that contains '(?P<', begins with a '^', or ends with a '$'. This was likely an oversight when migrating to django.urls.path().
10:31:44 RQ worker 'rq:worker:bddd57b4668b4d59ab7617b9b91d6b7c' started, version 1.0

2019-11-06 10:31:44,702 DEBG 'rqworker_default_0' stderr output:
10:31:44 *** Listening on default...

2019-11-06 10:31:44,706 DEBG 'rqworker_low' stderr output:
System check identified some issues:

WARNINGS:
?: (2_0.W001) Your URL pattern 'api/swagger.<slug:format>$' [name='schema-json'] has a route that contains '(?P<', begins with a '^', or ends with a '$'. This was likely an oversight when migrating to django.urls.path().
10:31:44 RQ worker 'rq:worker:6c0e4bbcdc734d72ab3c5bc0d2436647' started, version 1.0

2019-11-06 10:31:44,706 DEBG 'rqworker_low' stderr output:
10:31:44 *** Listening on low...

2019-11-06 10:31:44,706 DEBG 'rqworker_low' stderr output:
10:31:44 Cleaning registries for queue: low

2019-11-06 10:31:45,707 INFO success: ssh-agent entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-11-06 10:31:45,707 INFO success: git_status_updater entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-11-06 10:31:45,708 INFO success: rqworker_low entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-11-06 10:31:45,708 INFO success: runserver entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-11-06 10:31:45,708 INFO success: rqworker_default_0 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-11-06 10:31:45,708 INFO success: rqworker_default_1 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-11-06 10:31:46,416 DEBG 'runserver' stdout output:
Operations to perform:
  Apply all migrations: account, admin, annotation, auth, authtoken, contenttypes, engine, git, sessions, sites, socialaccount
Running migrations:
  No migrations to apply.

2019-11-06 10:31:46,417 DEBG 'runserver' stderr output:
System check identified some issues:

WARNINGS:
?: (2_0.W001) Your URL pattern 'api/swagger.<slug:format>$' [name='schema-json'] has a route that contains '(?P<', begins with a '^', or ends with a '$'. This was likely an oversight when migrating to django.urls.path().

2019-11-06 10:31:46,611 DEBG 'ssh-agent' stderr output:
debug2: fd 4 setting O_NONBLOCK

2019-11-06 10:31:46,612 DEBG 'ssh-agent' stderr output:
debug1: type 17

2019-11-06 10:31:46,614 DEBG 'ssh-agent' stderr output:
debug1: XXX shrink: 3 < 4

2019-11-06 10:31:46,616 DEBG 'ssh-agent' stderr output:
debug2: fd 4 setting O_NONBLOCK
debug1: type 11

2019-11-06 10:31:46,616 DEBG 'ssh-agent' stderr output:
debug1: XXX shrink: 3 < 4

2019-11-06 10:31:46,959 DEBG 'runserver' stdout output:

0 static files copied to '/home/django/static', 382 unmodified.

2019-11-06 10:31:47,066 DEBG 'ssh-agent' stderr output:
debug2: fd 4 setting O_NONBLOCK

2019-11-06 10:31:47,067 DEBG 'ssh-agent' stderr output:
debug1: type 17

2019-11-06 10:31:47,069 DEBG 'ssh-agent' stderr output:
debug1: XXX shrink: 3 < 4

2019-11-06 10:31:47,071 DEBG 'ssh-agent' stderr output:
debug2: fd 4 setting O_NONBLOCK
debug1: type 11

2019-11-06 10:31:47,071 DEBG 'ssh-agent' stderr output:
debug1: XXX shrink: 3 < 4

2019-11-06 10:31:47,619 DEBG 'runserver' stdout output:
Successfully ran command.
Server URL         : http://localhost:8080/
Server Root        : /tmp/mod_wsgi-localhost:8080:1000
Server Conf        : /tmp/mod_wsgi-localhost:8080:1000/httpd.conf
Error Log File     : /dev/stderr (INFO)
Request Capacity   : 5 (1 process * 5 threads)
Request Timeout    : 60 (seconds)
Startup Timeout    : 15 (seconds)
Queue Backlog      : 100 (connections)
Queue Timeout      : 45 (seconds)
Server Capacity    : 20 (event/worker), 20 (prefork)
Server Backlog     : 500 (connections)
Locale Setting     : C.UTF-8

2019-11-06 10:31:47,637 DEBG 'runserver' stderr output:
[Wed Nov 06 10:31:47.637143 2019] [mpm_event:notice] [pid 11:tid 139669396490112] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.6.2 Python/3.5 configured -- resuming normal operations
[Wed Nov 06 10:31:47.637196 2019] [mpm_event:info] [pid 11:tid 139669396490112] AH00490: Server built: 2019-10-08T13:31:25
[Wed Nov 06 10:31:47.637201 2019] [core:notice] [pid 11:tid 139669396490112] AH00094: Command line: 'apache2 (mod_wsgi-express) -f /tmp/mod_wsgi-localhost:8080:1000/httpd.conf -D MOD_WSGI_MPM_ENABLE_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_WORKER_MODULE -D MOD_WSGI_MPM_EXISTS_PREFORK_MODULE -D FOREGROUND'
[Wed Nov 06 10:31:47.637123 2019] [wsgi:info] [pid 199:tid 139669396490112] mod_wsgi (pid=199): Starting process 'localhost:8080' with threads=5.

2019-11-06 10:31:47,637 DEBG 'runserver' stderr output:
[Wed Nov 06 10:31:47.637458 2019] [wsgi:info] [pid 199:tid 139669396490112] mod_wsgi (pid=199): Python home /usr.
[Wed Nov 06 10:31:47.637480 2019] [wsgi:info] [pid 199:tid 139669396490112] mod_wsgi (pid=199): Initializing Python.

2019-11-06 10:31:47,663 DEBG 'runserver' stderr output:
[Wed Nov 06 10:31:47.663696 2019] [wsgi:info] [pid 199:tid 139669396490112] mod_wsgi (pid=199): Attach interpreter ''.

2019-11-06 10:31:47,666 DEBG 'runserver' stderr output:
[Wed Nov 06 10:31:47.666030 2019] [wsgi:info] [pid 199:tid 139669396490112] mod_wsgi (pid=199): Imported 'mod_wsgi'.

2019-11-06 10:31:47,666 DEBG 'runserver' stderr output:
[Wed Nov 06 10:31:47.666063 2019] [wsgi:info] [pid 199:tid 139669396490112] mod_wsgi (pid=199, process='localhost:8080', application=''): Loading Python script file '/tmp/mod_wsgi-localhost:8080:1000/handler.wsgi'.

2019-11-06 10:31:47,796 DEBG 'ssh-agent' stderr output:
debug2: fd 4 setting O_NONBLOCK

2019-11-06 10:31:47,797 DEBG 'ssh-agent' stderr output:
debug1: type 17

2019-11-06 10:31:47,798 DEBG 'ssh-agent' stderr output:
debug1: XXX shrink: 3 < 4

2019-11-06 10:31:47,801 DEBG 'ssh-agent' stderr output:
debug2: fd 4 setting O_NONBLOCK
debug1: type 11

2019-11-06 10:31:47,801 DEBG 'ssh-agent' stderr output:
debug1: XXX shrink: 3 < 4

2019-11-06 10:32:07,523 DEBG 'runserver' stderr output:
[Wed Nov 06 10:32:07.523117 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454] [2019-11-06 10:32:07,522] ERROR django.request: Internal Server Error: /auth/login
[Wed Nov 06 10:32:07.523129 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454] Traceback (most recent call last):
[Wed Nov 06 10:32:07.523131 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454]   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 34, in inner
[Wed Nov 06 10:32:07.523132 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454]     response = get_response(request)
[Wed Nov 06 10:32:07.523133 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454]   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 115, in _get_response
[Wed Nov 06 10:32:07.523134 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454]     response = self.process_exception_by_middleware(e, request)
[Wed Nov 06 10:32:07.523135 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454]   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 113, in _get_response
[Wed Nov 06 10:32:07.523136 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Wed Nov 06 10:32:07.523137 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454]   File "/usr/local/lib/python3.5/dist-packages/django/views/generic/base.py", line 71, in view
[Wed Nov 06 10:32:07.523138 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454]     return self.dispatch(request, *args, **kwargs)
[Wed Nov 06 10:32:07.523139 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454]   File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 45, in _wrapper
[Wed Nov 06 10:32:07.523140 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454]     return bound_method(*args, **kwargs)
[Wed Nov 06 10:32:07.523141 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454]   File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
[Wed Nov 06 10:32:07.523142 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454]     return view(request, *args, **kwargs)
[Wed Nov 06 10:32:07.523143 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454]   File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 45, in _wrapper
[Wed Nov 06 10:32:07.523144 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454]     return bound_method(*args, **kwargs)
[Wed Nov 06 10:32:07.523145 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454]   File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 142, in _wrapped_view
[Wed Nov 06 10:32:07.523146 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454]     response = view_func(request, *args, **kwargs)
[Wed Nov 06 10:32:07.523147 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454]   File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 45, in _wrapper
[Wed Nov 06 10:32:07.523148 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454]     return bound_method(*args, **kwargs)
[Wed Nov 06 10:32:07.523149 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454]   File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
[Wed Nov 06 10:32:07.523151 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454]     response = view_func(request, *args, **kwargs)
[Wed Nov 06 10:32:07.523151 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454]   File "/usr/local/lib/python3.5/dist-packages/django/contrib/auth/views.py", line 61, in dispatch
[Wed Nov 06 10:32:07.523153 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454]     return super().dispatch(request, *args, **kwargs)
[Wed Nov 06 10:32:07.523154 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454]   File "/usr/local/lib/python3.5/dist-packages/django/views/generic/base.py", line 97, in dispatch
[Wed Nov 06 10:32:07.523155 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454]     return handler(request, *args, **kwargs)
[Wed Nov 06 10:32:07.523156 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454]   File "/usr/local/lib/python3.5/dist-packages/django/views/generic/edit.py", line 133, in get
[Wed Nov 06 10:32:07.523157 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454]     return self.render_to_response(self.get_context_data())
[Wed Nov 06 10:32:07.523158 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454]   File "/usr/local/lib/python3.5/dist-packages/django/contrib/auth/views.py", line 95, in get_context_data
[Wed Nov 06 10:32:07.523159 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454]     current_site = get_current_site(self.request)
[Wed Nov 06 10:32:07.523160 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454]   File "/usr/local/lib/python3.5/dist-packages/django/contrib/sites/shortcuts.py", line 13, in get_current_site
[Wed Nov 06 10:32:07.523161 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454]     return Site.objects.get_current(request)
[Wed Nov 06 10:32:07.523162 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454]   File "/usr/local/lib/python3.5/dist-packages/django/contrib/sites/models.py", line 58, in get_current
[Wed Nov 06 10:32:07.523163 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454]     return self._get_site_by_id(site_id)
[Wed Nov 06 10:32:07.523164 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454]   File "/usr/local/lib/python3.5/dist-packages/django/contrib/sites/models.py", line 30, in _get_site_by_id
[Wed Nov 06 10:32:07.523165 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454]     site = self.get(pk=site_id)
[Wed Nov 06 10:32:07.523166 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454]   File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py", line 82, in manager_method
[Wed Nov 06 10:32:07.523167 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454]     return getattr(self.get_queryset(), name)(*args, **kwargs)
[Wed Nov 06 10:32:07.523168 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454]   File "/usr/local/lib/python3.5/dist-packages/cacheops/query.py", line 354, in get
[Wed Nov 06 10:32:07.523169 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454]     return qs._no_monkey.get(qs, *args, **kwargs)
[Wed Nov 06 10:32:07.523170 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454]   File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 408, in get
[Wed Nov 06 10:32:07.523171 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454]     self.model._meta.object_name
[Wed Nov 06 10:32:07.523173 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454] django.contrib.sites.models.Site.DoesNotExist: Site matching query does not exist.
[Wed Nov 06 10:32:07.523176 2019] [wsgi:error] [pid 199:tid 139669160658688] [remote 172.20.0.1:41454] 
</details>

**Comment by nmanovic** [comment]
@doublelipeng , could you please checkout the latest develop branch and build/run the container again? Did you modify the code?

If you don't have valuable data the full instruction is below:
- `docker-compose down -v` (remove containers with volumes)
- Checkout the latest develop branch 
- `docker-compose up -d --build` (build and run containers, add extra -f options if it is necessary)

**Comment by doublelipeng** [comment]
Yes! It solved the problem, I can log in now. But it also remove all the superusers, tasks I created. Why removing all the container with volumes would help to solve it? AIs there any relationship with that I created more than one superusers, and put them in one group?

**Comment by doublelipeng** [comment]
I did modify the Dockerfile to download the packages on another website. I think it doesn't matter.

**Comment by nmanovic** [comment]
@doublelipeng , I have no idea why you get the problem. But it is invisible for us to investigate problems inside CVAT with modified code.

 I will close the issue for now and see if somebody from community reports a similar problem.

**Comment by doublelipeng** [comment]
Thank you very much.
