### ISSUE TITLE
Build docker image failed - ERROR: Service 'cvat' failed to build

### ISSUE THREAD

**Issue by bessszilard** [opencv/cvat#822]
I downloaded and installed the OpenVino toolkit. Then I downloaded the OpenVino kit for CVAT and put it into `cvat/components/openvino` directory. 

I ran this command:

```shell
$ sudo docker-compose -f docker-compose.yml -f components/openvino/docker-compose.openvino.yml build
```
 The build is stopped with this error:

```shell
Exception:
Traceback (most recent call last):
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connection.py", line 137, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/util/connection.py", line 67, in create_connection
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 787, in _validate_conn
    conn.connect()
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connection.py", line 217, in connect
    conn = self._new_conn()
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connection.py", line 146, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
pip._vendor.requests.packages.urllib3.exceptions.NewConnectionError: <pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f5090886160>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 317, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 512, in _prepare_file
    finder, self.upgrade, require_hashes)
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 273, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 442, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 400, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python3/dist-packages/pip/index.py", line 545, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 648, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 757, in get_page
    "Cache-Control": "max-age=600",
  File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/pip/download.py", line 378, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 610, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 228, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
You are using pip version 8.1.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

As I know, the pip version is only a warning, and that didn't cause an interruption in the build.
How can I fix this error?

**Comment by nmanovic** [comment]
@bessszilard , it looks like a problem with your network. Do you have proxy or something like that?

**Comment by bessszilard** [comment]
Thanks @nmanovic, the problem was with my network. Yesterday I tried several times, and it has the same problem. Today I tried again, and it was built without any problems.

**Comment by arcibiyo** [comment]
I had locally a old version cvat repo. I wanted to `$ sudo docker-compose -f docker-compose.yml -f components/openvino/docker-compose.openvino.yml build`
```
Step 52/54 : RUN python3 manage.py collectstatic
 ---> Running in 37374f28702d
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/config.py", line 388, in resolve
    found = getattr(found, frag)
AttributeError: module 'logstash_async' has no attribute 'handler'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/config.py", line 390, in resolve
    self.importer(used)
  File "/opt/venv/lib/python3.8/site-packages/logstash_async/handler.py", line 11, in <module>
    from logstash_async.worker import LogProcessingWorker
  File "/opt/venv/lib/python3.8/site-packages/logstash_async/worker.py", line 12, in <module>
    from limits import parse as parse_rate_limit
  File "/opt/venv/lib/python3.8/site-packages/limits/__init__.py", line 5, in <module>
    from . import _version, aio, storage, strategies
  File "/opt/venv/lib/python3.8/site-packages/limits/aio/__init__.py", line 1, in <module>
    from . import storage, strategies
  File "/opt/venv/lib/python3.8/site-packages/limits/aio/storage/__init__.py", line 6, in <module>
    from .base import MovingWindowSupport, Storage
  File "/opt/venv/lib/python3.8/site-packages/limits/aio/storage/base.py", line 5, in <module>
    from limits.storage.registry import StorageRegistry
  File "/opt/venv/lib/python3.8/site-packages/limits/storage/__init__.py", line 12, in <module>
    from .base import MovingWindowSupport, Storage
  File "/opt/venv/lib/python3.8/site-packages/limits/storage/base.py", line 4, in <module>
    from limits.storage.registry import StorageRegistry
  File "/opt/venv/lib/python3.8/site-packages/limits/storage/registry.py", line 5, in <module>
    from limits.typing import Dict, List, Tuple, Union
  File "/opt/venv/lib/python3.8/site-packages/limits/typing.py", line 13, in <module>
    from typing_extensions import Counter, ParamSpec, Protocol
ImportError: cannot import name 'ParamSpec' from 'typing_extensions' (/opt/venv/lib/python3.8/site-packages/typing_extensions.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/config.py", line 563, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/lib/python3.8/logging/config.py", line 721, in configure_handler
    klass = self.resolve(cname)
  File "/usr/lib/python3.8/logging/config.py", line 397, in resolve
    raise v
  File "/usr/lib/python3.8/logging/config.py", line 390, in resolve
    self.importer(used)
  File "/opt/venv/lib/python3.8/site-packages/logstash_async/handler.py", line 11, in <module>
    from logstash_async.worker import LogProcessingWorker
  File "/opt/venv/lib/python3.8/site-packages/logstash_async/worker.py", line 12, in <module>
    from limits import parse as parse_rate_limit
  File "/opt/venv/lib/python3.8/site-packages/limits/__init__.py", line 5, in <module>
    from . import _version, aio, storage, strategies
  File "/opt/venv/lib/python3.8/site-packages/limits/aio/__init__.py", line 1, in <module>
    from . import storage, strategies
  File "/opt/venv/lib/python3.8/site-packages/limits/aio/storage/__init__.py", line 6, in <module>
    from .base import MovingWindowSupport, Storage
  File "/opt/venv/lib/python3.8/site-packages/limits/aio/storage/base.py", line 5, in <module>
    from limits.storage.registry import StorageRegistry
  File "/opt/venv/lib/python3.8/site-packages/limits/storage/__init__.py", line 12, in <module>
    from .base import MovingWindowSupport, Storage
  File "/opt/venv/lib/python3.8/site-packages/limits/storage/base.py", line 4, in <module>
    from limits.storage.registry import StorageRegistry
  File "/opt/venv/lib/python3.8/site-packages/limits/storage/registry.py", line 5, in <module>
    from limits.typing import Dict, List, Tuple, Union
  File "/opt/venv/lib/python3.8/site-packages/limits/typing.py", line 13, in <module>
    from typing_extensions import Counter, ParamSpec, Protocol
ValueError: Cannot resolve 'logstash_async.handler.AsynchronousLogstashHandler': cannot import name 'ParamSpec' from 'typing_extensions' (/opt/venv/lib/python3.8/site-packages/typing_extensions.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/opt/venv/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/opt/venv/lib/python3.8/site-packages/django/utils/log.py", line 75, in configure_logging
    logging_config_func(logging_settings)
  File "/usr/lib/python3.8/logging/config.py", line 808, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python3.8/logging/config.py", line 570, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'logstash'
The command '/bin/sh -c python3 manage.py collectstatic' returned a non-zero code: 1
ERROR: Service 'cvat' failed to build : Build failed
```

Then, ı used `docker-compose up -d`. When ı go to localhost, ı got this error. 

![image](https://user-images.githubusercontent.com/47760055/164000154-b32f822e-1136-4740-b196-e62c0f6021f6.png)
![image](https://user-images.githubusercontent.com/47760055/164000265-8161baee-7857-415a-8127-848df9f4fe27.png)

**Comment by schliffen** [comment]
Im getting the same error. I tried multiple time

**Comment by msaqib17** [comment]
> Im getting the same error. I tried multiple time

Hi Schliffen were you able to solve the problem?

**Comment by msaqib17** [comment]
I gettting the following error at the last step.


Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/config.py", line 388, in resolve
    found = getattr(found, frag)
AttributeError: module 'logstash_async' has no attribute 'handler'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/config.py", line 390, in resolve
    self.importer(used)
  File "/opt/venv/lib/python3.8/site-packages/logstash_async/handler.py", line 11, in <module>
    from logstash_async.worker import LogProcessingWorker
  File "/opt/venv/lib/python3.8/site-packages/logstash_async/worker.py", line 12, in <module>
    from limits import parse as parse_rate_limit
  File "/opt/venv/lib/python3.8/site-packages/limits/__init__.py", line 5, in <module>
    from . import _version, aio, storage, strategies
  File "/opt/venv/lib/python3.8/site-packages/limits/aio/__init__.py", line 1, in <module>
    from . import storage, strategies
  File "/opt/venv/lib/python3.8/site-packages/limits/aio/storage/__init__.py", line 6, in <module>
    from .base import MovingWindowSupport, Storage
  File "/opt/venv/lib/python3.8/site-packages/limits/aio/storage/base.py", line 5, in <module>
    from limits.storage.registry import StorageRegistry
  File "/opt/venv/lib/python3.8/site-packages/limits/storage/__init__.py", line 12, in <module>
    from .base import MovingWindowSupport, Storage
  File "/opt/venv/lib/python3.8/site-packages/limits/storage/base.py", line 4, in <module>
    from limits.storage.registry import StorageRegistry
  File "/opt/venv/lib/python3.8/site-packages/limits/storage/registry.py", line 5, in <module>
    from limits.typing import Dict, List, Tuple, Union
  File "/opt/venv/lib/python3.8/site-packages/limits/typing.py", line 13, in <module>
    from typing_extensions import ClassVar, Counter, ParamSpec, Protocol
ImportError: cannot import name 'ParamSpec' from 'typing_extensions' (/opt/venv/lib/python3.8/site-packages/typing_extensions.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/config.py", line 563, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/lib/python3.8/logging/config.py", line 721, in configure_handler
    klass = self.resolve(cname)
  File "/usr/lib/python3.8/logging/config.py", line 397, in resolve
    raise v
  File "/usr/lib/python3.8/logging/config.py", line 390, in resolve
    self.importer(used)
  File "/opt/venv/lib/python3.8/site-packages/logstash_async/handler.py", line 11, in <module>
    from logstash_async.worker import LogProcessingWorker
  File "/opt/venv/lib/python3.8/site-packages/logstash_async/worker.py", line 12, in <module>
    from limits import parse as parse_rate_limit
  File "/opt/venv/lib/python3.8/site-packages/limits/__init__.py", line 5, in <module>
    from . import _version, aio, storage, strategies
  File "/opt/venv/lib/python3.8/site-packages/limits/aio/__init__.py", line 1, in <module>
    from . import storage, strategies
  File "/opt/venv/lib/python3.8/site-packages/limits/aio/storage/__init__.py", line 6, in <module>
    from .base import MovingWindowSupport, Storage
  File "/opt/venv/lib/python3.8/site-packages/limits/aio/storage/base.py", line 5, in <module>
    from limits.storage.registry import StorageRegistry
  File "/opt/venv/lib/python3.8/site-packages/limits/storage/__init__.py", line 12, in <module>
    from .base import MovingWindowSupport, Storage
  File "/opt/venv/lib/python3.8/site-packages/limits/storage/base.py", line 4, in <module>
    from limits.storage.registry import StorageRegistry
  File "/opt/venv/lib/python3.8/site-packages/limits/storage/registry.py", line 5, in <module>
    from limits.typing import Dict, List, Tuple, Union
  File "/opt/venv/lib/python3.8/site-packages/limits/typing.py", line 13, in <module>
    from typing_extensions import ClassVar, Counter, ParamSpec, Protocol
ValueError: Cannot resolve 'logstash_async.handler.AsynchronousLogstashHandler': cannot import name 'ParamSpec' from 'typing_extensions' (/opt/venv/lib/python3.8/site-packages/typing_extensions.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/saq001/manage.py", line 21, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/opt/venv/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/opt/venv/lib/python3.8/site-packages/django/utils/log.py", line 75, in configure_logging
    logging_config_func(logging_settings)
  File "/usr/lib/python3.8/logging/config.py", line 808, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python3.8/logging/config.py", line 570, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'logstash'

**Comment by schliffen** [comment]
Hi @[msaqib17](https://github.com/msaqib17),
I did. I got the same errors, I solved doing the following steps:
1- remove all CVAT related docker images,
2- checkout to branch release_2.1.0
3- inside cvat/requirements/base.txt change open3d==** version to open3d==0.12.0
4- In Dockerfile.ci, add libusb-1.0-0 It would be like the following run:
`RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get --no-install-recommends install -yq \
        gpg-agent \
        gnupg2 \
        apt-utils \
        build-essential \
        python3-dev \
        ruby \
        libusb-1.0-0 \
        && \
    curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | tee /etc/apt/sources.list.d/google-chrome.list && \
    curl https://deb.nodesource.com/setup_16.x | bash - && \
    DEBIAN_FRONTEND=noninteractive apt-get --no-install-recommends install -yq \
        google-chrome-stable \
        nodejs \
        && \
    rm -rf /var/lib/apt/lists/*;
`

**Comment by msaqib17** [comment]
Thank you so much schliffen. The build is successful now. But i get another error about libusb-1.0-0 when i create superuser. Although i have added libusb-1.0-0 in Dockerfile.

sudo docker exec -it cvat bash -ic 'python3 ~/manage.py createsuperuser'
Traceback (most recent call last):
  File "/home/saq001/manage.py", line 21, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/venv/lib/python3.8/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 79, in execute
    return super().execute(*args, **options)
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/base.py", line 393, in execute
    self.check()
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/base.py", line 419, in check
    all_issues = checks.run_checks(
  File "/opt/venv/lib/python3.8/site-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/opt/venv/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/opt/venv/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/opt/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 416, in check
    for pattern in self.url_patterns:
  File "/opt/venv/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 602, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/venv/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 595, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/saq001/cvat/urls.py", line 27, in <module>
    path('', include('cvat.apps.engine.urls')),
  File "/opt/venv/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/saq001/cvat/apps/engine/urls.py", line 7, in <module>
    from . import views
  File "/home/saq001/cvat/apps/engine/views.py", line 42, in <module>
    import cvat.apps.dataset_manager.views  # pylint: disable=unused-import
  File "/home/saq001/cvat/apps/dataset_manager/views.py", line 15, in <module>
    import cvat.apps.dataset_manager.task as task
  File "/home/saq001/cvat/apps/dataset_manager/task.py", line 18, in <module>
    from .bindings import TaskData
  File "/home/saq001/cvat/apps/dataset_manager/bindings.py", line 23, in <module>
    from cvat.apps.engine.frame_provider import FrameProvider
  File "/home/saq001/cvat/apps/engine/frame_provider.py", line 13, in <module>
    from cvat.apps.engine.cache import CacheInteraction
  File "/home/saq001/cvat/apps/engine/cache.py", line 13, in <module>
    from cvat.apps.engine.media_extractors import (Mpeg4ChunkWriter,
  File "/home/saq001/cvat/apps/engine/media_extractors.py", line 22, in <module>
    import open3d as o3d
  File "/opt/venv/lib/python3.8/site-packages/open3d/__init__.py", line 56, in <module>
    _CDLL(next((_Path(__file__).parent / 'cpu').glob('pybind*')))
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libusb-1.0.so.0: cannot open shared object file: No such file or directory

**Comment by schliffen** [comment]
Can you try open3d==0.11.2

**Comment by msaqib17** [comment]
> Can you try open3d==0.11.2

Thank you so much it worked.
